### ISSUE TITLE
Support for other DBs

### ISSUE THREAD

**Issue by torstenfeld** [healthchecks/healthchecks#1]
Hi,

first: thanks for this project. Was just looking for cronitor.io alternatives and thought to create something similar, but I guess you already did the job. ;)

One question though: Is it possible, not to use Postgresql but use MySQL instead?

**Comment by cuu508** [comment]
Hi Torsten,

so far the only Postgres-specific thing is a database trigger which updates `api_check.alert_after` field. This trigger gets created when you run `manage.py ensuretriggers` command. I've just added a MySQL version of the trigger and it seems to work. 

I've updated README with some basic instructions on setting up a development environment.
You can update `DATABASES` key in `settings.py` and give it a spin.
