### ISSUE TITLE
new integration: twilio

### ISSUE THREAD

**Issue by jayzeng** [healthchecks/healthchecks#100]
Will be cool to see twilio as integration, users can put in their keys (auth token, sid, and from number) and a list of subscribers to receive texts when checks fail or succeed after a number of (definable) failures

**Comment by cuu508** [comment]
I've added SMS integration which uses Twilio under the hood. Twilio accounts are not configured per user though, there's one Twilio account configured in `local_settings.py`, shared by all users.
