### ISSUE TITLE
Slack integration - default integration name to channel name

### ISSUE THREAD

**Issue by chriselion** [healthchecks/healthchecks#1003]
Just a small workflow improvement - when adding a Slack integration, can you default the name of the integration to the channel name? Currently it defaults to _unnamed_

For precedent, the PagerDuty integration defaults to the Service's name; I think the same behavior here would be nice.

![image](https://github.com/healthchecks/healthchecks/assets/6877802/59eeb9b1-2413-4baf-b35b-9c6495b62fb5)

**Comment by cuu508** [comment]
Good idea, thanks for the suggestion @chriselion !
