### ISSUE TITLE
Support failover checks

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [healthchecks/healthchecks#1027]
It would be great, if multiple checks could be grouped by tag.

A notification should always include all checks of this tag group and should be sent if and only if the whole group is down.

This enables admins to send notifications to "clients" (someone, who does not care, if a node of a cluster goes down, but if at least one node is up).
The option to send notifications per check should be retained for admins though.

This could be achieved, by adding the tags as a "check" on their own, which only goes down, if all checks which are tagged for this tag are down as well.
Integrations could be enabled like every other check.

**Comment by cuu508** [comment]
Thanks for the suggestion, but this is too niche and far outside the scope of this project. 

You can achieve something similar if you configure all nodes in the cluster ping the same check, and only ping on success, and keep quiet on failures. As long as at least one node is pinging, the check will stay up.

**Comment by TheCataliasTNT2k** [comment]
Sad to hear that.
Yes, that would be a way, but only for the "users", the admins would not be notified if a single node goes down, which is important for them but not the "users"

**Comment by cuu508** [comment]
You could set up each node to ping two URLs, the second  one being a node-specific check which triggers notifications to admins.

Not elegant, but possible today.
