### ISSUE TITLE
Telegram test works, but sending alerts fails

### ISSUE THREAD

**Issue by AbelLykens** [healthchecks/healthchecks#1028]
Sending alerts using the Telegram integration fails:

![image](https://github.com/user-attachments/assets/f1932b4f-034b-45a4-962e-3534c26217df)

I get `Received status code 404 with a message: "Not Found"`.

When I click test:
![image](https://github.com/user-attachments/assets/0dd57d3e-a343-453b-87c0-d2057e993419)

The test message is sent to my Telegram just fine. Which means (I guess) the API keys are set correctly:

```
$ grep TELEGRAM hc/settings.py 
#TELEGRAM_BOT_NAME = os.getenv("TELEGRAM_BOT_NAME", "ExampleBot")
TELEGRAM_BOT_NAME = "HealthySuperBot"
#TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_TOKEN = "xxx"
```

**Comment by cuu508** [comment]
Hello @AbelLykens, perhaps you didn't restart the sendalerts process after updating `TELEGRAM_TOKEN`?

**Comment by AbelLykens** [comment]
Thank you @cuu508 . That was it. Thanks for thinking with me, much appreciated.
