### ISSUE TITLE
Issue with psycopg2 install on upgrade

### ISSUE THREAD

**Issue by stevenmcastano** [healthchecks/healthchecks#103]
I tried to do a "git pull" and do an upgrade today, which I finally managed to get working, but I'm getting this error when trying to do a "pip install -r requirements.txt":

```
 Downloading psycopg2-2.6.2.tar.gz (376kB)
    100% |████████████████████████████████| 378kB 2.5MB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-et5hSb/psycopg2/
```

Just to make sure all the details are in here this is:

python v2.7.6
pip 9.0.1
ubuntu 14.04.5 (kernel 3.13.0.103-generic)

I was able to comment out that package from the requirements.txt and get through the install and do the migration and things are back up and running again. I'm just wondering what's missing and what I can do to resolve it?

**Comment by stevenmcastano** [comment]
Just to make sure all the details are in here this is:

python v2.7.6
pip 9.0.1
ubuntu 14.04.5 (kernel 3.13.0.103-generic)

**Comment by cuu508** [comment]
psycopg2 is the Python library for accessing PostgreSQL database. If you're using MySQL or MariaDB then you don't need it -- you can indeed safely comment it out and it will not affect anything.

On Ubuntu you can install psycopg2 system-wide with `apt-get install python-psycopg2` or `apt-get install python3-psycopg2`. If you install with pip inside a virtualenv, you need to have a few -dev packages -- `apt-get install build-essential libpq-dev` (IIRC)

**Comment by stevenmcastano** [comment]
Ah ok, that makes sense. As long as it’s not buried in the code somewhere where it will cause a problem, I’ll just leave it commented out as I am using MariaDB.

Thanks!
