### ISSUE TITLE
Cannot increase ping log limit on self-hosted instance

### ISSUE THREAD

**Issue by EricAntidot** [healthchecks/healthchecks#1032]
We have a self hosted instance and we want to increase the ping log limit from 100 up to 2000 and even if I saw:
- the doc (https://github.com/healthchecks/healthchecks/blob/master/README.md#database-cleanup)
- some ticket comment https://github.com/healthchecks/healthchecks/issues/572#issuecomment-958756877

that says it is possible to do so. I am unable to do it?

I cannot find the "Ping log limit" field in the user's Profile ??

I am running hc v3.4

**Comment by cuu508** [comment]
You can set the ping log limit through Django admin:

![image](https://github.com/user-attachments/assets/a6912923-0434-4263-9142-8d3fbb752b90)

* Create a superuser account: `manage.py createsuperuser`
* Log into Healthchecks as the superuser
* Once logged in, in the top left "Account" menu you will see "Site Administration" item. It will take you to Django admin:

![image](https://github.com/user-attachments/assets/b9a102b0-314c-4a57-8857-c47318aa9fb2)

* In Django admin, click on "Profiles", select the profile, and in the edit form you will be able to adjust ping log limit.

**Comment by EricAntidot** [comment]
Thank you very much. However it is not that to guess "where" to click for editing the profile entry.
One need to click on "number" in the first column in order to edit the entry, all other clickable area will (mis)lead somewhere else.
