### ISSUE TITLE
Does cron syntex in healthchecks support the SECOND field?

### ISSUE THREAD

**Issue by lukedoomer** [healthchecks/healthchecks#1038]
Healthchecks uses the [cronsim](https://github.com/cuu508/cronsim) library to parse and evaluate cron expressions.
Can I write `59 59 9 * * *` to run job at 09:59:59 everyday?

if not, please add the SECOND field into healthchecks. Thank you.

**Comment by cuu508** [comment]
No, a seconds field is not supported in cron expressions.

As a workaround you can use a systemd  OnCalendar expression: `9:59:59`.

As an alternative workaround, use a cron expression without the seconds field (`59 9 * * *`) and increase grace time by one minute.
