### ISSUE TITLE
Feature request: support additional PostgreSQL DB SSL parameters via environment variables

### ISSUE THREAD

**Issue by gclawes** [healthchecks/healthchecks#1041]
It would be useful to support the following SSL parameters in postgresql DB connections, especially when using custom trusted CAs or certificate-based authentication.

* [`sslrootcert`](https://www.postgresql.org/docs/10/libpq-connect.html#LIBPQ-CONNECT-SSROOTCERT) - useful when using a custom certificate authority for the postgresql server
* [`sslcert`](https://www.postgresql.org/docs/10/libpq-connect.html#LIBPQ-CONNECT-SSLCERT)/[`sslkey`](https://www.postgresql.org/docs/10/libpq-connect.html#LIBPQ-CONNECT-SSLKEY) - useful for certificate-based authentication, especially with `cert-manager` in Kubernetes

These can be set in `local_settings.py` manually, but having this in environment variables would be more convenient in container environments.

**Comment by cuu508** [comment]
Thanks for the suggestion. All three of `sslrootcert`, `sslcert` and `sslkey` take file paths – to use them, you would need to mount files inside the image, or build a custom image. If you are doing that anyway, is mounting one additional file (`local_settings.py`) that difficult?

And another thought, these parameters have default values – perhaps you can mount the certs and key at their default locations?
