### ISSUE TITLE
C#/.NET API Wrapper

### ISSUE THREAD

**Issue by FizzBuzz791** [healthchecks/healthchecks#1042]
Hi, I've started building out a new wrapper here: https://github.com/FizzBuzz791/NHealthCheck

I'm happy to submit a PR to have it added to the third-party resources list if you'd like. Otherwise, I would appreciate it if you could add it on my behalf.

Thanks.

**Comment by cuu508** [comment]
Thanks for the tip, and thanks for the work on the library!

Looks like you started it very recently. I'm happy to add it to the 3rd-party resource pages once it has matured, has documentation, and has some traction (github stars, issues and PRs by external contributors).
