### ISSUE TITLE
Allowed hours for running Simple checks

### ISSUE THREAD

**Issue by malarzm** [healthchecks/healthchecks#1044]
We're looking for a way to monitor a process that is running fairly often during day, and very rarely in night. To illustrate it better, we'd like to monitor whether a 3rd party app keeps feeding our platform with product stock data. It happens a lot during the day when people are buying things, rarely in the night when most folks are sleeping :)

`Simple Schedules` would be a perfect match for us, but we'd like to keep it quiet during night. This could be achieved by allowing user to specify "working hours" for a simple schedule. For example if a check is specified to "work" between 8-18, it would not produce a notification (or be failed) when no ping is coming before 8 or after 18.

Another approach would be something I've seen in uptimerobot.com, namely "Maintenance windows" (https://uptimerobot.com/blog/new-feature-maintenance-windows-for-the-pro-plan/). User can specify what time the maintenance is and attach it to monitors: 
![image](https://github.com/user-attachments/assets/dbbc6963-7d31-4ee6-bdf0-5125467e1974)
currently we're using it like "Maintenance window starts at 18 and lasts14 hours".

Do you see such feature as fitting HealthChecks? I'm not sure if we'd be able to contribute it as we have no Python developers on board, but maybe you'd be open for a one-time sponsorship? :) Happy to see where it'll go.

**Comment by cuu508** [comment]
Perhaps a cron schedule could work for this:

* schedule: `* 8-17 * * *` (or perhaps `* 8-17 * * MON-FRI`)
* grace time: 10 minutes

The schedule means: expect a ping every minute from 8:00 until 17:59. The 10 minute grace time means: when a ping does not arrive on time, wait up to 10 minutes before sending alert. So, as long as gaps between the pings are no more than 10 minutes, the check will stay up/late. Obviously you can tweak the grace time as needed.

One limitation of this approach is that the check will regularly display as "late" (amber color). It will turn to green after each received ping, but flip back to amber at the start of every new minute. You will have to remember to think of amber color as "all is well", not "warning, something may be wrong".

**Comment by malarzm** [comment]
Thanks for prompt reply! Utilizing cron schedules will definitely work although we were hoping to avoid amber colouring :) But if this is the way to go, we will figure our how to live with it without interfering. 

Thanks for great tool :tophat:
