### ISSUE TITLE
Webhook should accept $SLUG as a placeholder

### ISSUE THREAD

**Issue by timdream** [healthchecks/healthchecks#1049]
I am trying to create a Webhook integration that connects to [Home Assistant binary sensor](https://www.home-assistant.io/integrations/http/#binary-sensor). It requires a URL like `http://IP_ADDRESS:8123/api/states/binary_sensor.DEVICE_NAME` with `DEVICE_NAME` confirmed to its entity ID character limits, i.e., no space nor dash (`-`).

With that I can't use `$NAME` nor `$CODE`. I could use `$TAG1` to workaround this, but it would be so much easier if it has a `$SLUG` placeholder available.

Thank you! I am using Healthchecks v3.4.

**Comment by cuu508** [comment]
Thanks for the suggestion! Just added support for $SLUG placeholder.
