### ISSUE TITLE
Website Login doesn't play well with password managers

### ISSUE THREAD

**Issue by FizzBuzz791** [healthchecks/healthchecks#1053]
I've got all my passwords (and 2FA) set up in 1Password, so I choose the entry, and it auto-fills and clicks the relevant buttons on the login screens. 

When I do this on the healthchecks.io website, I get a "Too Many Requests Please try again later." error. I can immediately retry using 1Password for the same error seemingly infinite times. Alternatively, I can manually enter my credentials and 2FA and immediately log in with no issues.

Based on the symptoms, there is some rudimentary rate-limiting (probably to prevent bots, hackers, etc.), and it is unintentionally inhibiting 1Password, too.

**Comment by cuu508** [comment]
There is rate-limiting: https://github.com/healthchecks/healthchecks/blob/3968a4f9e0f80ae99c55b6980d4e6803a850f471/hc/api/models.py#L1257

But it is performed server-side, and there should be no difference whether the form was filled with a password manager or manually.

Just to be sure, can you reproduce a situation where:

* you fill the form with password manager, click "Log In", and get the "Too Many Requests" message
* in the same browsing session, right after, fill the form manually, click "Log In" and get logged in?

If so, could you send me to contact@healthchecks.io a HAR file of the HTTP POST request that results in "Too Many Requests"?
