### ISSUE TITLE
NTFY Integration Sends plain JSON instead of formatted Notification

### ISSUE THREAD

**Issue by daytonrea** [healthchecks/healthchecks#1059]
Currently the NTFY integration is sending me plain JSON as a notification instead of the expected formatted notification. 
![IMG_2578](https://github.com/user-attachments/assets/b2dfdc8b-16ab-4a97-8d24-eff011c1b7bd)

**Comment by cuu508** [comment]
* Can you please send me a link to the check in email (to contact at healthchecks io)?
* Can you reproduce the problem if you create a new project, create a ntfy integration in it and press the "Test!" button?
* What ntfy client are you using? Do you see the same problem with other clients (for example, in the web interface)?

**Comment by daytonrea** [comment]
yes problem is reproduced when creating a new project and using test button, I am using ios client but problem is also reproduced on the web ui. do you want me to email the link to contact at health checks dot io?

**Comment by cuu508** [comment]
I reproduced the issue and am looking into it. Sorry about the couple of test notifications you received.

**Comment by cuu508** [comment]
Ah, the problem is the server URL.

For your integration the server URL is `https://ntfy.sh/<topic_name>`.

When posting message as JSON, the server URL should not contains the topic name and should be just `https://ntfy.sh` (as the topic name is contained in the JSON payload): https://docs.ntfy.sh/publish/#publish-as-json

**Comment by cuu508** [comment]
I'm thinking about adding a help text under the "Server URL" field: 

![image](https://github.com/user-attachments/assets/db1361cc-70e0-4929-be56-7a92e2621ac9)

I know this may hard to say after the fact, but do you think this would have helped?
