### ISSUE TITLE
Integration with Discord

### ISSUE THREAD

**Issue by ChaosMTA** [healthchecks/healthchecks#106]
Hi,

I would be interested with integration to push a message to a channel in discord if a healthcheck fails. Our team uses discord frequently for communication. Let me know if this is at all a possibility!

**Comment by cuu508** [comment]
Hello, yes, adding Discord integration sounds good to me.

**Comment by ChaosMTA** [comment]
Right now this is sort of possible by doing a integration with slack and then adding a discord webhook to slack:
https://discordapp.com/api/webhooks/260835008367820800/ou1jH2__QdQt_iNwpaB4THvrskRXYPHwu_Jr1O8uRoj0iKjGhMVof4t1f8SBxPz8G1r5

**Comment by cuu508** [comment]
Hi @ChaosMTA, the Discord integration is ready for testing, you can try it out on https://healthchecks.io

For notifications, it uses the same format as the Slack integration: http://i.imgur.com/NQJPYRA.png

When you get a chance, it would be great to test this out. I had not previously used Discord so please let me know if anything looks weird or could be improved!
