### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [healthchecks/healthchecks#1062]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Healthchecks application as shown [here](https://elest.io/open-source/healthchecks). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/healthchecks)

**Comment by cuu508** [comment]
I'm happy to link to Elestio from the [Third-Party Resources](https://healthchecks.io/docs/resources/) page. Before I add the link, I wanted to try out Healthchecks on Elestio to see how it works. First observations:

* After I deploy the service, it starts up, and I could log in - nice!
* It uses linuxserver docker image. I would feel more confident recommending Elestio if it used the official image
* The default configuration has DEBUG=True. This is insecure, a better default would be DEBUG=False
* I tried setting a custom domain name but couldn't get it to work. After editing ALLOWED_HOSTS (using the "Update config" feature) and restarting the container it still seems to use the old configuration. I suspect it is some weirdness with the linuxserver image but not sure.

**Comment by cuu508** [comment]
Ah, I figured out the issue with ALLOWED_HOSTS, I was using incorrect syntax when setting it.

I used

    - ALLOWED_HOSTS=["example.com"]

I should have used

    - ALLOWED_HOSTS=example.com

**Comment by kaiwalyakoparkar** [comment]
Hey @cuu508 Thanks for trying it out,
- We use our images as they are found to be more trusted by our users, also we can fix and release quickly if there is any bug. If you insist on an official image then surely we can make that change. Let me know :)
- I will inform the team of your suggestion about DEBUG=false for default 🙌 
- I will make the pr to your suggested page shortly

**Comment by cuu508** [comment]
> We use our images as they are found to be more trusted by our users, also we can fix and release quickly if there is any bug

Wait, is Elestio behind linuxserver?
