### ISSUE TITLE
[Feature] Global dark mode - prior to logging in?

### ISSUE THREAD

**Issue by rwjack** [healthchecks/healthchecks#1063]
Every time my login times out, I am blasted with a white screen before I login.

This change could be a simple environment variable that enables dark mode globally (by default, meaning users can still use white mode if they chose so).

**Comment by cuu508** [comment]
Thanks for the suggestion.

How about instead extending the session cookie age, so the session doesn't time out?

There's a [SESSION_COOKIE_AGE](https://docs.djangoproject.com/en/5.1/ref/settings/#session-cookie-age) setting, with the default value set to to 2 weeks. On Healthchecks.io I've set it to one year. This means in practice I get never automatically logged out (unless I don't visit the site for more than a year ;-).

Healthchecks does not currently read SESSION_COOKIE_AGE from an environment variable (setting an environment variable with this name currently has no effect), but we could look into doing that.

**Comment by rwjack** [comment]
Yeah, that would solve my particular issue. So to clarify, I would only get logged out, if I don't open HC for a year (with the variable set to a year obviously)?

I would honestly prefer to keep it at 2 weeks, but with that logic - so if I keep opening HC every 13 days, the cookie is refreshed and the session is extended - unless that is how it currently works?

I don't think I've ever went for 2 weeks without opening the page at least once, but I'm not 100% sure.
