### ISSUE TITLE
State reason for failure (late or explicit failure) in notifications

### ISSUE THREAD

**Issue by rwjack** [healthchecks/healthchecks#1069]
Related: https://github.com/healthchecks/healthchecks/discussions/1067

**Comment by cuu508** [comment]
I updated the Flip object to track failure reason, and updated the email template. When the grace time runs out:

![image](https://github.com/user-attachments/assets/aa3b1527-509e-4225-8156-94512c339ee6)

When the check receives a failure signal:

![image](https://github.com/user-attachments/assets/306fa36d-093a-45b6-b695-70e1a10baab9)

@rwjack, @davidkcarey thoughts on this, does this help? 

Changing the contents of the subject line is risky, as people may already have email filters set up that look for the "DOWN" keyword. 

I thought about adding a more verbose paragraph explaining why a check went down. Something like:

> **Downtime Reason**
> The period of this check is **10 minutes** and the grace time is **5 minutes**.
> The last success signal was at **Nov 8, 06:50**.
> The next success signal was expected at **Nov 8, 07:00**.
> There was no success signal by Nov 8, 07:05, so this check has changed status to **DOWN**.

And even fancier way would be to show a visual timeline of (non-)events:

![image](https://github.com/user-attachments/assets/06b5ffbe-a33e-48cb-93cd-c410330aa000)

Problems with this:

* Need to track more information (as minimum, one additional date)
* The email notification gets longer. It gets harder to find information that the user is looking for.
* The visual timeline would be a PITA to implement given HTML email limitations

**Comment by cuu508** [comment]
@rwjack, by the verbose paragraph do you mean these?

> "{check_name}" is DOWN (success signal did not arrive on time, grace time passed).

and

> "{check_name}" is DOWN (received a failure signal).

I started with the email integration as it is the most used one, but once we settle on a pattern I'm going to gradually all other integrations to use same or similar pattern.

The issue I see with `[STATE] [MISSED GRACE] - check name` is for some users it would be unclear what "MISSED GRACE" means. You know it, and from the context in this issue I know it, but for a new user it could be confusing.

**Comment by cuu508** [comment]
Matrix messages support fair few HTML tags and attributes. I updated the message template to be similar to Signal, Telegram templates, and to include tags, schedule, last ping body, a list of other checks that are down.

Here's how it looks now:

![image](https://github.com/user-attachments/assets/04134119-cbbb-4413-90bd-9653c67a77ea)

I couldn't get two-column layout as in Slack and email messages. There are table tags, but Element renders the tables with borders and alternating row background colors, so not useful for layout:

![image](https://github.com/user-attachments/assets/b36891fb-f249-4c05-8d29-86a30817a07f)
