### ISSUE TITLE
dockerized healthchecks 3.6 - high cpu utilization, not in 3.4

### ISSUE THREAD

**Issue by heikoh81** [healthchecks/healthchecks#1071]
Hi,

I have a proxmox debian lxc container running debian 12.7, only for docker (fresh install).
I run portainer, mariadb, uptime-kuma and healthchecks.
There are 10 cronjob healthchecks that run only once a day (borgmatic backups).
As soon as healthchecks is running, proxmox is giving me a CPU utilization of 7-8%.
With stopped healthchecks, it is 1%.

I invoked healthchecks with the follow run-command:
`docker run -d \
  --name=healthchecks \
  -p 0.0.0.0:8001:8000 \
  --restart unless-stopped \
  -e ALLOWED_HOSTS=192.168.179.20 \
  -e DB=mysql \
  -e DB_NAME=healthchecks \
  -e DB_HOST=192.168.179.22 \
  -e DB_PASSWORD=secret \
  -e DB_PORT=3306 \
  -e DB_USER=root \
  -e DEBUG=False \
  -e DEFAULT_FROM_EMAIL=mail@example.com \
  -e PING_BODY_LIMIT=250000 \
  -e EMAIL_HOST=example.com \
  -e EMAIL_HOST_PASSWORD=secret \
  -e EMAIL_HOST_USER=mail@example.com \
  -e EMAIL_PORT=587 \
  -e EMAIL_USE_TLS=True \
  -e SECRET_KEY=secret \
  -e SITE_ROOT=http://localhost:8001 \
  -v /opt/dockerfiles/healthchecks:/data \
healthchecks/healthchecks:latest`

Also tried sqlite, same CPU utilization.
Inside the proxmox lxc center, top shows spikes of process phython3 using 30% for a very short time, which results in the average of 7% (that proxmox shows on the hourly average).

I also tried running healthchecks itself in a fresh lxc container (no docker), cpu utilization is 1% all the time.
(I did not manage all of the autostart things...)

Any ideas how to solve this?
Thanks,
Heiko

**Comment by heikoh81** [comment]
I tried older versions from Docker hub.
With 3.5.2, CPU utilization is still higher than expected.
With 3.4, however, CPU utilization is very fine. (Didn't try 3.5.1).

So what happened from 3.4 to 3.5.2?

See screenshot below, changed to 3.4 around 22:56:
![grafik](https://github.com/user-attachments/assets/943d72bc-ee5a-4a43-9eca-7131e8e0e721)

Inside portainer:
![grafik](https://github.com/user-attachments/assets/09eab7e8-aee7-49d6-87b2-eed9e34e5de6)

**Comment by cuu508** [comment]
Looking at changelog, in v3.5 I added a `HEALTHCHECK` instruction in the Dockerfile:

```
HEALTHCHECK --interval=10s --start-period=10s --retries=1 CMD ./manage.py fetchstatus
```

The `fetchstatus` management command fetches `/api/v3/status/` which in turns checks database connectivity.

When `top` is running you can press `c` to see the full command line of each process instead of just the process name. Perhaps you could use it to see if the python process causing spikes is in fact `python manage.py fetchstatus`?

**Comment by heikoh81** [comment]
Thanks for your reply.

I tested again with 3.6. Below is a screenshot of `top` with `c` pressed:
![grafik](https://github.com/user-attachments/assets/8d96417e-8400-47e9-a7cf-5651442582f4)

Below is another screenshot of my docker VM in proxmox. The increase to 8% - 10 10% is while 3.6 is running. 1.5% is before and after that with 3.4:
![grafik](https://github.com/user-attachments/assets/3e68cac2-cac5-4283-9c74-bf4a9890fcad)

First thought for solution: Can the `HEALTHCHECK` be configured to be enabled or disabled with an environment variable?
I hat 3.4 running for month without any problems and without the `HEALTHCHECK`.
I have a very small homelab installation with proxmox running on a Intel N100, that's why I noticed the increase of CPU consumption to 10 %.

**Comment by cuu508** [comment]
I rewrote `fetchstatus.py` (the script that runs every 10 seconds and checks if the webapp still has DB connectivity) to be a standalone script instead of a Django management command. Django management commands load a bunch of Django machinery every time they run; this should be faster. On my machine, in some quick, unscientific testing, it seemed to be ~5x faster.

**Comment by heikoh81** [comment]
Thanks, I'll test it as soon as the new version is available on Docker Hub.
Don't know how to build custom image from v3.8-dev commit.

**Comment by cuu508** [comment]
To build a custom image, you can clone the repo:

```
git clone https://github.com/healthchecks/healthchecks.git
```

Then `cd` into it and run `docker build` like so:

```
cd healthchecks
docker build -t healthchecks-dev -f docker/Dockerfile .
```

And it will build an image tagged "healthchecks-dev".

The `-f` flag is needed because the Dockerfile is not in the parent directory but in a subdirectory.

**Comment by heikoh81** [comment]
Thanks for the hint, this worked well and I learned how to build docker images.
CPU usage is much better, but still twice as high as with v3.4 (2x on N100).

I would prefer to have an environment variable to turn healthcheck off (default = healthcheck on).
Would that be possible?

I will now try to edit my local Dockerfile an set
`HEALTHCHECK --interval=3600s --start-period=3600s --retries=1 CMD ./fetchstatus.py`
I guess I could also just delete that line in Dockerfile?

**Comment by heikoh81** [comment]
Update:
CPU usage at 1,3%-1.4% with intervall=3600s
![grafik](https://github.com/user-attachments/assets/82e074d9-bbe7-4cfa-99bb-56eba686a4e3)

**Comment by heikoh81** [comment]
Update:
If I delete the line
`HEALTHCHECK --interval=3600s --start-period=3600s --retries=1 CMD ./fetchstatus.py` from Dockerfile
CPU usage is back at 1,2 %.
I still think an option to disable container healthcheck would be best solution.

![grafik](https://github.com/user-attachments/assets/855e19d6-954f-488b-b994-9cfbaece7290)

**Comment by cuu508** [comment]
I updated the `--interval` parameter to 60 seconds.

If you want to disable the HEALTHCHECK instruction completely, as an alternative to editing `docker/Dockerfile` you can also use your own Dockerfile which inherits from the official image. The contents of it would be:

```
FROM healthchecks/healthchecks:v3.7
HEALTHCHECK NONE
```

This way you do not need to keep a copy of the git repository with local changes in `docker/Dockerfile`.

**Comment by heikoh81** [comment]
Thanks for the hint with "own Dockerfile".
Worked very well, CPU usage is now below 1%.
