### ISSUE TITLE
running local docker build crashes missing libexpat.so.1

### ISSUE THREAD

**Issue by rophy** [healthchecks/healthchecks#1076]
healthchecks version: 3.5.2
build env: same results in both WSL2/Ubuntu 22.04, and a native Ubuntu 22.04 VM.
docker version (windows): 27.2.0, build 3ab4256

```bash
$ git checkout v3.5.2

$ docker build -t healthchecks -f docker/Dockerfile .

$ docker run --rm -it healthchecks
uwsgi: error while loading shared libraries: libexpat.so.1: cannot open shared object file: No such file or directory
```

On the same windows machine with WSL2, running dockerhub image works:

```bash
$ docker pull healthchecks/healthchecks:v3.5.2
v3.5.2: Pulling from healthchecks/healthchecks
Digest: sha256:f2a69426e7d0ad1b383d3de0c07e651e218d526765829aa46429132b0b1f4e9c
Status: Image is up to date for healthchecks/healthchecks:v3.5.2
docker.io/healthchecks/healthchecks:v3.5.2

$ docker run --rm -it healthchecks/healthchecks:v3.5.2
[uWSGI] getting INI configuration from /opt/healthchecks/docker/uwsgi.ini
[uwsgi-static] added check for static-collected/
*** Starting uWSGI 2.0.26 (64bit) on [Sun Oct 20 04:59:04 2024] ***
compiled with version: 12.2.0 on 21 August 2024 12:55:05
os: Linux-5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024
nodename: 3854b91f4244
machine: x86_64
...

**Comment by cuu508** [comment]
Thanks for the report, @rophy !

I was able to reproduce the problem (also with the current git version of Healthchecks, and also on the host system running Ubuntu 24.04). 

The docker base image we are using is `python:3.12-slim-bookworm`. It recently updated to python 3.12.7 and looks like something's been removed there. If I edit the Dockerfile to use `python:3.12.6-slim-bookworm`, the resulting image works.

**Comment by cuu508** [comment]
Ah, here's a commit from yesterday that removes libexpat dependency from python's Dockerfile: https://github.com/docker-library/python/commit/37a6827e0b7a9ef099cfdec5de305e3d4cea7331

**Comment by cuu508** [comment]
Upstream issue: https://github.com/docker-library/python/issues/984
