### ISSUE TITLE
Block spam requests

### ISSUE THREAD

**Issue by miskovicm** [healthchecks/healthchecks#1077]
Hello,

First things first: Thank you for the amazing piece of software.

### Issue

We are receiving a handful of spam attempts to use selfhosted `hc` app as a smtp relay.

According to our tests, these messages were never sent, which is correct.

Issue is that every message is received successfully and `hc` app returns `2xx` success code.

Sent email request:
```bash
$ sendEmail -f noreply@healthchecks.io -s "0.0.0.0:2525"  -t "abc@example.com" -u "Testing email from python" -m
```

Current behaviour:
```bash
Email was sent successfully!
```

Expected behaviour (550 error code in some form):
```bash
WARNING => The recipient <abc@example.com> was rejected by the mail server, error follows:
WARNING => Received:         550 5.7.1 Relaying to <abc@example.com> denied (authentication required)
ERROR => Exiting. No recipients were accepted for delivery by the mail server
```

### Proposal

Although I am not a python dev, according to the `aiosmtpd` [documentation](https://aiosmtpd.aio-libs.org/en/latest/controller.html#tcp-based-server), it appears to be possible by implementing `handle_RCPT` handle. Handle should block messages, that are not destined to the `hc` app domain.

**Comment by cuu508** [comment]
Thanks for the report, @miskovicm!

Are there practical problems caused by Healthchecks returning 2xx codes for all emails?

I suppose some spammers might give up sooner if their email is rejected.

**Comment by miskovicm** [comment]
The main benefit is to provide an expected outcome for the admin.

After install / update you want to make sure that smtp behaves as expected or perform integration tests.
Instead of seeing 550 error message, right now you have to search logs to verify that the spam requests were not relayed.

**Comment by cuu508** [comment]
Ah, thanks, that makes sense.

I added the `handle_RCPT` handler. It checks the local part of the email address, and returns 550 if the local part does not look like an UUID. It still allows any domain in the address, but I think the valid UUID requirement by itself will already take care of rejecting spam messages.

**Comment by miskovicm** [comment]
imho these are two different scenarios, which could complement each other.

Firstly, verify that the recipient is indeed my domain.
In my opinion, this is expected behaviour even when I send a message with the UUID format.

Secondly, check the UUID format as you recommend,
as the application provides functionality only for this specific format.

It will make logs cleaner as well.

**Comment by cuu508** [comment]
I tried to be lazy but you are right. 
I've now added a check for the domain part as well – if it doesn't match `settings.PING_EMAIL_DOMAIN`, the SMTP server will return 550.

**Comment by miskovicm** [comment]
Yes, I believe this is the best solution.

Thank you very much for your prompt response.

Looking forward to the next release!
