### ISSUE TITLE
Ping often returns 500 Internal server error

### ISSUE THREAD

**Issue by saschabrockel** [healthchecks/healthchecks#1078]
Hey there,

since I'm using the ability to measure script run time I have the problem that the normal ping after the start ping returns HTTP code 500. 

It returns:
`500 - "\n<!doctype html>\n<html lang=\"en\">\n<head>\n <title>Server Error (500)</title>\n</head>\n<body>\n <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n"`

It happens completely randomly. It works for several days and then crashes again once. There is no scheme.

I use n8n and a flow there and begin with a GET call to trigger the start of the measuring like http://unraid-server:8003/ping/7e6e9eab-a047-4fa6-849d-c8622a905f22/start and after everything run through (which can be very fast like <1 second but as well 16 seconds and I have seen error code 500 for both variants). For this case, I have already built some kind of catch trigger. If the confirmation of the ping fails, Healthchecks will call/trigger the process execution again.

![image](https://github.com/user-attachments/assets/6894906b-1b71-48df-a4fb-44a939b1b563)

It works but is annoying and I still the emails appearing like XYZ is down and then in 30 minutes it's up again. I would really like to know what is causing this behavior.

![image](https://github.com/user-attachments/assets/6da25c19-5242-4fa2-95db-bff9d3cb764d)

You can see here that this is the third time this specific monitor has been used this month. It happens for two other n8n processes randomly too. I have 29 monitors running. The others work fine. Is it something with n8n instead that it sends a faulty request sometimes? But why only with Healthchecks? I got 7 monitors at exactly 0:00 but I think this shouldn't be a problem.

I also see several 500 in the logs of the container:
`2024-10-20T23:05:01.187827901Z [pid: 12|app: 0|req: 9055/36259] 172.18.0.1 () {24 vars in 433 bytes} [Sun Oct 20 23:05:01 2024] GET /ping/xyz/start?rid=80de955c-0aee-4070-947d-038aee1a1b3b => generated 145 bytes in 8 msecs (HTTP/1.1 500) 7 headers in 240 bytes (1 switches on core 0)`

This is my WordPress cron runner that runs every 15 minutes and there I can imagine something does not always work perfectly but I'm still wondering because it is the /start command and isn't that something Healthchecks internal then? I mean the call.

I'm running Healthchecks original Docker image with Healthchecks v3.6.

**Comment by cuu508** [comment]
Are you using sqlite as the database? If yes, my hunch is this is same as #1057

**Comment by saschabrockel** [comment]
Yes, I'm using SQLite. If I find time I will switch to Postgres and see if it fixed it and tell you here. Thank you.

**Comment by cuu508** [comment]
I released v3.7 yesterday which includes a fix for #1057, you could also test that with your existing setup and see if 500s go away.

**Comment by saschabrockel** [comment]
Okay, I have updated it and will wait. I will tell you if it is fixed!

**Comment by saschabrockel** [comment]
Until today, nothing failed. Your new version with the included fix seems to work. If it should appear again, I will close this issue and reopen a new one with a reference.
