### ISSUE TITLE
[Feature Request] support being logged in to multiple accounts at the same time

### ISSUE THREAD

**Issue by seidnerj** [healthchecks/healthchecks#1105]
I have two accounts, one under my work email and another under my personal email. It would be great if one could stay logged in to multiple accounts and easily switch between their respective views ala-Google. 

I could then open multiple tabs showing projects from various accounts, now I have to use two different browsers in this use case.

Thanks in advance 🙏

**Comment by cuu508** [comment]
Any thoughts on how to make this work with Django?

I'm a Firefox user, and, as a practical tip, Firefox has built-in support for containers: https://support.mozilla.org/en-US/kb/how-use-firefox-containers

I use it, for example, with Fastmail: I am logged in two separate Fastmail accounts on the same browser, same browser window, but separate containers.

**Comment by cuu508** [comment]
> I admit I'm not sure how to implement this using Django but I guess one possibility is to prefix all cookies with some customer identifier and then depending on the target url, use either X or Y. Does that make sense?

That would be one part of the puzzle but I have no idea how to integrate it with Django's authentication and session framework. I'm afraid this is not feasible without huge effort.
