### ISSUE TITLE
Limit sign-up/log-in

### ISSUE THREAD

**Issue by elisiariocouto** [healthchecks/healthchecks#113]
Hello,
I'm giving this project a try and I'm running a docker container from [`haswalt/docker-healthchecks`](https://github.com/haswalt/docker-healthchecks) repository. I want to limit sign-up/log-in for only users with e-mails ending in `@mydomain.xyz`. Is this possible? If not, how can I manage the sign-up process?
Thanks in advance

**Comment by cuu508** [comment]
Hello,

at the moment there is no "official" way of limiting signups. Adding an email domain whitelist would not be too hard. 

Alternatively, we could add a "registration closed" flag in settings. With the flag set, existing users can sign in but new users cannot register. You would then explicitly invite users. If you have a number of users with company addresses but also one contractor with gmail.com address then this would work better.

Can you tell a bit more about your use case?

**Comment by elisiariocouto** [comment]
These two options sound nice and are not exclusive, but I'd rather go with the second one. Basically, we have a bunch of daily batch jobs that we need to monitor. We use G Suite so I would like to only open registrations for users with a whitelisted domain, but the "contractor" option seems that could happen anytime.

In other words, a registration flag should work.
Thanks

**Comment by cuu508** [comment]
@elisiariocouto I've just added a `REGISTRATION_OPEN=True` setting which you can override in `local_settings.py`. 

After you close new user registration, create a new superuser account with `manage.py createsuperuser` command. The new superuser will have "team access" privilege enabled by default. You can then use this superuser account to invite more users into the system: go to "Account Settings -> Invite a Team Member"

**Comment by elisiariocouto** [comment]
Amazing @cuu508! Thanks and congratulations for the project 👍
