### ISSUE TITLE
Save/Display Mailbody

### ISSUE THREAD

**Issue by maltetgh** [healthchecks/healthchecks#116]
There a numerous applications for health checks which would require me to be able to confirm the email address on the first ping. To be able to do this I would need the option to display the mail body in the log.

Use case examples:
Filter "Backup OK" email in Gmail and forward/archive to healthchecks so that I would be notified if the Backup OK Message won't arrive -> Not possible because I can not get the verification code which google requires to initialize the forwarding address.

Process Amazon SNS Notifications
URL -> Not possible, requires verification
E-Mail -> Same problem, I would have to click on a verification link. 
I would use SNS for example to notify me every day after the new backup file arrived in S3.

Thanks 👍

**Comment by cuu508** [comment]
Hey @maltetgh, thanks for the report. These are good use cases, and I would definitely want healthchecks to support them!

The primary reason we're not saving mail body (or HTTP POST body) at the moment is to save space in database and keep everything small. Operations are simpler when the database size is measured in megabytes not gigabytes...

I will throw out some ideas on what to do here:

- for each received ping start storing the mail / http request body. Probably just the first kilobyte or first 5 kilobytes or something like that. Cons: database size goes up, more data to juggle
- for each check, only store the most recent mail / http request body. Cons: if multiple sources are pinging a check frequently, it might be hard to catch the moment when it has the confirmation message
- "auto-approve" some hardcoded types of confirmation messages, like these from Gmail and SNS. Cons: complexity, doesn't solve the general problem

**Comment by cuu508** [comment]
I decided to go with the second option -- for each check, save and expose the most recent request body. It is implemented, deployed and ready for testing!

When a request body contains the string "confirmation" healthchecks.io shows a green label like so:

![screenshot from 2017-05-09 16-48-33](https://cloud.githubusercontent.com/assets/661859/25854221/f58b3f0e-34d7-11e7-9fbd-d6c303befd4b.png)

Clicking on the timestamp / label opens a modal dialog with more details:

![screenshot from 2017-05-09 16-48-55](https://cloud.githubusercontent.com/assets/661859/25854253/02fb61be-34d8-11e7-8068-abc19d709057.png)

Here, you have to fish out the confirmation link from the raw message body. Not ideal UX, but at least it's possible to do. 

From a quick testing, I was able to set up Gmail forwarding, AWS SNS notifications to email and AWS SNS notifications to a webhook address.
