### ISSUE TITLE
[off] Nodequery

### ISSUE THREAD

**Issue by szepeviktor** [healthchecks/healthchecks#119]
Have you seen https://nodequery.com/ ?

**Comment by szepeviktor** [comment]
Excuse me, it does not seem to be a good idea.

But it has very good design!

**Comment by cuu508** [comment]
Yeah, it does have nice design. And UI polish is something that can always be improved further.

For the last few weeks I've been focusing on infrastructure--how services get deployed, how healthchecks.io server failures are handled etc. I was switching cloud providers which didn't go as smoothly as hoped. I will be doing some more work on infrastructure. New features and UI refinements will have to come afterwards.

**Comment by szepeviktor** [comment]
@cuu508 I would be gladly contributing for that.
As for cloud providers:
https://github.com/szepeviktor/wordpress-speedtest/blob/master/README.md
As for monitoring:
https://github.com/szepeviktor/debian-server-tools/tree/master/monitoring/monit/services
As for software:
https://github.com/szepeviktor/debian-server-tools/blob/master/debian-setup.sh#L29-L65
