### ISSUE TITLE
Telegram integration not working with supergroups

### ISSUE THREAD

**Issue by hackedbellini** [healthchecks/healthchecks#123]
The telegram integration is working great! I can integrate with a single user or even add the bot to a group and it will message me/us everytime a check fails.

But when adding the bot to a supergroup it will not work. I try to `/start`/`/start@bot_name` and it will simply not reply to me.

**Comment by cuu508** [comment]
I think I've fixed it, @hackedbellini can you please try again?

**Comment by hackedbellini** [comment]
@cuu508 wow, how fast! Just tested and it is working, thanks!
