### ISSUE TITLE
Automatically assign checks to integrations

### ISSUE THREAD

**Issue by hackedbellini** [healthchecks/healthchecks#124]
After you create an integration (email/pushover/telegram/etc) it will not assign new checks automatically to it and you have to do that manually.

That is a huge problem when you have lots of checks and lots of them are created every time. For example, in the company that I work we use healthchecks for some services that we deploy. We usually create ~10 new checks per week using the api (i.e. it is not created manually). That means that from time to time I have to go to the integrations page and manually assign the missings checks to all the integrations that I have there.

I understand that there are some people that probably wouldn't like the "auto async" thing so my suggestion is to make that configurable for each integration: Add a checkbutton there to verify if "New checks should be automatically assigned".

**Comment by cuu508** [comment]
Hi Thiago,

one of the parameters for "Create a check" API call is "channels". If you set it to "*", the check will be assigned to all existing channels. By setting this field, you can match the UI behavior: when a check is added from UI, it is assigned to all existing checks. 

Would the `"channels": "*" ` help your use case?

**Comment by hackedbellini** [comment]
@cuu508 oh, I didn't know about that `channels`. Yes it worked great! Marking this as closed, thank you!
