### ISSUE TITLE
C# usage example

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#127]
```
using (var client = new System.Net.WebClient())
{
       client.DownloadString("ping url");
}
```

I know nothing about C#. Does the above look OK?

**Comment by taylus** [comment]
For pinging a check? Yeah, that's the way to do it.

There's a newer class called HttpClient which you might see around, but it's not a straight replacement and both are still widely used.

http://www.diogonunes.com/blog/webclient-vs-httpclient-vs-httpwebrequest/
https://stackoverflow.com/questions/20530152/need-help-deciding-between-httpclient-and-webclient

**Comment by rud** [comment]
Looks legit, issue seems possible to close now?

**Comment by cuu508** [comment]
Yeah, I'll add an usage example and close this issue when that's done.
