### ISSUE TITLE
Graphical display or running crons

### ISSUE THREAD

**Issue by oguzy** [healthchecks/healthchecks#128]
It might be great if the crons are also displayed on a graphical interface with timelapping and durations. I am not sure if there is a solution but the current repo does not has a solution for it.

**Comment by cuu508** [comment]
Hey @oguzy, are you thinking about a visualization of a cron schedule when user enters a cron expression? Something like a timeline view with expected run "windows" colored in?

**Comment by oguzy** [comment]
No the expected but the overall timeline window of all running cron. That can help to see the most busy hours, overlap ones.

**Comment by cuu508** [comment]
There is a similar issue (#443), so I'll close this one.
