### ISSUE TITLE
MS Teams Integration

### ISSUE THREAD

**Issue by KazuyDarklight** [healthchecks/healthchecks#135]
MS Teams have a lot of bot integration for services similar to Healthcheck, it might be nice to join the bandwagon there.  I've got work arounds in the meantime though.

**Comment by tommydejong** [comment]
+1 on this! @KazuyDarklight, what kind of work arounds have you implemented?

**Comment by KazuyDarklight** [comment]
@tommydejong You can send messages to Team Channels via email. (https://blogs.technet.microsoft.com/skypehybridguy/2017/08/26/reduce-email-with-microsoft-teams-how-and-why-to-do-it/) It generates a random email address that you can revoke. So if you are comfortable with the security by obscurity aspect of that then you can just drop it into HealthCheck's email integration and call it a day. If you'd rather keep it a bit more locked down then I would restrict it to your work domain or team, have it come to your email and then set an email rule to forward messages from HealthChecks to the desired channel address, since the forward is coming from you it should go through.
