### ISSUE TITLE
Allow reordering of listed checks

### ISSUE THREAD

**Issue by danemacmillan** [healthchecks/healthchecks#136]
Every now and then I add a new check that would better fit higher up within a given tag. I'd like to be able to reorder the order in which checks are listed. Drag or drop, or simply assigning numbers to checks would suffice. Even just allowing us to sort alphabetically by the name of the check would effectively provide enough power to provide the desired sorting order.

**Comment by cuu508** [comment]
I've been thinking about this as well. As the number of checks in an account goes up, it gets increasingly chaotic.

One option I'm thinking about is to add sorting by different fields: name, status, last ping date, date created. Either sort using list headers or have a separate "sort order" selector, and and save the last selected sort order with user's profile.

Out of interest, in what cases would you want the sort order be arbitrary and specified manually? Would it be for grouping checks together by their project / host system / role?

**Comment by danemacmillan** [comment]
> Out of interest, in what cases would you want the sort order be arbitrary and specified manually?

I would probably never want the sorting to be arbitrary. As they are currently, they're sorted by the order in which they're defined, which is a good default. Sorting by name would be the most useful for me, but if the task of adding sorting to any number of headings once the problem is solved initially becomes trivial, I would probably sort by "Last Ping" from time to time just because I could. Ultimately, though, I think sorting by name would be biggest quality of life win for me.

Requesting the ability to sort by name has really grown out of the increase in the number of checks I now have (31). As you've mentioned, it gets chaotic after a while, especially when you think of a new check and have some mild OCD that would prefer placing the check alongside, or injected between two other checks. For example, I recently added a schedule for resizing our application group instances based on the day of the week and the hours of the day. I have three base rules that run every day, and then more specific rules that run from Sunday to Saturday. In describing these checks to you, I've described them in a meaningful order; unfortunately, I didn't define them in precisely that order, so the days of the week are not in order, and nor are the general rules that run daily. The schedule grew organically. For this example, being able to sort by their name, or some other property that makes customizing the order possible, would restore order and make it easier to skim.

> Would it be for grouping checks together by their project / host system / role?

I use tags to group by the type of checks, but even if I just selected a tag group, most checks would be out of order, because of the organic nature of creating new checks.

**Comment by cuu508** [comment]
I've added sorting by name and by last ping. Default sort order is still "oldest first". Clicking on table headers cycles through ascending/descending/"use-default-sort-order" modes. The site remembers and uses user's sort preference.

Please let me know if you have ideas on how to improve this further, UX-wise.

**Comment by danemacmillan** [comment]
This is fantastic! It behaves exactly as it should. It's simple, no JavaScript, and fast. I couldn't ask for more, but if I think of anything, I'll let you know.

**Comment by danemacmillan** [comment]
One thing I've noticed is that it does not do natural sort. For example, it will sort the a sort of ten items like this:

```
10
1
2
3
4
5
6
7
8
9
```

It's minor, and can be adjusted by prepending `0` to each single number, but I thought I should mention it.
