### ISSUE TITLE
Cant find the Discord integration

### ISSUE THREAD

**Issue by TheFonix** [healthchecks/healthchecks#138]
So ive built the HealthCheck app locally but cant seems to find the Discord integration option? Am i missing something here?

Thanks!

**Comment by cuu508** [comment]
Hi @TheFonix,

have you set `DISCORD_CLIENT_ID` and `DISCORD_CLIENT_SECRET` settings in the `local_settings.py` file? 

You can create your Discord API credentials here: https://discordapp.com/developers/applications/me

**Comment by TheFonix** [comment]
Ah perfect! Thank you!

**Comment by TheFonix** [comment]
So i added them all in & Woo, the integration button pops up, but when i click the `Connect discord` button it directs me to the discord page & tells me there was an unknown error? :(

as seen here
https://imgur.com/CZAWBEQ

**Comment by cuu508** [comment]
When setting up the Discord app, did you specify a redirect URI?

If you're experimenting locally, and your server is running on localhost:8000 then use the correct redirect URI would be `http://localhost:8000/integrations/add_discord/`

**Comment by TheFonix** [comment]
I still seem to get the same issue, im running it globally now, which can be accessed through https://sanity.corinthmc.com Its running through a reverse proxy on Nginx

**Comment by TheFonix** [comment]
in the redirects i currently have `https://sanity.corinthmc.com/integrations/add_discord/` just for reference

**Comment by cuu508** [comment]
The redirect URL looks fine. Can you show the URL of the page with "UNKNOWN_ERROR"?

**Comment by TheFonix** [comment]
The URL is directs me to is:
```https://discordapp.com/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fsanity.corinthmc.com%2Fintegrations%2Fadd_discord%2F&client_id=369875152080470016&scope=webhook.incoming&state=lumeMSbI9KHM```

**Comment by cuu508** [comment]
The discordapp.com URL looks good too... 

Another thing to check: when you are on the UNKNOWN_ERROR page, open developer tools and in the Network tab look for a `authorize` call and see what status code and response body it returns.

As an example, here's what I get if I change redirect_uri slightly:

![image](https://user-images.githubusercontent.com/661859/31811793-8c1930b6-b589-11e7-99c8-7eb4e75436f5.png)

**Comment by cuu508** [comment]
Realized I can take the URL you posted and check this myself.

The error message for your URL is "Invalid OAuth2 redirect_uri" too. 

Can you double check that the redirect URL in the Discord app is indeed `https://sanity.corinthmc.com/integrations/add_discord/`? The http / https in the protocol matters. If you had created several Discord apps, make sure you're ussing the correct `client_id`.

**Comment by TheFonix** [comment]
Oh my goodness! After far too many hours of working on this it was down to the reverse proxy i was using not correctly applying SSL to the URL, Thank you so much for all of your help!

**Comment by TheFonix** [comment]
So, just to keep you on your toes, i got the bot to join discord & i deleted the channel for it to post to but sadly it doesn't send any messages to the discord when something goes down or comes up, ive check through all the settings in the online page, but they are all set to alert when the service goes down, & ive double checked the bot has read & write permissions to the channel its using, anything else im missing here?

Sorry to be a pain

**Comment by cuu508** [comment]
No worries, just means there's more work to do on documentation side here ;-)

First thing to check: do you have `manage.py sendalerts` command running? It's the command responsible for monitoring check states and sending alerts. In a server environment I would use either supervisor or systemd to start it up and keep it running. For testing purposes you can just run it in a shell or a screen session. 

https://github.com/healthchecks/healthchecks#sending-emails

**Comment by TheFonix** [comment]
So, im not able to see it running & doing `/manage.py sendalerts` Returns this:
```
root@SANITY-CHECKER ~/webapps/healthchecks # ./manage.py sendalerts
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
```

**Comment by cuu508** [comment]
Looks like the virtualenv is not activated. Try this:

    $ cd ~/webapps
    $ source hc-venv/bin/activate
    $ ./manage.py sendalerts

For supervisor & systemd you would use a command like this:

    /root/webapps/healthchecks/hc-venv/bin/python /root/webapps/healthchecks/manage.py sendalerts

The above command is using virtualenv's python executable, instead of the system-global python.

**Comment by TheFonix** [comment]
Yep that fixed it! Can confirm updates are now being sent through discord and email! Thanks man :)
