### ISSUE TITLE
Reverse healthcheck - Signal

### ISSUE THREAD

**Issue by Braintelligence** [healthchecks/healthchecks#144]
Hi everyone!
Is there a way to set up kind of a "reverse" healthcheck? Like, not watch a regularly incoming ping but rather a single ping that is meant as a warning-trigger?

For example I have a machine that I am monitoring by pinging every 5 minutes but I also want it to be able to ping me when it rebooted for some reason only once, and by doing so, triggering a warning.

So instead of a "ping regularly for relaxation" I want to be able to "ping once for danger".

Is this possible?

**Comment by cuu508** [comment]
This is an interesting use case. 

There is not specific support for it, but you can use the regular checks and it sort of works: set up a new check, and set its period and grace time both to 1 minute. Its normal, default state will be "down". And it will flip to "up" for a short time each time it is pinged.

When you ping this check, you will immediately get a "<name of the check> is UP". Two minutes later you will get "<name of the check> is DOWN". Each time you see this pair of messages you will know the machine had rebooted.

If you send a ping during a shutdown, you could name the check "Machine Shutdown Process". And if you call it during boot, name the check "Machine Boot-up" so the wording in notifications make at least some sense...

It's not ideal that you would be getting two notifications, and the wording in the notifications also would not be the clearest, but this is something you can use today.

**Comment by Braintelligence** [comment]
Actually the machine doesn't shutdown properly when this happens.
To be more precise: I have machines running unstable applications, that MAY just crash at some point. When this happens they just reboot but they don't restart the processes by themselves (which is wanted this way).

So I want to know if they run properly after their processes were started by hand and I want to know ASAP when they rebooted by themselves.

Your hint was great, I'll incorporate it!

**Comment by Braintelligence** [comment]
(Though it would be really cool if we had the option to create such "signals" as well in the future 😸)

**Comment by Braintelligence** [comment]
Oh and as another possible enhancement:
If there are green checks for a tag and also red checks for a tag, then I'd like for the check-tag to be yellow instead of red, so I'd know that SOME stuff is working, while others is not.

**Comment by cuu508** [comment]
> If there are green checks for a tag and also red checks for a tag, then I'd like for the check-tag to be yellow instead of red, so I'd know that SOME stuff is working, while others is not.

Are you thinking of the tags in "My Checks" screen or the badges in Account > Badges?

For the latter, I've had an idea about optionally showing the badges like this:

    [production | 5 up | 2 down]

instead of just 

    [production | up] 

or

    [production | down]

**Comment by Braintelligence** [comment]
On the "My Checks" part, where below the checks are listed.

Showing the tags like you proposed would be even better. This way I could have something like:

```
[rebooted | 5 down]
```

Then if I have 5 machines, I know none have rebooted in the last X timeframe.

**Comment by cuu508** [comment]
I've been playing around with the badge styling, trying to incorporate the "5 down" bit in them. It's not easy to add the extra information without making the tags area look busy and noisy. Especially for accounts that use dozens of tags. So for now I'll leave the tag area as-is.

PS. There have been a couple related changes & improvements though:

* Failed checks are always shown at top, so they are to notice
* The page title shows "X down" if any checks are down. The title does auto-refresh
* Filtering by tags was semi broken but works correctly now. If any tag is red, you can click on it and easily see all matching checks.

PPS. On the original issue about triggering failures, that's been implemented, check out "Signalling a Failure" in https://healthchecks.io/docs/
