### ISSUE TITLE
Model changes missing corresponding migrations

### ISSUE THREAD

**Issue by iphoting** [healthchecks/healthchecks#145]
I think there might be missing a migration for this change-set cb1eac50d98aa161c4ad7f888bd3be44cec030d1 (PagerTree) and one other change-set touching accounts, which I couldn't locate?

I'm getting the following notice when I do a pre-deploy executing `python manage.py migrate`.
```
$ python manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, api, auth, contenttypes, payments, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
Running `makemigrations` got me the following new files:
```
	hc/accounts/migrations/0014_auto_20171227_1456.py
	hc/api/migrations/0034_auto_20171227_1456.py
```

Hope this helps!

**Comment by cuu508** [comment]
You are right -- thanks!

I think neither of the migrations change anything in the database, but it is good to have them to avoid the above warning and for the completeness sake.

**Comment by cuu508** [comment]
PS the other changeset is this one: https://github.com/healthchecks/healthchecks/commit/f611a23f0bd5d9d83cff349a86313f6d25191bbf

I had added a `related_name` parameter on `Member.user` field but had not created a migration for it.

**Comment by iphoting** [comment]
Thanks for the quick response.
I was wondering, had the migrations not been created and applied to the database, and should a PagerTree integration be added, wouldn't it crash the app?

**Comment by cuu508** [comment]
The live site at https://healthchecks.io has the PagerTree integration, but doesn't have these two migrations applied yet. It seems to be working OK. 

If I understand it correctly, neither migration makes any changes to the database (no altered columns, constraints, indexes or anything like that), they just bring the migration history in sync with the model classes defined in `models.py`. And if the model classes and the database structure match up, it works.
