### ISSUE TITLE
Reverse webhooks - healthchecks pinging web services

### ISSUE THREAD

**Issue by Braintelligence** [healthchecks/healthchecks#146]
Hi everyone!

Is it possible to set up healthchecks, so instead of listening for a ping it would ping web services itself and see if they're online and responding?

**Comment by cuu508** [comment]
Thanks for the suggestion. There are services that do exactly that and do it well -- UptimeRobot, StatusCake, Pingdom etc.

At least for time being I would like to keep healthchecks focused on monitoring regular tasks and sending alerts when the pings stop.

**Comment by Braintelligence** [comment]
Big thangs for the namedrops, I'll look into those 👍

**Comment by Braintelligence** [comment]
@cuu508 Again big thanks for mentioning those services. I chose StatusCake and used the free account tests to incorporate webhooks to my healthchecks-instance. Thus not only achieving what I wanted but also creating kind of a Telegram integration to StatusCake 👍 

Did you work with Icinga yet? Looks like a possible self-hosted solution to StatusCake to me. Maybe gonna try it soon.
