### ISSUE TITLE
Problem with telegram

### ISSUE THREAD

**Issue by retraut** [healthchecks/healthchecks#147]
I up and running healthckecs.io on my website.
Everything is fine, you have done a lot of work, product is great, but I have some problems with setting up telegram integration.
I have added `TELEGRAM_TOKEN, TELEGRAM_BOT_NAME` to my settings.py. 
I have set webhook url with

```
healthchecks@56373e540a6c:/healthchecks$ python3 ./manage.py settelegramwebhook                                                                                
Done, Telegram's webhook set to: https://healthcheck.servonline.xyz/integrations/telegram/bot/
```
When I get telegram update from getWebhookInfo i have next error 

```
{"ok":true,"result":{"url":"https://healthcheck.servonline.xyz/integrations/telegram/bot/","has_custom_certificate":false,"pending_update_count":2,"last_error_date":1515392356,"last_error_message":"Wrong response from the webhook: 400 Bad Request","max_connections":40}}
```

What I do wrong?

**Comment by cuu508** [comment]
Hi @retraut, as a troubleshooting step, can you try the Telegram integration on https://healthchecks.io? Try to set it up for the same user/group/supergroup as you tried before and see what happens?

**Comment by alex-phillips** [comment]
I'm getting the same issue. 400 response to the endpoint `/integrations/telegram/bot/` but with no body so no idea what the error is. Is there a way to find some logs to help figure out what is going wrong?

**Comment by cuu508** [comment]
@retraut @alex-phillips can you please share some details about your setup?

Is healthchecks running on a server, or on your local machine? Are you using a reverse proxy, and what kind? Are the SITE_ROOT and ALLOWED_HOSTS values in local_settings.py correct and matching?

The `settelegramwebhook` management command prints out the fully qualified webhook URL. If you open it in the browser, do you get response code 405 (Method Not Allowed) or something else?

**Comment by alex-phillips** [comment]
@cuu508 I am running this on a server in a docker container (you can see the container here: https://github.com/linuxserver/docker-healthchecks). It is behind an nginx reverse proxy and my `SITE_ROOT` and `ALLOWED_HOSTS` are set up properly. I am able to hit the fully qualified URL and I do get a 405 response.

**Comment by cuu508** [comment]
Found and fixed an issue where healthchecks would respond with HTTP 400 if there's no `text` field in webhook's payload. That would happen for example when adding or removing members from a group.

**Comment by cuu508** [comment]
I think I found the root problem: `settelegramwebhook`, as written, was subscribing for all update types, but we are only interested in one. When receiving a telegram update of an unexpected type 400's were thrown.

@retraut @alex-phillips I've just commited a fixed settelegramwebhook command. Please run it again, and see if you are still getting 400 errors. They might continue for a short period of time until Telegram "gives up" on any already created updates.

**Comment by alex-phillips** [comment]
Upgraded the software and now the logs aren't showing any requests (failed or otherwise) to the endpoint. Still 405 if I hit it directly.

**Comment by cuu508** [comment]
Did you send a "/start" or "/start@YourBotName" command in the Telegram chat?

**Comment by alex-phillips** [comment]
I did and clicked through to the integration page

**Comment by cuu508** [comment]
OK, then it sounds like you're set -- after confirming the integration, it should show up on Integrations page. 
Next, if `sendalerts` management command is running, when a check goes up or down, you should be getting Telegram notifications.

I did not see `manage.py sendalerts` being run anywhere in https://github.com/linuxserver/docker-healthchecks but maybe I'm missing something...

**Comment by alex-phillips** [comment]
Ooo, I got it. I thought the sendalerts was done automatically. Looks like I should just add it to cron (maybe run every minute?) and it should work. If I run it manually, it is working fine.

Thanks for the help!

**Comment by alex-phillips** [comment]
(or is `sendalerts` a daemon and just run continuously?)

**Comment by cuu508** [comment]
Yes, you can put it in cron. Use `manage.py sendalerts --no-loop` in that case. Note that if you run it every minute, the notifications could arrive up to a minute late. Might not be a concern, but something to keep in mind.

You can also run it as a systemd service, or use supervisord. Or, if you're going to use uwsgi, a neat way is to use uwsgi's `attach-daemon` directive, and it will take care of keeping the `sendalerts` process alive.

I will think about adding a "Degraded service: notifications may be delayed" (or something along those lines) message in the website whenever `sendalerts` is not running. That would make this issue easier to troubleshoot.

**Comment by alex-phillips** [comment]
Sounds good! I'll set it up as a service. Thanks again for the help, love the project!
