### ISSUE TITLE
Allow to submit a "fail" ping

### ISSUE THREAD

**Issue by pladen** [healthchecks/healthchecks#151]
It would be great to add the option to submit a "fail" status for a ping
In my use case we run quite a long daily script. I want to know if it runs and if everything is ok.

Cronalarm.com has such a feature. It allows to also submit a short text message like "error occurred at step X"

From API point of view it can be like 👍 
```
curl https://hchk.io/9e525010-64ba-42ea-91aa-db5c7b7598b4/fail
```
Optional text message can be submit via POST data

Regards

**Comment by mlaitinen** [comment]
How this would work if the "regular" ping overrides the failed status on the next run? My point:

10:00 OK (green light)
10:05 OK (green light)
10:10 OK (green light)
10:11 FAIL (red light)
10:15 OK (green light again despite of failure a few minutes ago)

**Comment by pladen** [comment]
Yes, that seems  great.
That's how cronalarm.com is handling it.

The purpose is to give feedback about what's wrong, not to replace logs / alerting system.

Regards

**Comment by cuu508** [comment]
I've now added this as an experimental feature: you can append "/fail" to any ping URL and cause the check to immediately go into the "down" state. If its previous state would have been "up", then a notification is sent as well.

I have not yet updated documentation or examples anywhere – I want to trial this feature for a while to make sure there are no corner cases where it does the wrong thing. @pladen and @mlaitinen you are welcome to test it out, both https://healthchecks.io and https://hchk.io are up-to-date.

**Comment by pladen** [comment]
Thanks, will test that.

**Comment by pladen** [comment]
i can confirm it works as expected, thanks !
