### ISSUE TITLE
sendalerts not sending notificaions

### ISSUE THREAD

**Issue by mgeorgy** [healthchecks/healthchecks#156]
I'm using healthchecks in a development environment and am able to send login emails, however, notification emails are never sent.  I'm assuming the notifications flow uses the same configuration so not sure why this isn't working properly.

**Configuration:**

- Ubuntu 16.04 Server
- Nginx Reverse Proxy
- sendalerts is running via a Systemd service process
- Single Test Check - (checked in once) with a poll period of 1 minute and grace of 1 minute.
- User account is configured to 'Remind me hourly'

**Expected Behavior:**

- Hourly E-Mails send while checks fail

**Actual Behavior:**

- No E-Mails Send
- Console Reports: Alarm (icon); Last ping - '12 hours ago'

**Comment by cuu508** [comment]
You are right, `manage.py sendalerts` is using the same email settings as the main app. 

First thing to check would be the output of `manage.py sendalerts` command to see if it throws any errors: `journalctl -f -u sendalerts-task-name`

Also, healthchecks will not send alerts to unverified email addresses -- in the web UI, "Integrations" page you can check if there is "(unverified)" next to the email address.

**Comment by cuu508** [comment]
PS. the hourly/daily reminders are sent by `manage.py sendreports`. If you are looking for the reminders, this command needs to be running as well.

**Comment by mgeorgy** [comment]
Thank you.  sendreports worked!

Is it ideal to run this as a cronjob?

**Comment by cuu508** [comment]
Good stuff!

Yes, running it as a cronjob is fine. Or, for consistency, you can run it as a systemd process, same way as `sendalerts`. In that case, you would run it with the `--loop` flag: 

    `manage.py sendreports --loop`

**Comment by mgeorgy** [comment]
Perfect!  Thanks again.
