### ISSUE TITLE
Consider integrating with notifiers 

### ISSUE THREAD

**Issue by liiight** [healthchecks/healthchecks#162]
Hi, I'm the author of [notifiers](https://github.com/liiight/notifiers). I apologize for the shameless self plug but I feel like your project could very much benefit from mine, as it makes integration with 3rd party notifers a breeze.

If you'd consider using it I'd very much appreciate it!

**Comment by cuu508** [comment]
Thanks for the tip!
In my experience, constructing the correctly formatted HTTP request for sending a notification has not the hard part. The hard part has been figuring out user onboarding (say, user wants to receive notifications in Telegram. How do we acquire the required credentials for posting to the user via Telegram API?), which is slightly or significantly different for each provider. Also making sure the messages use rich format where available, and look good on the other side.
I think notifiers is a neat project, but is not the perfect fit here.
