### ISSUE TITLE
Question: why not use Django's logging?

### ISSUE THREAD

**Issue by coaxial** [healthchecks/healthchecks#168]
I hope this is the right place to ask. I was going through the app's code when trying to figure out why it's not printing anything to the console when run as an s6 service within a Docker container.

I see you're doing things like 

```python
self.stdout.write("sendalerts is now running\n")
```
(https://github.com/healthchecks/healthchecks/blob/master/hc/api/management/commands/sendalerts.py#L90)

If I use Django's logger here instead, I get the output to my console. I don't know much about Python or Django and couldn't figure it out from reading the code: why not use Django's loggers here?

**Comment by cuu508** [comment]
Management commands originally used simple `print()` statements, and latter switched to `self.stdout.write` as that's what's recommended in Django docs:

https://docs.djangoproject.com/en/2.0/howto/custom-management-commands/

> When you are using management commands and wish to provide console output, you should write to self.stdout and self.stderr, instead of printing to stdout and stderr directly. By using these proxies, it becomes much easier to test your custom command.

If I run a management command locally, I see this output printed to console. In production I run it as a systemd service and can see the messages with `journalctl -u sendalerts` (assuming the service is named "sendalerts").

Have you made any changes to the logging configuration in settings.py or local_settings.py?

**Comment by coaxial** [comment]
I found out what the issue was. I didn't set the `PYTHONUNBUFFERED` env var nor did I use the `-u` option for Python  (cf. https://docs.python.org/3/using/cmdline.html#cmdoption-u)

Because of that, anything from stdout.write was buffered and wouldn't show until it reached the buffer size (1024 I suspect).

Setting the env var solved it.
