### ISSUE TITLE
Are releases still published?

### ISSUE THREAD

**Issue by coaxial** [healthchecks/healthchecks#169]
I'm dockerizing healthchecks and would like to pin the version I'm using for consistency.

The last release is v1.0.4 but it's over a year old. Are releases still used or is it better to pin version to a particular commit instead?

**Comment by cuu508** [comment]
It would be better to pin to a particular commit.

I used releases for a short period of time when I investigated using Docker & Dokku for deployments. What usually happens is I want to push updates to at least some servers after almost every commit -- release early, release often. If I was going to use releases, I would need to create a release after almost every commit, which adds overhead to operations.

**Comment by coaxial** [comment]
Noted, thank you.
