### ISSUE TITLE
[FEATURE REQUEST] Read-only rights

### ISSUE THREAD

**Issue by mlaitinen** [healthchecks/healthchecks#172]
It would be very cool to be able to create a user with read-only rights to the alarms.

Use case: we'd like to have a screen (possibly raspberry pi powered) in our room displaying the healthchecks' status. I wouldn't want to login as a user that has also the rights to create and manage the monitors.

**Comment by cuu508** [comment]
Hi,

we have tag badges with public but hard-to-guess URLs, you can find them in Account Settings > Badges. It would be easy enough to set up a page that lists them, and automatically refreshes itself from time to time.

Are per-tag badges not specific enough, and you want to monitor the status of each individual check?

Some people have set up their own dashboards that use "Get List of Existing Checks" API call to poll statuses. This requires custom coding but lets you build a custom dashboard which pulls information from many different sources.

There have been requests about having a "kiosk" mode before, and this sounds like a similar use case, I will think about that.

**Comment by 1activegeek** [comment]
I'd like to propose this enhancement be re-opened. While I've been able to do some basics with the badges (thank you!!) - I think it would offer a more robust usage of the API itself as well as the information available. I'm building a basic status dashboard that would be publicly/externally hosted where the page source can be seen (JS in browser loading). In this case I'd like to be able to insert read-only credentials to give me the details of the checks, but remove options like deleting, creating, altering the current checks.

It would also be useful to allow having other team members have access to pull this data with the API, but restrict their usage away from being able to modify/alter anything. This would be extremely useful in my opinion.

**Comment by cuu508** [comment]
Makes sense, I'm thinking about two possible feature additions:

* in addition to the current account-wide API key, allow creating a separate, read-only, API key. It would work the same but only be able to do GET requests (no creating, updating, pausing, deleting checks).
* for team members, allow setting permissions to either "full access" or "read only". There's a similar issue #183 about this too.

**Comment by 1activegeek** [comment]
I would totally agree - the read-only type API option affords much more flexibility for many use cases even beyond my own I'm sure. The read only option for users was an ancillary thought I had, so I'd agree that may have some additional use as well.

**Comment by cuu508** [comment]
Just FYI, read-only API keys are now available.

(Still think read-only team members is a good idea, but that's not yet implemented.)

**Comment by cuu508** [comment]
I'll track the work on more fine-grained access rights in #183, and so will close this issue.

**Comment by 1activegeek** [comment]
Awesome work! Thank you very much. The read only API is great for now!
