### ISSUE TITLE
sort checks by status in UI

### ISSUE THREAD

**Issue by thisisshi** [healthchecks/healthchecks#173]
Hi, this is a great tool that I've been using for monitoring our cron jobs, one feature that would be great to add would be to sort checks by status: (failed | OK | pending). Right now, I find my self scrolling through my hundreds of checks to find the failed one. Tags work to some degree to narrow down where the error is but I have multiple crons running that fall under the same tag so it's still hard to diagnose at times at a glance.

Thanks

**Comment by cuu508** [comment]
Thanks, this is a good idea. To be honest, with only ~30 checks in my personal account, I don't have a good grasp on what the pain points are for the "heaviest" users. So feedback like this is very welcome.

I've been thinking about this, and how this would be implemented without major changes to the current sorting UI. I'm leaning towards **always showing the failed checks at the top**. Any failed check should be a priority to fix (or to pause, or to remove if it's obsolete). Showing them at top would emphasize this. 

For example, if user has selected sorting by name, then,

1. we first show all the failed checks in A-Z order
2. we then show all the remaining checks in A-Z order

The list of checks is also being auto-refreshed using AJAX requests. I think it would be confusing for table rows to jump around when checks change status, so I would avoid doing that and keep the initial order until page is reloaded.

**Comment by thisisshi** [comment]
Yeah, always showing failed checks at the top would be great. For some context, I'm running two installations of healthchecks-- one for a prod env and one for a dev env. In each I'm running 600+ checks so getting at a glance view of what is failing would be much better. 😄

**Comment by thisisshi** [comment]
Yeah, always showing failed checks at the top would be great. For some context, I'm running two installations of healthchecks-- one for a prod env and one for a dev env. In each I'm running 600+ checks so getting at a glance view of what is failing would be much better. 😄
