### ISSUE TITLE
A docker version, and an Ansible role

### ISSUE THREAD

**Issue by coaxial** [healthchecks/healthchecks#174]
Just wanted to share the docker service I'm using, along with the Ansible role to deploy it.

It supports optional backups to a [borg](http://borgbackup.readthedocs.io/) repository, and https with lets encrypt. It will also restore the latest backup after (re-)installing if desired.

Ansible role (hourly backups, https, backup restore): https://galaxy.ansible.com/coaxial/healthchecks/
Healthchecks docker service: https://github.com/coaxial/docker-healthchecks

**Comment by ShalbafZadeh** [comment]
thank you very much for sharing
but i think  a merge request to add dockerfile and adding ansible role manual to wiki would be better
