### ISSUE TITLE
Edit function for Webhook Integrations

### ISSUE THREAD

**Issue by david-vfde** [healthchecks/healthchecks#176]
Currently there is no “edit” function for Integrations.
Once any Integration (e.g. “Webhook”) is created, it is not possible to change any of their values any more.
Especially on more complex integrations, the only solution is to delete and create a new one with the same settings, which is unnecessary work and potentially error-prone.
![screen-0](https://user-images.githubusercontent.com/13542446/41286361-6b409aae-6e3f-11e8-809c-da89850b9f1f.jpg)

**Idea:** Add an “edit” function to the integrations details page

**Comment by cuu508** [comment]
From #341 

> 
> You're probably aware of this, but I thought I'd summarize my experience anyway. I just went through setting up an integration with zulipchat (compare #202) via a custom webhook. That involved a bit of tweaking things, which turned out to be quite painful because
> 
> *  integrations don't start out with a name / distinguishable in the listing
> * integrations can't be edited
> 
> From my outside perspective, the best fix for this would be to allow editing integrations with a form similar to the "create integration" form, and to include the integration name there.

**Comment by cuu508** [comment]
This is finally implemented – you can edit parameters of existing webhooks, instead of recreating them each time a change is required.
