### ISSUE TITLE
period 1 month

### ISSUE THREAD

**Issue by ZUNbado** [healthchecks/healthchecks#18]
Hi,

I want to healthchecking some scripts monthly executed, is possible to modify period for this?

Thanks

**Comment by cuu508** [comment]
Thanks for suggestion!

This is trickier than it first seems. Behind the scenes the app stores period as a number of seconds. For "1 month", the period would not be fixed, it would be 28, 29, 30 or 31 days, depending on current date. So there would be changes how period gets stored in database. I think it's worth doing though.

**Comment by ZUNbado** [comment]
Hi,

Thanks for your reply, I am aware of this problem.

At this moment, I assume the risk, and interval of 31 days for me are valid if you believe is possible to add this option.

Kind regards

**Comment by diwu1989** [comment]
We just hit this usecase too, and I think a 30 days best estimate with a grace period of 2 days will satisfy the usecase.

**Comment by cuu508** [comment]
Yes, makes sense to do it the simple way.

@diwu1989 I saw the "1 month" option already added in your branch, so I cherry-picked that and did a bit of refactoring on it.
