### ISSUE TITLE
Check settings goes over display

### ISSUE THREAD

**Issue by DimaDK24** [healthchecks/healthchecks#181]
Hi! I'm just starting to use this amazing tool. Thank you for developing it :)
I meet minor UI issue: check settings goes over display: 
![image](https://user-images.githubusercontent.com/25607790/43005978-1c304f60-8c3d-11e8-8997-5b66b11639ce.png)
I have 1366x768 display. Google Chrome 67.0.3396.99 Windows 10
Hope it will be resolved. Notify me, if I can help with anything about this issue

**Comment by cuu508** [comment]
Thanks @DimaDK24, good catch, fixed!
