### ISSUE TITLE
./manage.py not working: "No module named 'django.utils'"

### ISSUE THREAD

**Issue by clovisd** [healthchecks/healthchecks#184]
Hey there, I'm trying to setup a development install of HC and am getting this message on trying to run anything off of `manage.py`:

```python
(hc-venv) cl@s4:~/webapps/healthchecks$ ./manage.py createsuperuser
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/home/cl/webapps/hc-venv/lib/python3.5/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
ImportError: No module named 'django.utils'
```

Same with `./manage.py runserver` etc.

Any help or advice would be appreciated!

Thank you.

**Comment by cuu508** [comment]
Hi,

sorry about that -- not quite sure yet why that's happening. Haven't managed to reproduce this yet. 

When the virtual environment is activated, what is the output of `pip freeze`?

What OS & version are you using? 

Does `/home/cl/webapps/hc-venv/lib/python3.5/site-packages/django/utils/version.py` exist?
