### ISSUE TITLE
login expired

### ISSUE THREAD

**Issue by ZUNbado** [healthchecks/healthchecks#19]
Hi,

The login link is only valid for doing one login (next ones it says is invalid or expired), is this correct? Do I have to resend the link every time I want to login?

It is possible to save the login link in bookmarks?

Kind regards

**Comment by cuu508** [comment]
Yes, that's by design.
Are you using several accounts, or is there any other reason why you get logged out frequently?
There's the issue #6 about using good old usernames/passwords. If that gets implemented, it solves your problem, right?

**Comment by ZUNbado** [comment]
Hi,

Sorry, I don't see this issue before open this issue. I need to share login with my team. You can close this issue if you thinks this is duplicated.

Kind regards

**Comment by cuu508** [comment]
It is now possible to set a password for your account.
While there's no proper team access, you can at least share the login/password with your team.
