### ISSUE TITLE
Persist selected tag open after browser refresh

### ISSUE THREAD

**Issue by danemacmillan** [healthchecks/healthchecks#191]
I frequently select a tag from the top of the page to reduce the size of the health checks list, and out of habit will refresh the page from time to time while that tag is selected (visually appears black). After refresh, the tag is no longer selected and all of the health checks are listed.

It would be nice if the tag selection(s) persisted after browser refreshes.

Priority: utterly unimportant, but nice to have.

**Comment by cuu508** [comment]
Good suggestion – done!
