### ISSUE TITLE
Adding whatsapp as a notification option

### ISSUE THREAD

**Issue by mikisarhian** [healthchecks/healthchecks#197]
Would love to have whats app as a notification option as its notifications are instant in nature and its  popular

**Comment by cuu508** [comment]
Indeed! WhatsApp Business API is in a limited preview stage, waiting for access to it.

Whatsapp charges non-negligible fees for sending messages via API, so Whatsapp integration might not be viable on the free plan.

**Comment by hongkongkiwi** [comment]
I think as an option it would be great and allow the user to put in their own API key (if they have it). That way the burden is taken away from you to pay for this.

**Comment by cuu508** [comment]
The WhatsApp integration is implemented and live. It uses Twilio for delivery and is in fact 99% the same as the SMS integration.
