### ISSUE TITLE
Make the server listen to outside of localhost

### ISSUE THREAD

**Issue by raamee** [healthchecks/healthchecks#2]
Hey,

Recently came to know your tool. A very sincere work from your side. Congrats! 

I'm trying to set it up in my system (centos 6.5 64 bit). I have started the development server:

System check identified no issues (0 silenced).
September 11, 2015 - 16:24:15
Django version 1.8.2, using settings 'hc.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

How to make it listen to server's public IP address instead of localhost?

Thank you.

**Comment by cuu508** [comment]
Hi raamee,

You can look up startup options for Django development server like this:

    $ ./manage.py runserver --help

The parameter you're looking for is [addrport]. Start it like this:

    $ ./manage.py runserver 192.168.1.123:8000
    Performing system checks...

    System check identified no issues (0 silenced).
    September 11, 2015 - 16:33:01
    Django version 1.8.2, using settings 'hc.settings'
    Starting development server at http://192.168.1.123:8000/
    Quit the server with CONTROL-C.

Note that development server should indeed only be used for development/testing. For production, you would ideally run it using gunicorn or uwsgi, and serve static files with something like nginx. 
On deployment side, I don't think there any specific gotchas, you can follow guides for deploying any regular Django app. 
Please let me know how you get on!

**Comment by raamee** [comment]
Hi,

Great! Thank you for the reply. I got it working! I'm new to Django apps, so I'm kinda slow in setting up. I'm gonna start setting checks. Will let you know if I face any challenges.

**Comment by yad2nus** [comment]
so good
