### ISSUE TITLE
CLI for managing interacting with API

### ISSUE THREAD

**Issue by apnewberry** [healthchecks/healthchecks#205]
https://cronitor.io/docs/using-cronitor-cli has a nice CLI tool that will parse crontab, add healthchecks via the API, and update crontab with the urls. It would be awesome to have these tools for healthchecks too!

**Comment by apnewberry** [comment]
Wrong repo, sorry.

**Comment by brammeleman** [comment]
I just published a cron shell for integration with healthchecks. It synchronizes cron jobs without altering crontab files. It's in the testing phase right now. Check out https://gitlab.science.ru.nl/bram/sch
/bram

**Comment by greenspray** [comment]
Any update on this issue? @brammeleman cool project. How can we make this happen? I am willing to contribute as well

**Comment by brammeleman** [comment]
@greenspray thanks! Feel free to checkout the code. If you're interested to contribute, I could move the repo to gitlab.com / github.com for easier contributions. Let me know!
