### ISSUE TITLE
Different Grace Time for each Notification Method

### ISSUE THREAD

**Issue by Eh2406** [healthchecks/healthchecks#209]
Thanks for making healthchecks! It is saving us at work!

We have a daily backup script that (now) has a ping to a check. It is set up to notify me and my boss. Inpractice it is not a big deal if we miss a day, so it is overkill for my boss to be bothered unless it is more then 2 days late. 

My current solution is to set up 2 checks, one with a 30 minute grace time for me, and a second with a 1 day grace time for my boss. With the script pinging both checks. It would be easier to maintain if I could override the grace time on a per notification bases.

Thoughts?

**Comment by cuu508** [comment]
I understand the use case, and it makes sense, but it would require major changes to support in Healthchecks. 

Using two checks with different grace times is a clever trick! Another option would be to offload this task to an incident management system, and configure the escalation policy there. We already have integrations for PagerDuty, OpsGenie, VictorOps, PagerTree. Happy to add others.
