### ISSUE TITLE
[FEATURE REQUEST] Chartpie uptime

### ISSUE THREAD

**Issue by acosaburca** [healthchecks/healthchecks#215]
Would be great, if you can add a chart or plot to the log.
To show how many cron missed in a period (1day,1week,1month)

Thanks

**Comment by cuu508** [comment]
That's a good idea. 
With the recent changes to the data model (addition of the Flip model), we can calculate the downtime in minutes and the number of downtimes  (but not the number of missed pings, at least not easily).
Related: #104

**Comment by acosaburca** [comment]
Good to know, when can be implemented? (i hope as soon as possible)

**Comment by cuu508** [comment]
Unfortunately I cannot promise dates. I'm working on this as time allows, and have a backlog of features waiting to be implemented...

**Comment by cuu508** [comment]
The Details page now shows the number of outages, and the downtime in minutes for last three months. Not a chart, but serves a similar purpose:

![image](https://user-images.githubusercontent.com/661859/61579031-5b381180-ab08-11e9-8de4-a819b7d38817.png)
