### ISSUE TITLE
email status is unconfirmed with healthcheck integration

### ISSUE THREAD

**Issue by Rajeev9045** [healthchecks/healthchecks#216]
When i go for email integration with Healthcheck it send an Emil for verification . When i click on that link it shows nothing like site is not available but in actual server is running fine.

**Comment by Rajeev9045** [comment]
Can anyone help?

**Comment by cuu508** [comment]
What address does your site run on?
Can you please post an example verification link that you receive in email?

**Comment by Rajeev9045** [comment]
this is fixed thanks .
