### ISSUE TITLE
Missing DB_HOST, DB_PORT for MySQL

### ISSUE THREAD

**Issue by Jacq** [healthchecks/healthchecks#220]
Related to settings.py:
https://github.com/healthchecks/healthchecks/blob/836ea5afda0997d32c5270baa2b8c2c8fd9a8f57/hc/settings.py#L125

I did not find the settings for the DB_PORT and DB_HOST related for the MySQL, is there any reason they are only specified for the postgres configuration?
I changed the MySQL settings to:
````
if os.getenv("DB") == "mysql":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': os.getenv("DB_HOST", ""),
            'PORT': os.getenv("DB_PORT", ""), 
            'NAME': os.getenv("DB_NAME", "hc"),
            'USER': os.getenv("DB_USER", "root"),
            'PASSWORD': os.getenv("DB_PASSWORD", ""),
            'TEST': {'CHARSET': 'UTF8'}
        }
    }
````

,to allow remote connection to database by tcp connection and avoid adding a local.settings.py

Cheers,
Jacq

**Comment by cuu508** [comment]
Hi @Jacq, no good reason – I'm not using MySQL myself, so missed these. I've added them now, thanks!
