### ISSUE TITLE
Refresh with presistent tag results in 404 Not Found

### ISSUE THREAD

**Issue by danemacmillan** [healthchecks/healthchecks#221]
I've noticed over the last couple of weeks that anytime I refresh the browser (Firefox v65 RC) while looking at checks with a tag selected, the server responds with 404 Not Found page:

![](https://i.imgur.com/rNf7Bz0.png)

Persistent tags were introduced in https://github.com/healthchecks/healthchecks/issues/191.

**Comment by cuu508** [comment]
Good catch, fixed!
