### ISSUE TITLE
Twilio integration

### ISSUE THREAD

**Issue by daarond** [healthchecks/healthchecks#222]
I would like to see Twilio integration, sending an SMS using the account I already have with them. What may make this more interesting is that Twilio also has chat and email as well as SMS/MMS.

**Comment by cuu508** [comment]
On self-hosted instances, you can either use the existing SMS integration with your own Twilio credentials, or alternatively use the Apprise integration which supports Twilio.

On the hosted service, please upgrade and use the standard SMS integration.
