### ISSUE TITLE
Slack notifications: cron schedule asterisks interpreted as bold formatting

### ISSUE THREAD

**Issue by danemacmillan** [healthchecks/healthchecks#223]
The asterisks used for cron scheduling that appear in a Slack notification are interpreted by Slack as bold formatting.

**Example cron:**

```
*/5 * * * *
```

**Interpreted in Slack:**

![](https://i.imgur.com/fioAgxs.png)

In other words, `*/5 *` is turned into **/5**.

**Comment by cuu508** [comment]
Thanks, good catch again! Fixed.
