### ISSUE TITLE
Log in Check Configuration View blank

### ISSUE THREAD

**Issue by djreynolds922** [healthchecks/healthchecks#224]
https://github.com/healthchecks/healthchecks/blob/f8c0c20d344f38e12b786a25d8ee2ba1a1cc0d8d/hc/front/views.py#L497

Was able to fix on a local version by changing this line to
         updated = events[0].created.strftime("%S.%f")

**Comment by cuu508** [comment]
Can you please describe in a little more detail how the problem manifests?
Are you on the "Check Details" page, and the log is not auto-refreshing?
If you are self-hosting, what python version and what database do you use?

**Comment by djreynolds922** [comment]
Correct - when going to the checks page for a project and then clicking the gear icon on the right side of the check - it's just blank over on the right side under log.

Self-hosted, SQLite, Python 3.7.2 - latest commit. Running in Production mode with wfastcgi and IIS 10. Adding this code in settlings.py to log errors to determine the cause:
```(python)
#settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'mysite.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'DEBUG',
        },
        'MYAPP': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    }
}
```
Found an error in the log regarding an invalid time format for this line. Looked up the strftime method here: https://docs.python.org/3.7/library/datetime.html#strftime-strptime-behavior - Lowercase %s isn't in that list but uppercase is. Made the change - errors in the log went away and the Log area started populating and auto-refreshing.

If that's not enough info - I'll recreate the issue when I have a minute and send you the actual log entries.

**Comment by cuu508** [comment]
Thanks, I understand the issue now!

From the same documentation link:

> The full set of format codes supported varies across platforms, because Python calls the platform C library’s strftime() function, and platform variations are common. 

Apparently "%s" works on Ubuntu but not Windows. It's meant to convert the datetime to UNIX timestamp. "%S" is the formatting string for second (0 - 59). Not the same thing, but works in practice.

I still want to use UNIX timestamp (or a similar always increasing value) so will look for an different, cross-platform way to generate it.

**Comment by djreynolds922** [comment]
Ah cool - thanks for explaining it. This might be useful - I'll see if I can patch my local version and if so - I'll submit a pull request. https://stackoverflow.com/questions/11743019/convert-python-datetime-to-epoch-with-strftime

**Comment by cuu508** [comment]
@djreynolds922 I found and commited a simple fix soon after the previous comment. I replaced datetime.strftime(...) with [datetime.timestamp()](https://docs.python.org/3.7/library/datetime.html#datetime.datetime.timestamp).
