### ISSUE TITLE
Add error message if name is too long

### ISSUE THREAD

**Issue by pbengert** [healthchecks/healthchecks#225]
I created some new tasks and gave them a new name instead of "unnamed".
Some of those names were obviously not accepted because they were to long but there was not message indicating it. So in the end the name stayed at "unnamed" but I did realize it.
Maybe add some kind of error message to avoid it.

**Comment by cuu508** [comment]
Thanks for reporting this!

As a simple fix, I added a "maxlength" attribute to HTML input elements. For check names, the input box will not accept more than 100 characters. If you are pasting a long value from somewhere else, it will get truncated.
