### ISSUE TITLE
Warn Status

### ISSUE THREAD

**Issue by abitlegacy** [healthchecks/healthchecks#227]
A feature that I currently have some use for - and I believe other people will to would be a "Warn" status - when a script hasn't actually failed and ran completely through but something was a little off that might require further digging.

Real World Example: I'm using this application to monitor data pulls from various SFTP/SSH/SCP sites. Sometimes, the vendor I'm pulling data from is late - so when my scheduled pull happens I get no files. Sometimes, there aren't any actual files to pull. Both of these situations don't require immediate action so I don't want trigger a down alert - but it would be useful to have identified in the log.

**Comment by cuu508** [comment]
Thanks for the suggestion! Generally I'd like to keep the service focused on "dead man's switch" style monitoring, and not move too far into the generic logging direction, but it's possible we could do something here.

If you don't need to be alerted about the "warn" state, how would you ideally want this information displayed? Would you be periodically looking over the the logs?

When sending pings, you can already send POST requests and put arbitrary information (up to 10K per ping) in the payload. You can click on entries in the log listing, it opens the "Ping Details" dialog with all details including POST body. Admittedly, for routine checking, this would not be convenient to use.

**Comment by djreynolds922** [comment]
Correct - I'm currently looking over the logs every day because we're still testing and implementing and this popped into my head as a useful feature. Ideally, the option to be have "levels" of alarms for your integrations would be nice too (one integration gets a message when a warning or a failure happens, another one gets a message only when a failure happens). This would allow something like an on-call pager to be alarmed when it's super important and needs to be handled now - and something like a slack message to be created when it's something less time sensitive.

**Comment by Crush3rX** [comment]
+1 for Warn status.

**Comment by wlupton** [comment]
+1

I've converged on a pattern like this:

```
status=$(egrep -i 'warning:|error:' $LOGFILE | tail -255 | wc -l)
egrep -i ':apitools|:gsuite|warning:|error:' $LOGFILE | $CURL --data-binary @- $URL/$status
```

So the "failure" code is the number of errors in the log file (capped at 255), and the POST body is the error lines. I want to see this:

![Screenshot 2020-11-25 at 12 55 32](https://user-images.githubusercontent.com/8874729/100230356-8c56fc00-2f1d-11eb-9575-b59d25a92590.png)

and this:

![Screenshot 2020-11-25 at 12 57 25](https://user-images.githubusercontent.com/8874729/100230572-c922f300-2f1d-11eb-9d9a-bca0cc80c84d.png)

but I don't really want the service to be marked as being "down".

**Comment by cuu508** [comment]
> Real World Example: I'm using this application to monitor data pulls from various SFTP/SSH/SCP sites. Sometimes, the vendor I'm pulling data from is late - so when my scheduled pull happens I get no files. Sometimes, there aren't any actual files to pull. Both of these situations don't require immediate action so I don't want trigger a down alert - but it would be useful to have identified in the log.

There's now a `/log` endpoint that should work for this use case: https://healthchecks.io/docs/http_api/#log-uuid

1. If a data pull is successful, report success (the normal ping)
2. If there are no files to pull, use the `/log` endpoint.

A single "log" event will not trigger any notifications. But if there are no "success" events for too long (depends on the period and grace you've configured), the check will go down and you will receive notification(s).
