### ISSUE TITLE
Feature Request: Turn off/separate "Up" emails on an integration

### ISSUE THREAD

**Issue by dalee-bis** [healthchecks/healthchecks#231]
We are planning to configure emails to be sent to our ticketing system but we only want to create tickets for when checks are down. At the moment, a ticket would also be created when the check comes back up.

It would be great if the "up" email could be turned off or sent to a different email address (so that the "up" email could go to the team rather than the ticketing system).

**Comment by cuu508** [comment]
Thanks for the suggestion, makes sense!
At the contact@healtchecks.io address I see various automated replies from
services and mail agents, and yeah, there's a fair share of confirmations
about tickets being created -- both for "down" and for "up" events.
I will look into making the "up" notifications configurable and optional.
