### ISSUE TITLE
Feature Request: Move badges in UI

### ISSUE THREAD

**Issue by dalee-bis** [healthchecks/healthchecks#234]
I like the badges and have put a few of them on our confluence pages as a quick indication of the check status but I don't think they are in an intuitive place. Account settings (https://healthchecks.io/accounts/profile/badges/) seems like a strange place for them given that they are created for project level objects (tags on a check). I don't think they are specific to my account (i.e. others with access to the project would have the same URLs) but the location makes it seem like they are.

**Comment by cuu508** [comment]
Thanks, a very good point.
 
One thing I've had at the back of my mind is improving the "Project Settings" page: make it available to all team members (with owner-only functions greyed out / hidden), and make the "Project Settings" page more discoverable. The top right dropdown menu is a clunky way to access it. Badges are project-specific and would logically belong in "Project Settings".
