### ISSUE TITLE
Cannot build latest release

### ISSUE THREAD

**Issue by thelamer** [healthchecks/healthchecks#235]
https://github.com/healthchecks/healthchecks/blob/5d9f19d2f9bd1ec199e747c56aabc46d499c7b57/requirements.txt#L1

It looks like crontier has removed this specific version , maybe a bugfix release or  greater than instead of specific version string matching.

Let me know if you need anymore information we are unable to build on our side at linuxserver.io. 
https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-healthchecks/detail/master/58/pipeline

**Comment by cuu508** [comment]
Just added a new release, v1.6.0 which has croniter==0.3.29 in requirements.txt.
