### ISSUE TITLE
Request: Add PushBullet integration

### ISSUE THREAD

**Issue by KrunchMuffin** [healthchecks/healthchecks#24]
This app is exactly what I am looking for. Could you possibly add PushBullet integration

https://docs.pushbullet.com/

Thanks!

**Comment by ovizii** [comment]
This is weird, I can't find it, was this integration alter removed?

**Comment by cuu508** [comment]
It has not been removed, where are you not finding it?

Note that on self-hosted installations, you must set `PUSHBULLET_CLIENT_ID` and `PUSHBULLET_CLIENT_SECRET` environment variables to enable it.

**Comment by ovizii** [comment]
Thanks, I didn't find that documentation as the documentation has no search function that I can see, even a Google search didn't yield that result: site:healthchecks.io "pushbullet" 

Would you mind to share where you found that documentation, so I can look it up further?

###edit###
As I was typing, I found the documentation on the full configuration page: https://healthchecks.io/docs/self_hosted_configuration/ very weird that a search didn't find it.

**Comment by cuu508** [comment]
I just added setup instructions in the Docs > Self-Hosted > Configuration page. Once the site is updated and reindexed, I'm hoping Google will be able to find it.
