### ISSUE TITLE
Grid View

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#245]
Offer a grid view layout as an alternative to the list.

**Comment by bryanroth** [comment]
@cuu508 Any movement on this feature?

**Comment by cuu508** [comment]
Not yet unfortunately, but I am looking forward to have a go with this.

For the past couple of weeks I've been working on infrastructure / ops improvements for the hosted service. Now reasonably happy with it for time being, so will go back to working through the issues & features.

**Comment by cuu508** [comment]
A standalone dashboard page with a grid layout: https://github.com/healthchecks/dashboard/
