### ISSUE TITLE
Auto delete logs in self hosted version

### ISSUE THREAD

**Issue by Foddy** [healthchecks/healthchecks#250]
I couldn’t find any information about that in the docs so I am wondering if the self hosted version is able to automatically remove old logs from pings?

I have some jobs running every minute. I don’t want to imagine how many no longer relevant rows my database will have in a few months...  :S

**Comment by Foddy** [comment]
I am blind. Sorry.

**Comment by yonas** [comment]
@Foddy I'm looking for an automated method as well. What did you find?

**Comment by cuu508** [comment]
@yonas – there is a `prunepings` management command ([details in README](https://github.com/healthchecks/healthchecks#database-cleanup)). Run it regularly from e.g. a cron job.

**Comment by yonas** [comment]
@cuu508 -- Thanks! I've created a pull request so it can find Python 3. https://github.com/healthchecks/healthchecks/pull/504

However, after running the script, I still see log entries in the web UI when looking at a check's details page.

On first run, it reports deleted a couple thousand pings. On second run, immediately after, it reports 0 pings pruned. It seems like the web UI is either caching pings or using another source to fetch ping logs.
