### ISSUE TITLE
Quota limits while adding team members to projects

### ISSUE THREAD

**Issue by prgTW** [healthchecks/healthchecks#258]
I experience rate limits while adding team members to project. I want to add 8 people to 5 projects but I'm unable to do so due to rate limits on, I believe, POST requests. Giving that I have to add them on a per-project basis (do the same thing 5 times) this problem is quite annoying :(

![image](https://user-images.githubusercontent.com/203249/58794171-de081a00-85f7-11e9-96ec-6578f60712ef.png)

**Comment by cuu508** [comment]
Hi @prgTW, sorry about that! Yes, the "Invite" function has a rate limit. The limit is currently 20 invites per user per 24 hours. 

The reason to have the rate limit in the first place is a specific abuse pattern I had observed: somebody was inviting an email address, then removing them from the project. The had automated this and were doing it in a loop, over thousands of email addresses. This causes thousands of useless & unwanted invite emails to be sent, which is not good.

This is the first instance I know of a legitimate user hitting this rate limit. As a quick "fix", I just manually reset the rate limit for you so you should be able to invite 20 more members. If this gets reported again, I will look into either adjusting the rate limit, or using different rate limits for the free and the paid user accounts.

**Comment by prgTW** [comment]
Hi @cuu508 and thanks for the reply!

I'm currently inviting 8 team members to 6 projects so even boosted quota didn't fit for me :(. 

Looking into the future I see two options for now:
- to not send any emails because not every invite requires an email to be sent - I just can talk to guys sitting next to me and tell them I've granted them access
- having team members defined per account and only select to which projects they have access to and send 1 email per user that summarises their access (a matrix panel with many checkboxes would be great although ugly :D)

Currently adding the same team members to few projects is clicking, clicking and again clicking :(

Cheers!

**Comment by cuu508** [comment]
Just made a  couple improvements in this area:

* In the "Team Access" section, list existing users from account's other teams, and a one-click "Add to Team" action:

![Screenshot from 2020-02-14 13-08-20](https://user-images.githubusercontent.com/661859/74525993-1b64cb80-4f2b-11ea-87a2-c1397d5dc2fa.png)

* Adding an existing user to a team does not count towards to the "invites / day" rate limit.

If you need to set up 6 projects of identical 8-member teams, there would still be a fair bit of clicking, but less than before. And you will not hit the rate limit.
