### ISSUE TITLE
No POST data to be found for webhook integration

### ISSUE THREAD

**Issue by ktkaushik** [healthchecks/healthchecks#259]
I am using the webhook integration and i have the body setup but i don't see any data coming in on my Node.js server using Express.

I keep getting an empty object. Why could this be happening? Is my configuration incorrect?

<img width="631" alt="Integrations - Healthchecks io 2019-06-06 11-48-37" src="https://user-images.githubusercontent.com/877806/59011128-3f76f580-8851-11e9-90a4-5109c63b950a.png">

**Comment by ktkaushik** [comment]
Please let me know if you would need any details. Thanks

**Comment by cuu508** [comment]
Tested POST data with a requestbin-type service and with a similar POST body as yours, and it seemed to work:

![image](https://user-images.githubusercontent.com/661859/59013250-37638980-8842-11e9-8821-6764516215fa.png)

If you send POST requests to the Node.js servers manually with e.g. curl, does the POST body show up then?

**Comment by ktkaushik** [comment]
Yeah i have tested by sending it manually using Postman multiple times on the same webhook. 

By any chance have you set any content type that perhaps Express is not able to parse?

**Comment by cuu508** [comment]
By default it doesn't set any content type. When adding the webhook integration, you can specify the request headers and set the Content-Type header explicitly.

**Comment by ktkaushik** [comment]
I can't seem to edit the webhook except for it's name. Seems like i will have to create a new one.

**Comment by cuu508** [comment]
Yeah. "allow editing existing webhooks" has been at the back of my mind for a while. Filed it just now:  #260

**Comment by ktkaushik** [comment]
@cuu508 Adding the header worked. Thanks.

It's parsing vaguely though for json and x-www-form-urlecoded 

1. ` $NAME went down. Current status is $STATUS ` (key is the string)

```
Body - { 'TEST went down. Current status is down': '' }
```

2. `{message: $NAME went down. Current status is $STATUS }`
```
Body - { '{"message": "TEST went down"}': '' }
```

However, when i use POSTMAN i get the body perfectly in JS Object meaning that it could parse well.

```
Body for POSTMAN - {Subject: 'Test went down'}
```

![image](https://user-images.githubusercontent.com/877806/59016037-fda07c00-885d-11e9-871e-3c36f654ed4f.png)

You think i should raise this as a separate issue?

**Comment by cuu508** [comment]
If the endpoint can handle JSON payload, try using body:

    {"Subject": "$NAME went down"}

And headers:

    Content-Type: application/json

**Comment by ktkaushik** [comment]
Let me try this in a bit

**Comment by ktkaushik** [comment]
Yup, the JSON payload worked. Thanks @cuu508
