### ISSUE TITLE
400 Bad request on webhook for missing double-inverted commas

### ISSUE THREAD

**Issue by ktkaushik** [healthchecks/healthchecks#262]
In the `Request Body` for **Webhook intergrations**, i added - 

```javascript
{ message: "$NAME went $STATUS" }
```

This renders a `400 - bad request` on my express server. On trying out a few other ideas, i realised that not adding `message` as `"message"` did that.

It works if add the double inverted commas - 

```javascript
{ "message": "$NAME went $STATUS" }
```

Image for reference - 

<img width="647" alt="Screenshot 2019-06-22 at 12 38 10 PM" src="https://user-images.githubusercontent.com/877806/59961502-31360400-94f6-11e9-8833-1712d85b40a7.png">

Is this intentional? Do you think the Object key without double inverted commas can be made to work please?

**Comment by cuu508** [comment]
I'm not sure I understand what the issue is. 
Did Healthchecks send a payload that looks different from what you had entered in webhook configuration?

**Comment by ktkaushik** [comment]
It just gave bad request which would mean that the payload is not JSON.

Basically, if i didn't put double inverted commas in the key of the `Request body` then it's not a JSON payload that i receive on my webhook deeming it as `Bad Request with 400 status code`

**Comment by cuu508** [comment]
Yep, `{ message: "$NAME went $STATUS" }` is indeed not a valid JSON document. 

Healthchecks doesn't do any special formatting on the POST body: whatever you put there is what gets sent. You could post JSON, XML, just a plain text string etc.

**Comment by ktkaushik** [comment]
Cool. Thanks @cuu508
