### ISSUE TITLE
1.7.0 sendalerts is not working

### ISSUE THREAD

**Issue by stevenmcastano** [healthchecks/healthchecks#263]
I've got 1.7.0 installed in an Alpine Linux 3.10 container... the entire site it working, everything migrated over, but sentalerts does nothing.... I get:

```
sendalerts is now running
```

But then nothing happens... no more timing marks, no output at all... it just sits there doing nothing. I've made a test trigger, configured my webhook.... tested the webhook and it runs fine, hitting the ping URL updates the status as it should... but sendalerts doesn't seem to be detecting the change in status. I've even run it with the `-v 3` option... and after it says its running, it still outputs nothing.

**Comment by cuu508** [comment]
How do you run sendalerts? 

One thing I've run into a few times is python buffering output. Check if you see any output if you run it with the "-u" (unbuffered) flag:

    python3 -u manage.py sendalerts

**Comment by stevenmcastano** [comment]
I still get nothing.

I actually push 1.7.0 into production the other day anyway... figuring I'll work these things out over time and since then I've had a few checks go down and the alerts are 100% not being sent.

Is there anywhere in the database where it stores alerts that are intended to be sent? I'm seeing the new flips table, but there doesn't seem to be much in it. I have 2 entries that seem to be not processes... one from a new check I created to test that shows it going from "New" to "Up" and one from the weird check I had stuck in the null state which shows it going from "-" to "Up".

**Comment by cuu508** [comment]
Very weird: even if there's no work to be done, I'd expect the `--- MARK [timestamp]---` lines every minute. 

Yes, the "Flips" table is a sort of a queue of alerts that need to be sent out. It has a "processed" column – that gets filled when the alert actually gets sent. `sendalerts` now has dual purpose: 
 * it looks for checks going down and adds entries in the Flips table
 * it looks for unprocessed entries in the Flips table and sends alerts

When `sendalerts` is running, if you deliberately let a check fail (set up a 1 minute check, ping it once, wait a bit), do you see a new entry in the Flips table appearing? If yes, is the "processed" field filled out?

Seeing as it seemingly just freezes – could you check if it's running into database deadlock issues? Run sendalerts and then check if there are any deadlocks in the database?

**Comment by stevenmcastano** [comment]
> Very weird: even if there's no work to be done, I'd expect the `--- MARK [timestamp]---` lines every minute.

Super weird... just nothing... it reports that it's running then does nothing after that

> Yes, the "Flips" table is a sort of a queue of alerts that need to be sent out. It has a "processed" column – that gets filled when the alert actually gets sent. `sendalerts` now has dual purpose:
> 
> * it looks for checks going down and adds entries in the Flips table
> * it looks for unprocessed entries in the Flips table and sends alerts
> 
> When `sendalerts` is running, if you deliberately let a check fail (set up a 1 minute check, ping it once, wait a bit), do you see a new entry in the Flips table appearing? If yes, is the "processed" field filled out?

Yup... I did this... nothing gets put in the Flips table and the two entires that are in there from "manual" intervention, me setting the broken check to "Up" and the new check being created... both of those entries are there, but they are not marked as processed, as in they have no date.

> Seeing as it seemingly just freezes – could you check if it's running into database deadlock issues? Run sendalerts and then check if there are any deadlocks in the database?

I checked my logs and from the client directly with a `SHOW ENGINE INNODB STATUS` and it says there have been no deadlocks since it started last, which was weeks ago.

**Comment by cuu508** [comment]
Thank you for investigating this further. FWIW I installed MySQL (5.7.26) and tested the v1.7.0 tag – but unfortunately no luck reproducing the issue so far... 

Can you reproduce this in a non-production database with dummy data? If so, could you dump the database and send it on to me? I suspect it's some kind of a data corruption issue but really hard to tell without being able to reproduce and tinker with it myself.

**Comment by stevenmcastano** [comment]
I honestly hadn't tried it with a fresh DB... let me deploy a new docker container now with a fresh DB and we'll see what happens... and sure, I can send you the DB... I can probably even send you my production DB and/or recreate a lot of the pings... I only have about 10 and I'm sure I could manually cut and paste the UUIDs from one system to the other so I don't have to change all my scripts too, right?

**Comment by stevenmcastano** [comment]
So, so now for the crazy part... brand new data... it works as expected.

I noticed a few things... 

1. sendalerts didn't appear to actually start fully running until after I configure my first integration
2. now when a ping goes up or down it IS reflected in the database which is is not in production
3. the Flips table does get populated now and entries do show up as processed very quickly after the sendalerts process catches them

So now what I'm wondering is... maybe if I delete my single integration in prod and totally recreate it, maybe that would jump start things?

What I'm wonder is, what actually marks the DB as "Up" or "Down" for a check... is that the sendalerts processes? Or somewhere else in the code? I'm trying to track down if my problem is sendalerts not running so status changes aren't being detected, or is sendalerts not running because status changes aren't being detected somewhere else?

**Comment by stevenmcastano** [comment]
Just a super quick update... hoping for a little magic... I deleted my one webhook integration in my production system and recreated it, then restarted the sendalerts process... and it's still dead. So weird!

**Comment by stevenmcastano** [comment]
Sorry for the multiple updates here... I'm posting this as I'm working!

So in my testing database, I copied to contents out of the api_checks table from production and inserted them into testing, so now in testing I have all my checks, tags, schedules, etc...

Seems like alerts are working fine still...

The one thing that I notice is different, which isn't a big deal... I can change a few pages... but the badges now have different URLs. They used to have the username in the path... now they've been regenerated with the project ID in the path and the badge codes are new. Is there any way to go back and get the old codes/path... ? I couldn't find anything in the database.

**Comment by cuu508** [comment]
Sorry for the delay getting back to you, 

> What I'm wonder is, what actually marks the DB as "Up" or "Down" for a check... is that the sendalerts processes? 

When a check goes down, it's the `sendalerts` script. First, it creates an entry in the `Flips` table (if you look in it's source, it's the `handle_going_down` function). Second, it works through entries in the `Flips` table and sends out notifications (the `process_one_flip` function).

When a check goes up, the first step is done right when receiving a ping. The code is in `hc.api.models.Check.ping()`.

If you're still interested in diagnosing the issue with the original production database, but cannot send it as-is (which would be totally understandable), –  maybe, if it's feasible, you could sprinkle the `sendalerts.py` with "print(...)" statements to see how far in the execution it gets, where it freezes, or goes into an infinite loop? I've been testing a few things locally, but still no luck reproducing this...

> The one thing that I notice is different, which isn't a big deal... I can change a few pages... but the badges now have different URLs. They used to have the username in the path... now they've been regenerated with the project ID in the path and the badge codes are new. Is there any way to go back and get the old codes/path... ? I couldn't find anything in the database.

The `accounts_project` table has a `badge_key` column. If you paste the original username value in there, you should then see the old badge URLs.

**Comment by cuu508** [comment]
Hey @stevenmcastano, did you manage to solve this?
