### ISSUE TITLE
Non-parallel run/lock mode

### ISSUE THREAD

**Issue by ttr** [healthchecks/healthchecks#265]
Hi,
Would be possible to have optional switch in check definition to allow only single run?
So if check is already running/started, throw error if another request to /start is received.

This way, if we have scheduled tasks that could overlap, healtcheck can be used as distributed locking system.

**Comment by cuu508** [comment]
Hello, 

by throwing an error do you mean returning a non-200 response to the ping HTTP request?

**Comment by ttr** [comment]
That would be quicker to check in scripts, but even json reply with information that job is already started could be sufficient.

**Comment by cuu508** [comment]
Thanks for the suggestion! This is doable but a little too far outside the project's current scope.
