### ISSUE TITLE
Request: ability to copy all healthchecks from one project to another

### ISSUE THREAD

**Issue by caleb15** [healthchecks/healthchecks#266]
At https://www.15five.com we currently have two VPC's, each with their own project but all the healthchecks are the same. When I created the second project I manually copied over all ~60 healthchecks to the other project, which was a pain. In the future we will be expanding to more VPC's so it would be awesome if we could automatically copy all the healthchecks from one project to another.

**Comment by cuu508** [comment]
I think this would be reasonably easy to do using API calls. Here's a quick example, with no error handling, using Python and the requests library:

```
import requests

API_URL = "https://healthchecks.io/api/v1/checks/"
SOURCE_PROJECT_KEY = "..."
TARGET_PROJECT_KEY = "..."

r = requests.get(API_URL, headers={"X-Api-Key": SOURCE_PROJECT_KEY})
for check in r.json()["checks"]:
    print("Cloning %s " % check["name"])
    requests.post(API_URL, json=check, headers={"X-Api-Key": TARGET_PROJECT_KEY})

```

**Comment by ScottBeeson** [comment]
My request (#288) was a bit less specific than this (or more, depending on perspective).  But I'm fine with it being here.

My use case is within the SAME project.  I would like to be able to clone or duplicate any given check.  I suspect it's extremely common that users have many checks on the same schedule or with the same tags.  Duplicating these options over and over is tedious.  A copy, clone or duplicate feature would be immensely useful.

**Comment by caleb15** [comment]
@cuu508 thanks, that works great :)

**Comment by caleb15** [comment]
I improved the script so it won't add duplicate healthchecks:

```python
import requests

API_URL = "https://healthchecks.io/api/v1/checks/"
SOURCE_PROJECT_READONLY_KEY = "..."
TARGET_PROJECT_KEY = "..."

source_checks = requests.get(API_URL, headers={"X-Api-Key": SOURCE_PROJECT_READONLY_KEY})

target_checks = requests.get(API_URL, headers={"X-Api-Key": TARGET_PROJECT_KEY})
target_check_names = [check["name"] for check in target_checks.json()["checks"]]

for check in source_checks.json()["checks"]:
    if check["name"] in target_check_names:
        print("%s check already present in target" % check["name"])
    else:
        print("Cloning %s" % check["name"])
        requests.post(API_URL, json=check, headers={"X-Api-Key": TARGET_PROJECT_KEY})
```
It's possible to further improve the script to update the healthcheck if already present using `check["update_url"]` 

I also made a quick script for renaming the healthchecks in bulk:
```python
# you can use below to rename checks en masse
# TARGET_PROJECT_KEY = "..."
# target_checks = requests.get(API_URL, headers={"X-Api-Key": TARGET_PROJECT_KEY})
# target_checks = target_checks.json()["checks"]
# for check in target_checks:
#     check["name"] = check["name"].replace("(cloud5) ", "")
#     print("Updating %s" % check["name"])
#     requests.post(check["update_url"], json=check, headers={"X-Api-Key": TARGET_PROJECT_KEY})
```

**Comment by caleb15** [comment]
Another possibility is to use https://github.com/kristofferahl/terraform-provider-healthchecksio to describe the healthchecks as code. One could write a terraform module with the desired healthchecks, and then call that for each environment, passing in a different API key each time.

**Comment by caleb15** [comment]
No longer needed now that we are using https://gist.github.com/caleb15/1a817ef5e58e8a8caf65190cff33806e - closing
