### ISSUE TITLE
E-mails silently fail to send, enabling blocking results in 504

### ISSUE THREAD

**Issue by kidoz-yvr** [healthchecks/healthchecks#267]
Hi,

I'm running in docker and no matter what configuration I try e-mails simply silently fail to send. I tried BLOCKING_EMAILS which resulted in the page eventually timing out when trying to send an e-mail.

Nothing appears in the logs in any case.

I've tried Mailgun, Gmail and Sendmail, all have the same result. The services have no record of receiving an e-mail from the app.

Would appreciate any help! This app looks exactly like what I want, but e-mails really need to work.

My docker-compose:

> version: "2"
> services:
>   healthchecks:
>     image: linuxserver/healthchecks
>     container_name: healthchecks
>     environment:
>       - PUID=1003
>       - PGID=1001
>       - SITE_ROOT=https://health.skyraker.ca
>       - SITE_NAME=Skyraker Health Check
>       - DEFAULT_FROM_EMAIL=<redacted>
>       - EMAIL_HOST=smtp.mailgun.org
>       - EMAIL_PORT=465
>       - EMAIL_HOST_USER=<redacted>
>       - EMAIL_HOST_PASSWORD=<redacted>
>       - EMAIL_USE_TLS=True
>       - REGISTRATION_OPEN=False
>       - DEBUG=True
>     volumes:
>       - /home/ben/healthchecks:/config
>     ports:
>       - 13005:8000
>     restart: unless-stopped

And my local_settings.py:

> EMAIL_PORT = "25" //Experimenting with other ports
> EMAIL_HOST = "smtp.mailgun.org"
> EMAIL_USE_TLS = "False" // Experimenting with configurations
> EMAIL_HOST_USER = "<redacted>"
> SITE_ROOT = "https://health.skyraker.ca"
> SITE_NAME = "Skyraker Health Check"
> DEBUG = "True"
> EMAIL_HOST_PASSWORD = "<redacted>"
> DEFAULT_FROM_EMAIL = "<redacted>"
> BLOCKING_EMAILS = "True" // Results in eventually getting a 504

**Comment by kidoz-yvr** [comment]
I've used telnet to confirm my VM can in fact reach smtp.mailgun.org on port 465.

Also, I see this in the logs when I try to send an e-mail:

> => generated 1794 bytes in 18 msecs (HTTP/1.0 404) 4 headers in 116 bytes (1 switches on core 0)
[uwsgi-daemons] spawning "/usr/bin/python3 ./manage.py sendalerts" (uid: 1003 gid: 1001)

**Comment by cuu508** [comment]
Thanks for the report! 
Do the "Email me a link" emails work? Or, you don't see *any* emails delivered?
If it's the latter, I would suspect some sort of ports / firewall issue. You could try the telnet check from within the container to see if Docker has anything to do with it.

Are you running this on a cloud VM or from a residential IP?

If you add a, say, webhook integration, does that work? – Ttrying to verify tha the sendalerts command is doing any work at all.

Based on the "OSError: write error" message, maybe the port isn't explicitly closed but there still is a firewall rule that's interfering? Have you tried the alternative SMTP ports like 2525?

Unfortunately I cannot jump on reproducing this right now. I'm hoping I can do that next week. In the meantime, could you also report this issue to https://github.com/linuxserver/docker-healthchecks ?

**Comment by kidoz-yvr** [comment]
Thanks for the reply!

No, the 'Email me a link' don't work either - no e-mails ever come through. However a Slack integration I made did.

I'm running this on Google's Cloud Engine. After more reading I see they block port 25, but the others should work fine without firewall modifications.

From _within_ the container I'm able to connect to Mailgun:

> root@f9e32c83e8d5:/# nc -zv smtp.mailgun.org 587
> smtp.mailgun.org (3.209.125.89:587) open
> root@f9e32c83e8d5:/# nc -zv smtp.mailgun.org 465
> smtp.mailgun.org (3.209.125.89:465) open

Unfortunately Mailgun doesn't support 2525.

I'll definitely report to the docker github as well, though I also tried this alternative docker image with the same results: https://hub.docker.com/r/galexrt/healthchecks/

Thanks so much for the help!

**Comment by kidoz-yvr** [comment]
I tried deploying the same configuration on another VM of mine with a different host to see if this is a Google thing. I see the same behaviour so I don't _think_ it's a firewall issue (all outgoing traffic should be unrestricted).

**Comment by kidoz-yvr** [comment]
Cross-posted: https://github.com/linuxserver/docker-healthchecks/issues/24

**Comment by cuu508** [comment]
Is the other VM also in GCP?

As it happens, for a while I was running Healthchecks.io, the hosted service, on GCP as well. I also ran into port issues, and this was the configuration that worked for me:

```
EMAIL_HOST = "email-smtp.us-east-1.amazonaws.com"
EMAIL_PORT = 2587
EMAIL_HOST_USER = "***"
EMAIL_HOST_PASSWORD = "***"
EMAIL_USE_TLS = True
```

Are you sure Mailgun doesn't support 2525? A quick google search turned up [this](https://www.mailgun.com/blog/which-smtp-port-understanding-ports-25-465-587):

> Port 2525:
> 
> This port is not endorsed by the IETF nor IANA. Instead, Mailgun provides it as an alternate port, which mirrors port 587, in the event the above ports are blocked. Because 2525 is a non-traditional high port number, it is typically allowed on consumer ISPs and Cloud Hosting providers, like Google Compute Engine. If you’ve tried the above ports, but experience connectivity issues, try port 2525. This port also supports TLS encryption.

**Comment by kidoz-yvr** [comment]
Ok! Port 2525 (with an explicit firewall rule allowing it) works!!!!

Thank you so much! Very happy to have this working!
