### ISSUE TITLE
No emails send from sendalerts while sendreports (and sendtestmail) work

### ISSUE THREAD

**Issue by vdrHorst** [healthchecks/healthchecks#275]
All processes are running fine. (runserver, sendalerts and sendreports running)
Email configuration to email server is ok, as sendreport process and sentestmail work correctly.
Only the sendalerts process does not send out actual emails to the project team owner/members.

Sendalerts output shows the (idle) timemarks, and the status up/down triggers correctly, hereby snippet of the output:
> -- MARK 2019-08-15T00:14:00.081499+00:00 --
> -- MARK 2019-08-15T00:16:00.475288+00:00 --
> -- MARK 2019-08-15T00:18:00.907085+00:00 --
> Sending alert, status=up, code=57335f8a-7958-4a47-93e2-a49e14fa4510
> -- MARK 2019-08-15T00:20:01.324241+00:00 --
> Sending alert, status=down, code=57335f8a-7958-4a47-93e2-a49e14fa4510
> Sending alert, status=up, code=57335f8a-7958-4a47-93e2-a49e14fa4510
> -- MARK 2019-08-15T00:22:01.782026+00:00 --
> Sending alert, status=down, code=57335f8a-7958-4a47-93e2-a49e14fa4510
> -- MARK 2019-08-15T00:24:02.207298+00:00 --
> -- MARK 2019-08-15T00:26:02.608053+00:00 --
> -- MARK 2019-08-15T00:28:03.015432+00:00 --
> Sending alert, status=down, code=2f714af4-473f-4fa5-ada6-51d52a5d98c9
> -- MARK 2019-08-15T00:30:03.433232+00:00 --

However, no email have been send during this timeframe.
What am I missing?. What could I do to further investigate the problem?

**Comment by cuu508** [comment]
If you look in the Integrations page on the website, does it by any chance show "(unconfirmed)" next to the email address?

**Comment by vdrHorst** [comment]
The /integrations page did not work yet, server error 500. 
(As I thought this was only needed for "special" integrations, I did not investigate this as possible root cause for the sendalerts not working, as sendreports do work... Ok, so need to fix the integration now...)

Got this error, most likely to to with my choice using an Oracle backend:

> DatabaseError at /integrations/
> ORA-00932: inconsistent datatypes: expected - got NCLOB
> Request Method:	GET
> Request URL:	http://<hostname>:8000/integrations/
> Django Version:	2.2.3
> Exception Type:	DatabaseError
> Exception Value:	
> ORA-00932: inconsistent datatypes: expected - got NCLOB
> Exception Location:	/ohi/envBase/OPHC/healthchecks-venv/lib64/python3.6/site-packages/django/db/backends/oracle/base.py in execute, line 510
> Python Executable:	/ohi/envBase/OPHC/healthchecks-venv/bin/python
> Python Version:	3.6.3

**Comment by vdrHorst** [comment]
Btw, as owner of the project, ain't my email address automatically "confirmed"? Saw that added members need to confirm their email.

**Comment by cuu508** [comment]
For the project that was automatically created when creating – yes, your email address is already confirmed. If you added the email address manually, or created a second project, it would need to be verified / confirmed. 

Just wanted to confirm the issue was not something simple such as an unconfirmed address before we dig deeper...

**Comment by vdrHorst** [comment]
Investigation results so far, most likely ran into known issue https://code.djangoproject.com/ticket/24096
My workarround for now: manually changed database field API_CHANNEL.VALUE from NCLOB type to NVARCHAR2(2000 CHAR)
I do not know if the sizing is enough, but the page now loads successfully.

**Comment by vdrHorst** [comment]
This solved the sendalerts issue, email is now send.
Root cause was that I did not know (then) the mandatory integration setup.
