### ISSUE TITLE
Feature Request: Mattermost Integration

### ISSUE THREAD

**Issue by pjaudiomv** [healthchecks/healthchecks#276]
it would be nice to be able to integrate with mattermost, especially fot on-prem solutions. 

https://developers.mattermost.com/integrate/incoming-webhooks/

**Comment by cuu508** [comment]
Thanks for the suggestion! Went ahead and implemented this, as the integration is very similar to the Slack one, and so not much extra effort for me.

The integration is available on Healthcecks.io, you are welcome to try it out!

**Comment by pjaudiomv** [comment]
awesome, that was quick. I tested it on healthchecks.io, and local docker dev. works great. thank you so much.
