### ISSUE TITLE
Support multiple language

### ISSUE THREAD

**Issue by roperluo32** [healthchecks/healthchecks#277]
Do we have any plan to support multiple language？

**Comment by cuu508** [comment]
So far there haven't been any requests for localization support, so I have no near-term plans for that. 

I've assumed the audience of this tool is technical and so is generally fine with English. What languages are you interested in? Are you dealing with a regulatory requirement?

**Comment by roperluo32** [comment]
Thank you for your replay.
I want to translate this web to Chinese. I found this web don't support multiple language template now. So may be we can make the django html support language template.

**Comment by cuu508** [comment]
In #406, we set up the landing page  for translation, and added translations in Italian and Latvian. You can submit a PR for translations in other languages. 

I'm happy to review PRs that add translation support for other pages as well.
