### ISSUE TITLE
Support schedules such as every 85 minutes

### ISSUE THREAD

**Issue by ojotoxy** [healthchecks/healthchecks#281]
We can set schedules with granularity every minute, up to 60 minutes, then the granularity is 1 hour... So we can't set schedules such as every 80 minutes.

**Comment by jesse-holden** [comment]
You can already achieve granularity by creating/updating checks via API, you can supply the schedules with intervals accurate to the second.

**Comment by cuu508** [comment]
UI suggestions [from @peternlewis on twitter](https://twitter.com/peternlewis/status/1360029641663160320):

> maybe just something between the sliders and cron that just lets me enter the number of days/hours for each as numbers. Or maybe in the slider window, a text field, so changing the slider changes the number, but changing the number also works (and changes the slider).

**Comment by cuu508** [comment]
One part I'm not sure about is the "[number] minutes|hours|days" special syntax. It would need to be documented somewhere, there would be corner cases, and user errors. A more structured alternative:

![image](https://user-images.githubusercontent.com/661859/140081440-7b099770-383c-4d7f-bae3-94a6d99a6b43.png)

The user can enter a number, and select minutes / hours / days from the dropdown. This would prevent invalid inputs like "2 months" but would still allow "85 minutes" or "60 days".

**Comment by ojotoxy** [comment]
I like the dropdown a lot.
