### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by mzch** [healthchecks/healthchecks#283]
Hi,

in local_settings.py when set DEBUG = False, healthchecks works well, but when DEBUG = True, only the error message shows 'Server Error (500). How can I fix this issue?

HealthCheck: 1.9.0
Python: 3.7.4
MariaDB: 10.3.15-MariaDB
OS: Debian GNU/Linux 10 (Buster)

**Comment by cuu508** [comment]
To diagnose this, we need to know the error details. When DEBUG is False, Django sends tracebacks to email addresses listed in the [ADMINS](https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-ADMINS) setting. Try putting your name and address there and see if you get an email with more details. You may also need to fix the [SERVER_EMAIL](https://docs.djangoproject.com/en/2.2/ref/settings/#server-email) setting.

Alternatively, you can tweak Django's logging to print error details to console even with DEBUG=False. Details here: https://www.agiliq.com/blog/2017/12/configure-django-log-exceptions-production/

**Comment by mzch** [comment]
Thanks for your reply. I added ADMIN to local_settings and the error report said 'You may need python manage.py compress'. When I did it, everything went well. :) Please add the step to README.md.

**Comment by cuu508** [comment]
Thanks, good idea – I've updated README with a "Running in Production" section. Some parts of it probably need to be expanded, but it's a start.

**Comment by mzch** [comment]
Great! Thanks, @cuu508 !
