### ISSUE TITLE
add_pushover logic seems completely broken

### ISSUE THREAD

**Issue by anymuster2** [healthchecks/healthchecks#285]
The logic in the function add_pushover ( https://github.com/healthchecks/healthchecks/blob/master/hc/front/views.py#L1060 ) doesn't make a lot of sense. I cannot get it to add a valid Pushover entity.

I'm unclear on what the intended purpose of PUSHOVER_SUBSCRIPTION_URL is, but POST seems to redirect to that URL (when judging by other functions, a POST should create a `Channel` db entry).

There's also a spelling error in a h1:
```
grep -r "Pushbover" 
templates/integrations/add_pushover.html:10:    <h1>Pushbover</h1>
```

Also, assuming you're the owner of pushover.io, just a heads up that in 'Billing' my account says 'Checks: n / 500' but under pricing it says I'm limited to 20 :)

**Comment by cuu508** [comment]
The Pushover integration setup works like this:

1. In the "Add Pushover" page you click on "Subscribe with Pushover". This makes a POST call to the Healthchecks server
2. Healthchecks redirects you to pushover.net (the exact location specified in `PUSHOVER_SUBSCRIPTION_URL`)
3. On pushover.net you log into your Pushover account and grant permission to send you notifications
4. After granting the permission, the pushover.net website redirects you back to Healthchecks, and passes the credentials (most importantly, `pushover_user_key`) in query string
5. Healthchecks creates a `Channel` object and stores the credentials

More details: https://pushover.net/api/subscriptions#web

> I cannot get it to add a valid Pushover entity.

Can you please describe step by step what you're doing and what you're seeing (any error messages?)

> There's also a spelling error in a h1:

Fixed the spelling error – thanks!

> Also, assuming you're the owner of pushover.io, just a heads up that in 'Billing' my account says 'Checks: n / 500' but under pricing it says I'm limited to 20 :)

Did you by any chance create your Healthchecks.io account long ago (2017 or before)?
When I was making changes to pricing and account limits, I made sure to "grandfather" the existing users.

**Comment by anymuster2** [comment]
Ah, that makes sense - coming from other services, I expected to create a pushover API code and add that to the local healthchecks instance manually. 

Could you please give a demonstration of correct PUSHOVER_SUBSCRIPTION_URL and PUSHOVER_API_TOKEN values?  (On Pushover Dashboard I have a 'User Key' and per-'application' API keys)

**Comment by cuu508** [comment]
To enable Pushover integration on your instance, you will need to:

* register a new application at https://pushover.net/apps/build
* enable subscriptions in your application and make sure to enable the URL
  subscription type

Pushover will then show you the values to use as `PUSHOVER_API_TOKEN` and `PUSHOVER_SUBSCRIPTION_URL`.

**Comment by anymuster2** [comment]
I've gotten slightly further, but Pushover doesn't redirect back to my local healthchecks instance. The URL my healthchecks redirects to Healthchecks with is as follows (sorry for the redactions)

`https://pushover.net/subscribe/MyHCAppName-RandomKeys?success=http%3A%2F%2Fredacted%2Fintegrations%2Fadd_pushover%2F%3Fstate%3DOAVy0oF20LxW%26prio%3D0%26prio_up%3D0&failure=http%3A%2F%2Fredacted%2Fintegrations%2F`

On opening Healthchecks, it prompts me to subscribe to the app, on clicking 'subscribe me' I get redirected to https://pushover.net/ which renders my landing dashboard (app list, api keys, settings etc)

**Comment by cuu508** [comment]
In Pushover, Edit Application > Edit Subscription Settings, have you selected Subscription Type = URL?

![image](https://user-images.githubusercontent.com/661859/64514802-09d02580-d2f4-11e9-8e4f-0b5ab58f57b1.png)

**Comment by anymuster2** [comment]
Thanks that's fixed it :) See the above PR feel free to reject if you don't see it as appropriate.

**Comment by nightah** [comment]
@cuu508 I don't mean to necro bump an old thread but has something changed with the pushover integration?
I've followed the respective steps but when healthchecks redirects to Pushover I get an error stating:
```
Subscribe to Healthchecks
Error: This application did not supply a required parameter and is not accepting subscriptions at this time. Please contact the application maintainer.
```

The link constructed by healthchecks to send to Pushover is very similar to the one @anymuster2 posted above, I can see both the `PUSHOVER_API_TOKEN` and `PUSHOVER_SUBSCRIPTION_URL` are present and accurate too.

**Comment by nightah** [comment]
Nevermind, looks like the issue was because when I first setup healthchecks the `SITE_ROOT` variable didn't include the `https://` string.
