### ISSUE TITLE
Edit option on mobile

### ISSUE THREAD

**Issue by alex-phillips** [healthchecks/healthchecks#286]
The mobile view doesn't have any way to enter the edit page of a check. I have to request the desktop site to edit.

**Comment by jesse-holden** [comment]
I believe this is in fact a CSS issue, visiting the page in landscape mode does reveal the edit button to the right.

A suggestion I have would be to add a click event to the entire row, that way if you click between the columns you could go to the details page for that check.

**Comment by cuu508** [comment]
I "fixed" the mobile view to always show the gear icon. To make room for it, the "Last Ping" column is now hidden in the mobile view. 

Thanks for the suggestion about handling clicks on the entire row. Currently, clicking on name brings up the "Edit Name" dialog. And, before I removed the "Last Ping" column, clicking on the last ping area was bringing up another dialog. That leaves very little space for "entire row" click target.
