### ISSUE TITLE
Request: Ability to clone or duplicate a check

### ISSUE THREAD

**Issue by ScottBeeson** [healthchecks/healthchecks#288]
I'm creating checks for a bunch of servers. It would be nice if I could just clone or duplicate them instead of modifying the schedules and other values over and over.

**Comment by cuu508** [comment]
Hi @ScottBeeson – this has been requested already: #266.

**Comment by cuu508** [comment]
> My use case is within the SAME project. I would like to be able to clone or duplicate any given check. I suspect it's extremely common that users have many checks on the same schedule or with the same tags. Duplicating these options over and over is tedious and prone to error. A copy, clone or duplicate feature would be immensely useful.

Sorry – I should have read more carefully! This is of course different from the "duplicate my whole project" use case. And I can see how this would be useful when setting up checks for several similar services within a project. I'm planning to work on this, but, as with all feature requests, cannot promise deadlines.

**Comment by ScottBeeson** [comment]
No problem!  I'm quoting my updated response from that post here for convenience (sorry I edited it like 10 times)

> My request (#288) was a bit different than this one. My use case is within the SAME project and applied only to a SINGLE check. But I'm fine with it being here.

I would like to be able to clone or duplicate any given check. I suspect it's extremely common that users have many checks on the same schedule or with the same tags. Duplicating these options over and over is tedious and prone to error. A copy, clone or duplicate feature for individual checks (in my case) would be immensely useful. A separate "Copy Project" function might satisfy OPs need.

The API call above does not fit my use case.

**Comment by cuu508** [comment]
Hi @ScottBeeson – I've now implemented and deployed a "Create a Copy" function. You are welcome to test it out when you get a chance!

**Comment by ScottBeeson** [comment]
Outstanding! I'll try to do that soon.
