### ISSUE TITLE
OpsGenie EU support

### ISSUE THREAD

**Issue by robertbeal** [healthchecks/healthchecks#294]
Annoyingly, OpsGenie have a US (?) and EU service, both with slightly different api urls and you can only belong to one or the other.

https://api.eu.opsgenie.com
https://api.opsgenie.com

Would it be possible to add a way of selecting "EU" as part of the integration?

I currently have an EU account, and the integration points to `api.opsgenie.com` which results in a 401 (as my account isn't in that region)

**Comment by cuu508** [comment]
Oops, wasn't aware of the EU region. There should be no problem adding support for it – I'm planning to do this, but cannot promise deadlines.

**Comment by robertbeal** [comment]
No worries and no rush (at least on my behalf). Been having a nose through the code myself but sturggled to pinpoint where to apply the change.

**Comment by robertbeal** [comment]
Wow, that's a crazy quick turnaround! I'll get trying it :)
