### ISSUE TITLE
slackbot link expand triggering ping

### ISSUE THREAD

**Issue by tpatrascu** [healthchecks/healthchecks#297]
Hello,

When using the slack integration, if the check triggered a slack message, the slackbot link expanding will ping the check URL daily and we won't get notified if a daily task fails.

User Agent
Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)

Thanks!

**Comment by cuu508** [comment]
Hello,

how have you set up the Slack integration? How do the Slack messages with check URLs look?

Just sent a quick test message, and here's how the Slack notification looks for me:

![image](https://user-images.githubusercontent.com/661859/67840363-5c60dd80-fafe-11e9-9a53-23ff7b679a9b.png)

It does not contain the check URL and so Slack doesn't visit it.

If I paste the check URL in a Slack channel myself, then Slack does indeed visit the link, and that gets registered as ping.

**Comment by tpatrascu** [comment]
Hello,

Actually I realized the healthcheck url was being posted to a slack channel by a logging setup.

Would be nice to be able to exclude User-agents or have an exact match for them though.

Thanks,
Tiberiu

**Comment by jesse-holden** [comment]
I don't think adding a user-agent exclusion list is an ideal way to handle this situation. 

I think the best solution is to add a configurable options to our checks to only register POST requests to the endpoints, this will resolve any issues of links being pre-fetched.

**Comment by cuu508** [comment]
I agree, an option to ignore anything but POST requests seems a more robust way to prevent link prefetching, scraping etc. 

I'm planning on adding this but cannot promise an ETA.

**Comment by cuu508** [comment]
Added a "Filtering Rules" dialog where you can specify that a check should only accept HTTP POST requests. 

![image](https://user-images.githubusercontent.com/661859/69732905-26327000-1135-11ea-92db-3975da9333ee.png)


https://healthchecks.io is not updated yet. I'll re-close this issue once that's done.

**Comment by cuu508** [comment]
Updated https://healthchecks.io
