### ISSUE TITLE
heroku deployment documentation

### ISSUE THREAD

**Issue by diwu1989** [healthchecks/healthchecks#3]
can you make it possible to deploy this on heroku easily?

**Comment by diwu1989** [comment]
I forked this app and made some changes to the settings file to make it Heroku friendly
https://github.com/BetterWorks/healthchecks

**Comment by cuu508** [comment]
Thanks for heads up! I'll see if I can appropriate some of the changes you've done.
One suggestion: you can create a file local_settings.py next to settings.py and put deployment-specific settings in there. Things like Postmark configuration, NewRelic configuration, the code which  looks at environment variables and so on.

**Comment by diwu1989** [comment]
Deal, that's a good idea, then I'd have less merge conflicts against your version of the settings file when I rebase

**Comment by diwu1989** [comment]
and :+1: for the additional 'pause' state, the try-except around the sendalerts task is the first thing I had to implement

**Comment by diwu1989** [comment]
closing this issue, if anyone is interested to see how I run this on Heroku, check out my fork
