### ISSUE TITLE
Could we have a prometheus integration ?

### ISSUE THREAD

**Issue by BobCashStory** [healthchecks/healthchecks#300]

**Comment by cuu508** [comment]
Possibly! 

What type of integration are you thinking about?

* Healthchecks exposing an API endpoint that Prometheus can scrape. Build Grafana (or whatever) dashboards with some data coming from Healthchecks
* or, using Healthchecks to monitor a Prometheus instance, and to get alerted when Prometheus isn't running?

**Comment by BobCashStory** [comment]
i was thinking about Healthchecks exposing an API endpoint that Prometheus can scrape.

**Comment by DaveTCode** [comment]
This just came up in our org. What I'd be looking at is a single endpoint we can call for a given project:
e.g. https://healthchecks.io/projects/REDACTED/checks/metrics

which exposed metrics like 
my_healthcheck_by_name_up 1

Nothing particularly complicated, just a way to bring those alerts into the same grafana dashboard as ones coming from alert manager and into the same location as the metrics for the systems sending the healthchecks.

**Comment by BobCashStory** [comment]
Prometheus endpoint should be global and query in grafana should be specific

**Comment by BobCashStory** [comment]
any update on this ?

**Comment by cuu508** [comment]
I looked at this a little bit further. I'm new to Prometheus, have no experience with setting up dashboards and writing exporters. Ideally I'd like someone experienced with Prometheus to provide a sample of what the metrics endpoint should return. This would help me out a lot. 

A few things I'm unsure about in particular:

* Prometheus metric names use lower_case and only [a-zA-Z0-9:_] symbols. So, in many cases, we cannot use check names as metric names as-is. Should we sanitize them ("Prod Database Backup" -> "prod_database_backup")?

* Also, in Healthchecks.io, you can have two checks with identical names. How do we disambiguate them in the /metrics endpoint?

* When exporting check's status, what data type should we use? Use "gauge" and 0=down, 1=up? Would it pontentially be useful to also report the "new", and "paused" status somehow?

* Do we report anything besides each check's status? e.g., the timestamp of the last received ping? 

* Do we report the status of each tag as well? It would be similar to the status badges, just fed into Prometheus

* Do we report project-wide totals like "num_checks", "num_checks_down"?

As a concrete example, here's a sample response from the "get checks" API call:

```
{
    "checks": [
        {
            "name": "UptimeRobot",
            "tags": "",
            "desc": "",
            "grace": 600,
            "n_pings": 54018,
            "status": "up",
            "last_ping": "2020-01-21T14:36:43+00:00",
            "next_ping": "2020-01-21T14:41:43+00:00",
            "unique_key": "23cdd9acde006730f3cbad75cf359296016751e8",
            "timeout": 300
        },
        {
            "name": "HetrixTools",
            "tags": "",
            "desc": "",
            "grace": 600,
            "n_pings": 728712,
            "status": "up",
            "last_ping": "2020-01-21T14:39:16+00:00",
            "next_ping": "2020-01-21T14:44:16+00:00",
            "unique_key": "a77daf1dac141777a664cbc882eb028d77e88315",
            "timeout": 300
        },
        {
            "name": "Checkly",
            "tags": "",
            "desc": "",
            "grace": 600,
            "n_pings": 4497,
            "status": "down",
            "last_ping": "2019-11-02T08:24:36+00:00",
            "next_ping": null,
            "unique_key": "1a10a78902d09ce721a732c9a283162e441d9f51",
            "timeout": 300
        },
        {
            "name": "Circonus",
            "tags": "",
            "desc": "",
            "grace": 600,
            "n_pings": 579322,
            "status": "up",
            "last_ping": "2020-01-21T14:39:19+00:00",
            "next_ping": "2020-01-21T14:44:19+00:00",
            "unique_key": "f94406f51e73f3b551c1b6c94f78da040320de10",
            "timeout": 300
        },
        {
            "name": "StatusCake",
            "tags": "",
            "desc": "",
            "grace": 600,
            "n_pings": 56693,
            "status": "up",
            "last_ping": "2020-01-21T14:36:31+00:00",
            "next_ping": "2020-01-21T14:41:31+00:00",
            "unique_key": "1e2f9f26387e0a12e3e6f32cf4b0ecee54dea747",
            "timeout": 300
        },
        {
            "name": "NIXStats",
            "tags": "",
            "desc": "",
            "grace": 600,
            "n_pings": 57293,
            "status": "up",
            "last_ping": "2020-01-21T14:35:14+00:00",
            "next_ping": "2020-01-21T14:40:14+00:00",
            "unique_key": "6c3f1f0fd7b834949cf4cec5ed5676279fd44855",
            "timeout": 300
        },
        {
            "name": "Updown.io",
            "tags": "",
            "desc": "",
            "grace": 60,
            "n_pings": 31224,
            "status": "up",
            "last_ping": "2020-01-21T14:37:00+00:00",
            "next_ping": "2020-01-21T14:42:00+00:00",
            "unique_key": "677b6d7095e977def83cf21f286999ab2410e8a9",
            "timeout": 300
        },
        {
            "name": "Port Monitor",
            "tags": "",
            "desc": "",
            "grace": 600,
            "n_pings": 57671,
            "status": "up",
            "last_ping": "2020-01-21T14:36:22+00:00",
            "next_ping": "2020-01-21T14:41:22+00:00",
            "unique_key": "869b64dc93597d40f95a7b7fd60011d235371559",
            "timeout": 300
        }
    ]
}
```

How would one go about converting it into a Prometheus friendly format?

> Prometheus endpoint should be global and query in grafana should be specific

@BobCashStory do you mean global across multiple projects?

To me, having a separate endpoint for each project seems natural: we already have per-project API keys, and we could reuse them here.

**Comment by cuu508** [comment]
From https://prometheus.io/docs/instrumenting/writing_exporters/ --

> As a rule of thumb, no part of a metric name should ever be procedurally generated (use labels instead). 

So perhaps,

```
check_status{label="/opt backups"} 0
check_status{label="New Reports"} 1
check_status{label="Product Sync"} 1
check_status{label="DB Backups"} 0
check_status{label="Weekly Reports"} 0
```

**Comment by BobCashStory** [comment]
@cuu508 i agree on `To me, having a separate endpoint for each project seems natural: we already have per-project API keys, and we could reuse them here.` i was not getting your point at first.

**Comment by DaveTCode** [comment]
@cuu508 - that proposal would certainly work for _my_ use case but despite using it fairly extensively I'm not sure I'm qualified to sign it off. I've asked internally at my org to see if we have someone happy to review.

In the meantime I looked at the output of a few exporters:
```
# HELP pg_up Whether the last scrape of metrics from PostgreSQL was able to connect to the server (1 for yes, 0 for no).
# TYPE pg_up gauge
pg_up 1
```

lends credence to using a gauge for hc_status

**Comment by AlexHockey** [comment]
@cuu508 your latest comment is along the right line I think. 

As the application developer you decide what metrics are useful to expose about your application. Each one of those then becomes a metric with a name of your choosing. But the metrics wouldn't change depending on what checks are configured. 

A metric can have multiple labels. So instead of just `hc_status{label="/opt backups"} 0` you could have `hc_status{name="/opt backups", tags="sandbox", unique_key="8ae6264ea885d3e2c8ea63b7470858e97281cfaf"} 0`. This could be used to disambiguate checks with the same name. 

You should only use labels for properties of the check that don't change (because if you change the label values for a check prometheus treats it as a completely fresh time series). Also labels have a cost in prometheus, so not *everything* should be a label (think of them like indexes in a relational database - i.e. primarily for filtering rather than conveying information). 

> When exporting check's status, what data type should we use? Use "gauge" and 0=down, 1=up?

I agree that gauge is appropriate here. 

> Do we report the status of each tag as well?

Not all the metrics need to have the same labels, so you could have a metric like `tag_status{tag="foo"} 1`

> Do we report project-wide totals like "num_checks", "num_checks_down"?

Sounds reasonable. Though the [metrics and label naming guide](https://prometheus.io/docs/practices/naming/) suggests `checks_up_total` and `checks_down_total` might be better names.

**Comment by cuu508** [comment]
@DaveTCode, @AlexHockey thanks for the feedback!

A couple additional thoughts:

* looks like `hc_checks_up` would be a more idiomatic metic name than `hc_status`
* I had included `hc_pings_total`, `hc_last_ping` and `hc_next_ping` in the above mockup, but perhaps we should start with bare minimum, and only add metrics when there is a specific need.
* checks can have multiple tags. I'm not sure how that would work with Prometheus labels. If one check has `tags="sandbox"` label and another has `tags="sandbox worker"` label, is that useful?

A revised mockup:

```
# HELP hc_check_up Whether the check is currently up (1 for yes, 0 for no).
# TYPE hc_check_up gauge
hc_check_up{name="/opt backups", unique_key="819..."} 0
hc_check_up{name="New Reports", unique_key="aa2..."} 1
hc_check_up{name="Product Sync", unique_key="27e..."} 1
hc_check_up{name="DB Backups", unique_key="9e6..."} 0
hc_check_up{name="Weekly Reports"} 0

# HELP hc_tag_up Whether all checks with this tag are up (1 for yes, 0 for no).
# TYPE hc_tag_up gauge
hc_tag_up{tag="sandbox"} 0
hc_tag_up{tag="worker"} 0
hc_tag_up{tag="prod"} 0
hc_tag_up{tag="db"} 0

# HELP hc_checks_total The total number of checks.
# TYPE hc_checks_total gauge
hc_checks_total 5

# HELP hc_checks_total The number of checks currently down.
# TYPE hc_checks_down_total gauge
hc_checks_down_total 3
```

**Comment by AlexHockey** [comment]
> checks can have multiple tags. I'm not sure how that would work with Prometheus labels. If one check has tags="sandbox" label and another has tags="sandbox worker" label, is that useful?

The Prometheus Query Language ([PromQL](https://prometheus.io/docs/prometheus/latest/querying/basics/)) supports regex matching on labels so if you have `hc_check_up{tags="sandbox worker"} 1`, then the query `hc_check_up{tag=~"sandbox"}` will find it.

**Comment by cuu508** [comment]
I've now implemented an experimental version of the metrics endpoint. 
You can look up its address in **Project Settings > Show API Keys** (already available on https://healthchecks.io). 

In prometheus.yml, I used:
```
scrape_configs:
  - job_name: 'healthchecks-io'
    scheme: https
    metrics_path: /projects/<code>/checks/metrics/<readonly-api-key>
    static_configs:
    - targets: ['healthchecks.io']
```

And Prometheus seemed to be able to scrape it. 

@BobCashStory, @DaveTCode feel free to try it out. I'm interested in feedback on whether this is useful, and what should be changed or added.

**Comment by DaveTCode** [comment]
Great, I've added a scrape config to our prometheus instance which pulls those in and trivially added some panels to our grafana single pane dashboard. All working fine, I'll stress it a bit more on Monday

**Comment by cuu508** [comment]
Added setup instructions in the Integrations section:

![Screenshot from 2020-02-20 11-39-10](https://user-images.githubusercontent.com/661859/74920968-b2230380-53d5-11ea-9189-f2a5d2a5f9e1.png)

I'll consider the initial version done, and close this issue.

**Comment by tabic** [comment]
Has anyone already written a grafana dashboard for those metrics?

**Comment by jayjah** [comment]
@tabic There's not so much of data to evaluate in grafana dashboards. I have only these values: 

# HELP hc_checks_total The total number of checks.
# TYPE hc_checks_total gauge
hc_checks_total 1

# HELP hc_checks_down_total The number of checks currently down.
# TYPE hc_checks_down_total gauge
hc_checks_down_total 0 

I made just a simple dashboard to evaluate if cronjob failed or not. Herefore I just use the /fail flag for the healthcheck url to indicate a fail of my cronjob. Moreover I integrated alertmanager for the same fail rule.
