### ISSUE TITLE
Feature Request: Make ping.body size configurable

### ISSUE THREAD

**Issue by nightah** [healthchecks/healthchecks#301]
Hi Team,

I've recently replaced numerous different tools and processes with healthchecks and I have to say it's a fantastic piece of software.

While migrating I noticed based on the documentation/code that when POSTing to an endpoint we can include additional diagnostic information, however, this is truncated to 10 kilobytes.

I've searched around the issue and PR history to see when/how this got included and I can see discussions about the database size and looking to try and minimise any impact.
Could we perhaps have an opt-in configurable field to increase the limit of the body which can be stored?

**Comment by cuu508** [comment]
Yes, I think that's doable. The 10'000 byte limit is currently enforced both at database level and in python code. We could:

* in the Ping model, change `CharField(max_length=10000)` to `TextField` – removes the database limit
* replace the hardcoded 10000 value in `hc.api.models.Check.ping()` method with a value from django.conf.settings

**Comment by nightah** [comment]
Thanks @cuu508!
