### ISSUE TITLE
Feature Request: Add integration to run local shell/python scripts

### ISSUE THREAD

**Issue by gganeshan** [healthchecks/healthchecks#302]
@cuu508 thank you once again for this amazing tool. I have been playing around with it a lot and am almost ready to deploy the self hosted version to prod.

I love the numerous tools with which we can integrate this app.

In our org though, we use `snmp-traps` for alerting and I was wondering if you can add an integration to run local shell/python scripts for me to accomplish this.

This integration can have the same variables as the ***Webhook*** integration.
Please let me know your thoughts.

Alternatively, can you suggest a workaround to be able to run a shell/python script when the status of an alert changes state.

**Comment by cuu508** [comment]
Thanks for the suggestion, I like this idea – would give the ultimate flexibility to selfhosted instances with trusted users. Will work on implementing it.

**Comment by gganeshan** [comment]
> Will work on implementing it.

This is great news.
Thanks @cuu508 once again.

**Comment by cuu508** [comment]
@gganeshan – just added an initial version of the "Shell Commands" integration. 

I've done some testing locally, but it would be great if you could give it a shot and see if it works OK for you, and handles your use case(s). 

A word of caution: only enable it if you fully trust the users of your Healthchecks instance. The commands will be executed by the `manage.py sendalerts` process, and will run with the same system permissions as the `sendalerts` process. (Added this note to README too)

**Comment by gganeshan** [comment]
> t would be great if you could give it a shot and see if it works OK for you, and handles your use case(s).

sure thing. will try today and revert with comments/feedback.



> only enable it if you fully trust the users of your Healthchecks instance. The commands will be executed by the `manage.py sendalerts` process, and will run with the same system permissions as the `sendalerts` process.

Good to know.
Our container is configured to run as an unprivileged user and has a `readonly` filesystem. So we should be pretty much safe but I will still test it rigorously.

Thanks once again for the quick turnaround.

**Comment by gganeshan** [comment]
> sure thing. will try today and revert with comments/feedback.

Looks good to me @cuu508 .
Please let me know when you plan on cutting a new release with this feature.

Thanks once again for the quick turnaround.

**Comment by cuu508** [comment]
In the coming couple days – I'll reopen this issue so I don't forget.

**Comment by cuu508** [comment]
Released v1.11.0
