### ISSUE TITLE
Where do I get PD_VENDOR_KEY ?

### ISSUE THREAD

**Issue by gsiddardha** [healthchecks/healthchecks#303]
Hi, 

I'm trying to setup healthchecks on my system with PD integration. This requires PD_VENDOR_KEY value to be set. I am not able to find any documentation on pagerduty website on how to get this value. Can someone please help point me to the right documentation?

**Comment by cuu508** [comment]
PD_VENDOR_KEY is needed for PagerDuty Connect, a mechanism for authorizing an integration to access user's PagerDuty account.

From https://www.pagerduty.com/docs/guides/pagerduty-connect/

> vendor: A unique identifier for the partner. Please contact support for your vendor key.

I got my vendor key after filling out a "Become a Partner" form somewhere on their site (this was a while ago, not sure if the process would be the same now). 

For private self-hosted installations becoming a partner might not be feasible, but it should be possible to use PagerDuty API without using PagerDuty Connect. In fact, this is how the integration used to work before I implemented PagerDuty Connect here:

https://github.com/healthchecks/healthchecks/commit/96e00df0ab4c330b40b74c7c8fbe3c8668f9e38f

Ideally Healthchecks would use the old way if PD_VENDOR_KEY is not set, and PagerDuty Connect if PD_VENDOR_KEY *is* set.

**Comment by gsiddardha** [comment]
Got it. 

Currently healthchecks also has a restriction on the key to be non-null, to allow PD integration. 
1. [Enable PD integration only if `enable_pd`](https://github.com/healthchecks/healthchecks/blob/master/templates/front/channels.html#L254)
2. [Set `enable_pd` to `false` if `PD_VENDOR_KEY` is None](https://github.com/healthchecks/healthchecks/blob/master/hc/front/views.py#L255)

I guess I can manually add a Channel entry with `kind` = pd as a hack for now. Please correct me if I'm wrong.

**Comment by cuu508** [comment]
Ah yes, that would be a clever workaround for time being. When creating the Channel, the value field needs to look like so:

`{"service_key": "api key here", "account": "name of the account for display"}`

**Comment by gsiddardha** [comment]
cool. got it working. thanks for the support. 

Any thoughts on how we can manage this better? instead of manually adding a channel for each new project.

**Comment by cuu508** [comment]
> Any thoughts on how we can manage this better? instead of manually adding a channel for each new project.

I'm working on supporting both the old onboarding flow where the user supplies an API key, and the PagerDuty Connect one (if PD_VENDOR_KEY is set).

**Comment by cuu508** [comment]
This is now implemented – you can now add a PagerDuty integration without having the `PD_VENDOR_KEY` set.
