### ISSUE TITLE
Add shields.io json endpoint

### ISSUE THREAD

**Issue by SuperSandro2000** [healthchecks/healthchecks#304]
Ideally I would like to use a json endpoint from healthchecks to fill the badges from shields.io with data.

Shields.io has great badge customization, uniform look and caching to keep stress from my personal server.

Sadly you can't customize the fields shields.io should use so I can't use the current json endpoint.

Could you add support for that? You can find the simple and short documentation [here](https://shields.io/endpoint)

**Comment by cuu508** [comment]
I've added shields.io-compatible API endpoint, this is now available on https://healthchecks.io –

![image](https://user-images.githubusercontent.com/661859/70232593-79c04180-1765-11ea-961a-09903c23427f.png)
