### ISSUE TITLE
Badge per check

### ISSUE THREAD

**Issue by SuperSandro2000** [healthchecks/healthchecks#305]
I would like to generate a badge from a specific check with that checks name for a project I maintain.

Sadly currently you can only get badges from projects or tags which both do not have the badge name customization I would like to have.

So my requests: Could you add badges per check? Maybe they need to be enabled on a by check case to save performance?
And/or can you add a customization option to change the text on all badges? I would like to have something like "Project synced with upstream" which is currently no possible.

**Comment by cuu508** [comment]
> And/or can you add a customization option to change the text on all badges? I would like to have something like "Project synced with upstream" which is currently no possible.

We could add support for overriding labels via query string. Let's say the SVG badge URL is:

    https://healthchecks.io/badge/(...)/1VABRI5G/worker.svg

We could support this:

    https://healthchecks.io/badge/(...)/1VABRI5G/worker.svg?label=Project synced with upstream

As for badges per individual check: if the number of checks is manageable, you could give each check an unique tag. And each unique tag would have its badge, controlled by a single check.

**Comment by cuu508** [comment]
Ah, if shields.io endpoint gets implemented, then shields.io could handle the label override:

    https://img.shields.io/endpoint?label=Project synced with upstream&url=<healthchecks-url-here>

**Comment by SuperSandro2000** [comment]
> As for badges per individual check: if the number of checks is manageable, you could give each check an unique tag. And each unique tag would have its badge, controlled by a single check.

This would totally work for me right now. Thanks!

Label override via query string is exactly what I had in mind.

**Comment by cuu508** [comment]
I've just added shields.io support which also lets you override badge labels. 

Example badge: 

![](https://img.shields.io/endpoint?url=https%3A%2F%2Fhealthchecks.io%2Fbadge%2Fc673dfd3-0ea6-4e72-9787-2a6aa4%2FXhaG0fag%2Fsandbox.shields)

    https://img.shields.io/endpoint?url=https%3A%2F%2Fhealthchecks.io%2Fbadge%2Fc673dfd3-0ea6-4e72-9787-2a6aa4%2FXhaG0fag%2Fsandbox.shields

Same badge, custom label:

![](https://img.shields.io/endpoint?url=https%3A%2F%2Fhealthchecks.io%2Fbadge%2Fc673dfd3-0ea6-4e72-9787-2a6aa4%2FXhaG0fag%2Fsandbox.shields&label=Project%20synced%20with%20upstream)

    https://img.shields.io/endpoint?url=https%3A%2F%2Fhealthchecks.io%2Fbadge%2Fc673dfd3-0ea6-4e72-9787-2a6aa4%2FXhaG0fag%2Fsandbox.shields&label=Project%20synced%20with%20upstream
