### ISSUE TITLE
Feature Request: Add Healthchecks version number on footer

### ISSUE THREAD

**Issue by Thlb** [healthchecks/healthchecks#306]
Hi,

At the moment, i don't think we can see the currently installed version of Healthchecks.

Can you add the version number on the footer (or in an "about" page) ?

Thanks

**Comment by immanuelfodor** [comment]
It might be desirable to have a config option to opt-in/out of displaying this info as it can open up an attack vector if a self-hosted Healthchecks is exposed to the world.

**Comment by Thlb** [comment]
Agreed, and/or maybe only display this info for logged in users.

**Comment by Thlb** [comment]
Hello,

Yeah, that's works too !

Thanks :)

**Comment by immanuelfodor** [comment]
How can one enter the admin page? The `/admin` redirects to `/admin/login/?next=/admin/` but there is the frontend login, which takes to the projects page. Should I do something in the settings py file?

**Comment by immanuelfodor** [comment]
Well, I needed to create a super user but the admin login still does't work with it, signs into an empty account. 

FYI, the super user email must not exist in the DB, otherwise there is a nice 500 error page after login, and you need to manually update the auth user table in sqlite, the CLI admin creator doesn't complain, learnt it the hard way 😃

**Comment by cuu508** [comment]
> FYI, the super user email must not exist in the DB, otherwise there is a nice 500 error page after login, and you need to manually update the auth user table in sqlite, the CLI admin creator doesn't complain, learnt it the hard way

Sorry about that! Email's uniqueness is not enforced, that's a known problem – #290 
Just looked at hooking into `createsuperuser` management command. It's possible but would be quite hacky. Perhaps a cleaner solution would be to rewrite it completely.

> Well, I needed to create a super user but the admin login still does't work with it, signs into an empty account.

First, log in the normal way with your superuser credentials (you'll end up in an empty account). Once logged in, go to `/admin/` and you should see the admin interface.

**Comment by immanuelfodor** [comment]
Thanks for the guidance! Now, I managed to login to the admin page and fix the uniqueness in SQLite as well (https://github.com/healthchecks/healthchecks/issues/290#issuecomment-570529077).
