### ISSUE TITLE
When `/fail` endpoint is called, include request body in email alert

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#308]
This would allow failing a check with an explicit message, and getting that message in email:

    curl -fsS -X POST -d "No space left on device" https://hc-ping.com/uuid/fail

**Comment by vdaynm** [comment]
Hello, this would be my first contribution but I have several years of experience in Python, Django and Linux Server Admin. Mind if I work on this issue?

**Comment by cuu508** [comment]
@vdaynm sure, sounds good!

I'd like to do a bigger revamp of the email message (#348) but we can do it a step at a time.

**Comment by vdaynm** [comment]
Can you point me to the method or class that is sending the notification email?

**Comment by cuu508** [comment]
> Can you point me to the method or class that is sending the notification email

Here: https://github.com/healthchecks/healthchecks/blob/master/hc/api/transports.py#L57

> should it be sent to all notification channels or only email?

Do you mean, should  the request body be included in all notification templates? – No, each notification type would need to be considered separately. For example there's no way the request body will fit in in a SMS message.

**Comment by dlecan** [comment]
I would like to implement the same feature, but for Slack notifications. Would you like to track this with another issue?

**Comment by lukastribus** [comment]
I'm looking for this feature as well (in email, telegram, pushover integrations).

Seeing the request body without logging into to the dashboard would be extremely convenient, for obvious reasons.

**Comment by cuu508** [comment]
I've updated the email template to include the last ping body:

![image](https://user-images.githubusercontent.com/661859/103155470-0e4e7500-47a9-11eb-91ad-9e1272b25b66.png)

@dlecan, @lukastribus:

The ping body can be 10KB – it may need to be truncated to, say, 1KB for IM notifications. Let's track each in a separate issue. I'm happy to review PRs.
