### ISSUE TITLE
Feature: add a pause button to the checks list

### ISSUE THREAD

**Issue by foozmeat** [healthchecks/healthchecks#312]
I have quite a few checks for hosts overseas and sometimes they lose connectivity for long periods. Pausing these hosts is tedious as it require jumping in and out of settings. If there was a pause button on the checks list it would be a big time saver.

**Comment by cuu508** [comment]
Thanks for the suggestion @foozmeat. I see your point about jumping in and out of settings being tedious. 

Currently brainstorming UI ideas, and have added a few mockups in issue #322. If you have any feedback on them, I'll be happy to hear it!
