### ISSUE TITLE
Feature Request: Upload/Attach a small log file

### ISSUE THREAD

**Issue by skycrash** [healthchecks/healthchecks#315]
can upload/attach a log file from my cron routine, inform if was error or something else

**Comment by cuu508** [comment]
This is already sort of possible: you can make HTTP POST requests to the ping URLs and include arbitrary content in the request body. 

Healthchecks stores first 10KB of the request body, so small JSON documents or logfile fragments would work.

Here's an example (not mine, sent in by an user):

    m=$(/usr/bin/certbot renew 2>&1); curl -fsS -X POST --data-raw "$(echo "$m" | tail -c 10000)" "https://hc-ping.com/UUID$([ $? -ne 0 ] && echo -n /fail)" >/dev/null

It runs certbot and saves output in the $m variable. It then makes a HTTP POST request with the output in request body. As a bonus, it adds `/fail` to the ping URL if the certbot command returned non-zero exit code.

This could be simplified (or extended...) depending on your needs.
