### ISSUE TITLE
Idempotence key for ping requests

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#319]
When curl (another HTTP client) retries failed requests we can end up with multiple logged pings:

https://twitter.com/epikhinm/status/1217147491986133002

Look into making ping requests idempotent.

**Comment by abandholm** [comment]
Maybe something simple like (assuming a shell like Bash):

`curl -fsS --retry 3 -H "HC-Id: $RANDOM" https://hc-ping.com/your-uuid-here`

Bash will add a random number, but curl will use the same value on all 3 calls -- server discards duplicates.

People who want idempotency include the id-header.

**Comment by cuu508** [comment]
If there is idempotence key, it could be also used to measure job execution times for concurrent / overlapping jobs.

* 00:00 Job A starts (idempotence key "A")
* 00:10 Job B starts (idempotence key "B")
* 00:20 Job A finishes (based on the idempotence key "A", we can calculate the run time – 20 minutes)
* 00:25 Job B finished (based on the idempotence key "B", we can calculate the run time – 15 minutes)
