### ISSUE TITLE
If Last Duration is under 1 second, show millisecond

### ISSUE THREAD

**Issue by BobCashStory** [healthchecks/healthchecks#321]
I do have ping where i want to mesure response time. some of them are under a second to run . it's show 0 sec, but with other service i used to see 400ms for exemple.
Can we have the same behavior ?
<img width="1354" alt="Screenshot 2020-01-17 at 10 50 49" src="https://user-images.githubusercontent.com/47117399/72602398-7f3da980-3917-11ea-9ef4-09015248910d.png">
<img width="1073" alt="Screenshot 2020-01-17 at 10 56 24" src="https://user-images.githubusercontent.com/47117399/72602739-08ed7700-3918-11ea-832e-32e64a529cc9.png">

Optional point:

- in Configuration ability to change the icon path, i straight build Hc into a docker and i don't want to change the code source .

**Comment by cuu508** [comment]
Thanks for the suggestion!

> Optional point

Filed a separate issue for this one: #322

**Comment by BobCashStory** [comment]
@cuu508 thanks i edited my point to remote it :)

**Comment by cuu508** [comment]
> in Configuration ability to change the icon path, i straight build Hc into a docker and i don't want to change the code source 

@BobCashStory just to be sure, you mean the site logo at the top left of most pages, correct? 

Should be fairly straightforward to add a LOGO_URL variable which you can then point to any external resource, or use a "data:..." URI

**Comment by BobCashStory** [comment]
@cuu508 yes this logo ! Sound perfect a LOGO_URL !

**Comment by cuu508** [comment]
> @cuu508 yes this logo ! Sound perfect a LOGO_URL !

Filed #323
