### ISSUE TITLE
Replace the gear icon with something more appropriate

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#322]
This one:

![image](https://user-images.githubusercontent.com/661859/72603136-207d2d80-3921-11ea-84b2-838dc7238bb5.png)

The gear icon typically means "Edit Settings", but in our case it's more a "More Details".

Look into using a different icon, or replace with a text label.

**Comment by SuperSandro2000** [comment]
Drop down carret?

**Comment by cuu508** [comment]
Also thinking about:

* A button with three horizontal dots. Maybe an additional "Pause" action on hover:

![image](https://user-images.githubusercontent.com/661859/72617923-b70e1680-3942-11ea-953a-83c7422f1ab2.png)

* A button with wrench icon and caret. Click on it, get a dropdown menu with 3 items: Details, Pause, Remove.

* A simple text link:

![image](https://user-images.githubusercontent.com/661859/72618095-0fddaf00-3943-11ea-8dc4-2ec2d743db14.png)

The part I'm struggling with is – going to the "Details" page is a very common action. It needs to be very easy. Ideally a single click on a large click target. Hiding it in a menu means two clicks. Using a button with an icon means small click target.

The entire row could also be a click target for the "Go to Details page" action, but that could clash with inline editing (clicking on name, on channel icons or on period & grace).

**Comment by cuu508** [comment]
Here's an experiment with the three dots button and a pause button. Default state:

![image](https://user-images.githubusercontent.com/661859/72622372-bb8afd00-394b-11ea-959a-751e8a0dd0a7.png)

Hovering over a row:

![image](https://user-images.githubusercontent.com/661859/72622412-d2315400-394b-11ea-8075-c98894744562.png)

Hovering over the button:

![image](https://user-images.githubusercontent.com/661859/72622450-e83f1480-394b-11ea-947e-012e61531823.png)
