### ISSUE TITLE
markdown missing in requirements.txt

### ISSUE THREAD

**Issue by brammeleman** [healthchecks/healthchecks#329]
I think `markdown` is missing in the requirements file.

**Comment by cuu508** [comment]
You need markdown installed if you edit docs and want to run `manage.py render_docs`. But you don't need it installed to run in production.

Similar with pygments and the `manage.py pygmentize` command. 

Perhaps we should catch an import error in the render_docs command and print user-friendly instructions.

**Comment by brammeleman** [comment]
Ah, my misunderstanding. Thanks!

**Comment by SuperSandro2000** [comment]
Also you could maybe add a ``requirements-dev.txt`` file to collect those extra pip packages.
