### ISSUE TITLE
Alerts should pause when jobs aren't supposed to run

### ISSUE THREAD

**Issue by screencom** [healthchecks/healthchecks#330]
Running self hosted, version v1.12.0

I have a job with the following schedule `*/5 6-23 ͏* ͏* ͏*` and a grace time of 15 minutes.

At 23:15 I receive an alert that the job is DOWN
At 06:00 I receive an alert that the job is UP

Is it possible to suspend alerts for jobs that shouldn't be running? Or do I need to change something in the configuration?

**Comment by cuu508** [comment]
How does the configuration in Healthchecks look currently? 
Are you using a "cron" check (not "simple")? Is the timezone set correctly?

**Comment by screencom** [comment]
Yes, I'm using only "cron" checks. The timezone for the check is set to the same timezone as the server (Europe/Amsterdam)

Can you point me to something that I could attach here that might shed more light on this?

**Comment by cuu508** [comment]
Could you post a screenshot of the received pings log, from around 23:00 where the sent notifications are visible? Edit out IP addresses and User-Agents, if they're sensitive. Set the display timezone to UTC:

![image](https://user-images.githubusercontent.com/661859/74430338-58668a80-4e65-11ea-8f38-9f7e34024375.png)

**Comment by screencom** [comment]
I will do that tomorrow morning.

**Comment by screencom** [comment]
![Screenshot 2020-02-14 at 09 10 09](https://user-images.githubusercontent.com/29376713/74518442-206a5080-4f14-11ea-8b7c-58d8ec41992a.png)

**Comment by cuu508** [comment]
`*/5 6-23 ͏* ͏* ͏*` would translate to "every 5th minutes, from 6 to 23 (inclusive).

There is a ping on 21:55 UTC (22:55 Amsterdam time), and no more pings until the morning. But Healthchecks is still expecting pings at 22:00, 22:05, 22:10, ..., 22:55 (Amsterdam time: 23:00, 23:05, 23:10, ...., 23:55).

It looks as if the actual cron schedule on the server is `*/5 6-22 ͏* ͏* ͏*`.

**Comment by screencom** [comment]
It would certainly seem that way. I have a feeling I know where I went astray.

These crons have been created from Laravel tasks (an external project that can convert tasks to crons) so I think I have been barking up the wrong tree. I will triple check it.

Thanks for now. I'll let you know if that was indeed the problem

**Comment by screencom** [comment]
Your hunch was absolutely correct. It was user error. I had entered the crons incorrectly.

Thank you for you assistance. Everything is working perfectly now!
