### ISSUE TITLE
can't query tags that contain certain characters

### ISSUE THREAD

**Issue by brammeleman** [healthchecks/healthchecks#333]
Hi,
I have some tags that contain equal signs in it. When using the API, I can't filter those particular checks. 
For example, to get the checks that match "a=b", the query url would look like:
```
https://hc.example.com/api/v1/checks/?tag=a%3Db
```
With the tag `a=b` urlencoded to `a%3Db` because the query `tag=a=b` would be nonsensical.
This does not return any matches. I tried to figure out why this does not work.. without any result so far...
I did test tags with other funny characters, like `%`, `&` and `$` in it (urlencoded) and that seems to work fine. A tag with `!` in it also fails to be queried.

Bests,

Bram

**Comment by cuu508** [comment]
> https://hc.example.com/api/v1/checks/?tag=a%3Db

This looks good and should work. How does the request look in server's access log? Maybe the encoding goes wrong on client side, and the server sees something else.

**Comment by brammeleman** [comment]
Excuse me, sorry for bothering you. There was an error in my testing code.
