### ISSUE TITLE
URL Verification without TLD

### ISSUE THREAD

**Issue by ivanmihov** [healthchecks/healthchecks#334]
Can we adjust the URL verification to allow URLs without the TLD?
My use case is in Docker, where the container is part of an internal network and is given access only to that network. I need to create a Webhook that does a post request to a URL: http://notify/messages
At the moment the UI shows an error "Enter a valid URL"  because the TLD is missing, however, the address is still valid.

**Comment by cuu508** [comment]
Not easily, would require changes in a number of places. And I definitely would not want to copy, modify and maintain [the monster regex](https://github.com/django/django/blob/master/django/core/validators.py#L82) that Django uses for URL validation.

This is the first time TLD-less webhook addresses have come up. Maybe you can get by with a workaround: edit the webhook address in Django admin > Api > Channels? There's no URL validation there.

**Comment by ivanmihov** [comment]
You are right, it might be too specific of a use case to go through all that. 
Your suggestion about editing the Django admin channel worked:) Thank you, I will close the issue now.
