### ISSUE TITLE
API return single check

### ISSUE THREAD

**Issue by jameskirsop** [healthchecks/healthchecks#337]
Similar to, but not quite the same as, #256, it would be great if the `hc-api-update` URL (aka `api/v1/checks/<uuid:code>`) could be adjusted to support returning the data for a single check.

The current situation of providing a list of all checks and their status is great. However, I'm writing a [datasource integration with Grafana](https://github.com/jameskirsop/grafana-healthchecksio-datasource), which will be significantly easier to do if the datasource can poll for a single check via a `GET` by uuid (after a user selects the check they wish to display in the panel).

**Comment by cuu508** [comment]
Thanks for the suggestion. Makes sense and should be relatively easy to support.

It will take me some time to get this done and deployed. In the meantime, you can use the `POST /api/v1/checks/<uuid:code>` call and send an empty JSON dictionary ("update the check but don't change any fields"). It's going to be less efficient, but should allow you to continue without waiting on me. 

And – great to see you working on a Grafana datasource – looking forward to try it out!

**Comment by jameskirsop** [comment]
@cuu508, I'm happy to fork and create a branch for these changes and do a PR for review.

I'll update this comment with a link to the fork/branch once I've made some meaningful changes.

**Comment by cuu508** [comment]
Sorry for the silence – I missed the edit!

Unless I'm missing something, it looks like `hc.api.views.update` would now be unused and can be removed.

It would be good to have a test case that exercises the `GET /api/v1/checks/<uuid:code>` route.

The API documentation is in the `templates/front/docs_api.html` file, and example requests/responses are in `templates/front/snippets/` directory. Each snippet has a .txt file and a generated .html file. The html versions are generated with `manage.py pygmentize`.

Please hold off updating documentation for a bit – I'll see if I can reformat the API documentation to Markdown. This should make updating it much easier.

**Comment by cuu508** [comment]
I've now converted the API reference to Markdown format. To update documentation:

* edit `templates/docs/api.md`
* run `manage.py render_docs` to generate the HTML version

**Comment by cuu508** [comment]
@jameskirsop what are your plans on this? I can take over if you've moved on to something else.

**Comment by jameskirsop** [comment]
Sorry @cuu508, got distracted on something else. I'm still keen to make this change (and have some other suggestions too). I'll try and do a PR today.

**Comment by cuu508** [comment]
Thanks for updating the PR, @jameskirsop !
I cleaned up a few bits and merged it. It's now been deployed to https://healthchecks.io
