### ISSUE TITLE
Configure integrations via API or config file

### ISSUE THREAD

**Issue by bertbesser** [healthchecks/healthchecks#339]
Hi,

your software seems to fulfill my needs quite well.

However, automated installation is hard, if not impossible, due to integrations not being configurable programatically (unlike checks, which can be configured via your API).

I would very much like to provide the app with an exhaustive config file upon first boot, so that it is fully configured when entering the web UI for the first time. Moreover, it would be very convenient if this file could be created by manually setting up desired projects/integrations/checks and then exporting it.

An alternative would be configuration by means of a script calling the API.

Did I miss some other way to achieve this?

Thanks!

**Comment by cuu508** [comment]
Hi @bbesser,

I agree it would be great to have API for setting up integrations. There's already an issue for that (#129). I don't have the bandwidth to work on this myself but am happy to review pull requests. 

Could you share more background about your use case? What integration types would you be using?

**Comment by cuu508** [comment]
Closing: I will not be working on this myself, and the reporter has not followed up.
