### ISSUE TITLE
integration editing is awkward

### ISSUE THREAD

**Issue by robx** [healthchecks/healthchecks#341]
You're probably aware of this, but I thought I'd summarize my experience anyway. I just went through setting up an integration with zulipchat (compare #202) via a custom webhook. That involved a bit of tweaking things, which turned out to be quite painful because

1. integrations don't start out with a name / distinguishable in the listing
2. integrations can't be edited

From my outside perspective, the best fix for this would be to allow editing integrations with a form similar to the "create integration" form, and to include the integration name there.

**Comment by cuu508** [comment]
Thanks for the feedback!

Allowing integrations to be edited definitely makes sense for webhook integrations. All is well when you know precisely what webhook parameters you want. But it's a PITA when you're experimenting and iterating. 

Also agree on editing the integration name in the same form. 

There's an issue on this already: #176, so I'll comment there and close this one.

**Comment by cuu508** [comment]
@robx just a heads up – the following is now implemented:

* you can now name a webhook integration right from the start, in the "Add Webhook" form
* you can now edit existing webhook integrations

**Comment by robx** [comment]
Sounds awesome, thank you! I'll be sure to test as soon as I need to set up another integration.
