### ISSUE TITLE
API @authorize decorator doesn't allow read-only for Single Check

### ISSUE THREAD

**Issue by jameskirsop** [healthchecks/healthchecks#346]
We need to rewrite the `@authorize` decorator to allow for a read-only API key to do a GET request on the `single` view.

Current thought would be to merge the write and read-only decorators and handle the request based on the `request.method` parameter.

Without this, you currently need to use a full-access key to read a single check.

**Comment by cuu508** [comment]
Good catch, forgot about the read-only keys!

Just committed a fix which splits the "single" view into separate "get_check", "update_check" and "delete_check" functions. This way we can use the appropriate authorization and validation decorators separately for each HTTP verb. 

There's a bit of repetition in doing get_object_or_404 three times but I think it's not too bad.
