### ISSUE TITLE
Cron syntax

### ISSUE THREAD

**Issue by Desmaster** [healthchecks/healthchecks#35]
It would be great if one could just insert the cron syntax. Got any ideas about that?

**Comment by cuu508** [comment]
In cron, you specify *when* you want your task to be run. healthchecks.io, as implemented now, monitors the gaps between runs. It doesn't care when the task runs. It only cares that it runs frequently enough. Adding cron syntax support would require pretty significant changes.

cron syntax is flexible and allows things like "every 15 minutes, but only on weekdays". healtchecks.io would not currently be able to effectively monitor a schedule like that. I'm not sure how common schedules like that are. Are you working with a more complex schedule like that, or are you looking for an alternative to the current sliders UI?

**Comment by cuu508** [comment]
One added complication when dealing with points in time is timezone differences, DST changes, and inaccurate clocks on servers. Much easier with time durations.

**Comment by Desmaster** [comment]
I see the complicaties, but what bothers me right now, is the following:

I have many cron jobs running from for example 7-23, so I het tons of emails because they didnt run at night. Not every cron is meant to be a fixed schedule, right?

**Comment by cuu508** [comment]
Thanks, I see, will take this into consideration. 

As a workaround, you could move the 7-23 constraint to your code. For example, configure a hourly cron job that runs 00-24, but inside your script, change

    do_something()
    ping_healthchecks()

to
    if (hour >= 7 and hour <= 23) {
        do_something()
    }
    ping_healthchecks()

Not ideal, but would get around the issue for now...

**Comment by cuu508** [comment]
I've now added support for cron syntax and rolled the change out on healthchecks.io. 
@Desmaster if you're still interested in this, you are welcome to test it out!

**Comment by Desmaster** [comment]
@cuu508 That's great, I'll check it out and let you know!
