### ISSUE TITLE
TimeZone

### ISSUE THREAD

**Issue by Rustymage** [healthchecks/healthchecks#350]
Morning,

Maybe I'm being slightly dense but my timezone is now an hour out and it's causing my notifications to continually trigger.

I'm in the London BST timezone using docker to run the Healthchecks container.

How can I update my timezone or setup my system to not trigger the alerts when the timezones from container to running check do not line up?

Thanks in advance :)

**Comment by cuu508** [comment]
Hi @Rustymage, make sure the timezone for individual checks match the timezone on your monitored systems. 

You can see and change the timezone in check details page:

![image](https://user-images.githubusercontent.com/661859/78110157-30c28600-7403-11ea-9c89-34dfa11927b7.png)

Also related: https://healthchecks.io/faq/#timezones

**Comment by Rustymage** [comment]
As an example:

- My **server** cron is setup to backup and ping Healthchecks at `0120` (GMT BST), it does this successfully

- My _Healthchecks_ cron job is awaiting a ping at `0120` (Europe/London) with a grace time of 60 minutes, the timestamp on the ping from the **server** is `2020-04-01T01:20:00.491177+00:00`

- The Healthchecks container sends out an alert at `0120`, clearly just before the **server** pings it

The date on my **server** is: `Wed  1 Apr 08:48:07 BST 2020`
The date on the _Healthchecks_ container is: `Wed Apr  1 07:48:29 UTC 2020`

Is it recommended to restart the container and server?

**Comment by cuu508** [comment]
What is the configured timezone for the specific check – what do you see in the "Check Details" page?

Could you post a screenshot of the check details page, with the "Schedule" and "Log" sections visible, and any sensitive bits edited out?

**Comment by Rustymage** [comment]
<img width="1367" alt="Screenshot 2020-04-01 at 16 57 05" src="https://user-images.githubusercontent.com/19926955/78159231-338c9d80-743a-11ea-928a-631e01fc05a4.png">
<img width="1354" alt="Screenshot 2020-04-01 at 16 58 24" src="https://user-images.githubusercontent.com/19926955/78159243-36878e00-743a-11ea-95fe-119fc6ad6a90.png">

**Comment by cuu508** [comment]
Thanks for posting the screenshots!

To me it looks like the pings from last few days are sent an hour late. The ping is expected at 3:00 BST, which is 2:00 UTC. Instead in the log we see it arrives at 3:00 UTC.

What are you using to schedule the daily runs? If it's cron, have you by any chance changed server's timezone recently? cron daemon may need to be restarted to pick up the timezone change.

**Comment by Rustymage** [comment]
The timezone has auto changed when I entered BST. I'll restart and check back. 

Cheers

**Comment by cuu508** [comment]
If the server has systemd, what's the output of `timedatectl status` and what is in your `/etc/timezone`? Are you using cron as the scheduler?

**Comment by Rustymage** [comment]
So I found the issue.  It was a container with the incorrect time. Thanks for the assistance. I learnt to triple check containers :)

**Comment by cuu508** [comment]
Thanks, good to hear you tracked down the issue!
