### ISSUE TITLE
v1.13.0 Cannot see new features

### ISSUE THREAD

**Issue by BobCashStory** [healthchecks/healthchecks#351]
Replace the gear icon with three horizontal dots icon (#322) for exemple i see the past icon not new one

**Comment by cuu508** [comment]
When you log in `/admin/`, what version do you see in the top navigation? 

Here:

![image](https://user-images.githubusercontent.com/661859/78116428-f0680580-740c-11ea-8a79-7a01f92b1289.png)

**Comment by BobCashStory** [comment]
I cannot access to admin  if i go there : https://health.cashstory.com/admin/ it redirect me on home after login .

**Comment by cuu508** [comment]
Are you logging in with a superuser account (created with `manage.py createsuperuser`)? 

Had a quick look at https://health.cashstory.com/, it's hard to tell precisely but it appears to be running an older version, older than 1.12 at least.

**Comment by BobCashStory** [comment]
@cuu508 i'm sure i'm on the wrong one but we have an issue with the archive downloaded by https://github.com/galexrt/docker-healthchecks
i created an issue : https://github.com/galexrt/docker-healthchecks/issues/28
I created a super user and i get this page when loggin now ...
<img width="772" alt="Screenshot 2020-04-29 at 18 47 36" src="https://user-images.githubusercontent.com/47117399/80623047-f112ac80-8a49-11ea-95fa-c804352f6bba.png">

**Comment by galexrt** [comment]
To chime in here, running my Docker image which checks out the `v1.14.0` git tag and then install the dependencies.
The admin page doesn't show a version:
![image](https://user-images.githubusercontent.com/3718398/80702759-dab82f80-8ae1-11ea-82c3-e13c56a0cf4b.png)

**Comment by cuu508** [comment]
The version is determined in settings.py, by parsing the first few lines of CHANGELOG:

https://github.com/healthchecks/healthchecks/blob/master/hc/settings.py#L39

But looks like CHANGELOG gets stripped out in your image:

https://github.com/galexrt/docker-healthchecks/blob/master/Dockerfile#L33

**Comment by galexrt** [comment]
@cuu508 I see. Yeah I added that because at one point the installation failed due to an invalid UTF8 or so character in the file.

![image](https://user-images.githubusercontent.com/3718398/80705685-1ef9fe80-8ae7-11ea-8adb-442c86e90570.png)

**Comment by BobCashStory** [comment]
@galexrt @cuu508 okay i found my issue for upgrading ! I didn't see env vars changed in the docker machine conf so i was still with old names, and that prevent me to upgrade apparently, and the admin page works too now
