### ISSUE TITLE
Does the schedule get automatically determined by pings intervals if not set?

### ISSUE THREAD

**Issue by caleb15** [healthchecks/healthchecks#352]
Whenever I create a healthcheck I didn't bother setting the schedule at all. This seems to have worked out - when I looked over our healthchecks they had the schedules I expected. I assumed healthchecks.io automatically figured out the schedule based on the time between pings. For example, there's a healthcheck I think I created and it currently has a 30 minute period - I don't ever remember setting that. I assume healthchecks.io did it.

While investigating https://github.com/healthchecks/healthchecks/issues/343 I saw that there were options to set the schedule but the automatic schedules were not mentioned at all. I read all the documentation and didn't see automatic schedules mentioned anywhere. I checked the website and same thing. I talked to my boss and he sets the schedule manually. 

Now I'm confused - does healthchecks.io automatically figure out the period or grace time or anything schedule related?

I'm 99% certain I've never set the schedule for a healthcheck so I'm baffled as to how we have everything set correctly if it needs to be done manually. But I suppose there's a slight chance that I'm misremembering or that some other employee is setting the schedules for me lol.

**Comment by cuu508** [comment]
Hi @caleb15, 

Healthchecks does not set schedules automatically – each check starts with the 1 day period, 1 hour grace time by default and it is up to the user to adjust the schedule.

However, if you clone ("Create a copy") a check, the schedule will be copied over. And if you duplicate checks via API [as suggested here](https://github.com/healthchecks/healthchecks/issues/266#issuecomment-511111866) then the schedule also gets copied over.

Or it could have been your colleague adjusting the schedules. 

BTW, there is a feature request to [suggest a grace time](https://github.com/healthchecks/healthchecks/issues/218) based on the observed data. But this hasn't been implemented yet, and would be a suggestion only (not applied automatically).

**Comment by caleb15** [comment]
Damn, that's really weird. I'll have to go through the healthchecks again to make sure the schedules are set properly :| 

Thanks for the info!
