### ISSUE TITLE
Custom JS / CSS

### ISSUE THREAD

**Issue by alex-phillips** [healthchecks/healthchecks#353]
Is there a way to add in custom JS or CSS to a self-hosted instance? I would like to add in a link inline for each watch item that links off to a resource related to each job. I could do this with JS if there was a way to specify some custom code.

I can add this to the description, but having it inline would be great as an icon.

**Comment by cuu508** [comment]
There isn't an easy way currently.

You can fork the repository, and add light tweaks to the templates and JS files. If you're comfortable patching the page with JS then perhaps this is an option.

Can you describe a little more what you have in mind? Are you thinking of a third icon next to these two that links out to an external resource? 

![image](https://user-images.githubusercontent.com/661859/78558099-b5a20b00-781a-11ea-9c97-641ff04c269b.png)

Would the link be derived from check's name or tags?

**Comment by alex-phillips** [comment]
Yes. This is a bit of a unique case, but I have as script that runs and sends healthcheck ping times to influx DB / Grafana for charting jobs and their health over time. It would be nice if I could expose a link to each job's chart without having to view the details screen. These links are derived from the job's name or ID. The description exposes the URL as a clickable link, but I can only view this by clicking through to the details page.

Or if when you click on the job to get the edit window, if the description was rendered out instead of editable initially (click an edit button to turn this into a textarea?) then that would expose the description as well.

**Comment by cuu508** [comment]
I think forking the repo and editing the template (`templates/front/my_checks_desktop.html`) is the way to go here.
