### ISSUE TITLE
2FA support: TOTP

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#354]
Add support for 2FA using TOTP (Google Authenticator, Authy).

**Comment by apiening** [comment]
You can integrate **authelia** (https://github.com/authelia/authelia) as a middleware. No change on the code base required. This plays well together with **Traefik** (https://docs.traefik.io/) in a **docker** stack.
However, you need to be careful to filter out the urls that need to be public accessible, like `/ping/`.
