### ISSUE TITLE
2FA support: U2F

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#355]
Add support for 2FA using U2F security keys.

**Comment by apiening** [comment]
Please have a look at https://github.com/healthchecks/healthchecks/issues/354#issuecomment-625973458 which addresses 2FA.

**Comment by cuu508** [comment]
I've implemented and deployed an initial version of WebAuthn support.
Users can add security keys in the Account Settings page:

![image](https://user-images.githubusercontent.com/661859/99685839-ae6afd00-2a8b-11eb-9bfe-a6da40353e34.png)

If an account has any registered security key, then Healthchecks uses it as a second factor during login:

![image](https://user-images.githubusercontent.com/661859/99686043-dc504180-2a8b-11eb-9f6f-a8f7f68b3641.png)

These changes are deployed and ready for testing and use on https://Healthchecks.io. 

Any and all feedback welcome!
