### ISSUE TITLE
Pause a check should ask for confirmation

### ISSUE THREAD

**Issue by smknstd** [healthchecks/healthchecks#356]
On a project page, pausing a check could have been made by misclicking and it is impossible to undo. UI should ask for confirmation with modal or something.

![Screenshot from 2020-04-07 10-23-23](https://user-images.githubusercontent.com/2412608/78646955-24827100-78ba-11ea-817a-a923b31bfefa.png)

**Comment by cuu508** [comment]
Thanks for the suggestion! Here's what I've implemented – clicking once will show a "Pause this check? Click again to confirm." tooltip:

![image](https://user-images.githubusercontent.com/661859/79761835-a3e85980-832a-11ea-92fe-2cdf9bab54ef.png)

Clicking a second time will pause the check.

**Comment by smknstd** [comment]
Great !
