### ISSUE TITLE
Any way to get 'last successful ping'?

### ISSUE THREAD

**Issue by alex-phillips** [healthchecks/healthchecks#357]
I'm using all pings available (not sure if that provides any benefit or not): start, success, and fail.

But using the API, a success ping and a fail ping register the same for `last_ping`. There's no way to determine when the last "successful" ping was. Any way to include this in the response?

I'm pumping data into InfluxDB to keep track of how long jobs go until they are completed successfully. Should I just not be using the start / fail pings?

**Comment by alex-phillips** [comment]
Just curious if this was given any thought. I can write a cron script that runs every minute and checks for a successful ping, but if we could query this directly from HC, that would be ideal.

**Comment by cuu508** [comment]
> I'm pumping data into InfluxDB to keep track of how long jobs go until they are completed successfully. 

There's a potentially related feature request: https://github.com/healthchecks/healthchecks/issues/371

If you have a process that periodically fetches data from healthchecks and pumps it into another system, perhaps having access to last n events would work too?
