### ISSUE TITLE
Expose job run times history via API

### ISSUE THREAD

**Issue by mountaindude** [healthchecks/healthchecks#371]
Similar to #349 , but not quite the same thing I believe.

I am particularly interested in run times of jobs, and would like to access this info via the API.
Basically, for a specific (or all) checks I'd like to retrieve start/end times in a JSON. And maybe the duration too, for convenience.

**Comment by cuu508** [comment]
We keep a log of received pings, and show them in web UI:

![image](https://user-images.githubusercontent.com/661859/84148255-63be7100-aa67-11ea-9db1-cf5fc36d66db.png)

Would exposing the same information via API suffice? Let's say, if there was 

    GET https://server/api/v1/checks/<uuid>/log/

endpoint, which would return (very approximately) this JSON:

	[
	    {
		"type": "success",
		"date": "2020-05-12T12:31:01.881509+00:00",
		"n": 7282404,
		"duration": 5.09289,
		"scheme": "http",
		"remote_addr": "127.0.0.1",
		"ua": "curl/7.68.0"
	    },
	    {
		"type": "start",
		"date": "2020-05-12T12:31:01.881509+00:00",
		"n": 7282403,
		"duration": null,
		"scheme": "http",
		"remote_addr": "127.0.0.1",
		"ua": "curl/7.68.0"
	    },
	    {
		"type": "success",
		"date": "2020-05-12T12:31:01.881509+00:00",
		"n": 7282402,
		"duration": null,
		"scheme": "http",
		"remote_addr": "127.0.0.1",
		"ua": "curl/7.68.0"
	    },
	    (...)
	]

**Comment by mountaindude** [comment]
Yeah that would be great!

If the run time is readily available via the API that would be even better,
but that's icing on the cake.

**Comment by cuu508** [comment]
This is now implemented and deployed on https://healthchecks.io

**Comment by mountaindude** [comment]
Cool!

Is the API endpoint the one you mentioned before, i.e.
GET https://server/api/v1/checks/<uuid>/log/ ?

**Comment by cuu508** [comment]
Sorry, docs:  https://healthchecks.io/docs/api/#list-pings

**Comment by cuu508** [comment]
Ah, sorry, forgot to mention – the endpoint is

    GET https://healthchecks.io/api/v1/checks/<uuid>/pings/

And it is documented here: https://healthchecks.io/docs/api/#list-pings
