### ISSUE TITLE
Add Telegram integration

### ISSUE THREAD

**Issue by jsorondo** [healthchecks/healthchecks#373]
Would it be possible to add telegram integration?

**Comment by SuperSandro2000** [comment]
healthchecks can send notifications to telegram.

**Comment by cuu508** [comment]
Yes, a Telegram integration already exists: https://healthchecks.io/integrations/telegram/

**Comment by flofeld** [comment]
But is it usable in the selfhosted version? If not, why not?

**Comment by SuperSandro2000** [comment]
I am using it for over 6 months and as long as you have network connectivity it works great.
