### ISSUE TITLE
[feature request] ability to specify paused ping handling through API

### ISSUE THREAD

**Issue by caleb15** [healthchecks/healthchecks#376]
Thanks for implementing https://github.com/healthchecks/healthchecks/issues/369!

Would it be possible to have that feature be able to be specified through the API when creating a check? That way I can add it to the healthcheck manager script to solve the problem described in https://github.com/healthchecks/healthchecks/issues/343.

On a unrelated note, we are now using the [healthcheck managing script](https://gist.github.com/caleb15/1a817ef5e58e8a8caf65190cff33806e) in production and it's working well so far. I just have a small bug I need to look into. My boss said I can open-source the script, I'll let you know when it's ready.

**Comment by caleb15** [comment]
I tested it and it works so far, thanks! :)

**Comment by caleb15** [comment]
I've modified the script to specify manual_resume: true and it's been working well :) 

https://gist.github.com/caleb15/1a817ef5e58e8a8caf65190cff33806e

I'm planning on announcing the script in our [engineering blog](https://dev.to/15five), I can send you a link to the article draft before I publish it in case you're curious.

**Comment by cuu508** [comment]
Sure, I'd love to see it! My email is in my Github profile.

It's interesting to see the "Update check" API call being used more as a "fetch ping URL by check's name". If this becomes a frequently used pattern, I may look into optimizing the "update check" API call a bit: when updating a check, if none of the fields change, skip a write to the database.

**Comment by caleb15** [comment]
Another way of having less API calls is if you added a parameter to let you pass in the channels by name rather than by id (it would assume channel names are unique) - that way I could skip the extra API call to get the channel id from the name  :)
