### ISSUE TITLE
"Apprise is disabled and/or not installed" depends on caller

### ISSUE THREAD

**Issue by CosmicToast** [healthchecks/healthchecks#378]
On one of my servers, when an apprise integration actually runs, it fails with "Apprise is disabled and/or not installed".
However, apprise is enabled, present in the integrations list, and pressing the "Test" button on the integration successfully sends the notification via apprise.
The apprise(1) executable is present, and `import apprise` by hand works ok.
I looked through the code, but that doesn't appear to help.
`DEBUG = True` does not provide any additional insights.
How would I go about debugging this further?

**Comment by cuu508** [comment]
How are you running the `sendalerts` command? 

My hunch would be that the `sendalerts` command doesn't have the same environment variables, or is not using the same virtualenv as the web server.

**Comment by CosmicToast** [comment]
Aha! That wasn't quite it, but I have it solved now.
I was running sendalerts as a systemd service, but while tinkering around I didn't reload it (only the main deployment) when making changes.
All it took was a restart of the sendalerts service to get everything working as expected, thank you for the hint!
Hopefully this issue helps anyone else that has any similar problems.
