### ISSUE TITLE
Add a curl example in PHP example section

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#384]
Suggested here: https://twitter.com/smknstd/status/1272818956076810247

![image](https://user-images.githubusercontent.com/661859/84868470-69c6da00-b085-11ea-9b3e-62eeeeac5dfc.png)

Aside from the code sample, it will need some accompanying information–

- is curl support typically built in with PHP, or does it need to be installed / enabled separately?
- in the "20 retries, 5 second timeouts" example, what is the maximum amount of time it can use up?
- is there a risk of curl code throwing exceptions? Should the snippet perhaps be wrapped in try..catch?

I'm very out of touch of today's PHP, so would appreciate any help.

**Comment by SuperSandro2000** [comment]
> is curl support typically built in with PHP, or does it need to be installed / enabled separately?

curl is a very common used php module but not installed when you install php on Debian.

> in the "20 retries, 5 second timeouts" example, what is the maximum amount of time it can use up?

my uneducated guess would around about a minute.

> is there a risk of curl code throwing exceptions? Should the snippet perhaps be wrapped in try..catch?

Nope but it could fail to connect in the same ways curl could which is not checked by this code.

https://stackoverflow.com/a/11297495/4446318

**Comment by smknstd** [comment]
There is a php-curl module (https://www.php.net/manual/en/book.curl.php) but my example use a complete different library: https://github.com/php-curl-class/php-curl-class that looked convenient to me (install through composer + retry option).

> is there a risk of curl code throwing exceptions?
no the library chose a different pattern https://github.com/php-curl-class/php-curl-class/issues/403

What I was trying to say by "updating the doc", was not something specific to php but maybe a section on those options (timeout + retry) in general. Then each langage specific page could give insight on how to do it. It could be great to mention multiple solutions, for php I'd keep mentionning "file_get_contents" but adding "curl" + options

**Comment by smknstd** [comment]
If you need snippet :

```
use Curl\Curl;

$curl = new Curl();
$curl->setRetry(20);
$curl->setTimeout(5);
$curl->get('https://hc-ping.com/your-uuid-here');     
```

**Comment by cuu508** [comment]
> What I was trying to say by "updating the doc", was not something specific to php but maybe a section on those options (timeout + retry) in general. Then each langage specific page could give insight on how to do it.

That's a good idea! I've started work on the general page. Current version live here: https://healthchecks.io/docs/reliability_tips/

I'm confident I can also update Python examples, but for other languages help is very welcome.

**Comment by smknstd** [comment]
the new page is great. Tried to update the php example here https://github.com/healthchecks/healthchecks/pull/395, hope it will help ...

**Comment by cuu508** [comment]
@smknstd thanks for the PR, looks good!

I noticed just now that PHP samples have no syntax highlighting. Related issue: https://github.com/Python-Markdown/markdown/issues/334 I will keep an eye on python-markdown releases.
