### ISSUE TITLE
Hour ranges in cron expressions are ignored

### ISSUE THREAD

**Issue by gpaddis** [healthchecks/healthchecks#385]
I have configured a heartbeat cronjob with the following cron expression: `*/5 9-23 * * *`, i.e. the cron runs daily from 9:00 to 23:55 (last execution). I have set the same expression in the healthchecks configuration with a 5 min grace period, however I keep receiving downtime and uptime notifications at 00:05 and 9:00 respectively.

Is the tool expecting to receive a heartbeat even after 23:55 (and thus ignoring the hour range 9-23) or is there possibly an error in my cron configuration?

**Comment by cuu508** [comment]
This is often caused by a timezone mismatch (the server has has one timezone, Healthchecks is configured to use a different one). 

Also, if you've recently changed timezone on your server – if the cron daemon was not restarted afterwards it might still be using the old timezone.

**Comment by gpaddis** [comment]
Hi @cuu508, you are absolutely right. I had not payed attention to the timezone mismatch. I tested it again after the timezone change and it works as expected. Thank you! :)
