### ISSUE TITLE
How to extend the limit of log

### ISSUE THREAD

**Issue by aleqcz** [healthchecks/healthchecks#388]
Hi,
can anybody help me out how to change the limit of 100 log entries on self-hosted instance of Healthchecks? Can't find it anywhere...

Thank you, great work,
Aleq

**Comment by cuu508** [comment]
If you need it changed for a single user or a few users, the easiest is to edit user's Profile in the admin UI. Each profile has a `ping_log_limit` which determines how many pings are displayed in web UI. The database may in fact have more pings stored already if you haven't been not running the `manage.py prunepings` command.
