### ISSUE TITLE
integration stay red until next message is send even if test succeeds 

### ISSUE THREAD

**Issue by SuperSandro2000** [healthchecks/healthchecks#391]
I am self hosting my healthchecks and after a connectivity issue a few of my integrations are red. They didn't turn back green when I tested them to see if they are working. I think this should be added cause they should not stay red until the next real alarm is send.

**Comment by cuu508** [comment]
Thanks for the suggestion, makes sense.

I changed how the "Test!" button works:

*  sending test notification now creates a Notification object, same as for normal notifications. Consequently, sending a test notification now updates the "Status" and "Last Notification" columns in the Integrations page:

![image](https://user-images.githubusercontent.com/661859/86237738-ff458c00-bba4-11ea-8a2e-f97c1380285a.png)

* sending a test notification now updates (sets or clears) the Channel.last_error field. This is what determines if we show the red exclamation sign in top nav or not.

**Comment by SuperSandro2000** [comment]
Thanks!

Does this also mean both notification are send from the same process?

**Comment by cuu508** [comment]
No, normal notifications are sent by the `manage.py sendalerts` process. Test notifications are sent by the web server process while handling the HTTP request.

**Comment by SuperSandro2000** [comment]
Good to clarify that. I noticed this error initially while debugging this.
