### ISSUE TITLE
Email subject filter for Failure state

### ISSUE THREAD

**Issue by revilo951** [healthchecks/healthchecks#396]
Is there any way to specify a subject word to trigger a notification?

At the moment, I'm receiving emails from some software with 3 possible outcomes: Success, Warning, and Failed.

If the task fails, I still get the email, therefore healthchecks thinks the task succeeded.

It'd be nice if we could specify that an email with the words "Warning" or "Failed" (for example) meant that the task failed, and a notification needs to be sent (or did I miss something, and this is possible already somehow?).

**Comment by revilo951** [comment]
Edit: in this case, there isn't a specific timing for the emails, so the "ignore" filter can't really help with this.

**Comment by cuu508** [comment]
Currently we cannot signal failure to Healthchecks via an email, but I'm open to implementing it.

I want to run an UI mockup past you and ask a few questions to see if it's any good:

![image](https://user-images.githubusercontent.com/661859/87163921-b8f0db00-c2d0-11ea-9f00-4955d5548eb0.png)

* Looking at this UI, do you think it would your solve your use case?
* What do you expect to happen if both keyword text boxes are empty?
* What do you expect to happen if only the "Success Keyword" is filled?
* What do you expect to happen if only the "Failure Keyword" is filled?

> In this case, there isn't a specific timing for the emails, so the "ignore" filter can't really help with this.

Are the emails coming in at random intervals, and you want any "success" email to flip a check to green, and any "failure" email to flip it to red?

**Comment by revilo951** [comment]
- Looking at this UI, do you think it would solve your use case?
    - Pretty much, I think the option to have multiple words, maybe comma-separated would be good, eg if I want to be notified/trigger red for both "Warning" and "Failed" keywords
- What do you expect to happen if both keyword text boxes are empty?
    - Behave the same as the current configuration, expect emails within the specified timeframe.
- What do you expect to happen if only the "Success Keyword" is filled?
    - Perhaps any email received that _doesn't_ have a success word would trigger failed/missed? Otherwise behave the same as currently, like the filter system.
- What do you expect to happen if only the "Failure Keyword" is filled?
    - That is a tricky one - maybe make it so that a "Success keyword" must also be specified? Otherwise, perhaps the system can re-notify whenever a new email with a failure keyword is received.
- Are the emails coming in at random intervals, and you want any "success" email to flip a check to green, and any "failure" email to flip it to red?
    - Yes, exactly.

**Comment by revilo951** [comment]
Another scenario that has come up, is a piece of software that handles multiple backups that need monitoring (software runs from a single piece of equipment) doesn't have the ability to send to a unique email address per job, however, I can put the unique identifier in the subject. A way to handle this would be nice, not sure how hard that would be though. I'm currently running the emails through a postfix smtp relay, and filtering/running rules to forward the emails to a different address, per the ID in the subject.

**Comment by cuu508** [comment]
Thanks for the feedback @revilo951, that's very useful. And looks like the different options (and their combinations) are not as clear as they should be.

Here's a new attempt:

![image](https://user-images.githubusercontent.com/661859/87787520-71c09800-c844-11ea-8b93-79090831fd58.png)

> Another scenario that has come up, is a piece of software that handles multiple backups that need monitoring (software runs from a single piece of equipment) doesn't have the ability to send to a unique email address per job, however, I can put the unique identifier in the subject.

**Comment by revilo951** [comment]
@cuu508 That looks excellent! Only question I have is - do these Keyword fields have any provision for more than one keyword, eg comma-separated keywords?

**Comment by cuu508** [comment]
@revilo951 I see the value of comma-separated keywords. They would add a bit of complexity but are doable. 

I think I'll start with implementing the above single-keyword version and once that's working, look at adding support for comma-separated keywords.

**Comment by revilo951** [comment]
Awesome, thanks for that.

**Comment by cuu508** [comment]
FYI – the initial, single-keyword version is deployed on https://healthchecks.io and is ready for testing.

**Comment by cuu508** [comment]
The multiple, comma-separated keywords are now implemented and deployed as well:

![image](https://user-images.githubusercontent.com/661859/88299487-16dae500-cd0b-11ea-81d0-00f9fcfb23f6.png)

**Comment by revilo951** [comment]
I've tested the single keyword version yesterday, it's working well.

Many thanks for this awesome change, and very useful software. :)
