### ISSUE TITLE
Problem Running ./manage.py settelegramwebhook

### ISSUE THREAD

**Issue by jimmybrancaccio** [healthchecks/healthchecks#400]
Greetings,

I was attempting to run `./manage.py settelegramwebhook` the other day but got the following result returned:

```
Running manage.py ...
/healthchecks/hc/settings.py:226: UserWarning: local_settings.py not found, using defaults
  warnings.warn("local_settings.py not found, using defaults")
Fail: status=404, b'{"ok":false,"error_code":404,"description":"Not Found"}'
```

However, it appears I can run the following without issue which allows the webhook to be created:

```
curl -F "url=https://<YOURDOMAIN.EXAMPLE>//integrations/telegram/bot/" https://api.telegram.org/bot<YOURTOKEN>/setWebhook
```

So it seems to me there might be an issue in the - `hc/api/management/commands/settelegramwebhook.py` file. I'm no Python person (but I can report issues!!), but that would be where I would start looking for resolving this.

**Comment by cuu508** [comment]
I looked at galexrt/docker-healthchecks instructions and ran the following:


```
cepe@oreo:/tmp$ docker run \
>     -d \
>     --name=healthchecks \
>     -p 80:8000 \
>     -e 'DB_NAME=/data/hc.sqlite' \
>     -e 'SECRET_KEY=...redacted...' \
>     -e 'PING_EMAIL_DOMAIN=example.com' \
>     -e 'SITE_ROOT=https://example.com' \
>     -e 'EMAIL_HOST=smtp.example.com' \
>     -e 'EMAIL_PORT=25' \
>     -e 'EMAIL_USE_TLS=True' \
>     -e 'EMAIL_HOST_USER=user@example.com' \
>     -e 'EMAIL_HOST_PASSWORD=YOUR_PASSWORD' \
>     -e 'ALLOWED_HOSTS=localhost,*' \
>     -e 'TELEGRAM_TOKEN=...redacted...' \
>     galexrt/healthchecks:latest
Unable to find image 'galexrt/healthchecks:latest' locally
latest: Pulling from galexrt/healthchecks
e9afc4f90ab0: Pull complete 
72a9df45630e: Pull complete 
e89445857363: Pull complete 
56cb6510d61e: Pull complete 
a31d6b5080bc: Pull complete 
c5396530805f: Pull complete 
Digest: sha256:fb2e9c7495242c5aae0f29b59c54ee0baa8e4155908d205cb8bb32f363e99a58
Status: Downloaded newer image for galexrt/healthchecks:latest
61362ea95c0535c2f021c70565f14266ba141dda52e4d1800bd48b4bc31a2ce7

cepe@oreo:/tmp$ docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                             PORTS                            NAMES
61362ea95c05        galexrt/healthchecks:latest   "/entrypoint.sh app:…"   14 seconds ago      Up 13 seconds (health: starting)   2525/tcp, 0.0.0.0:80->8000/tcp   healthchecks

cepe@oreo:/tmp$ docker exec -it healthchecks /entrypoint.sh app:managepy settelegramwebhook    
Running manage.py ...
/healthchecks/hc/settings.py:226: UserWarning: local_settings.py not found, using defaults
  warnings.warn("local_settings.py not found, using defaults")
Done, Telegram's webhook set to: https://example.com/integrations/telegram/bot/

```

The `settelegramwebhook` command makes a HTTP request to Telegram API and is getting 404 back. A couple ideas why this might be happening:

* The TELEGRAM_TOKEN value is wrong. For example, if I set `TELEGRAM_TOKEN=/foo`, I get the same error
* when the docker container makes the HTTP call, it hits a proxy, a firewall or a captive portal instead of Telegram API.

**Comment by jimmybrancaccio** [comment]
I think you're definitely right there @cuu508. I had double double quotes surrounding my token. I could have sworn it was something from the `galexrt/healthchecks` container that required those double double quotes. Once I removed those, it worked perfectly fine. I will close this out. Sorry about that!

**Comment by SAOPP** [comment]
Guys, someone had trying to run this hook from linuxserver image? I has asked into linuxserver repo, but didn't get answer.

I created bot, add token and his name trought variables, but when I try to add integration from HC web ui, open my bot and send /start - nothing is happens, HC is not send back integration link.

Or maybe someone can explaine me how I can add telegram bot to HC? Thanks in advance.

**Comment by SAOPP** [comment]
When I run it from my container I got env issue:

```
root@healthchecks:/app/healthchecks# ./manage.py settelegramwebhook
env: ‘python’: No such file or directory
```

**Comment by cuu508** [comment]
Try `python3 ./manage.py settelegramwebhook`

**Comment by SAOPP** [comment]
Thanks homie, it's works, damn, I was stupid 'bout python environments. It didn't occur to me to try something like that. :+1:
