### ISSUE TITLE
Telegram Not Sending Message When Using /start

### ISSUE THREAD

**Issue by jimmybrancaccio** [healthchecks/healthchecks#401]
Hello!

This may be related to #400. I've setup the bot, however when using the `/start` the bot doesn't send anything back. I setup [a request bin](https://requests.linuxbox.ninja/wkxkc1y) to see if Telegram was actually sending anything and it definitely is. It seems like Healthchecks may not be handling it properly anymore or ignoring it, I am not 100% sure. Nonetheless I felt it was worth creating a GitHub issue on. 😄 Don't hesitate to let me know if there's anything else I can provide to further troubleshoot!

**Comment by cuu508** [comment]
@jimmybrancaccio after you fixed TELEGRAM_TOKEN in #400, did this start to work too?

**Comment by jimmybrancaccio** [comment]
@cuu508 Yes it did! We can consider this one resolved!
