### ISSUE TITLE
Ability to change frequency of "monthly" report email

### ISSUE THREAD

**Issue by gunr2171** [healthchecks/healthchecks#407]
I'd like to receive the "monthly" report email more frequently than one a month. For example, once a week. I'm new to this software and I'd like to have a bit more security that I know everything is working correctly. Getting reports once a week would make me slightly less paranoid than checking the website every day.

![image](https://user-images.githubusercontent.com/8290105/89232753-1f0e0c80-d5b6-11ea-9570-af3fbe5be9ed.png)

I'm all for better suggestions on wording.

Also, this example UI only has the 2 selections, it could be more expansive if needed.

**Comment by czeigler** [comment]
I would also find this feature very helpful.  Would you consider a pull request if I were to implement this feature?  I find Healthchecks indispensable and very much appreciate all the hard work you have put into it.

**Comment by cuu508** [comment]
Yes, happy to review a PR!

Quick feedback on the above screenshot – I would try combining the checkbox with the first radio group:

```
Send me periodic email reports:
( ) Don't send me email reports
( ) Weekly on Mondays
(*) Monthly on 1st of every month
```

For the week option I would leave out the day of week selector at least initially, to keep it simple.

**Comment by kassyss** [comment]
> I'd like to receive the "monthly" report email more frequently than one a month. For example, once a week. I'm new to this software and I'd like to have a bit more security that I know everything is working correctly. Getting reports once a week would make me slightly less paranoid than checking the website every day.
> 
> ![image](https://user-images.githubusercontent.com/8290105/89232753-1f0e0c80-d5b6-11ea-9570-af3fbe5be9ed.png)
> 
> I'm all for better suggestions on wording.
> 
> Also, this example UI only has the 2 selections, it could be more expansive if needed.

I am in the same boat. I am using Healchecks since a few days, everything is perfect but just like you i am really missing a more frequent report. In addition to a weekly report, i would need a daily report option. Monthly, weekly, daily would be just perfect and garantee that everything is working well on cron job side but also Heathchecks side.

To me, receiving an alert if something goes wrong is good, but receiving a confirmation that everything is going well is as important. That's just my 2 cents.

Best regards,

**Comment by immanuelfodor** [comment]
Why there is no periodic email section in my account? :) Maybe the self-hosted variant doesn't have this feature? Even in Django admin, my user profile has a "Reports allowed" checkbox ticked. I also haven't seen any related env variable in the readme to turn this on.

![image](https://user-images.githubusercontent.com/21174107/103295577-907ea980-49f4-11eb-9bc4-a967716cc026.png)

**Comment by gunr2171** [comment]
@immanuelfodor that's a separate issue.

**Comment by cuu508** [comment]
@immanuelfodor if you're looking at the screenshots in this issue – these are mockups and have not been implemented yet.

**Comment by immanuelfodor** [comment]
Ohh, sorry, I missed the "example UI" part but reading it carefully there it is, my bad :grinning:

**Comment by cuu508** [comment]
Weekly reports are now implemented:

![image](https://user-images.githubusercontent.com/661859/119347585-616b1c00-bca4-11eb-8c4f-fcf0ce20d6d7.png)

Te above form also collects browser's time zone. Healthchecks uses the time zone to send the report at an appropriate time (between 9AM and 11AM in user's time zone). There is not yet a way to set the time zone explicitly, that may come in the future (#365)
