### ISSUE TITLE
CI Build failure introduced by commit "Use separate counters for SMS and phone calls."

### ISSUE THREAD

**Issue by iphoting** [healthchecks/healthchecks#408]
https://travis-ci.org/github/healthchecks/healthchecks/builds/714508466
```
FAIL: test_it_sends_link (hc.accounts.tests.test_signup.SignupTestCase)
282----------------------------------------------------------------------
283Traceback (most recent call last):
284  File "/home/travis/build/healthchecks/healthchecks/hc/accounts/tests/test_signup.py", line 23, in test_it_sends_link
285    self.assertEqual(profile.sms_limit, 5)
286AssertionError: 500 != 5
```
Looks like it might be introduced by the following bug in the test, when `USE_PAYMENTS=False` is the default: 
```
        # A profile should have been created
        profile = Profile.objects.get()
        self.assertEqual(profile.sms_limit, 5)
        self.assertEqual(profile.call_limit, 0)
```
Ref: https://github.com/healthchecks/healthchecks/compare/77ee8452c5f8...8c134570371c#diff-9336213c71d0ba69ae89055c09e2c53aR21-R25

**Comment by cuu508** [comment]
Sorry, that's my bad. I have `USE_PAYMENTS=True` in my `local_settings.py` and so the tests passed for me. And somehow I missed the Travis notification(s).

Thanks for tracking it down and fixing, @iphoting !
