### ISSUE TITLE
Request: Flexible Schedules beyond X timeframe

### ISSUE THREAD

**Issue by ericcholis** [healthchecks/healthchecks#41]
In my use case, there are a few tasks that are paused off-hours. This creates quite a bit of downtime alerts for tasks that only run between certain times.

For example, we have a batch of tasks that run from 2:00 AM to 11:59pm. These tasks are scheduled like this to allow for maintenance related tasks to be run in that Midnight to 1:59 AM period.

Because of this, we receive quite a few downtime alerts which are actually false positives. This can cause legitimate downtimes to be missed.

**Comment by cuu508** [comment]
I've now added support for cron syntax and rolled the change out on healthchecks.io. 
@ericcholis  if you're still interested in this, you are welcome to test it out!

**Comment by ericcholis** [comment]
Thanks for the update!
