### ISSUE TITLE
Issue with Slack integration setup - How to ?

### ISSUE THREAD

**Issue by xakraz** [healthchecks/healthchecks#413]
Hi !

I am facing an issue with Slack integration. Whenever I try to create an integration, I do not get the blue alert bubble saying the integration is created like I see in the doc and as a matter of fact, no integration is created.

Notes:
* I have created a Slack app to get `client_id` and `client_secret`
  * I have setup the app with `incoming-webhook` bot Token scopes
  * I have setup a `redirect_url` as requested for the Slack workspace integration.
  * I have set the equivalent of SITE_ROOT for the `redirect_url` mentioned above
* I am using the docker image https://github.com/linuxserver/docker-healthchecks/ tag `v1.16.0-ls65`
  * All I get is `uWSGI` requets logs but not `Django's`
  * When trying to create the integration I don't see errors, I have requests with `200`
* I am trying to deploy Healtchecks on Kubernetes

These are all the logs I can get, whether or not the `DEBUG` var in set to true in ENV or in `local_settings.py`

```
[pid: 284|app: -1|req: -1/162] 10.201.3.90 () {50 vars in 1131 bytes} [Wed Aug 19 18:24:30 2020] GET /static/img/integrations/add_to_slack.png => generated 5705 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 3 headers in 112 bytes (0 switches on core 0)

[pid: 284|app: -1|req: -1/163] 10.201.3.90 () {48 vars in 1086 bytes} [Wed Aug 19 18:24:30 2020] GET /static/img/integrations/setup_slack_btn_2.png => generated 36300 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 3 headers in 113 bytes (0 switches on core 0)

[pid: 284|app: -1|req: -1/164] 10.201.3.90 () {50 vars in 1141 bytes} [Wed Aug 19 18:24:30 2020] GET /static/img/integrations/setup_slack_btn_1.png => generated 21604 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 3 headers in 113 bytes (0 switches on core 0)

[pid: 284|app: -1|req: -1/165] 10.201.3.90 () {48 vars in 1086 bytes} [Wed Aug 19 18:24:30 2020] GET /static/img/integrations/setup_slack_btn_3.png => generated 32033 bytes in 0 msecs via sendfile() (HTTP/1.1 200) 3 headers in 113 bytes (0 switches on core 0)

[pid: 284|app: 0|req: 6/166] 10.201.3.90 () {48 vars in 1253 bytes} [Wed Aug 19 18:24:41 2020] GET /?code=14341150006.1309604133461.9bbc3d3da064be75b43226d89d4239da8235ecf0b9de5fd6503dd6ea85b8af29&state=wiFqViOpAjulu06zQqTLcujOVMSD3w58pfUBJObk8P0 => generated 10663 bytes in 313 msecs (HTTP/1.1 200) 7 headers in 359 bytes (1 switches on core 0)
```

Thanks for your help and great work !

**Comment by cuu508** [comment]
The redirect URL on Slack side should point to a specific view, `SITE_ROOT/integrations/add_slack_btn/`. For example, if your Healthchecks instance is running at

    https://example.org/

Then use this redirect URL in Slack:

    https://example.org/integrations/add_slack_btn/

Sorry – this is not documented anywhere at the moment. To be honest I didn't expect anybody other than me bother with setting up a Slack OAuth app. If you get it working, we can add a section in README with a summary of steps.

**Comment by xakraz** [comment]
Hi @cuu508 !

Thank you so much for your answer, it works ! :tada: 

Do you want me to submit a PR on the `README` for that update ?



And by the way (I know this is kind of out of the scope of this issue) do you have tips regarding my question about the logs, the `DEBUG` var and the usage of `uWSGI` ? Maybe I would have found more info in there before bothering you with the GitHub issue :smile:

**Comment by cuu508** [comment]
Happy to hear you got it working!

> Do you want me to submit a PR on the README for that update ?

If you are OK to do that, that would be great!

> do you have tips regarding my question about the logs, the DEBUG var and the usage of uWSGI

In this specific case, there were no errors thrown. Slack redirected to the index page, which ignored the GET parameters from Slack. If there were 400 or 500 responses, they would show up in uWSGI stdout output. 

For production use, definitely keep DEBUG=False. To get notified about cases when python code hits an error, you can:

* set the ADMINS setting, to receive email notifications (https://docs.djangoproject.com/en/3.1/ref/settings/#admins)
* use [Sentry](https://sentry.io/organizations/msmd/issues/), it integrates nicely with Django projects 

The sendalerts management command writes some diagnostics to stdout, these are useful to have if you are investigating why an alert wasn't delivered. Looking at [uwsgi.ini](https://github.com/linuxserver/docker-healthchecks/blob/master/root/defaults/uwsgi.ini), I think these logs would show up on uWSGI's stdout.

**Comment by xakraz** [comment]
Thank you for all these valuable information.

I will try to submit a PR about the doc.
Thx again !
