### ISSUE TITLE
API endpoints monitoring

### ISSUE THREAD

**Issue by esirK** [healthchecks/healthchecks#414]
Firstly thank you for this great tool you have created.
Currently, I don't think we have the functionality that would allow users to check the status of their API endpoints something like Datadog synthetics but just a basic one for now. Something like https://github.com/esirK/APIHealthchecks/blob/master/main.py
Feel free to close the issue if the tool was not designed to have such checks in mind.

**Comment by cuu508** [comment]
Thanks for the suggestion @esirK!

At least for now, my plan is to keep Healthchecks focused on doing one thing and doing it well – dead man's switch style monitoring (aka "passive monitoring", "heardbeat monitoring"). Luckily, there are many active monitoring options to choose from already!

**Comment by esirK** [comment]
> Thanks for the suggestion @esirK!
> 
> At least for now, my plan is to keep Healthchecks focused on doing one thing and doing it well – dead man's switch style monitoring (aka "passive monitoring", "heartbeat monitoring"). Luckily, there are many active monitoring options to choose from already!

Sounds great. Thank you for letting me know
