### ISSUE TITLE
[BUG] badge text messed up

### ISSUE THREAD

**Issue by LsHallo** [healthchecks/healthchecks#416]
With the last 2 updates I've noticed that all of my badges look like this: 
![image](https://user-images.githubusercontent.com/22171518/91204035-d1437a80-e703-11ea-87ec-5570c96ef66b.png)
![image](https://user-images.githubusercontent.com/22171518/91204066-d7d1f200-e703-11ea-8134-a1e112e22289.png)

which is not correct.
I'm using the linuxserver docker image to self host.

**Comment by cuu508** [comment]
Thanks for reporting this!

Do badges also look like this on healthchecks.io? How do they look in different browsers? Can you post an example of the generated SVG here?

**Comment by LsHallo** [comment]
Here is the raw svg as a gist since github doesn't support uploading svg. https://gist.github.com/LsHallo/ee4c73baf364a03c93ccd19a6a30cc27

I have no clue if it looks the same on healthchecks.io I'm running my own version on my server. Have restarted the docker container and cleared my cache. Also tried firefox and chrome and still looks the same.

**Comment by cuu508** [comment]
Managed to reproduce the isssue. 

With `USE_L10N = True`, in some locales the decimal values in templates get formatted as `15,0`, not `15.0`. This results in broken SVG. 

There are problems in other places too, for example the sliders in the  "Edit Timeout & Grace Time" dialog don't initialize properly.

I'll change `USE_L10N` back `False`. We can set it back to `True` after we've caught and fixed this and similar issues.

@LsHallo if you can modify `local_settings.py`, as a short term fix you can put `USE_L10N = False` there.
