### ISSUE TITLE
Successful Ping, then down alert prior to next scheduled check in.

### ISSUE THREAD

**Issue by mgeorgy** [healthchecks/healthchecks#418]
I have healthchecks running and all of the functionality is working, however I have daily scheduled check-ins (0 8 * * *) with a 1 hour grace, that ping at the appropriate time only to have an alert generated an hour later that the service is down.  Attached are images of the cron configuration and the check-in logs.

What am I missing?

![image](https://user-images.githubusercontent.com/1755116/91594894-a12cef00-e930-11ea-8313-d869b322f85f.png)
![image](https://user-images.githubusercontent.com/1755116/91594984-c1f54480-e930-11ea-9fce-6a86cff49392.png)

**Comment by cuu508** [comment]
This is often caused by a timezone mismatch (the server has has one timezone, Healthchecks is configured to use a different one).

Also, if you've recently changed timezone on your server – if the cron daemon was not restarted afterwards it might still be using the old timezone.

**Comment by mgeorgy** [comment]
That was it.  Thank you @cuu508 .
