### ISSUE TITLE
resume now button does not appear

### ISSUE THREAD

**Issue by caleb15** [healthchecks/healthchecks#421]
I paused a health check but the resume now button does not appear.

Oddly if I refresh the page it appears for split second and then goes away again.

Luckily I was able to click it in the split second that it appeared :joy: 

I didn't see any errors in the console / network traffic

![image](https://user-images.githubusercontent.com/46505081/92184545-5d415a80-ee06-11ea-81db-31406c91d253.png)

**Comment by caleb15** [comment]
OS: Ubuntu 18
Browser: Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by cuu508** [comment]
Thank you for reporting this!
That's my bad, I introduced a regression when adding support for read-only team members.
Fixed now, and the fix is deployed to https://healthchecks.io

**Comment by caleb15** [comment]
Thanks for the incredibly fast fix! There's this one vendor we use that has a bug that they haven't fixed for like 6 months now so this is lightning fast in comparison :joy: 

I've verified it works now :)
