### ISSUE TITLE
Valid JSON response rejected by update endpoint

### ISSUE THREAD

**Issue by msfjarvis** [healthchecks/healthchecks#422]
While working on my Rust library for healthchecks ([source available here](https://github.com/msfjarvis/healthchecks-rs)) I came across a HTTP 400 response from the implementation of [this](https://healthchecks.io/docs/api/#update-check) API method.

The JSON I was sending is `"{\"name\":\"dl_msfjarvis_dev_sync\",}"` which appears to be valid according to all the JSON validators and linters I had at hand but is rejected by the site.

Is this something that can be fixed or should I attempt to work around it myself?

**Comment by cuu508** [comment]
Hi @msfjarvis!

`"{\"name\":\"dl_msfjarvis_dev_sync\",}"` is a valid JSON *string*, but the API expects a JSON *object*: 

    {"name":"dl_msfjarvis_dev_sync"}

(not enclosed in quotes, no escaping for inner quotes, no trailing comma)

If I've misunderstood the question, please let me know!

**Comment by msfjarvis** [comment]
That'd certainly explain it. I'll fix this on my end, thanks for the help!
