### ISSUE TITLE
Feature request: Integration with Signal messenger

### ISSUE THREAD

**Issue by piramiday** [healthchecks/healthchecks#428]
since WhatsApp and Telegram are already there, why not **Signal**?

https://www.signal.org/

**Comment by cuu508** [comment]
Does Signal have an API or incoming webhook support for posting to Signal users / groups?
Do bots exist on Signal, if yes – can you point me to any prominent ones?

**Comment by piramiday** [comment]
I don't know about that -- does WhatsApp support all of the above?

I know that you can easily register a number and use a command-line interface: https://github.com/AsamK/signal-cli
if not the java library itself: https://github.com/signalapp/libsignal-service-java

I don't know more than this, though, so feel free to close this issue if it's not feasible without detailed information. :smile:

**Comment by varac** [comment]
Yes, Signal integration is really missing !

**Comment by ldavis2020** [comment]
Yes we would really like Signal integration too. I very happily use the signal-cli command line interface (https://github.com/AsamK/signal-cli) in some of our own scripts, but having it integrated into Healthchecks would make an amazing difference.

**Comment by cuu508** [comment]
I'm noting the interest!

Just tried out signal-cli, quite impressive how easy it was to go from downloading a tarball to sending messages. 

I'd love to add an integration in Healthchecks.io. 

One concern I have at the moment is with security and needing to run a new-to-me binary on the server. I'll need to look into shielding it from the rest of the system.

The other complication is using the same sender identity from multiple servers. It [can be done via linking](https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning)), but complicates the provisioning of new servers a bit.

Ah, also, sending messages to groups. Sending to phone numbers is straightforward, but for groups there will need to be some sort of an onboarding flow and instructions.

**Comment by cuu508** [comment]
An update on this: I implemented the basic functionality – adding a phone number, sending notifications to a single recipient – and pushed the changes. 

I haven't deployed these changes on the hosted service yet, because I made [a bit of a mess](https://www.reddit.com/r/signal/comments/ku0ji2/no_option_for_entering_an_alphanumeric_pin/) with registering and setting up sender account. I'll resolve this issue once I resolve this and deploy the integration.

**Comment by cuu508** [comment]
I resolved the registration issue and deployed the changes. The Signal integration is now available on https://healthchecks.io. For the time being, please treat this integration type as experimental. 

Currently, my biggest concern is variable delays when sending messages. Sending the first message to a new recipient can take 20+ seconds. From my testing, sending followup messages takes ~3 seconds, but it fluctuates and can sometimes take 10+ seconds. 

I've set the sending timeout to 30 seconds. If signal-cli exceeds this time, it gets killed. 

I'm hoping the sending delays are not inherent to the system, and will improve as Signal scales their infra up.
