### ISSUE TITLE
Suggestion: report exit status

### ISSUE THREAD

**Issue by piramiday** [healthchecks/healthchecks#429]
it would be useful to be able to report success or failure using only the exit status:
```
bash my-script.sh
curl https://hc-ping.com/xxxyyyzzz/$?
```
so that:
- `https://hc-ping.com/xxxyyyzzz/0` means success,
- `https://hc-ping.com/xxxyyyzzz/1` and other numbers mean failure.

this would make scripts shorter and would help to avoid the uglier `if` checks on the exit status.
ideally, it could be useful to store and show to the user the actual exit code `$?`, but that's another matter because it requires changing a lot more.

**Comment by cuu508** [comment]
That's a great suggestion, much cleaner than `if` logic.
I'm planning on implementing it.

**Comment by cuu508** [comment]
This now implemented, deployed and ready for testing. Any and all feedback welcome!

**Comment by piramiday** [comment]
happy to help! :tada:

**Comment by piramiday** [comment]
just got my first failure of a check for which I use the `curl https://hc-ping.com/xxxyyyzzz/$?` feature.
from the dasboard I can read a message like "Ping #XX (received via the /fail endpoint)" -- that mentions the `/fail` endpoint incorrectly -- and I see no mention of the reported exit status, which would help in debugging.

should I open up another issue with the feature suggestion of making the reported exit statuses transparent to the user?
IMHO even reporting the correct endpoint invoked by my curl would help, e.g. `/2 endpoint`, no need to change graphics or add labels.

**Comment by cuu508** [comment]
Thanks for the report @piramiday. There's a recent issue (#455) also about exposing the exit status, tlet's track this there.
