### ISSUE TITLE
debug = "False" not working

### ISSUE THREAD

**Issue by blade1989** [healthchecks/healthchecks#432]
The debug mode will not de disabled. We have set the `debug = "False"` option in `/opt/healthchecks/hc/local_settings.py`, but we still see the debug warning:

>  Running in debug mode, do not use in production.

We also appended ``debug = "False"`` to  `/opt/healthchecks/hc/settings.py`, but it still exists!

Any help is greatly appreciated!

**Comment by cuu508** [comment]
The setting names are all in UPPERCASE. `DEBUG` takes a boolean value (`False`, without quotes).
Please try adding:

    DEBUG = False

**Comment by blade1989** [comment]
Thanks for the reply, I changed the string to `DEBUG = False`, but now I get a 500 error when visiting the website? :thinking:

**Comment by blade1989** [comment]
@cuu508 When I add the quotes back, I can browse the website again? :thinking:

**Comment by cuu508** [comment]
@blade1989 check out #203 and #283

**Comment by cuu508** [comment]
@blade1989 did you manage to get it working?
