### ISSUE TITLE
Email notifications not being sent

### ISSUE THREAD

**Issue by PopeRigby** [healthchecks/healthchecks#433]
I'm using the official Healthchecks.io instance, and my email notification isn't working. The test notification works, but I'm not getting an email when my check is getting a ping. I know it's not an issue with the ping because it's showing up in the log.

**Comment by cuu508** [comment]
Please send me your account's email address to contact@healthchecks.io and I'll look into it!

**Comment by PopeRigby** [comment]
Thanks!

**Comment by bhargav-vekariya** [comment]
Hi, facing the same issue.. test email is working fine. but when ping gets down not sending any email alert

**Comment by cuu508** [comment]
@bhargav-vekariya is sendalerts running?

**Comment by bhargav-vekariya** [comment]
@cuu508 I have setup the Healthcheck on ubuntu server. how can I check if sendalerts is running or not?

**Comment by cuu508** [comment]
@bhargav-vekariya https://github.com/healthchecks/healthchecks?tab=readme-ov-file#sending-alerts-and-reports

**Comment by bhargav-vekariya** [comment]
Thank you so much!! @cuu508
