### ISSUE TITLE
Use Microsoft Teams Card Title instead of Text

### ISSUE THREAD

**Issue by andrewbrock-sahmri** [healthchecks/healthchecks#435]
Currently the integration uses the "text" attribute of a MS Teams Card to notify the up/down status of checks.
![image](https://user-images.githubusercontent.com/70552043/94623561-9c72a680-02f3-11eb-8d27-2e38369822ba.png)

This makes notifications unhelpful:
![image](https://user-images.githubusercontent.com/70552043/94623703-fa9f8980-02f3-11eb-8a0a-8237d50ca244.png)

If you instead use the title field of the Card (instead of text) you should get a better result.

**Comment by cuu508** [comment]
Thanks for the suggestion.

I'd like to experiment with it, where can I see these notifications (a specific app, browser, device model)?

**Comment by cuu508** [comment]
Nevermind, found the "Activity" section in MS Teams ;-)

Looks like if we set the "title" and "summary" fields to the same value, all looks well:

- summary gets displayed in the notification
- title gets displayed in the full "Posts" view
