### ISSUE TITLE
Document the handling of confirmation links

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#436]
When a ping body contains the word "confirm", Healthchecks assumes it might contain a confirmation link. To draw user's attention to it, it shows a badge in the dashboard:

![image](https://user-images.githubusercontent.com/661859/94653743-b799e200-0304-11eb-995a-c32f6d5bbafd.png)

The badge is not explained anywhere on the site or in the documentation.

**Comment by cuu508** [comment]
Added an informative tooltip:

![image](https://user-images.githubusercontent.com/661859/95975866-6703a800-0e1f-11eb-803a-a5a582692fc0.png)

**Comment by anxodio** [comment]
Hi! Why it's important to show a badge if the body contains the word "confirm"? What's the intention? Thank you :)

**Comment by cuu508** [comment]
@anxodio the specific use case I had in mind was AWS SNS and webhook subscriptions. 

In AWS SNS you can create a *Topic* and create *Subscriptions* for that topic. Among the supported subscription types is HTTP and HTTTPS: when a message is posted to the topic, AWS SNS will send an HTTP(S) request to the nominated URL. 

When you first create a HTTP(S) subscription, AWS SNS will first send a special HTTP request to the URL which contains a confirmation link. Once the confirmation link is clicked, the subscription is active. The message payload looks like this:

```json
{
  "Type" : "SubscriptionConfirmation",
  "MessageId" : "a75c4bbe-2925-4108-82b4-a9a7c4c72985",
  "Token" : "xxxx",
  "TopicArn" : "arn:aws:sns:eu-central-1:xxxx:Demo-Topic",
  "Message" : "You have chosen to subscribe to the topic arn:aws:sns:eu-central-1:xxxx:Demo-Topic.\nTo confirm the subscription, visit the SubscribeURL included in this message.",
  "SubscribeURL" : "https://sns.eu-central-1.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:eu-central-1:xxxx:Demo-Topic&Token=xxxx",
  "Timestamp" : "2024-05-22T11:50:05.094Z",
  "SignatureVersion" : "1",
  "Signature" : "xxxx",
  "SigningCertURL" : "https://sns.eu-central-1.amazonaws.com/SimpleNotificationService-60eadc530605d63b8e62a523676ef735.pem"
}
```

The "confirmation link" badge is meant to draw user's attention to the fact that the ping body contains the word "confirm" and so *perhaps* there's a confirmation link in there, that needs to be acted upon.

**Comment by anxodio** [comment]
Thank you for the explanation @cuu508 :)

We have some ping bodies that contain the word confirm but it's not a confirmation link, but knowing that it is not important, we can simply ignore the badge
