### ISSUE TITLE
ModuleNotFoundError: No module named 'cron_descriptor'

### ISSUE THREAD

**Issue by blade1989** [healthchecks/healthchecks#441]
I keep getting this error, but when I try to install it, I get `Requirement already satisfied:` message.

**Comment by cuu508** [comment]
I would first check if there's any issue with virtualenv. Perhaps the package is installed in a different virtualenv, or is installed globally, or something along these lines.

* are you using virtualenv?
* when you install cron-descriptor, do you do it from an activated virtualenv?
* when/how do you get the error? while running `manage.py runserver`? Is it running inside an activated virtualenv?

**Comment by blade1989** [comment]
I installed it in multiple ways, via virtualenv:

source hc-venv/bin/activate
pip install pretty-cron

Als via root terminal I executed `pip install pretty-cron`.

Als, after the update, i executed `pip install -r requirements.txt`, But, no luck. the same error is present

**Comment by blade1989** [comment]
@cuu508 my apologize, wrong button

**Comment by cuu508** [comment]
When/how do you get the error? while running manage.py runserver? Is it running inside an activated virtualenv?

Can you check if `cron-descriptor` shows up in the output of `pip freeze` when the virtualenv is active?

**Comment by blade1989** [comment]
Yes, I can clearly see `cron-descriptor==1.2.24` in the output of `pip freeze`. 

I just edited my previous comment, added: `I am using gunicorn with nginx to excecute the healthchecks`. In case you missed that

**Comment by cuu508** [comment]
How do you launch gunicorn? Is it installed in the virtualenv or globally?

**Comment by blade1989** [comment]
> When/how do you get the error? 
While visiting healthchecks via browser


> while running manage.py runserver? Is it running inside an activated virtualenv?
I excecute it via `gunicorn hc.wsgi -w 4`. I don't know if the virtualenv is being used. I think its globally? :thinking:

**Comment by cuu508** [comment]
My hunch would be that you have every dependency except cron-descriptor also installed globally, and gunicorn is not using the virtualenv.

**Comment by blade1989** [comment]
I also get the error from executing `./manage.py migrate`

**Comment by blade1989** [comment]
How do I make gunicorn use the virtualenv?

**Comment by cuu508** [comment]
One way to do that is to install gunicorn inside the virtualenv. And then run hc-venv/bin/gunicorn instead of /usr/local/bin/gunicron (or wherever it gets installed globally)

**Comment by cuu508** [comment]
Hey @blade1989, did you find out what the issue was?
