### ISSUE TITLE
[Feature Request] Send Syslog 

### ISSUE THREAD

**Issue by projx** [healthchecks/healthchecks#444]
Healthcheck provides a great place for centralising the monitoring on Cronjobs, but it becomes another dashboard that needs to be monitored.  Most organisations (and Homelabs) will use some kind of central analytics and monitor system to provide a single-pane to monitor systems, which takes inputs from via different mediums including Syslog and SNMP traps.

Could you the ability to send notifications to a remote syslog server on UDP or TCP, which will allows alerts and messages from Healthcheck to be centralised into existing analytics and monitoring systems.

**Comment by cuu508** [comment]
Healthchecks has an optional "Shell Commands" integration, which I think would help here. 

You can enable it by setting the `SHELL_ENABLED=True` environment variable. After enabling it, you can set up notifications to a remote syslog server like so:

![image](https://user-images.githubusercontent.com/661859/97438759-e9b35980-192d-11eb-8df1-0e76b246a76f.png)
