### ISSUE TITLE
MS Edge (Chromium)  - Not working with HalthChecks

### ISSUE THREAD

**Issue by AlphaOmega2020** [healthchecks/healthchecks#445]
When accessing HealthChecks with MS Edge (Chromium), you get an error: invalid HTTP request size (max 4096)... 

To fix: 
Edit: /app/healthchecks/uwsgi.ini
add: `buffer-size = 32768`

**Comment by cuu508** [comment]
Looking how to I reproduce this – are you doing something specific (e.g., submitting a form) when you hit the error?

**Comment by AlphaOmega2020** [comment]
> Looking how to I reproduce this – are you doing something specific (e.g., submitting a form) when you hit the error?

nothing, just installed HC and tried to access via MS Edge.

**Comment by cuu508** [comment]
Were you using one of the 3rd party Dockerfiles? If that's the case, it should be fixed in the Dockerfile's repository, where uwsgi.ini lives.
