### ISSUE TITLE
Show state changes (flips) in check's log

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#447]
If a check has no integrations enabled, then the log doesn't show any sent notifications. It only shows incoming pings. From glancing at the log, it's hard to tell if everything's fine (pings are arriving at expected times, with no gaps) or if there are problems.

Look into what's involved in also showing Flip instances in the log.

**Comment by ths-group** [comment]
+1, as this would help debugging situations where no notifications are configured as well. For example when the "up" status is monitored via the API.
