### ISSUE TITLE
Does this error  occurred by Healthchecks.io side?

### ISSUE THREAD

**Issue by aeharvlee** [healthchecks/healthchecks#449]
When I try to send ping to check, it shows the error message sometimes.

HTTPSConnectionPool(host='hc-ping.com', port=443): Max retries exceeded with url: /a3515c03-29cf-4997-9416-d14311b1d949 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe49001090>: Failed to establish a new connection: [Errno -2] Name or service not known'))

There was no error by my side at that time. 
I want to know whether this error is well-known(not serious) or something.

**Comment by cuu508** [comment]
"Name or service not known" means DNS resolution failed. The most likely reason is your network connection was down when the client was pinging hc-ping.com.

**Comment by aeharvlee** [comment]
@cuu508  Thanks for your answer.

If so, it must have been an error in my client program when connecting to hc-ping.com.
