### ISSUE TITLE
Opsgenie instraction page need update

### ISSUE THREAD

**Issue by soloradish** [healthchecks/healthchecks#450]
~~API Key generate page move to "APP SETTINGS" -> "API key management" in latest version of Opsgenie.~~
![1605495770519](https://user-images.githubusercontent.com/3396889/99208422-528a4500-27fb-11eb-974d-3605a67cd8ab.jpg)

UPDATE:
I'm wrong, the `API key generate from API key management`  is distinct from `integration api key`.

You should get a integration API key from team page's left sidebar `Integrations`.
![1605497023316](https://user-images.githubusercontent.com/3396889/99209496-405dd600-27fe-11eb-8279-7de4a1022b67.jpg)

**Comment by cuu508** [comment]
Thanks for the heads up, @soloradish!

The OpsGenie account I had used for testing did look quite different, there was no sign of "Team" or a team dropdown. Perhaps it was in some sort of legacy mode, or severely limited after a trial running out.

I created a throwaway account, took new screenshots and updated the instructions.
