### ISSUE TITLE
Question: How to configure receiving emails as pings

### ISSUE THREAD

**Issue by bensulli** [healthchecks/healthchecks#454]
I understand that I can send emails as a 'ping'. In my case, I want to use Cloudberry's backup status email as that ping. However, I can't find any way to configure this. The check says to send an email to 63207b7a-b9fc-4b79-b995-9687ac822e73@localhost, but this isn't a valid address.

How do I configure healthchecks.io to check an address with pop? Or am I going about this all wrong?

Either way, the documentation could be clearer.

Thank you!

**Comment by cuu508** [comment]
Hi @bensulli, are you running a self-hosting installation? 

The documentation for setting up inbound email could be improved for sure. There's a stub in the README here: https://github.com/healthchecks/healthchecks#receiving-emails

**Comment by bensulli** [comment]
That's very helpful, thank you!
