### ISSUE TITLE
'received via the /fail endpoint' to include the status code?

### ISSUE THREAD

**Issue by wlupton** [healthchecks/healthchecks#455]
I'm wondering whether log item details (in the GUI) could include the status code. Currently I believe we see this:

![Screenshot 2020-11-25 at 13 04 23](https://user-images.githubusercontent.com/8874729/100231325-c2e14680-2f1e-11eb-8b71-3139e52b0bd9.png)

regardless of whether the `/fail` or `/<status>` endpoint was used.

**Comment by cuu508** [comment]
Healthchecks currently doesn't tack the status code (and so cannot display it), but this is something it could and probably should do. 
Storing one extra single-byte field per ping should be fine.

**Comment by cuu508** [comment]
Once we start tracking exit status in the database, we can show it in the "ping details" dialog:

![image](https://user-images.githubusercontent.com/661859/100463770-0aa9ce80-30d5-11eb-968c-45aa9aaf25a8.png)


And in the event log:

![image](https://user-images.githubusercontent.com/661859/100463603-c7e7f680-30d4-11eb-8d2e-6d44b55626aa.png)

In the log, there's no explanation for what a number in a red badge means. But I think a technical user would be able to guess, especially the person who set it up.
