### ISSUE TITLE
Add a way to "pause" checks via Ping API

### ISSUE THREAD

**Issue by antoine2tt** [healthchecks/healthchecks#460]
Hello,

According to the doc : https://healthchecks.io/docs/http_api/ 

We can not "pause" a check via the Pinging API, it could be cool to be able to pause it that way. 

Thanks

**Comment by danemacmillan** [comment]
Just came across this and realized that this may have been implemented: https://healthchecks.io/docs/api/#pause-check

**Comment by cuu508** [comment]
Yes, it's implemented in Management API. Closing.
