### ISSUE TITLE
Sole numeric tag causes UI to fail to load with JS error

### ISSUE THREAD

**Issue by likuilin** [healthchecks/healthchecks#462]
Here's a minor UI bug that caused me a bit of headache. If a check has only one tag, and the tag is entirely numeric, then the /details/ page of the check fails to load, and, most notably, the Log to the right is blank. 

This is because of a JS error on the page `Uncaught TypeError: allTags.split is not a function` which is because `$("#update-tags-input").data("all-tags")` returns an integer type instead of the expected string type. 

Another example of the same issue is if the only tag is valid JSON, for instance, a tag called `{}` will cause the same issue. In general, the [jQuery .data(key)](https://api.jquery.com/data/#data2) API returns an object, not necessarily a string.

**Comment by cuu508** [comment]
Thanks for reporting, @likuilin !
