### ISSUE TITLE
Move self-hosting instructions from README to online docs

### ISSUE THREAD

**Issue by Romanmir** [healthchecks/healthchecks#467]
I'm not seeing where to configure options for Pushover notifications.

I already have a notification set up that pings me on backup failure, but I'd like to set up a new notification for a separate project that notifies me in an emergency fashion when an important process is missed.

Can you expand on the notes that you have in the "Configuring Notifications" page?

Here are the questions that should be expanded; "Where do I configure the push settings for pushover?", "Are the settings for pushover per project?", "Can multiple settings 'profiles' be used within a specific project?"

Thanks for making this software, I use it consistently.

**Comment by cuu508** [comment]
Thanks for the feedback!

> Where do I configure the push settings for pushover?

You can set the push settings (priority) when adding the Pushover integration. There is currently no option to edit the integration settings, after the integration is added.

You can, however, assign checks to integrations (tell which checks should use which integrations) at any time from 3 places:

* from the list of checks, by clicking on the integration icons
* from the check details page, by clicking on the ON / OFF buttons in the "Notification Methods" section
* from the integrations list, by clicking on cells in the "Assigned Checks" column

> Are the settings for pushover per project?"

They are per-integration (integration = "settings profile"). Each integration belongs to a specific project. If you have multiple projects, and want to use Pushover in each, you must add a Pushover integration to each project.

> Can multiple settings 'profiles' be used within a specific project?

Yes, you can add multiple integrations (settings profiles) of the same type to a single project. For example, you can have three Pushover integrations for low, medium and high priority within a single project. Or you can have multiple Pushover notifications that notify different people.

--

Some of the above is already in the docs, some isn't. I'll review the docs and see what can be improved.

**Comment by Romanmir** [comment]
Ok, but _how_ do I change the settings when setting up the integration?

Maybe I'm missing something. On my integrations list, I do not see Pushover. I've been using the Site Administration interface to do this. I'm using the self-hosted docker image. What am I missing?

**Comment by cuu508** [comment]
Ah, sorry, I didn't realize you don't see the integration in the list at all!

README has instructions for setting up the Pushover integration: https://github.com/healthchecks/healthchecks#pushover

**Comment by Romanmir** [comment]
Ok, I think I'm on the right track now. I think my feedback would change to be: I feel like the contents of the README.md file should be fully integrated into the online docs.

**Comment by cuu508** [comment]
The primary audience of the online docs is the end users of the service. I think publishing README as part of the online docs would just cause confusion. 

Perhaps there could be a page titled "Self-hosting" in the docs, giving a quick idea of what's involved in self-hosting, when it makes sense to do it, and where to get the code.

**Comment by cuu508** [comment]
Gave it some more thought, perhaps moving some of the README content to online docs does make sense after all. The README is getting rather long, and would need to be split into sub-documents at some point anyway. Online docs would probably be more discoverable than a /docs/ folder in the repository or wiki pages.

I'll update the title of this issue.

**Comment by Romanmir** [comment]
Thank you for reconsidering.
