### ISSUE TITLE
Health status shows a months when my check wasn't exist

### ISSUE THREAD

**Issue by vitalykarasik** [healthchecks/healthchecks#472]
I created my first check just 10 minutes ago, but Health Status shows "3 month healthy status". I think it's a bug.
Thank you for great service, Vitaly

<img width="520" alt="Screen Shot 2021-01-29 at 7 34 07" src="https://user-images.githubusercontent.com/7628795/106236067-c3d77280-6204-11eb-8f3e-8815ee0d6c46.png">

**Comment by cuu508** [comment]
Thanks for reporting, and I agree the -1 and -2 months don't make sense for freshly created checks. Same issue in monthly reports as well.
