### ISSUE TITLE
Cron expression with commas causes warning

### ISSUE THREAD

**Issue by bradbeattie** [healthchecks/healthchecks#473]
`45 9,19 * * *` is showing me an warning, even though the cronjob is running on time. Adjusting the expression to `45 9 * * *` out of curiosity then shows the check as healthy. So it looks like cron expressions with commas aren't being considered correctly.

**Comment by bradbeattie** [comment]
Running on v1.18.0, if that helps.

**Comment by cuu508** [comment]
By warning, do you mean the orange warning icon ("late" status)?

Can you post here or email me a screenshot of the check's details page when it is in the warning state (interested in seeing the schedule, timezone, and the log of received pings)?

**Comment by bradbeattie** [comment]
Interesting. Now that I go to check it, I see more orange warning icons than expected (late status).

![healthchecks home lan](https://user-images.githubusercontent.com/54340/106491391-ac4df300-646b-11eb-92e7-6aef8fa119ec.png)

But in the screenshot attached, the last ping was 22 hours ago, within the expected 24h window.

My browser's time is UTC-8 and so its the server that runs the cronjob... oh wait. Does Healthchecks assume that a cron expression is expressed in UTC? Such that `0 10 * * *` means 10am UTC+0? That might be the source of the hiccup here.

**Comment by bradbeattie** [comment]
Yeah, that was it. Apologies. I had set these before, but failed to set the server timezone when recreating the checks last time.

**Comment by andyg2** [comment]
I have a similar problem to this

A cron schedule for ever hour between 9am and 5pm
The last check was 26 minutes ago at 10am and a grace period of 1 hour (10:26 currently)

Perhaps I misunderstand how the grace period but from what it seems I should not be seeing a late status.

![image](https://user-images.githubusercontent.com/1462766/212298033-5464bcce-e6bb-4568-9ef2-bb490449ad42.png)

![image](https://user-images.githubusercontent.com/1462766/212298377-6c6139cb-f8d6-409a-82e1-6faac62a8063.png)

**Comment by cuu508** [comment]
@andyg2 it does not look right to me too. Is this on healthchecks.io or a self-hosted instance?

**Comment by andyg2** [comment]
> @andyg2 it does not look right to me too. Is this on healthchecks.io or a self-hosted instance?

It's self hosted. Oh, linuxserver docker image though, will report there instead. Will update here if I find anything useful as it seems related to this issue.
