### ISSUE TITLE
An option to keep nagging the user until they resolve issues

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#48]
When a check goes down we notify the user once and that's it. PagerDuty, VictorOps and PushOver (with Emergency setting) will in fact keep alerting user until they acknowledge the issue. It would be nice to have a similar option for the regular email notifications as well.

Alternatively this could be account-wide, similar to monthly reports, and be called "Daily Digest".

**Comment by diwu1989** [comment]
if there are failing checks, a daily mail that contains all the currently failing checks would be the least spammy way to nag

**Comment by andela-ijubril** [comment]
@cuu508 do you still want this enhancement included in healthchecks?
Would be happy to jump on it and any other feature or enhancements you have.
Thanks

**Comment by cuu508** [comment]
@andela-ijubril yes, I do think this would be an useful feature. 
UI wise,  I'm thinking of something like this:

!(http://i.imgur.com/V005Iqh.png)

**Comment by foozmeat** [comment]
I would like to propose a 3rd option for hourly emails. In the event of a notification storm it can be easy to miss the single email. A followup an hour later when hopefully things have calmed down would be really helpful.

**Comment by cuu508** [comment]
Thought about this some more, here's the UI I'm currently thinking of:

![screenshot from 2017-10-13 13-07-35](https://user-images.githubusercontent.com/661859/31541504-8b784ed4-b017-11e7-9d23-b7810b9e99ab.png)
