### ISSUE TITLE
[FEATURE REQUEST] permission to add other members

### ISSUE THREAD

**Issue by swoga** [healthchecks/healthchecks#484]
It would be great to have an owner-like permission setting for team members, for them to add other members.
This would ease the management of projects which many members.

Possible permissions would then be:
- Owner
- Manager <-- NEW
- Member
- Read-Only

What do you think about that idea?

**Comment by jakane** [comment]
I was just working with standing up a local instance yesterday.

The very first thing I wanted to do was to invite other team members to a project, as myself, and not the superuser.

If there were voting for this, I am obviously voting +1 :-)

**Comment by harshakhmk** [comment]
Can I work on this issue? I am willing tocontribute

**Comment by cuu508** [comment]
@harshakhmk, sure, happy to review a PR!
