### ISSUE TITLE
Feature Request: direct link back to healthcheck in slack alert

### ISSUE THREAD

**Issue by caleb15** [healthchecks/healthchecks#486]
This is just a minor annoyance, but it would be nice if the slack alert linked directly to healthcheck so I didn't have to type healthchecks.io, click on the project, search for the check, and click on the check. I would suggest making the "title" field at the top a link.

![image](https://user-images.githubusercontent.com/46505081/109861946-ba329780-7c14-11eb-8e44-3582ac533f8a.png)

The sentry app does this - the title is in blue so you can click on it to go to the sentry issue.

![image](https://user-images.githubusercontent.com/46505081/109862103-e2ba9180-7c14-11eb-9048-8ab45600761d.png)

**Comment by cuu508** [comment]
Thanks, good idea! 

Implemented and deployed.

**Comment by caleb15** [comment]
It works, thanks!
