### ISSUE TITLE
Integration: Webhook URL validation blocking Valid (for me) URLs

### ISSUE THREAD

**Issue by jamesbiederbeck** [healthchecks/healthchecks#493]
I'm hosting healtchecks in docker. I also hosting my notification service (gotify) in docker, meaning it can be reached with just the hostname of the container, no TLD ending. I'm trying to use the webhook integration to post notifications to it. 

For various reasons, the easiest way to reach gotify, which is tightly firewalled, is by making a request to the URL http://gotify/somepath. Because the host portion of the url does not have a dot in it, it fails validation. 

To state the problem differently, is there a way to not have to use a FQDN for the URL field in the webhook integration settings page?

Can this validation be relaxed, or otherwise bypassed?

**Comment by cuu508** [comment]
> Can this validation be relaxed, or otherwise bypassed?

One way to bypass the validation is to edit the URL in Django admin. 

1. In the "Add Webhook" form enter a valid, but wrong URL, e.g. https://example.org/somepath
2. Go to `/admin/api/channel/`, and set the right URL there, it will let you save any URL you enter

**Comment by jamesbiederbeck** [comment]
Awesome thanks, @cuu508!
