### ISSUE TITLE
smtplib.SMTPAuthenticationError: (535, b'5.7.3 Authentication unsuccessful')

### ISSUE THREAD

**Issue by bkalpa9** [healthchecks/healthchecks#494]
Unable to a sent email from the application:
Traceback (most recent call last):
   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
     self.run()
   File "./hc/lib/emails.py", line 28, in run
     msg.send()
   File "/usr/local/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
     return self.get_connection(fail_silently).send_messages([self])
   File "/usr/local/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
     new_conn_created = self.open()
   File "/usr/local/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 69, in open
     self.connection.login(self.username, self.password)
   File "/usr/local/lib/python3.9/smtplib.py", line 734, in login
     raise last_exception
   File "/usr/local/lib/python3.9/smtplib.py", line 723, in login
     (code, resp) = self.auth(
   File "/usr/local/lib/python3.9/smtplib.py", line 646, in auth
     raise SMTPAuthenticationError(code, resp)
 smtplib.SMTPAuthenticationError: (535, b'5.7.3 Authentication unsuccessful')

**Comment by cuu508** [comment]
Have you checked your SMTP credentials (host, port, username, password) are correct?

**Comment by bkalpa9** [comment]
@cuu508 
Yeah, I have double checked everything, Still got error, I was able to connect gmai server using the below setting ENVs though,
` SMTP credentials for sending email
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = envint("EMAIL_PORT", "587")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = envbool("EMAIL_USE_TLS", "True")
EMAIL_USE_VERIFICATION = envbool("EMAIL_USE_VERIFICATION", "True")`

**Comment by cuu508** [comment]
> I was able to connect Gmail server using the below settings ENVs

So, problem solved?

**Comment by bkalpa9** [comment]
@cuu508 
I want to set up a separate dedicated mail server for this app and it failed, I was testing with a Gmail account, and its works, I am still not sure why the Auth error is thrown when I can log in with the same credentials?

**Comment by cuu508** [comment]
Have you checked the SMTP (not POP3, not IMAP) credentials with a different client, and they work?

If you're using port 25, have you checked port 25 is not blocked?

**Comment by bkalpa9** [comment]
@cuu508 
As for the port  its open, that's not the issue, POP3 and IMAP I have to test it but I am confident that I am using SMPT credentials..

**Comment by cuu508** [comment]
Verify the SMTP credentials work with a different client. If you configure, say, Thunderbird, to send email through your SMTP server, does it work?

On residential and even some datacenter locations the port 25 may be blocked by the ISP.

**Comment by gelodefaultbrain** [comment]
It's so weird, when I tried this code on my COMPUTER it worked

```
def send_email(sender,sender_pass,receiver,mail_content,subject):
	'''Parameters are already some of the needed data'''

	#Setup the MIME
	message = MIMEMultipart()

	message['From'] = sender
	message['To'] = receiver
	message['Subject'] = subject

	message.attach(MIMEText(mail_content, 'plain'))

	#Create SMTP session for sending the mail
	session = smtplib.SMTP('smtp.gmail.com', 587) #use gmail with port
	session.starttls() #enable security
	session.login(sender, sender_pass) #login with mail_id and password
	text = message.as_string()
	session.sendmail(sender, receiver, text)
	session.quit()
	print('Mail Sent')
```

but if I tried to run it on a server based from the UK it doesn't work

**Comment by aarshcode** [comment]
Were you able to solve the problem?

I am also facing the same problem. On my own system, I am able to execute the send mail script but on GitHub actions, it gives me an authentication error.

```
smtplib.SMTPAuthenticationError: (535, b'5.7.3 Authentication unsuccessful [BN9PR03CA0842.namprd03.prod.outlook.com 2023-04-01T21:04:20.945Z 08DB30BAD36F4CE5]')
```

**Comment by cuu508** [comment]
@aarshcode I don't think this is a Healthchecks-specific problem. You should check Github docs and/or Github support to see if sending emails from GHA is allowed, and what ports and what protocols are allowed.

**Comment by harshd3001** [comment]
I'm facing the same issue can someone help me with this
it should me this error when i trying loging in gmail with smtp
(535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials f9-20020a170902e98900b001bb892a7a67sm5003108plb.1 - gsmtp')

my email and app password is correct the script runs fine when i run it in my computer but in workflow actions it is giving this error.

**Comment by cuu508** [comment]
@harshd3001 You should check Github docs and/or Github support to see if sending emails from GHA is allowed, and what ports and what protocols are allowed.

**Comment by linuxd3v** [comment]
When I had this error - It turned out to be that updating the docker-compose smtp settings just wasnt enough, because real smtp configuration was stored in local_settings.py.   
I think healthchecks populates the local_settings.py smtp config on container start, but if you updated the docker container smtp env varibles - it doesnt actually update the  local_settings.py.   
which was the problem in my case - I just had to update the smtp settings in local_settings.py.

**Comment by cuu508** [comment]
@linuxd3v were you using the linuxserver image by any chance?

The [healthchecks official image](https://hub.docker.com/r/healthchecks/healthchecks) does not write local_settings.py and always uses the environment variables that are passed in.

**Comment by linuxd3v** [comment]
@cuu508 yes - I'm using the [linuxserver/healthchecks](https://hub.docker.com/r/linuxserver/healthchecks). 
I think when I started using healthchecks - the official [healthchecks/healthchecks](https://hub.docker.com/r/linuxserver/healthchecks) image might not have been available yet.
