### ISSUE TITLE
Monthly Report email for April listed the month that just started

### ISSUE THREAD

**Issue by dimo414** [healthchecks/healthchecks#497]
I got a Monthly Report email earlier today that listed April in the second column. Unsurprisingly every entry in the column was "All good!" since the month has barely started :) Historically the email has included the month that just ended on the right and the prior month to its left, so I would have expected February and March instead of March and April.

![Screen Shot of Monthly Report email](https://user-images.githubusercontent.com/1885701/113364228-d3a82b80-9307-11eb-9e30-b21145cd9b75.png)

**Comment by cuu508** [comment]
Thanks for the report! 

I noticed the exact same thing when I looked at my this month's report. This is a bug, I made it in 597920469146d750923e9b600216f4a71930df99 while improving downtime summary in the check details page and "cleaning some code up" ... 

Fixed now.
