### ISSUE TITLE
How Remote User Header works

### ISSUE THREAD

**Issue by dharmendrakariya** [healthchecks/healthchecks#498]
Hi,

I have set remote user header in my helm chart like below.

```
extraenvs:
      REMOTE_USER_HEADER: "HTTP_X_CUSTOM_CLAIM_EMAIL"
```

but when I use Postman to send this header(X-Custom-Claim-email: xyz@abc) its not giving the result as expected(not logged in).

when I check by using curl, its showing header is going

``` curl -H "X-Custom-Claim-email: abc@xyz.dev" https://healthchecks.xyz.dev -v```

**Comment by cuu508** [comment]
Are you running at least v1.18.0?

I started a dev server like so:

    $ REMOTE_USER_HEADER=HTTP_X_CUSTOM_CLAIM_EMAIL ./manage.py runserver

In Firefox, I installed a "Modify Header Value" addon, and configured it to add a X-Custom-Claim-Email header:

![image](https://user-images.githubusercontent.com/661859/113832254-1ac37000-9791-11eb-9d91-09ef8de621cb.png)

After doing that, I opened http://localhost:8080 and was logged in:

![image](https://user-images.githubusercontent.com/661859/113832541-60803880-9791-11eb-8dcb-949b86309447.png)

**Comment by cuu508** [comment]
Also works in Insomnia (I don't have Postman):

![image](https://user-images.githubusercontent.com/661859/113833191-06cc3e00-9792-11eb-8cb0-2d2c034f065e.png)

**Comment by dharmendrakariya** [comment]
> Are you running at least v1.18.0?
> 
> I started a dev server like so:
> 
> ```
> $ REMOTE_USER_HEADER=HTTP_X_CUSTOM_CLAIM_EMAIL ./manage.py runserver
> ```
> 
> In Firefox, I installed a "Modify Header Value" addon, and configured it to add a X-Custom-Claim-Email header:
> 
> ![image](https://user-images.githubusercontent.com/661859/113832254-1ac37000-9791-11eb-9d91-09ef8de621cb.png)
> 
> After doing that, I opened http://localhost:8080 and was logged in:
> 
> ![image](https://user-images.githubusercontent.com/661859/113832541-60803880-9791-11eb-8dcb-949b86309447.png)

I am having ```linuxserver/healthchecks: amd64-version-v1.16.0``` does it require at least v1.18.0?

**Comment by dharmendrakariya** [comment]
I checked with the latest version and its working fine thanks for the help:)

**Comment by Mikhail5555** [comment]
I am sorry to reopen this issue, but i have been stuck with this problem for a while now.
I have been using `linuxserver/healthchecks: amd64-version-v1.22.0` and it just am not able to get it working.
I add `REMOTE_USER_HEADER = "HTTP_X_CUSTOM_CLAIM_EMAIL"` to local_settings.py and send a request containing the `X-Custom-Claim-Email` header but it doesn't do anything and normal login also stops working.

**Comment by cuu508** [comment]
Hi @Mikhail5555 – in settings.py, it has this bit:

```
REMOTE_USER_HEADER = os.getenv("REMOTE_USER_HEADER")
if REMOTE_USER_HEADER:
    AUTHENTICATION_BACKENDS = ("hc.accounts.backends.CustomHeaderBackend",)
```

So, if you pass REMOTE_USER_HEADER as environment variable, it adjusts AUTHENTICATION_BACKENDS. But if you define it in local_settings.py, it doesn't – because it imports `local_settings.py` at the very end.

To fix, try adding this line to `local_settings.py`:

```
AUTHENTICATION_BACKENDS = ("hc.accounts.backends.CustomHeaderBackend",)
```

**Comment by Mikhail5555** [comment]
Thank you! That indeed solved it!
I though i was going crazy, already spend so much time on trying to get this working. For some reason i though `local_settings.py` just created an environment variable, but it overwrites the `settings.py`
