### ISSUE TITLE
Server error 500 in 1.20.0

### ISSUE THREAD

**Issue by mzch** [healthchecks/healthchecks#500]
After updating to `1.20.0`, HealthChecks cause an error `500` when `DEBUG = False` and clicking a defined project.
When `DEBUG = True`, HealthChecks runs normally.
Could anyone tell me how to fix this issue?

OS: Debian `10.9`
Python: `3.7.4` and `3.9.4`
DB: MariaDB `10.5.9`

**Comment by tonoriesco** [comment]
I had the same problem this morning after upgrading 1.20. 
I solved with:

# python manage.py compress

Hope helps.

**Comment by mzch** [comment]
Great! Fixed my problem. Thanks!
