### ISSUE TITLE
Add UptimeRobot as integration

### ISSUE THREAD

**Issue by HilFing-Real** [healthchecks/healthchecks#501]
[UptimeRobot](https://uptimerobot.com/) Has a status page i can use to let others view if the checks are down.. Pls add a subdomain which is only up while the check is up. Or Else pls add a Status page.

**Comment by cuu508** [comment]
Do you want to get a check's status in UptimeRobot, so you can include it in UptimeRobot's status page?

Here's one way to do it: 

* assign the check an unique tag
* go to the Badges screen and copy the tag's JSON URL
* set up a monitor in UptimeRobot which checks for a keyword in that URL. Use "up" as the keyword

**Comment by HilFing-Real** [comment]
Can u pls tell me detailed steps. It will be super helpful. Thx in advance.

**Comment by cuu508** [comment]
As an example, let's say I have a check named "DB Backups". First, I add a tag to it named "db-backups". The name does not matter, it just needs to be unique (not used for any other check in the project).

![image](https://user-images.githubusercontent.com/661859/116855316-dc8b6600-ac01-11eb-8b54-080d18063b04.png)

I then copy "db-backups.json" URL from the Badges page:

![image](https://user-images.githubusercontent.com/661859/116855421-06448d00-ac02-11eb-8ac6-a2c76c49aabe.png)

I then set up a new Monitor that checks for the keyword "up" in that URL:

![image](https://user-images.githubusercontent.com/661859/116855514-2e33f080-ac02-11eb-8eac-240f5f4e5b85.png)

**Comment by HilFing-Real** [comment]
Thx a lot, i have a working status page now. here it is: https://stats.uptimerobot.com/9YZ31UmEOn

**Comment by HilFing-Real** [comment]
Thx a lot, i have a working status page now. here it is: https://stats.uptimerobot.com/9YZ31UmEOn
