### ISSUE TITLE
prunepings does not delete logs from web UI

### ISSUE THREAD

**Issue by yonas** [healthchecks/healthchecks#505]
After running the script, I still see log entries in the web UI when looking at a check's details page.

On first run, it reports having deleted a couple thousand pings. On second run, immediately after, it reports 0 pings pruned.

It seems like the web UI is either caching pings or using another source to fetch ping logs.

**Comment by cuu508** [comment]
`prunepings` deletes old pings, leaving the 100 most recent for every check. 

After running `prunepings` nothing should change in the web UI because the web UI is showing the last 100 pings for each check, and `prunepings` does not touch these. It only deletes pings that the web UI would not show any more anyway.

**Comment by yonas** [comment]
Thanks, I've created a pull request to add that info to the final output so new users don't need to check the README. https://github.com/healthchecks/healthchecks/pull/506

**Comment by cuu508** [comment]
New users definitely *should* read README :-)

""Done! Pruned %d pings. Kept 100 most recent pings." has a couple problems:

* It makes it sound like 100 pings total were kept. It is 100 pings per check. So a more precise wording would be "For each check, kept 100 most recent pings."
* 100 is the default value but it can be tweaked per user (the Profile.ping_log_limit field). So "kept 100 most recent pings" may sometimes not be accurate. README also has this problem, I'll update README with a note about 100 being a per-user  configurable value.

I'm leaning towards leaving the management command as-is.
