### ISSUE TITLE
Using docker and emails not going out

### ISSUE THREAD

**Issue by jurgenhaas** [healthchecks/healthchecks#508]
Thanks a lot for this amazing project, really amazing software.

I started using it with a docker based installation and it works just fine, except sending emails. The UI confirms "1 email sent" in a green background message bar when e.g. sending reports to a user from the admin interface. But no email gets delivered anywhere.

Can find anything in the logs either and credentials are configured correctly.

Any idea what could be going wrong and how I could further debug the problem?

**Comment by jurgenhaas** [comment]
I've tried without TLS and without SSL now, so port 25 and that seems to be working just fine. But when using port 465 and SSL, then it doesn't. Here are the environment variables I'm using:

```
EMAIL_HOST=smtprelaypool.example.com
EMAIL_PORT=25
EMAIL_HOST_USER=support@example.com
EMAIL_HOST_PASSWORD=+++
EMAIL_USE_TLS=False
EMAIL_USE_SSL=False
```

This config is working. When changing port to 465 and use ssl to True, it hangs indefinitely. Although those settings are working fine for other applications.

Maybe a limitation inside a docker container?

**Comment by cuu508** [comment]
> Any idea what could be going wrong and how I could further debug the problem?

I think it's one of two possibilities:

* The email sending task raises an exception, but it does not appear in logs
* The email sending task gets stuck indefinitely

I did a couple experiments with Docker (with the Dockerfile in this repository). First, I took a known-good email configuration and changed the username and password to dummy values. I started the container, submitted the Sign Up form, and saw this in the logs:

```
web_1  | [pid: 13|app: 0|req: 1/3] 172.18.0.1 () {44 vars in 863 bytes} [Wed May  5 16:23:01 2021] POST /accounts/signup/ => generated 73 bytes in 244 msecs (HTTP/1.1 200) 8 headers in 315 bytes (1 switches on core 0)
web_1  | Exception in thread Thread-1:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "./hc/lib/emails.py", line 29, in run
web_1  |     msg.send()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
web_1  |     return self.get_connection(fail_silently).send_messages([self])
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
web_1  |     new_conn_created = self.open()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 69, in open
web_1  |     self.connection.login(self.username, self.password)
web_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 734, in login
web_1  |     raise last_exception
web_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 723, in login
web_1  |     (code, resp) = self.auth(
web_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 646, in auth
web_1  |     raise SMTPAuthenticationError(code, resp)
web_1  | smtplib.SMTPAuthenticationError: (535, b'Authentication Credentials Invalid')

```

The error appeared pretty much immediately. Next, I reverted the username and password, but changed the port from 587 to 588. I submitted the Sign Up form again, waited and waited, but saw no exception getting logged. I think this is because the sending thread was indefinitely hanging, waiting for any response from the SMTP relay.

I then added `EMAIL_TIMEOUT=10` in setting, and got the exception:

```
web_1  | [pid: 12|app: 0|req: 1/1] 172.18.0.1 () {44 vars in 863 bytes} [Wed May  5 16:26:14 2021] POST /accounts/signup/ => generated 73 bytes in 249 msecs (HTTP/1.1 200) 8 headers in 315 bytes (1 switches on core 0)
web_1  | Exception in thread Thread-1:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "./hc/lib/emails.py", line 29, in run
web_1  |     msg.send()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
web_1  |     return self.get_connection(fail_silently).send_messages([self])
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
web_1  |     new_conn_created = self.open()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 62, in open
web_1  |     self.connection = self.connection_class(self.host, self.port, **connection_params)
web_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 253, in __init__
web_1  |     (code, msg) = self.connect(host, port)
web_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 339, in connect
web_1  |     self.sock = self._get_socket(host, port, self.timeout)
web_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 310, in _get_socket
web_1  |     return socket.create_connection((host, port), timeout,
web_1  |   File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection
web_1  |     raise err
web_1  |   File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection
web_1  |     sock.connect(sa)
web_1  | socket.timeout: timed out
```

I think this confirms my assumption that, without an explicit timeout value, the sending thread was hanging indefinitely. It also confirms that, if the sending thread raises an exception, you should be able to see it in docker logs.

I'm not sure what is going wrong with your configuration, given that it works for other applications. To troubleshoot, you could try the same things I tried: use a bad SMTP password and see if you get an exception in logs. Add EMAIL_TIMEOUT and see what happens.

Hope this helps!

**Comment by cuu508** [comment]
Hi @tristan-k, 

```
    ports:
        - 8000:8000
        - 587:587
        - 465:465
```

I think this should make no difference for sending email. You've mapped port 587 on the host system to port 587 in the Docker container. So, if there was something listening on port 587 in the Docker container, you would be able to communicate with it by connecting to localhost:587. 

But, when sending email, the SMTP client in the docker container is making *outbound* requests to a remote SMTP server's port 587 (or 465, or whatever is configured). 

Have you checked that your SMTP credentials work from the host system (one way to test would be with a GUI email client, for example, Thunderbird)?

**Comment by tristan-k** [comment]
Thanks for the quick reply. There was indeeed something wrong with my email credentials. I fixed that and I'm able to send emails with Thunderbird both with `SSL` at `465` and TLS at  `587`.

Sadly there still seems to be something wrong with the docker container.

If I set `EMAIL_PORT=587` and `EMAIL_USE_TLS=True` I can trigger an exception.

```
healthchecks_web  |   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
healthchecks_web  |     self.run()
healthchecks_web  |   File "/opt/healthchecks/./hc/lib/emails.py", line 22, in run
healthchecks_web  |     self.message.send()
healthchecks_web  |   File "/usr/local/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
healthchecks_web  |     return self.get_connection(fail_silently).send_messages([self])
healthchecks_web  |   File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 131, in send_messages
healthchecks_web  |     sent = self._send(message)
healthchecks_web  |   File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 149, in _send
healthchecks_web  |     self.connection.sendmail(
healthchecks_web  |   File "/usr/local/lib/python3.10/smtplib.py", line 887, in sendmail
healthchecks_web  |     raise SMTPSenderRefused(code, resp, from_addr)
healthchecks_web  | smtplib.SMTPSenderRefused: (554, b'5.7.8 User [tristan@censored.com] not authorized to send on behalf of <admin@censored.de>', 'admin@censored.de')
```

If I set `EMAIL_PORT=465` and `EMAIL_USE_SSL=True` the sending thread is hanging indefinitely and nothing gets reported in the logs.

```
...
healthchecks_web  | [pid: 11|app: 0|req: 6/16] 192.168.1.103 () {44 vars in 1035 bytes} [Sat Jun  4 11:36:12 2022] POST /integrations/1c9f876b-a318-44f8-ac10-4eecab7dd760/test/ => generated 0 bytes in 84 msecs (HTTP/1.1 302) 10 headers in 508 bytes (1 switches on core 0)
healthchecks_web  | [pid: 12|app: 0|req: 5/17] 192.168.1.103 () {38 vars in 1062 bytes} [Sat Jun  4 11:36:12 2022] GET /projects/66590a9c-90bd-40c8-af8c-c28303ceb299/integrations/ => generated 17348 bytes in 171 msecs (HTTP/1.1 200) 10 headers in 528 bytes (1 switches on core 0)
...
```

If I set `EMAIL_PORT=25` and `EMAIL_USE_SSL=False` as well as `EMAIL_USE_TSL=False` the sending thread is hanging indefinitely and nothing gets reported in the logs.

```
healthchecks_web  | Exception in thread Thread-1:
healthchecks_web  | Traceback (most recent call last):
healthchecks_web  |   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
healthchecks_web  |     self.run()
healthchecks_web  |   File "/opt/healthchecks/./hc/lib/emails.py", line 22, in run
healthchecks_web  |     self.message.send()
healthchecks_web  |   File "/usr/local/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
healthchecks_web  |     return self.get_connection(fail_silently).send_messages([self])
healthchecks_web  |   File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 131, in send_messages
healthchecks_web  |     sent = self._send(message)
healthchecks_web  |   File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 149, in _send
healthchecks_web  |     self.connection.sendmail(
healthchecks_web  |   File "/usr/local/lib/python3.10/smtplib.py", line 887, in sendmail
healthchecks_web  |     raise SMTPSenderRefused(code, resp, from_addr)
healthchecks_web  | smtplib.SMTPSenderRefused: (554, b'5.7.8 User [tristan@censored.com] not authorized to send on behalf of <admin@censored.de>', 'admin@censored.de')
```

**Comment by cuu508** [comment]
> If I set EMAIL_PORT=465 and EMAIL_USE_SSL=True as well (...)

Are you setting these as environment variables? If you look at [settings.py](https://github.com/healthchecks/healthchecks/blob/master/hc/settings.py), Healthchecks reads `EMAIL_USE_TLS` from env, but does *not* read `EMAIL_USE_SSL` from env. So setting an environment variable `EMAIL_USE_SSL` has no effect. 

> smtplib.SMTPSenderRefused: (554, b'5.7.8 User [tristan@censored.com] not authorized to send on behalf of <admin@censored.de>', 'admin@censored.de')

When testing with Thunderbird, did you test sending email with admin@censored.de as the From address?

**Comment by tristan-k** [comment]
> Are you setting these as environment variables? 

Yes, I'm setting these variables via the environment variables file `.env`. Why is there no way to configure healthchecks to send mails with `SSL` at `465`? I don't insist on doing so but it was just a way of testing if the exception is related to SSL or TSL.

> When testing with Thunderbird, did you test sending email with [admin@censored.de](mailto:admin@censored.de) as the From address?

Oh boy. That was it. Thank you so much. I set the `DEFAULT_FROM_EMAIL` variable to an different email because I was under the impression that it was a way of setting a email alias. So `DEFAULT_FROM_EMAIL` and `EMAIL_HOST_USER`have to be the same.

**Comment by cuu508** [comment]
> So `DEFAULT_FROM_EMAIL` and `EMAIL_HOST_USER` have to be the same.

This depends on the SMTP provider you are using.

`EMAIL_HOST_USER` and `EMAIL_HOST_PASSWORD` is the username/password Healthchecks uses to authenticate with the SMTP server. Use whatever values your SMTP provider instructs you to use. `EMAIL_HOST_USER` value can look like an email address, like an username, or like a string of random characters – it depends on the provider.

`DEFAULT_FROM_EMAIL` is the value Healthchecks will use in the "From:" field. You must use a value that your SMTP provider will accept. For example, if you've set up `censored.de` with your provider (added TXT records, configured SPF, DKIM etc.) but then try to use `jeff@amazon.com` as `DEFAULT_FROM_EMAIL` value, the provider will likely reject it.
