### ISSUE TITLE
Notifications not being sent.

### ISSUE THREAD

**Issue by stevenmcastano** [healthchecks/healthchecks#51]
I've added a little bit of code and got healthchecks to the a local postfix install via an GMail smarthost to send emails, config here:

```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost' 
EMAIL_PORT = 25  
EMAIL_USE_TLS = False
```

I've got a check purposefully set VERY small, set to come in every 1 minute with a 1 minute grace. The web interface shows the checks late, then it shows them missing, but the email never goes out.

I know the email config works because when I entered my email it correctly sent the confirmation email. Is there something I need to change somewhere?

**Comment by cuu508** [comment]
Hi Steven,

are you running the `manage.py sendalerts` command?

**Comment by stevenmcastano** [comment]
Well sun of a gun, I was not!! As soon as I fired it up, it started working! That’s great!!

Is there a link to some more detailed documentation on how to do things like logging in as the super user? Customizing email templates? Possibly writing web hooks with variable in them?

I have a pretty sophisticaed python application that I call “Notification Central”, that currently takes REST API commands in and allows you to pick which services you want to send a notification out through, pushover, pushbullet, email, growl, XBMC/Kodi, SMS (via google voice of Twilio), etc… and allows you send in a title, subject, message priority and a “selection code” to choose which, if not multiple of the services you’d like the notifications to go out out as. It takes inputs from the HTTP API and can also take inputs as if it was a Growl node.

Is there any easy way of integrating something like? I was thinking the easiest would be through the web hooks but couldn’t find any documentation on how/if you could but variables into the web call itself. Then to be honest, I’d love to have one call for “Down” situations, another for “Up” so the priority could be set different which translates in my software to different sounds, longer onscreen message time, etc.

Also, is there a way to block people from making new registrations? And how exactly does the superuser account log in?

*SMC

**Comment by stevenmcastano** [comment]
Oh… and of course, THANKS so much for the quick reply… with this working now, this is EXACTLY the type of solution I’ve been looking for!!!

*SMC

**Comment by stevenmcastano** [comment]
Jeez… one last thing I forgot to ask… I see a way in there to convert things over to MySQL which would be so much better since I already have a cluster setup with nightly backups (a script a plan to use this to monitor), how would I switch the backup to MySQL from postgres?

*SMC

**Comment by cuu508** [comment]
> Is there a link to some more detailed documentation on how to do things like logging in as the super user? 

Django administration is at http://localhost:8080/admin – added a note about this to README.

> Customizing email templates? 

Have not looked into this. You can of course just fork the repo and edit the templates, but then you'll have to do some merging going forward. There might be a better way to do this.

> Possibly writing web hooks with variable in them?

Can you please open a separate issue for this? I'm guessing the interesting variables would be check's status (up/down) and its name and code.

> I have a pretty sophisticaed python application that I call “Notification Central”, that currently takes REST API commands in and allows you to pick which services you want to send a notification out through, pushover, pushbullet, email, growl, XBMC/Kodi, SMS (via google voice of Twilio), etc… and allows you send in a title, subject, message priority and a “selection code” to choose which, if not multiple of the services you’d like the notifications to go out out as. It takes inputs from the HTTP API and can also take inputs as if it was a Growl node.

Cool, that's the type of application I added the webhooks support for. If we need to post more data to make the integration useful, we'll do that.

> Also, is there a way to block people from making new registrations? 

Not at the moment... What use case are you thinking of? 

> how would I switch the backup to MySQL from postgres?

I updated the README with details on this.

> this is EXACTLY the type of solution I’ve been looking for!!!

Good stuff, happy to hear that!

**Comment by stevenmcastano** [comment]
This all looks like GREAT stuff... thanks again for all your replies!! I just got pulled into a little bit of an emergency at one of my dataacenters, but I'll be back to look at everything you just posted about ASAP and I'll keep you updated!

I'm super pumped that I found this project, GREAT work so far!!

**Comment by stevenmcastano** [comment]
I'm getting a 500 error when trying to log in on port 8080, part of the problem is that I can't get the server to run on none localhost so I have to reverse proxy to it through nginx. Is there a way to get it to come up on 0.0.0.0/80 instead of 127.0.0.1?

**Comment by stevenmcastano** [comment]
> > Also, is there a way to block people from making new registrations?
> Not at the moment... What use case are you thinking of?

Basically, I'd want the site to almost be invite only, so I could have it publicly acessible, but only allow users from my company to log in... via invite code, or simply have to just create the account for them buy putting in there email or something.

As for the mysql stuff... AWESOME, that looks like it worked perfectly, I just need to handle the requirements.txt so it stops trying to build all the postgres stuff... I might just try to move my code over.

**Comment by cuu508** [comment]
I had added a `REGISTRATION_OPEN` setting a while back. I think it covers this issue.

From README:

> `REGISTRATION_OPEN` controls whether site visitors can create new accounts. Set it to False if you are setting up a private healthchecks instance, but it needs to be publicly accessible (so, for example, your cloud services can send pings).
> 
> If you close new user registration, you can still selectively invite users to your team account.
>
