### ISSUE TITLE
[Question] Checking healthchecks status

### ISSUE THREAD

**Issue by Synt3x** [healthchecks/healthchecks#515]
Me and my friend is selfhosting healthchecks on our servers. Is there any URL that we could ping to check that each server is up? hc.example.com/status.

**Comment by cuu508** [comment]
Yes: `hc.example.com/api/v1/status/`

It tests the database connection (runs `SELECT 1`) and returns the string `OK` if the query works.

**Comment by Synt3x** [comment]
@cuu508, thanks for the feedback!
