### ISSUE TITLE
[QUESTION/FEATURE REQUSET] fail message and more service status

### ISSUE THREAD

**Issue by Synt3x** [healthchecks/healthchecks#516]
1) is it possible to include a message when your scripts sends request to hc.example.com/uuid/fail or just a regular ping?
2) is there anyway to add more status then just "up" ans "down"? I would like to add "up, but degraded" (yellow color).

**Comment by cuu508** [comment]
1. Yes – https://healthchecks.io/docs/attaching_logs/
2. No, Healthchecks is designed for simple binary UP / DOWN notifications. I can think of two options here:

* treat "up, but degraded" as "down". 
* use a a monitoring & alerting service where you can submit metrics datapoints and define alerts based on the data (Healthchecks is not that)

**Comment by Synt3x** [comment]
No worries, it seems like I wanted Healthchecks to be my datapoint. Glad I got those questions answered. Thanks and happy friday!
