### ISSUE TITLE
[Question] Disable authentication for all/some projects

### ISSUE THREAD

**Issue by kvsankar** [healthchecks/healthchecks#517]
This is a question. I was wondering if there is a way to disable user authentication altogether or for some projects just for read only access to the project checks page. If there is no configurable way, it would be great if any pointers can be provided to modify the code. Thanks much!

**Comment by jungle-boogie** [comment]
Have you reviewed the API?
https://healthchecks.io/docs/api/

There is a read-only key

**Comment by kvsankar** [comment]
Thanks @jungle-boogie . The read-only key would help in programmatic access. However, I am looking for a way to provide read-only UI access.

**Comment by jungle-boogie** [comment]
With the api and the referenced read only key, you could make your own web
ui to your heart’s desire.

**Comment by cuu508** [comment]
Here's an example implementation of a public dashboard that uses read-only API keys: https://github.com/healthchecks/dashboard/

In fact, you can get a link to the same public dashboard, with your read-only key filled in, in Project Settings – API Access

![image](https://user-images.githubusercontent.com/661859/119097628-a3366100-ba1d-11eb-9f2a-53172107c462.png)

**Comment by kvsankar** [comment]
Thank you, @cuu508 ! That's exactly what I was looking for - a quick way to a read-only dashboard.
