### ISSUE TITLE
[Question] HA Setup - Pings not received on one Instance

### ISSUE THREAD

**Issue by janhoelscher** [healthchecks/healthchecks#518]
I have a question about my "simple" HA setup. 

**Environment:** 
My database is managed by another team an is behind a load balancer. 
I have two application server, both are running healthchecks that connects to same database and uses same secret key. 
Both Servers running nginx as reverse proxy for instance on same server, only one at a time is reachable via a virtual IP. 

**Problem:**
When a cronjob issue a ping to healthchecks, only one instance notices this ping. The other one shows job status as down. 

**Question:**
It this "works as designed" or are there any problemes in my installation?

**Comment by cuu508** [comment]
No, this is not working as designed. Application servers are stateless. If they both connect to the same database, they should both show the same state.

> Both Servers running nginx as reverse proxy for instance on same server, only one at a time is reachable via a virtual IP.

> When a cronjob issue a ping to healthchecks, only one instance notices this ping. The other one shows job status as down.

How do you access the other application server? Where do you see the job status discrepancy – is it in the web dashboard?

**Comment by janhoelscher** [comment]
Thanks for your answer!

> How do you access the other application server?
I can access the "activ" application over virtual ip, but also allowing access per node hostename. 
E.g hostname https://cluster.dns.name/hc is 192.168.1.100 (virtual ip), https://node1.dns.name/hc is 192.168.1.101 (real ip from node1), https://node2.dns.name/hc is 192.168.1.102 (real ip from node 2). Over this naming scheme there is an user friendly name "cluser.dns.name" but also direct access to both instances for debuging. 

> Where do you see the job status discrepancy – is it in the web dashboard?
Its in the web application frontend, not in the additional html/js dashboard if thats what you mean.

**Comment by cuu508** [comment]
On the instance that is not getting updates, can you please test the following: 

* open the  list of the checks page in your browser
* look at the browser's web developer tools, Console panel – are there any JS errors?
* in web developer tools, Network panel – do you see XHR requests every 3 or so seconds?

If you refresh the list of checks page, do you get up-to-date data then? If not, how old data are you seeing? For example, if you create a new check on the active instance, would it eventually show up on the other instance?
