### ISSUE TITLE
Ability to alert when check failed X times

### ISSUE THREAD

**Issue by caleb15** [healthchecks/healthchecks#525]
We have a healthcheck that fails about once or twice a month for unrelated reasons. It would be cool if we could configure the healthcheck to require X amount of consecutive failures to send an alert, so we don't get pinged for unrelated reasons.

**Comment by alainsharemat** [comment]
+1 :)

Our app has plenty of connectors to external api that are not too reliable. Showing that there was an error in the web interface is good, We'd like to get notified after only 2 or 3 consecutive fails though. So much noise we don't notice when there is a real problem...

**Comment by ben-z** [comment]
I've been working around this by implementing fault tolerance on the client side. i.e. retry the job if it fails before sending an alerts to healthchekcs. Though my situation may be different because I'm only working with idempotent jobs.

**Comment by alainsharemat** [comment]
This is also what we ended up doing.

If an error occured, we look for the presence of a given file, if it exists we return a non zero return code and healthcheck notifies us. If it doesn't, we touch the file and return a zero return code. Like that we are notified on the second consecutive error.

This is still a workaround though. We reduced the noise, but the first error code is lost. We know that if Healthcheck turns red, there already has been an error before, but don't know what error code it was. We still would like to log every errors but be notified after a given count (or duration) of consecutive errors. Healthcheck should turn red as soon as possible, but notification should be held for some time.

**Comment by joshlopes** [comment]
Using the file idea is not bad, I suggested it to runitor lib, I guess for debug purposes we could even send the actual output but as a "success" state so it doesn't trigger the failure. This is what I think I miss the most from cronitor.

**Comment by cuu508** [comment]
I'm thinking about alternative solutions that would avoid new configuration knobs, switches and dials. 

One idea:

* have a new ping endpoint which logs the payload, but does not report success or failure (say, `/{uuid}/log`)
* rely on the grace time parameter to send "down" alerts when a job is down for too long

Example: let's say there is a program which returns non-zero exit codes, and there's no practical way to fix the underlying issue. And it's also not possible to change the program to return different exit codes depending on error type (so a wrapper could filter out non-critical errors). The wrapper script could do the following:

* If the program returns exit code 0 (success), report success (call `/{uuid}`)
* If the program returns non-zero exit code (a failure, may be a critical or a non-critical failure, we don't know), log the output but do not change check's status (call `/{uuid}/log`)
* Decide what is the maximum tolerable time window without success signals. Set the "Grace Time" parameter in Healthchecks accordingly

**Comment by cuu508** [comment]
I've implemented the `/log` endpoint: https://healthchecks.io/docs/http_api/#log-uuid

**Comment by BlackScreen** [comment]
Sorry, I have not searched correctly, so I opened the other issue.
I would still prefer a configurable solution for this. The "log" solution does - as far as I can see - currently not work with runitor (would be solveable otherwise, sure), but it does also not work when I send a "start" signal, right?

**Comment by BlackScreen** [comment]
![image](https://user-images.githubusercontent.com/17316492/195325204-f32f2796-35ce-40ee-8d46-7a4d9cca7836.png)

Just tried, so when I use start, the "log" ping does not stop the runtime. So if I want to use log, then I would only use log.
This would - unfortunately - not be solution for my case. Maybe @cuu508 can check this and find a solution. Would be great! :)

**Comment by cuu508** [comment]
I think it can work with the "start" signal. Let's look at an example:

* A job runs every 10 minutes
* Each execution takes 2 minutes
* We want to tolerate two consecutive failures. Alert only if it fails 3 or more times in a row

The setup would be:

* send a "start" signal every time the job starts
* send a "success" signal every time the job completes successfully
* send a "log" signal every time the job fails

On the Healthchecks side,

* set the period to **10 minutes**
* set the grace time to **20 minutes**

In the two consecutive failure scenario the timeline of events would be:

* 10:00 job sends the `start` signal. status=up
* 10:02 job finishes successfully, sends a normal ping. status=up. (will go down if no success in the next 30 minutes)
* 10:10 job sends the `start` signal. status=up (will go down if no success in the next 22 minutes)
* 10:12 job fails, sends the `log` signal. status=late (will go down if no success in the next 20 minutes)
* 10:20 job sends the `start` signal. status=late (will go down if no success in the next 12 minutes)
* 10:22 job fails, sends the `log` signal. status=late (will go down if no success in the next 10 minutes)
* 10:30 job sends the `start` signal. status=late (will go down if no success in the next 2 minutes)
* 10:32 job finishes successfully, sends a normal ping. status=up (just in time! For some safety margin, may be a good idea to increase the grace time a little more, to, say 25 minutes)

**Comment by BlackScreen** [comment]
Ok, then I have looked at this the wrong way. Thanks for your example. That sounds useful for my situation.
Now I just have to open a feature request at runitor to add "log" as a possible way to ping the API.
