### ISSUE TITLE
How to change Ping URL from healthchecks.example.com

### ISSUE THREAD

**Issue by bluej007** [healthchecks/healthchecks#531]
I've set SITE_ROOT to http://healthcheck.mydomain.com but the Ping URL isn't changing. What am I missing?
![image](https://user-images.githubusercontent.com/53668195/122108012-5c037c00-cde1-11eb-8f0c-331d991b9615.png)

**Comment by kamudadreieck** [comment]
You need to set the environment variable `PING_ENDPOINT` to your domain. If it is different from SITE_ROOT, this domain has to be added to `ALLOWED_HOSTS` as well. :)

Another way is to unset `PING_ENDPOINT`, then it defaults to `SITE_URL + /pings/`

https://github.com/healthchecks/healthchecks/blob/6c8b6a2a19f25eaac84e15f59c082b91ef123534/hc/settings.py#L159

**Comment by bluej007** [comment]
Ok, I added the PING_ENDPOINT environment variable and set it to http://healthcheck.mydomain.com. ALLOWED_HOSTS already has healthcheck.mydomain.com. The Ping URL still reflects https://healthchecks.example.com and any new Checks use the same URL. I then deleted PING_ENDPOINT and nothing changed.

Also, this is running as a container.

**Comment by cuu508** [comment]
@bluej007 what Dockerfile are you using?

The base URL for ping endpoints is defined in  `settings.py`:

    PING_ENDPOINT = os.getenv("PING_ENDPOINT", SITE_ROOT + "/ping/")

**Comment by cuu508** [comment]
No response, closing.
