### ISSUE TITLE
Per-check badges

### ISSUE THREAD

**Issue by kennethjor** [healthchecks/healthchecks#534]
Would it be possible to add per-check badges? Meaning a badge that doesn't cover an entire project, but each individual check.

This was discussed in https://github.com/healthchecks/healthchecks/issues/305, but the code there just seems to cover custom text.

**Comment by cuu508** [comment]
If you assign an unique tag to a check, then the badge for that tag will be effectively per-check. Would that work?

**Comment by kennethjor** [comment]
It would, but then I'd have to have a project for each one and I'd have to set up integrations for each as well, right?

**Comment by cuu508** [comment]
No, you can use a single project. If you have a check "Backup Machine A", you can assign it a tag "backup-machine-a" (as an example). If you don't use that exact tag anywhere else, then its corresponding bade will be tied to the single "Backup Machine A" check. 

To clear up possible confusion:

* You can assign tags to checks; a check can have multiple tags. When entering multiple tags, separate them with spaces.
* In the Badges page, there is a separate badge *for each tag*. Each unique tag you've used will be listed in the Badges page. There is also a project-wide badge at the end of the list.

**Comment by kennethjor** [comment]
@cuu508 Oh wow, I had no idea that was a thing. This is perfect, thank you!

**Comment by kennethjor** [comment]
If anyone stumbles across this, this was implemented in #960.
