### ISSUE TITLE
Third-Party Resources to add to the list

### ISSUE THREAD

**Issue by nicoandrade** [healthchecks/healthchecks#536]
Hi, I would like to add a new Third-Party Resource.
It is a dashboard for an easy and beautiful way to see all your checks.

![Promo](https://raw.githubusercontent.com/nicoandrade/healthchecks-front/main/public/promo.jpg "Promo")

Here is the repo, ready to use for anyone:
https://github.com/nicoandrade/healthchecks-front

Thanks!

**Comment by cuu508** [comment]
Thanks for the suggestion – added. 
The dashboard looks great!
