### ISSUE TITLE
Bug in "Monthly Report" email

### ISSUE THREAD

**Issue by sqren** [healthchecks/healthchecks#539]
Once a month I receive an email called "Monthly Report". I think the email is supposed to show the downtime for the past two months but instead it's showing the downtimes for the past month and the upcoming month. 

### Example

I received this email on the 1st of July:

<img src="https://user-images.githubusercontent.com/209966/124144784-8ebd9d80-da8c-11eb-821c-b6d15bb06bd9.png" width="600">

It looks like I didn't have any downtimes in June, and I had 1 downtime in May. But I know for a fact I had a 1 downtime in June. The website shows this correctly:

<img src="https://user-images.githubusercontent.com/209966/124144801-91b88e00-da8c-11eb-8583-dd6548f99ece.png" width="400">

Btw. thanks for this great service 👍

**Comment by cuu508** [comment]
Thanks for the report!
You are right – in the monthly report, column headers are correct, but data in the rows is off by a month. Fixed now.
