### ISSUE TITLE
Time display text in a check log

### ISSUE THREAD

**Issue by stevenmcastano** [healthchecks/healthchecks#54]
On the screen where you view the log of a check, there is a note that says:

```Note: Dates and times are displayed in UTC.```

However, my system is set to EST. I think the log view should show the timezone it's displaying in.

![screen shot 2016-04-10 at 12 58 27 pm](https://cloud.githubusercontent.com/assets/6171444/14411629/f084bf78-ff1b-11e5-9961-8a11ffa4cd67.png)

**Comment by cuu508** [comment]
On the log page, I've added an option to switch between browser's local timezone and UTC. It defaults to local timezone, so the times you see should be in relation to your computer's clock. Do you think this would solve your problem?

**Comment by stevenmcastano** [comment]
Very possible.. I've been swamped the last few days, but I'll grab the new code ASAP and test it out ASAP.

**Comment by stevenmcastano** [comment]
I just did the upgrade... sorry for the long delay. Now I see the ```UTC/Local Time``` switch and it works perfectly, that's exactly what I was looking for! Thanks again!!

You can mark this one closed!
