### ISSUE TITLE
log entries: keep last n failure entries

### ISSUE THREAD

**Issue by lukastribus** [healthchecks/healthchecks#549]
Hello,

when the log entries hit the maximum, old messages are removed.

Especially with higher frequency intervals, keeping a few of those "failure" events (which may contain important debug information's in the body) would be useful, as opposed to remove log entries solely based on the timestamp. Positive log entries are often only useful for their timestamp.

It so happens that I could have 100 positives log entries but lacking the last 2 - 3 negative log entries with debug informations in the body, and I'm really interested in the failures.

I'm not sure how this could be structured clearly without over-complicating the UI, maybe always keep the last 3 negative entries in the log?

**Comment by cuu508** [comment]
Thanks for the suggestion!

I remember Mandrill (transactional email service, now part of Mailchimp) doing something like that. They were keeping a log of last 100 successful API calls, and a separate log of last 100 failed API calls. If there are lots of API calls, the successful log may only cover a short time period, but the last 100 failures were still available in the other log. I may have the details wrong, but that was the general idea.

It's possible to do something similar in Healthchecks but it would complicate bookkeeping, and would be a nontrivial change. It could also up to double database size. For operational simplicity, it's nice to keep the database size as low as possible.

If you use Healthchecks.io, you can upgrade to a paid plan for 1000 log entry limit. If you run a self-hosted instance, you can set any log entry limit.

**Comment by lukastribus** [comment]
Hello,

the goal would certainly be to keep the total database size the same, for example keeping 95 log entries regardless of whether the type was OK or fail, and another 5 entries that failed.

But yeah, I agree that this could make things more complicated.

**Comment by lukastribus** [comment]
Currently, my cronjob runs every 10 minutes. I implemented an additional check that the OK to healthchecks is sent only once an hour, not at every cronjob run.

Now I have the problem that when the job fails (sends fail to healthchecks), I don't get an OK on the next successful run, because it only sends an OK every hour.

The cron script would have to keep track of previous failures to be able to handle this correctly. To handle this the right way on the script side, lots of complexity is needed.

**Comment by lukastribus** [comment]
I use healthchecks.io for now. I ended up maintaining state locally in case of errors, this adds complexity but it works.


    LASTFAILFILE=lastfail
    
    fail () {
     eval "$CURLCALL --data-raw \"$1\" \"$HEALTHCHECKURL/fail\""
     echo >"$LASTFAILFILE"
     exit 1
    }
    
    test || fail "error"
    
    
    # submit ok when lastfail or hourly
    if [ -f "$LASTFAILFILE" ]; then
     eval "$CURLCALL $HEALTHCHECKURL"
     rm "$LASTFAILFILE"
    elif [ `date +%M` -lt "10" ]; then
     eval "$CURLCALL $HEALTHCHECKURL"
    fi
