### ISSUE TITLE
Feature Request: Logging

### ISSUE THREAD

**Issue by stevenmcastano** [healthchecks/healthchecks#55]
I use graylog to capture all of my application logs at the debug level almost and also use it to ensure certain things are still running.

So, for instance, it looks like the "sendalerts" process has failed on my a few time, once or twice I'm not exactly sure why, the other time because the MySQL connection went away while I was doing an upgrade and I didn't notice.

Usually in graylog I would capture all the logs and baseline the rate. So I have health checks pinging a few every minute and the check for alert sending runs basically once every minute which I can see from the ```-- MARK 2016-04-29T15:28:36.779584+00:00 --``` line, I should be able to have graylog send me an alert if the rate of those lines drops below say 8 times in a given 10 minute window.

Would it be possible to add a disk logging, syslog, or even better the option to use the python logging module so I could use something like the GELF library or AMPQ GELF library and send logs direct to my local RabbitMQ server?

P.S. Awesome job on the variable in webhooks, I moved that into production today and so far my tests show that it's working perfectly. Now I've got that much LESS email clutter! Thanks!!

**Comment by cuu508** [comment]
Management commands log to console, and I think it would be nice to keep it simple like that. 
You can redirect console output to a file or pipe it into a different program. 

For example, if you run sendalerts with supervisord, you can use `stdout_logfile` setting in your supervisor configuration.
