### ISSUE TITLE
SQLite vacuum is not called after purging

### ISSUE THREAD

**Issue by OGKevin** [healthchecks/healthchecks#556]
When using SQLite as the database, and you execute one of the purging commands, a lot of records are deleted but the disk usage remains the same. 
I've just purged 1GB of data and had to manually execute [vacuum](https://www.sqlite.org/lang_vacuum.html) to reclaim the disk space.

Is there a possibility to add a check, if DB is SQLlite, to execute vacuum after the purge? Happy to make a PR.

**Comment by idsvandermolen** [comment]
@cuu508 Excellent! For reference, here's the commit https://github.com/healthchecks/healthchecks/commit/e1f51093f1cc913fc71d5507038de7787dafafae
