### ISSUE TITLE
Attach log files to email notification

### ISSUE THREAD

**Issue by ahmedsajid** [healthchecks/healthchecks#561]
First of all, this is an AWESOME Open Source project. healthckecks.io service is unbelievably smart and well thought out. I didn't think such a product/project existed :)

Now onto my request/question.

I couldn't find any doc around attaching failure logs to as an email attachment part sent as part of failure notification. This eliminates the need of logging into healthchecks.io OR logging onto the server to check the logs. Of course to perform actual fix you would have to access some sort of system but this would help as part of initial investigation phase.

Does such a thing exist or this would be a new feature?

Feel free to close this if people think that this would be an unnecessary thing.

**Comment by ahmedsajid** [comment]
I think this exists? According to @cuu508 [here](https://github.com/ahmedsajid/home-setup/issues/97#issuecomment-925848447)
If that's the case, this can be closed :)

**Comment by cuu508** [comment]
Sorry, I missed this issue. Yes – this should already work, last ping's request body is included in the alert emails.
