### ISSUE TITLE
Add clickable external link to check

### ISSUE THREAD

**Issue by mark-00** [healthchecks/healthchecks#562]
I would like to add a clickbale link to a check.   For instance to the resource that failed. It makes it easy to navigate to the place where I have to fix the problem that was the cause of the failed check

**Comment by cuu508** [comment]
You can put links in check's description.

![image](https://user-images.githubusercontent.com/661859/134391315-a5dcd478-e34f-48de-8679-32f5898aa2b5.png)

 In the check details page, they will be clickable:

![image](https://user-images.githubusercontent.com/661859/134391261-3bb565dd-dd84-4f83-97f7-f6b6c1961eb5.png)

**Comment by mark-00** [comment]
Thank you for the quick response
I will go for that solution
