### ISSUE TITLE
Shields.io Json Endpoint Broke

### ISSUE THREAD

**Issue by onezero1010101** [healthchecks/healthchecks#566]
It would appear that Sheilds.io has changed the requirement for their json endpoint.  Need to add the schemaVersion: 1 (now required, but missing from Healthchecks)  I tested the json manually, and it works, but without it shows the "Custombadge Inaccessible"

Example from their site:
{
  "schemaVersion": 1,
  "label": "hello",
  "message": "sweet world",
  "color": "orange"
}

**Comment by cuu508** [comment]
Thanks for the report!

Somehow on Healthchecks.io it seems to still work without schemaVersion. But schemaVersion is listed as a required field in shields.io docs, so I'm adding it.
