### ISSUE TITLE
Bookmarking Messages in Single Chats

### ISSUE THREAD

**Issue by Michias** [healthchecks/healthchecks#567]
I would like to be able to mark single messages in chats to view them in a bookmarks sectian of the Messenger for later use or to remind me of stuff to do or else.

Kind regards 
Michael

**Comment by cuu508** [comment]
Just to make sure I'm understanding correctly, do you want permalinks to individual received pings?

When viewing received pings, each ping would have an unique URL, say, something like `https://healthchecks.io/checks/1e1fbf8f-c27e-4349-af44-0c85461bdd19/pings/131382/` which opens a standalone page with the ping details?

**Comment by cuu508** [comment]
No response, closing.
