### ISSUE TITLE
Cron output

### ISSUE THREAD

**Issue by szepeviktor** [healthchecks/healthchecks#57]
Hello!

This is a very nice project.
Have you been thinking about receiving script output?
```bash
./my-backup-script.sh > output.file 2>&1 || curl -X POST -d @output.file https://hchk.io/**************
```

All the best!

**Comment by diwu1989** [comment]
that would mean hchk has to allocate some storage space for each ping
if you are trying to store the output, can you just pipe the output into a s3 bucket with the latest run's timestamp as the name?

s3 is a much more proper storage mechanism than relying on healthcheck to keep track of pings + store run outputs

**Comment by szepeviktor** [comment]
Thank you.

**Comment by cuu508** [comment]
You can also look into hosted log aggregation services like Loggly, Papertrail, Splunk, SumoLogic.

**Comment by szepeviktor** [comment]
Currently testing Papertrail...
