### ISSUE TITLE
Support for logs larger than 10kb?

### ISSUE THREAD

**Issue by cysea** [healthchecks/healthchecks#571]
Hi,

I'm using the self-hosted implementation with runitor on debian and I got some rsync logs which go over 10kb, cutting of the beginning and only keeping the last 10kb.

Yes, I have the logs saved locally, but they're easier to access by date with your cool web UI. Was just wondering if it's possible at all to store logs larger than 10kb, even if it's "hacky"?

**Comment by cysea** [comment]
I should read .env files, sorry.

**Comment by sr7142x** [comment]
Adding to @cysea, for the future reference - the env. variable is **PING_BODY_LIMIT** and the default value is set to 10 000 bytes(10KB as mentioned in the docs).
