### ISSUE TITLE
Increase log length

### ISSUE THREAD

**Issue by caleb15** [healthchecks/healthchecks#572]
I have a healthcheck that is pinged every minute. There were some failures last night so I checked the log to see if I needed to up the grace period but the log only went back to the start of today. If the log length could be increased to 5760 entries (the number of minutes in two days times two, because there's a started and ok event) then that would be great.

**Comment by cuu508** [comment]
On self-hosted instance, you can set the number of stored pings per check to an arbitrary value. In Django admin / Profiles look up the profile and change the "Ping log limit" field. Note that Healthchecks does not use pagination when viewing logs, they are all loaded in a single page. So if you set a too high value (say, 100'000+), both the server and your browser will start to struggle to load them all.

To increase the limit on the hosted service, https://healthchecks.io, there would be supporting changes needed. Pings are stored in postgres, they may need to be moved out to keep the database size down. May need pagination / filtering / search when viewing logs. 

A possible workaround is to also store logs on the server being monitored. You will have X most recent logs in Healthchecks, and for older logs you would look them up on the server.

**Comment by caleb15** [comment]
We're paying for the hosted service. We also store cron runs as APM traces as well as logs in datadog, but it would be nice to have it in healthchecks too.

**Comment by cuu508** [comment]
Related: #609

**Comment by caleb15** [comment]
Thanks!
