### ISSUE TITLE
Not possible to install Apprise with default user in docker

### ISSUE THREAD

**Issue by Akruidenberg** [healthchecks/healthchecks#581]
When running the docker container with the default user, it is not possible to install Apprise because of permissions. Only the root user can install it.

Also, when recreate the container, Apprise is not installed anymore.

A better solution would be install Apprise when creating the container. Maybe APPRISE=1 as env?

Thanks in advance!

**Comment by Akruidenberg** [comment]
When is the updated docker image released?

**Comment by cuu508** [comment]
A new docker image gets [automatically built and published](https://github.com/healthchecks/healthchecks/blob/master/.github/workflows/publish_docker_image.yml) on every release. I release a new version when there is a substantial amount of changes, usually every 1-2 months.
