### ISSUE TITLE
cloaked notification URL showing an error

### ISSUE THREAD

**Issue by GhaziTriki** [healthchecks/healthchecks#582]
I have healthchecks installed behind nginx reverse proxy. When I get notifications I get `https://domain/cloaked/check-id` but the URL does not redirect to anywhere.

**Comment by cuu508** [comment]
Is your `SITE_ROOT` setting correct?

When you open "https://domain/cloaked/check-id" in the browser – what HTTP response code do you get and what is in the response body?

Does the `https://domain/` portion of the URL look the way you expect? Is it the same when you browse Healthchecks web UI normally? Is scheme, domain, port, subdirectory (if any) the same?

**Comment by GhaziTriki** [comment]
For the "domain/cloaked/check-id" I get 404 HTTP status. I am behind nginx.

**Comment by cuu508** [comment]
Is your `SITE_ROOT` setting correct?

Does the `https://domain/` portion of the URL look the way you expect? Does it look the same when you browse Healthchecks web UI normally? Is scheme, domain, port, subdirectory (if any) the same?

**Comment by GhaziTriki** [comment]
Here is my `local_settings.py` (I changed passwords and domains)

```python
SECRET_KEY="54qs5d1qs6ds15qd5qsd"
DEBUG=False
ALLOWED_HOSTS=["hc.mycompany.net"]
DEFAULT_FROM_EMAIL="hc@mycompany.net"
SUPPORT_EMAIL="devops@mycompany.net"
REGISTRATION_OPEN=False
DB="postgres"
COMPRESS_ENABLED=True

# You can switch database engine to postgres or mysql using environment
# variable 'DB'. Travis CI does this.
DATABASES={
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": "127.0.0.1",
        "PORT": "5432",
        "NAME": "health_checks",
        "USER": "health_checks",
        "PASSWORD": "54qs5d1qs6ds15qd5qsd",
        "CONN_MAX_AGE": 0,
        "TEST": {"CHARSET": "UTF8"},
        "OPTIONS": {
            "sslmode": "disable",
            "target_session_attrs": "read-write"
        }
    }
}

USE_TZ=True
TIME_ZONE="Africa/Tunis"

SITE_ROOT="https://hc.mycompany.net"
SITE_NAME="RIADVICE Infrastructure Jobs Health Checks"
SITE_LOGO_URL="https://riadvice.tn/wp-content/uploads/2021/03/sticky_logo_retina.png"

PING_ENDPOINT="https://hc.mycompany.net/ping/"
PING_EMAIL_DOMAIN="hc.mycompany.net"

# SMTP credentials for sending email
EMAIL_HOST="mail.mycompany.net"
EMAIL_PORT="25"
EMAIL_HOST_USER="riadvice/riadvice-net"
EMAIL_HOST_PASSWORD="54qs5d1qs6ds15qd5qsd"
EMAIL_USE_TLS="True"
EMAIL_USE_VERIFICATION=True

# Zulip
ZULIP_ENABLED=True
```

And my nginx config

```nginx
upstream hc {
    server 127.0.0.1:18800;
    keepalive 64;
}

server {
   listen 443 ssl http2;
   listen [::]:443 ssl http2;

   # the virtual host name of this subfolder should be exposed
   server_name hc.mycompany.net;
   
   	# SSL
	include snippets/ssl-mycompany.net.conf;
	include snippets/ssl-params.conf;

	# logging
	access_log /var/log/nginx/hc.access.log;
	error_log /var/log/nginx/hc.error.log warn;


    location / {
	include nginxconfig.io/proxy.conf;
        proxy_pass http://hc;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store on;
    }
}

# HTTP redirect
server {
	listen 80 http2;
	listen [::]:80 http2;

	server_name hc.mycompany.net;

	return 301 https://$server_name$request_uri; #redirect HTTP to HTTPS
}
```

**Comment by cuu508** [comment]
Thanks for the details!

The SITE_ROOT setting looks good. Assuming the 404 is returned by a Django, not earlier by URL dispatcher or by nginx, I can think of two possible causes:

* the cloaked URL is for a check that does not exist any more
* you are logged in hc.mycompany.net as user A, but the check belongs to user B

Can you please test the following:

* log into hc.mycompany.net, pick any check and navigate to its details page
* generate an alert for it by making a HTTP request to the check's ping URL + `/fail` 
* when you receive the new alert, click on the cloaked URL, see if it returns 404

**Comment by GhaziTriki** [comment]
@cuu508 The config you deleted can be kept without any issue. I am checking what you mentioned.

**Comment by GhaziTriki** [comment]
I have failing job that forward me to https://mycompany.net/checks/3e06fbd6-b60d-474c-82e1-47af10fa8010/details/

Is that the right behaviour?

**Comment by cuu508** [comment]
No updates, closing.
