### ISSUE TITLE
Improve Zulip notifications

### ISSUE THREAD

**Issue by GhaziTriki** [healthchecks/healthchecks#583]
Hello,

I would be good to improve Zulip notifications by adding the the ability to select the topic. As example we might have a checkbox "Automatic Topic" or if unchecked it will uncover the self-defined topic which is "alerts" in our case.

**Comment by cuu508** [comment]
Thanks for the suggestion. The Zulip integration currently generates topics in the form:

* [check name] is UP
* [check name] is DOWN

I want to make sure I understand the suggestion.

With "Automatic Topic" checked, the integration would work the same as currently, and use topics in one of the two above forms.
With "Automatic Topic" unchecked, the user would see a field to override the topic to a custom value, say, "alerts".

Is that correct?

**Comment by GhaziTriki** [comment]
Hi @cuu508,

Let me explain the perspective of this issue. Currently we have about 150 "HC" tied to our Jenkins Jobs. The problem is that for every "hc" job we have 2 topics, on for UP and one for DOWN.

To compare it with what we have done with Zabbix, all zabbix notifications goes to the "alerts" topic. So instead of having 2x number of jobs as topics, we would have a single one were it is easier visually follow issues and search for history of a single item since searching in a single topic is visually better.

To avoid complaints from users having 2 topics per HC job; UP and DOWN; it would be possible to configure using a single topic named by the HC job owner.

Here is what we have visually now

![image](https://user-images.githubusercontent.com/4991088/194544522-9b28af41-503c-4c38-9f02-35a57c487c0f.png)

**Comment by GhaziTriki** [comment]
Hi @cuu508,

It looks perfect !! No question is stupid !

Indeed Topics are only relevant in Streams https://zulip.com/help/streams-and-topics but not in private messages https://zulip.com/help/private-messages

I am leaving a small doc here for people who wants to use the custom topic, they just need to move old messages to that new topic, empty topics will be automatically removed.

**Comment by cuu508** [comment]
@GhaziTriki I've now deployed this change to Healthchecks.io.
