### ISSUE TITLE
block non trusted users to join

### ISSUE THREAD

**Issue by vipin5050** [healthchecks/healthchecks#586]
Hi,

I create a private instance of healthcheck and all is working fine though I have one issue. Any user from internet can join of they know the login page. How do I block user to join which are not part of my company. let's all my company email address are john@xyz.com then only people have email addresses in xyz.com should be able to join. if they put any non xyz.com address then it should not allow.
any setting for this would be great.

**Comment by cuu508** [comment]
Healthchecks reads `REGISTRATION_OPEN` environment variable, you can set it to `False` to disable signups:
https://healthchecks.io/docs/self_hosted_configuration/#REGISTRATION_OPEN

This of course disables signups for @xyz.com addresses as well. But you can still invite users into your projects from project's Settings page.
