### ISSUE TITLE
Some errors CentOS 6

### ISSUE THREAD

**Issue by tchraibi** [healthchecks/healthchecks#59]
Hello guy, 

I try to install your amazing project, but have some issue.

Do you have any requirement to install all needed packages with dependencies ? Do i need to use a sort of linux distribution?

Do you think that we can have a docker version of your application ?

Regards

**Comment by cuu508** [comment]
Hello,

can you say specifically what issues did you run into? Did you install requirements listed in `requirements.txt`?

Yes, it's possible to run this in docker container(s). We don't have instructions for doing that though. If you go ahead with it, you're very welcome to contribute the instructions.
