### ISSUE TITLE
prunepings missing in 1.24.1?

### ISSUE THREAD

**Issue by poblabs** [healthchecks/healthchecks#591]
Hi there, I've recently upgraded my docker container to 1.24.1, and noticed that in manage.py prunepings is missing. The [docs still contain](https://healthchecks.io/docs/self_hosted/) it as a way to perform database cleanup. 

Has that changed? Thanks!

**Comment by poblabs** [comment]
Just found this comment, which explains why it's missing. https://github.com/healthchecks/healthchecks/issues/556#issuecomment-948528834

I have a new question based on that; do I still need to vacuum the database or is that also automated within healthchecks?

**Comment by cuu508** [comment]
I forgot to update the selfhosted docs when I was removing the prunepings management command – thanks for pointing that out, fixed now!

> do I still need to vacuum the database or is that also automated within healthchecks?

Healthchecks does not run db vacuum automatically.
