### ISSUE TITLE
Telegram Channel Support

### ISSUE THREAD

**Issue by AuroraDysis** [healthchecks/healthchecks#592]
Now the telegram bot can only send messages to users or groups, but I want to post the message to the channel.

**Comment by cuu508** [comment]
Thanks for the report, @AuroraDysis!

I've added support for Telegram channels, and updated https://healthchecks.io – feel free to try it out!

Note that unlike groups, in channels the bot receives all messages sent to the group (looks like that's how bots work in channels – see [FAQ](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get)). The bot looks for messages that contain "/start" and ignores all other messages.

**Comment by AuroraDysis** [comment]
Awesome. Thank you very much!
