### ISSUE TITLE
Be able to setup/register a user account

### ISSUE THREAD

**Issue by CameronBanga** [healthchecks/healthchecks#6]
Or at minimum, let me tie two emails to a single account.

I signed up using my work email, because it made sense. But it sometimes can take 10-20 minutes for my work email address to process emails (we have a weird server set up that pulls it to a gmail instance for me).

So anytime I want to log into the site, I put in my email. Then wait 10 minutes. It's a pain, and a username/password would be much much much easier.

**Comment by cuu508** [comment]
Idea behind login links was to save the hassle of setting up another account for users, and the work of implementing the usual signup / password storage / forgot password bits in the app. Login links avoid some of that.

Refreshing inbox and fishing for the correct email with link is of course annoying, if required to be done often. I think it would be less of an issue if you only needed to log in every few months–you would be already logged in most of the time.

In the long run it might make a sense to set up more traditional user account creation, and implement team access. In short term, would it help to increase cookie expiration times so you stay logged in for longer?

**Comment by CameronBanga** [comment]
Team access is another great reason why this would be helpful. We have a team of three. We do have a shared email, I guess I could have used that, but didn't think about it when signing up.

Longer tokens would help a lot. Not sure what expiration is now, but been using a week and had to log in a couple times.
