### ISSUE TITLE
Add donation link

### ISSUE THREAD

**Issue by user8446** [healthchecks/healthchecks#605]
Hi,

I think it would be great if there was a donation link for the community to contribute if they are unable to help with code or to say thank you by buying those coffees.

Thank you for the development of healthchecks!

**Comment by cuu508** [comment]
Thanks, this is a really nice issue to see :-)

There is a $5/mo "Supporter" plan on https://healthchecks.io, which I added to provide a way to donate. Was very pleasantly surprised that people do sign up for this plan! 

I'll see if I can set up a similar GitHub Sponsors tier as an alternative.

**Comment by user8446** [comment]
Hi, I think an additional GitHub sponsors, Liberapay, Ko-fi, Open collective, etc. would be great as well for those that either don't need the subscription (setting up their own) or want to make a one-time donation.

**Comment by daviddavis** [comment]
👍 to this. I don't need a subscription but would make a one-time donation.
