### ISSUE TITLE
unnecessary html escaping in pushover title

### ISSUE THREAD

**Issue by lukastribus** [healthchecks/healthchecks#606]
A check with a `>` character in the name is correctly displayed in the pushover message, but unnecessarily escaped in the title:

![grafik](https://user-images.githubusercontent.com/15380567/152249534-1e60e79b-04d5-40a3-93fe-d0f5aeb00110.png)

Pushover itself works just fine:

![grafik](https://user-images.githubusercontent.com/15380567/152233908-07bf3729-04ce-4997-ac21-a904d504b6e9.png)

![grafik](https://user-images.githubusercontent.com/15380567/152233930-b99d6f50-8474-4a19-a264-f8c1e84784b6.png)

![grafik](https://user-images.githubusercontent.com/15380567/152234043-5a4cd0d6-2012-4cc0-9640-cf51276dcc05.png)

**Comment by cuu508** [comment]
Thanks for the report @lukastribus! Yes, Healthchecks was escaping special characters where it should not have. Fixed, and fix deployed!

I'm also in process of testing all the other integrations – already fixed the same issue for PagerDuty, Spike.sh, Pushbullet, LINE Notify, and there's more to come...

**Comment by lukastribus** [comment]
Thank you!
