### ISSUE TITLE
lowercase the ping received

### ISSUE THREAD

**Issue by audioscavenger** [healthchecks/healthchecks#607]
## feature request
lowercase the ping received

## rationale
it's difficult using msdos or powershell only, and also for convenience. why does the case matter in the first place?

**Comment by audioscavenger** [comment]
i can do a PR but after 20mn of searching for where the http listener is, i gave up

**Comment by cuu508** [comment]
> lowercase the ping received

Hi @audioscavenger – what do you mean by this precisely?

**Comment by cuu508** [comment]
No reply, closing.
