### ISSUE TITLE
Adding project doesn't work

### ISSUE THREAD

**Issue by rafaelorafaelo** [healthchecks/healthchecks#608]
Hi,
I installed healthchecks v1.25.0 as Docker instance from https://hub.docker.com/r/linuxserver/healthchecks. I can't add new project, the result is a Server Error (500) in the browser. I tried sqlite and postgres as database with the same result. With PostgreSQL server I see this error message:
```
FEHLER:  NULL-Wert in Spalte »owner_id« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (2, 5be737bc-16f6-4f99-9899-4f3500230e62, testproject, , , null, 1233456, null, f).
ANWEISUNG:  INSERT INTO "accounts_project" ("code", "name", "owner_id", "api_key", "api_key_readonly", "badge_key", "ping_key", "show_slugs") VALUES ('5be737bc-16f6-4f99-9899-4f3500230e62'::uuid, E'testproject', NULL, E'', E'', E'1233456', NULL, false) RETURNING "accounts_project"."id"
```

There is a missing owner_id in the SQL statement. In Healthchecks I see a dash as owner on the Add project page. Looks like it should be the current username as shown in the Default Project.

Regards
Ralf

**Comment by cuu508** [comment]
Hi @rafaelorafaelo – are you adding the project through Django admin?

**Comment by rafaelorafaelo** [comment]
Hi, what is Django admin, some kind of CLI? No, I add the project through this URL http://abc:8080/admin/accounts/project/add/

**Comment by rafaelorafaelo** [comment]
Hi, the problem is the Site Administration page under /admin/. If I add a project with the new project wizard on the homepage, everything works. Adding a project via Site Administration fails.

**Comment by cuu508** [comment]
> If I add a project with the new project wizard on the homepage, everything works. 

That's the correct way to add a project.

> Adding a project via Site Administration fails.

Don't use the admin interface for normal operations (creating projects, creating checks, creating integrations etc.). 

> In Healthchecks I see a dash as owner on the Add project page.

I've marked the field as read-only in the admin ([here](https://github.com/healthchecks/healthchecks/blob/master/hc/accounts/admin.py#L174)). This field normally renders as a dropdown control with all possible owners (all users in the system). This would slow things down if there are many users, and marking the field as read-only was a quick, simple fix.

**Comment by rafaelorafaelo** [comment]
Thank's, I got it. Great tool. I've been dreaming of this for years.
