### ISSUE TITLE
[Self-hosted] How to configure healthchecks.io in a multi-instances mode

### ISSUE THREAD

**Issue by tizard34** [healthchecks/healthchecks#610]
We have deployed Healthchecks.io in a kubernetes platform. The application is running in 2 instances (load-balanced).

When a check is down (The ping /fail is sent), we are receiving 1 notification.
When a check is down because it's to late, we sometimes feel like we get 2 notifications.

Is there a specific configuration that would allow Healthchecks.io to work in multi-instance mode ?

**Comment by cuu508** [comment]
Do both instances use the same database?

**Comment by tizard34** [comment]
@cuu508  yes of course
Are you insinuating that the sending of duplicate notifications is not related to the number of instances?

**Comment by cuu508** [comment]
Running multiple instances should not cause duplicate notifications, unless there's a  bug. 

> When a check is down because it's to late, we sometimes feel like we get 2 notifications.

Do you see the duplicate outgoing notifications in web UI, check's details page, Log section?

The sendalerts management command writes a log of sent notifications to stdout – can you see duplicate outgoing notifications in sendalerts logs?

**Comment by cuu508** [comment]
Healthchecks posts the notification by making a HTTP request to MS Teams incoming webhook address.
If a HTTP request fails, the request is retried 2 more times. The following conditions count as failures:

* the remote server responds with a non-2xx status code
* the request times out (timeout is 10 seconds)
* connection is refused

So in theory the following scenario is possible:

* Healthchecks makes a request to MS Teams 
* MS Teams accepts the request, posts the message in chat, but takes 15 seconds to send a HTTP response back
* After 10 seconds Healthchecks concludes the request has timed out, and retries the same request again
* MS Teams accepts the repeated request, posts a duplicate message

I don't know if that's what's happening here, but it's a possibility.
