### ISSUE TITLE
Integration Disabled

### ISSUE THREAD

**Issue by lettore** [healthchecks/healthchecks#613]
Hello,
I'm using the webook integration for Mattermost, I don't know why because I can't see any error, but happens after sometimes that I don't receive any messages and when I go to integrations page I see the mattermost integration is disabled.
If I do test I receive the message, but I don't get any messages from alarms.
The only way I can resolve is to delete and recreate the integration.

**Comment by lettore** [comment]
I see, this happens because sometimes the Mattermost server is down. You
can understand that disabling a notification channel without any advice is
not the best way to deal with such problem. It would be possible at least
to re-enable it when a test is successful? The best it would be to have the
choice to decide if enable such behavior, because I think it's not totally
wanted in most scenarios.

Il Mer 2 Mar 2022, 07:33 Pēteris Caune ***@***.***> ha
scritto:

**Comment by cuu508** [comment]
Thanks for the feedback! I've now split apart the Slack and Mattermost notification delivery logic, which was previously shared. For Slack integrations, 404 will still be treated as a permanent failure, and the integration will be marked as disabled. For Mattermost integrations, 404 will now be treated as a transient failure, and the integration will *not* be marked as disabled.

**Comment by lettore** [comment]
Amazing, thank you

Il giorno mer 9 mar 2022 alle ore 09:15 Pēteris Caune <
***@***.***> ha scritto:
