### ISSUE TITLE
Build problem with 1.25.0

### ISSUE THREAD

**Issue by SuperSandro2000** [healthchecks/healthchecks#615]
I am facing some build issues which is fixed on the latest master.

``Compressing... CommandError: An error occurred during rendering integrations/add_spike.html: [Errno 2] No such file or directory: '/app/static-collected/CACHE/js/output.b4ba48ed4f66.js'``

I think tagging a new version would be already enough to fix this because it works on latest master.

**Comment by cuu508** [comment]
For the failing build, what is your installed django-compressor version (what does pip freeze say?)?

**Comment by cuu508** [comment]
Ah, I can reproduce it:

```
$ export DEBUG=True
$ ./manage.py compress --force
CommandError: An error occurred during rendering integrations/webhook_form.html: [Errno 2] No such file or directory: '/home/cepe/Downloads/healthchecks-1.25.0/static-collected/CACHE/js/output.b4ba48ed4f66.js'
```

I suspect it's a bug in django-compressor, it is non-deterministic, and it could resurface again. There's a potentially related bug being worked on (https://github.com/django-compressor/django-compressor/issues/1099). Once that's fixed, I'll check if I can still reproduce this one.

**Comment by SuperSandro2000** [comment]
> For the failing build, what is your installed django-compressor version (what does pip freeze say?)?

I am building in [docker](https://github.com/SuperSandro2000/docker-images/blob/master/healthchecks/Dockerfile) and basically cloning the project and then do ``pip install -r requirements.txt`` which means I would have `django-compressor==3.0`.

> Ah, I can reproduce it

Great! Thank you so much.

**Comment by cuu508** [comment]
This might work as a workaround – replace https://github.com/SuperSandro2000/docker-images/blob/master/healthchecks/Dockerfile#L95 with

    && DEBUG=False /app/manage.py compress

**Comment by SuperSandro2000** [comment]
That did the trick for now. Thanks
