### ISSUE TITLE
Webhook integration works but does not send alerts automatically

### ISSUE THREAD

**Issue by retifrav** [healthchecks/healthchecks#618]
I have a Webhook integration (Telegram):

![healthchecks-telegram-webhook](https://user-images.githubusercontent.com/6904927/157859241-7ba9269f-3a99-4261-ad02-a7c4bebea808.png)

and I've managed to set it up correctly - when I click on `Test` button, the request is sent and I receive it in Telegram:

![healthchecks-telegram-messages](https://user-images.githubusercontent.com/6904927/157859218-6680ad03-d766-40ac-8419-1501794f0825.png)

So it works.

But it doesn't send alerts when the checks go down or up, although this integration is selected in Notification Methods of those checks and is set to `ON`:

![healthchecks-telegram-integration](https://user-images.githubusercontent.com/6904927/157859986-b72da08d-d42e-400b-93d9-f0b3c44b131b.png)

So I guess there might be a bug somewhere in the triggering mechanism, because of which the notification doesn't even attempt to send. There are no errors in the UI, the integration status is "Ready to deliver" and the Last Notification shows the one I sent manually with `Test` button.

Can I perhaps enable some logging to catch that?

My environment:

- Ubuntu 20.04.4
- self-hosted Healthchecks v1.25.0 (not in Docker)
- ran by uWSGI v2.0.20 behind NGINX

**Comment by cuu508** [comment]
Is the `sendalerts` management command running?

**Comment by retifrav** [comment]
Oooh, that might be it. Pardon my ignorance, I'm still getting familiar with running Django applications with uWSGI, so I might have missed something.

Here's my `.ini` file for uWSGI:

``` ini
[uwsgi]
module = hc.wsgi:application

master = true
processes = 5
threads = 10

socket = wsgi.sock
chmod-socket = 664

vacuum = true
die-on-term = true
```

Is setting `module = hc.wsgi:application` enough to run "everything", or do I need one more service to run `./manage.py sendalerts`?

**Comment by cuu508** [comment]
Running "hc.wsgi:application" does not start the `sendalerts` process, it needs to be started separately.

You can do that with uwsgi, using the `attach-daemon` directive. Example: https://github.com/healthchecks/healthchecks/blob/master/docker/uwsgi.ini 

Or you can run sendalerts as a systemd service. It's more work to setup, but has more flexibility, for example you can restart the web process independently from the `sendalerts` process.

**Comment by retifrav** [comment]
Right, I've just run in "manually" from shell, and immediately received my pending notification. I'll figure out the rest, how to run it as a service, thank you!
