### ISSUE TITLE
Shields.io JSON endpoint

### ISSUE THREAD

**Issue by mircotroue** [healthchecks/healthchecks#621]
The shields.io functionality seems to be broken in the selfhosted version of healthchecks. A correctly formatted json response is generated at the provided URL, however, testing of the endpoint of shield.io yields a "custom badge | inaccessible" error.

![](https://img.shields.io/endpoint?url=https://troue.xyz/badge/f270f094-afd0-4fbf-b415-e5eae2/lMU_sPrH-2.shields)

**Comment by cuu508** [comment]
Looks like shields.io returns "inaccessible" if the data endpoint returns HTTP status code >= 500. 

Example: https://img.shields.io/endpoint?url=https://statuscod.es/500

Perhaps there are more conditions when it returns "inaccessible", I'm not sure.

Can you check in your server's access logs to see what the HTTP status codes are for requests initiated by shields.io?

**Comment by mircotroue** [comment]
Performing a call on the badge URL from healthchecks results in a 200 (OK) status. Directly calling the shields.io URL does not produce any entry in my nginx access log. Therefore I believe that this a problem on the shield server side and that no GET request is actually performed. This might be due to an SSL problem.
