### ISSUE TITLE
Ongoing reminders to notification email

### ISSUE THREAD

**Issue by singpolyma** [healthchecks/healthchecks#625]
So it seems that notifications go to a configured email address from the integrations, but ongoing reminders go to my account email.  It seems uhintuitive that these reminders can only go by email and only to my account email, not my configured alert address.

**Comment by cuu508** [comment]
Here's an UI mockup with checkboxes that let the user select which configured notification channels to use for ongoing reminders:

![image](https://user-images.githubusercontent.com/661859/183888897-1dc25ece-faed-4773-a8ac-ca11e959cd7a.png)

Only few specific types of channels would show up here – email, Slack, perhaps a few others. 

What do you think, would this make sense to you?

**Comment by cuu508** [comment]
The notification integrations, including the email integration, notify on check state changes ("up" -> "down", and "down" -> "up"). They do not notify you about any account-level events (weekly or monthly reports, reminders about some checks still being down, warnings about running out of SMS quota, confirmation codes for sensitive actions, etc.)

>  It seems uhintuitive that these reminders can only go by email and only to my account email, not my configured alert address.

If you want to receive ongoing email reminders about checks still being down to multiple addresses, you can accomplish this by inviting more people to the project. If a user has enabled ongoing reminders, and has access to a project, they will the ongoing reminders about the project, even if they are not the project's owner.
