### ISSUE TITLE
[Bug] Status Badges > Overall Status - Texto cortado da Imagem

### ISSUE THREAD

**Issue by gui-angelo** [healthchecks/healthchecks#629]
Na aba Badges, ao criar uma tag, a imagem do badge fica cortado conforme o anexo.

Este problema tem prazo para solução?

![text-completo](https://user-images.githubusercontent.com/66852753/161122181-7c65e1c6-c355-40e3-bb10-946a0f530590.png)
![bug-text](https://user-images.githubusercontent.com/66852753/161122188-41ad67d9-4371-4133-a453-1a62b731cfe2.png)
![bug-text](https://user-images.githubusercontent.com/66852753/161123079-bef3a53f-500a-4d93-b65c-b71d8a75ade6.png)

**Comment by gui-angelo** [comment]
Sim, tenho este SVG
https://healthchecks.grupolinsferrao.com.br/badge/11a864e5-c7de-4d03-b5f0-89b7e8/pP7gAmE0-2.svg

**Comment by gui-angelo** [comment]
Segue SVG gerado

![pP7gAmE0-2](https://user-images.githubusercontent.com/66852753/161265616-64b833ff-875e-4e63-a647-e604e65be89b.svg)

**Comment by cuu508** [comment]
Thanks, having a look at it now...
