### ISSUE TITLE
Copy icon

### ISSUE THREAD

**Issue by szepeviktor** [healthchecks/healthchecks#63]
Please consider using
http://fontawesome.io/icon/clipboard/

**Comment by cuu508** [comment]
Thanks for the suggestion!
When adding the "copy" link, I also tried using the button+icon, GitHub style. I think the clipboard icon works well when working with <input type="text"> elements–you can combine the text box and the button together. For an isolated text on a page, a "copy" link looked cleaner to me.

**Comment by szepeviktor** [comment]
OK
