### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by SrilakshmiDoma14** [healthchecks/healthchecks#634]
Hi,

I'm running healthchecks on a docker container. I installed docker and docker compose on an ec2 server and running the health checks as a service. I also added a dns url through nginx. On trying to login, I'm getting `CSRF verification failed. Request aborted`
Any help would be appreciated!!
Also where should I check the error logs.
Thanks in advance

**Comment by SrilakshmiDoma14** [comment]
able to resolve the issue

**Comment by issmirnov** [comment]
Can you explain how you resolved this?

Otherwise: https://xkcd.com/979/

**Comment by jonasjancarik** [comment]
> Can you explain how you resolved this?

So I don't know about OP, but in my case, the first thing I did was I set `DEBUG` to `True` to see more details of the errors.

I am serving Healthchecks on `healthchecks.localhost:1111` and the service itself is listening on `localhost:7832`.

Mostly through trial and error, I got working with

**Comment by m-ocean-it** [comment]
Here's how my `/location` block looks like after I'd solved that issue:
```
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Ssl https;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass_header X-CSRFToken;
        proxy_pass http://100.88.104.117:9000;
    }
```
I bet some of those lines are redundant, but, well, it works and thanks for that.
