### ISSUE TITLE
Slack integration returns 404

### ISSUE THREAD

**Issue by Firesphere** [healthchecks/healthchecks#635]
When clicking the button to add a Slack integration, a 404 is returned.

**Comment by cuu508** [comment]
Are you seeing this on healthchecks.io or on a self-hosted instance?

**Comment by Firesphere** [comment]
This is on a self-hosted test, Docker container.

I've entered the slack Client ID and Secret in the `.env`, but I can't seem to find anything in the logs that would indicate what's going wrong

**Comment by cuu508** [comment]
Which URL is returning 404?

**Comment by Firesphere** [comment]
`/projects/{project-id}/add_slack_btn`

**Comment by cuu508** [comment]
OK, interesting 😬
Just to make sure, are the steps to reproduce:

* you are on the "Integrations" page (`/projects/{project-id}/integrations)
* you click on "Add Integration" next to Slack
* the browser navigates to `/projects/{project-id}/add_slack_btn` which returns 404?

What docker image are you using? What Healthchecks version are you using?

**Comment by Firesphere** [comment]
Yes, correct.

Healthchecks 2.0.1

**Comment by Firesphere** [comment]
My Slack ID and Secret are in the `.env` file:
```
SLACK_CLIENT_ID=123456789.1987654321
SLACK_CLIENT_SECRET=6516813516384dcg8464681638
SLACK_ENABLED=True
```
(Those are not my actual, nor are they valid, credentials, but in my env, they are, of course)

**Comment by Firesphere** [comment]
This is the error in the logs when I don't run docker as a daemon:
`docker-web-1  | [pid: 11|app: 0|req: 4/11] 172.19.0.1 () {60 vars in 1543 bytes} [Mon Apr 11 23:19:03 2022] GET /projects/47c54b36-1181-4291-8d14-7ab10b416e76/add_slack_btn/ => generated 0 bytes in 20 msecs (HTTP/1.1 404) 8 headers in 265 bytes (1 switches on core 0)`

**Comment by Firesphere** [comment]
Update!

A workaround that _does_ work, surprisingly, is opening the link with middle-click (open in new tab). By doing that, everything seems to work just fine.

Which... is odd, but maybe a lead?

**Comment by Firesphere** [comment]
- Copy-pasting the link works
- An extension... maybe? I'll have to see what I can test tomorrow (it's 9.30 PM here)
- `integrations/add_slack` shows an information page about slack
- Dev tools only shows
```
None of the “sha512” hashes in the integrity attribute match the content of the subresource.
```

**Comment by Firesphere** [comment]
Hmmm, turns out that _none_ of the integrations work... Although I got Slack to work, all others give a white page error 404 as well...

Might be something to do with the routing?

**Comment by cuu508** [comment]
Please make screenshots of Chrome Developer Tools showing 1) a successful and 2) a 404 request, showing all request and response headers. Like so:

![image](https://user-images.githubusercontent.com/661859/163324434-32368d1e-06d6-4307-b801-7de90e2c2e73.png)

**Comment by Firesphere** [comment]
![healthchecks-failure](https://user-images.githubusercontent.com/680570/163698801-7cfab992-863c-45f5-aeb3-3e2820af2008.png)
![healthchecks-success](https://user-images.githubusercontent.com/680570/163698805-486decea-4c70-478a-aebe-0a3823f97e49.png)

Here you go

**Comment by cuu508** [comment]
Thanks for all the information!

Unfortunately I still have no clue what precisely is going wrong, but my hunch is that your browser is hitting several instances of the Healthchecks app running with different configuration. For example, if you have multiple load balanced web servers, perhaps one of the servers has old configuration. 

Can you reproduce the issue if you run the Docker image locally, on localhost:8000 with no Cloudflare in the mix?

If yes, can you make a minimal reproducible example (a Dockerfile and a command to run it) that demonstrates the issue?

**Comment by schambers** [comment]
I am also experiencing the same issue after installing on a local docker host. Here are screenshots of network in chrome dev tools:

Many of the integrations do this (slack, discord, pushover) although some seem to work fine (microsoft teams, email)

Please let me know if I can provide any more details. I'm hosting healthchecks on a docker host and am maintaing the docker containers via portainer. I started the docker container according to the directions here: https://healthchecks.io/docs/self_hosted_docker/

![network-healthchecks-docker](https://user-images.githubusercontent.com/31563/164874474-7f053386-c591-4997-b83e-eed809ce649f.PNG)

**Comment by schambers** [comment]
Just saw your previous comment. Attached is the docker-compose.yml that I'm using to start up healthchecks web/db containers on my docker host and my env file (with sensitive settings <REDACTED>)
[schambers-healthchecks-io-env.txt](https://github.com/healthchecks/healthchecks/files/8546106/schambers-healthchecks-io-env.txt)
[schambers-healthchecks-io-docker-compose.yml.txt](https://github.com/healthchecks/healthchecks/files/8546108/schambers-healthchecks-io-docker-compose.yml.txt)

**Comment by cuu508** [comment]
I finally managed to reproduce this one as well. I used the default .env.example file and ran the docker container.

> Edit: My gut says it has something to do with the default settings in the .env file.

Yep! If the .env file has the following:

    DISCORD_CLIENT_ID=

Then settings.py will read it in as "" (empty string). But in the "Integrations" page, when deciding whether to show the Discord integration, we test if DISCORD_CLIENT_ID **is None**. 

I just fixed the code to treat both empty strings and None values as "unconfigured, do not show it in the list of available integrations". 

As a workaround until next release, in the .env file, you can comment out (or remove altogether) the settings with empty values:

    # DISCORD_CLIENT_ID=

**Comment by cuu508** [comment]
> A workaround that does work, surprisingly, is opening the link with middle-click (open in new tab). By doing that, everything seems to work just fine.

PS. I'm still not sure how this can happen. Some integration types, for example webhooks, don't need any configuration and are always available. @Firesphere perhaps you were clicking on different integration types, and the ones you opened with a middle click happened to be the always-working ones?

**Comment by Firesphere** [comment]
> > A workaround that does work, surprisingly, is opening the link with middle-click (open in new tab). By doing that, everything seems to work just fine.
> 
> PS. I'm still not sure how this can happen. Some integration types, for example webhooks, don't need any configuration and are always available. @Firesphere perhaps you were clicking on different integration types, and the ones you opened with a middle click happened to be the always-working ones?

I'm not sure, because I did get the Slack integration working. Even on a brand new Virtualbox Ubuntu 22.04, then setting up docker inside that, this issue occurs

**Comment by Firesphere** [comment]
Just did a rebuild of the container, all works as it is supposed to. Thanks!
