### ISSUE TITLE
prunenotifications

### ISSUE THREAD

**Issue by MokhlesHm** [healthchecks/healthchecks#636]
When im trying to run prunenotifications command using 
#./manage.py prunenotifications 
i get the following error 
"ValueError: Cannot use None as a query value"

does anyone face such issue or know how to solve it ?

According to this https://github.com/healthchecks/healthchecks/issues/556#issuecomment-948528834 normally the command 
#prunenotifications does not exist anymore therefore why i get this weird error 
which is not the case for the command #prunepings

**Comment by cuu508** [comment]
Did you by any chance manually delete entries from `api_ping` table?

**Comment by MokhlesHm** [comment]
I changed the database from sqlite to mysql and i uploaded the tables entries from the old database to the new one manually.
but for this table i didnt use it because i found no entries in the old database.
