### ISSUE TITLE
Add support for signal-cli-rest-api

### ISSUE THREAD

**Issue by alexw1982** [healthchecks/healthchecks#639]
Would be great if notification support for https://github.com/bbernhard/signal-cli-rest-api could be added as there is no need to run signal-cli locally. Especially useful when using docker … but setting it up via webhooks obviously works also

**Comment by cuu508** [comment]
I think you should be able to integrate with signal-cli-rest-api using the Webhook integration.

If you run  Healthchecks and signal-cli in separate Docker containers, you may be able to hook them up by using a shared volume and placing the signal-cli socket file there.
