### ISSUE TITLE
Multiple "RP_ID"  for  multiple "ALLOWED_HOSTS"

### ISSUE THREAD

**Issue by returntrip** [healthchecks/healthchecks#641]
I have tries to setup multiple "RP_ID" but this does not seem to work. Would it be possible to allow multiple "RP_ID"s?

**Comment by cuu508** [comment]
Can you please describe your setup and use case a little more? Why do you need multiple values in ALLOWED_HOSTS?

**Comment by returntrip** [comment]
I serve my self hosted healthchecks.io instance from two different subdomains:  a long, more descriptive, hostname and a short, more practical one. I could set a redirect at DNS level but it would be nice to be able to have multiple RP_IDs (one can make a wish :)).

**Comment by cuu508** [comment]
Do you use the longer domain for the web dashboard, and the shorter domain for ping URLs (like healthchecks.io and hc-ping.com)? 

Note that when you register a WebAuthn security key, it gets associated with the site's domain and the registration is only valid for that domain. For example, let's say we add support for multiple RP_ID values, and you register the key while on long-descriptive-hostname.example.org. If you later try to log in via short.example.org, it will not work.

**Comment by cuu508** [comment]
> At the moment I simply use the two hosts to reach the HC instance, nothing more.

I'm still not sure I understand why you need this. Is this purely cosmetic, and you use one domain or the other depending on mood?

To consider adding or changing features in the project I need a convincing use case.

> Say you guys enable multi RP_ID support, can I register the same key with different (sub)domains? After registration of each of them, will I be able to login on associated hosts?

I'm not sure – I haven't experimented with this.

**Comment by returntrip** [comment]
Yes this is purely cosmetic and not functional.

I just thought it was possible to use multiple RP_ID (cause you can have multiple allowed hosts), but I guess I misunderstood the use of ALLOWED_HOSTS.

Apologies, will close this request. Thanks.
