### ISSUE TITLE
Execution time of script not shown in log page

### ISSUE THREAD

**Issue by jsddsfoh** [healthchecks/healthchecks#644]
Hello,

I use /start and /stop for time measurement. It all works fine, but in the log the duration is not displayed for an entry, which execution time was about 2.5 days.
All other entries range from a few minutes to 8hrs and are displayed fine.

**Comment by cuu508** [comment]
If the "start" and "complete" events are more than 24 hours apart, Healthchecks assumes they are not related.
The 24 hour threshold is defined here in the code: https://github.com/healthchecks/healthchecks/blob/98f2536825f13fc043a0623add7be1429fa7e5b3/hc/api/models.py#L36

This has been brought up a couple times before, perhaps it makes sense to increase the threshold to 48 or 72 hours.

**Comment by jsddsfoh** [comment]
I see, thanks for the response!
It`s possible to set grace time and period up to 365days. I was wondering which script needs to run this long, but I`m sure there is somebody out there :D
So is there no way to make it possible to show the runtime? Maybe an alive-ping after a certain time? Or just remove the limit, but I assume it`s there for a reason?

**Comment by cuu508** [comment]
Period: yes, there are jobs that run only once a month, once every 3 months, or less frequently. For grace time, I'm not sure there's an use case for months-long grace time. But I wanted the Period and Grace Time sliders to look similar.

> Or just remove the limit, but I assume it's there for a reason?

Two reasons:

* If a "start" and "success" signals are very far apart, there's a good chance they are not actually related. For example, let's say a job is scheduled to run once a week, and normally completes in 20 minutes. The job sends a `/start` signal and then crashes. Five days later, somebody gets around to investigating what happened to the job. During investigation, they manually send a "success" ping. The UI now shows the last duration as "5 days". 
* With longer durations, it's harder to fit the information on the screen. You could have durations like "3 days 23 h 59 min 49 sec". This can be tested and tuned (don't show seconds for long durations etc.), but takes more work ;-)

**Comment by jsddsfoh** [comment]
Thanks for setting it to 72h! This should fit at least my needs most of the time.

Maybe it's possible to have MAX_DELTA editable in config file in the future?

**Comment by truppelito** [comment]
I recently ran into this issue. I have some backup jobs that can take days to complete and I want to track their duration. Would it be possible to make this 72 hour threshold configurable through an env. variable? Or a setting in the UI? Or to disable it entirely?

**Comment by cuu508** [comment]
@truppelito my two considerations against increasing the MAX_DELTA value further are:

* the further two events are apart, the higher the chance they are in fact unrelated
* to calculate the job's duration we have to look back in the database for a matching `start` event. If we have to look back further, the database query is more expensive.

And the consideration against making MAX_DELTA configurable is that each new configuration setting adds complexity.

With that in mind, something I think we could do is ignore MAX_DELTA when displaying the duration in the "Ping Details" dialog if the client is using Run IDs (see "Specifying Run IDs" [here](https://healthchecks.io/docs/measuring_script_run_time/)). 

* If the start and success/failure events have matching run IDs then there is no ambiguity whether they are related – they have the same run IDs, that cannot happen by accident!
* In the "Ping Details" we would be looking up the duration for one single event, not for a list of many events, so we can probably afford the database query to be more expensive.

Would it be useful for you to see the duration in the "Ping Details" dialog, even if it's not shown in the list view ("Event Log")? If you are currently not using Run IDs, would you consider to start using them?

For reference, the "Ping Details" dialog is this one:

<img width="1275" height="877" alt="Image" src="https://github.com/user-attachments/assets/73592b36-40ff-4fb6-8cd3-c9a04023ca5e" />

**Comment by truppelito** [comment]
@cuu508 I'm currently not using run IDs, but I think that's easy to change. As for showing the duration in the "Ping Details" dialog, how I am currently using Healthchecks.io is that I have a Grafana dashboard that queries the API at `https://<url>/api/v3/checks/<id>/pings` and then displays some graphs. As long as that endpoint gives back the correct duration values, it should be fine!
