### ISSUE TITLE
Ability to configure a proxy (for webhooks)

### ISSUE THREAD

**Issue by ScuttleSE** [healthchecks/healthchecks#654]
I am running Healtchecks behind a corporate proxy, monitoring internal system. 
To be able to create an integration to Teams, I need to use a proxy to access the internet. I can't find anywhere to enter a proxy in the configuration.

I have tried adding the HTTP_PROXY and HTTPS_PROXY environment variables when running HC in docker, but they don't seem to be used when accessing webhooks.

**Comment by cuu508** [comment]
I recently switched Healthchecks from using requests to using pycurl as the HTTP client library.

One of the benefits is that you can now set the "http_proxy" environment variable and libcurl will use it. I just tested this with the dev server:

```
http_proxy=http://proxyhost:proxyport ./manage.py runserver
```

This is a recent change, and I have not yet documented it, but in the meantime here's libcurl documentation (see the "Environment variables" section): https://curl.se/libcurl/c/CURLOPT_PROXY.html

**Comment by cuu508** [comment]
I recently switched Healthchecks from using requests to using pycurl as the HTTP client library.

One of the benefits is that you can now set the "http_proxy" environment variable and libcurl will use it. I just tested this with the dev server:

```
HTTPS_PROXY=socks5://proxyhost:proxyport ./manage.py runserver
```

This is a recent change, and I have not yet documented it, but in the meantime here's libcurl documentation (see the "Environment variables" section): https://curl.se/libcurl/c/CURLOPT_PROXY.html

Note: if the proxy IP address is in a private IP range, you will also need to set `INTEGRATIONS_ALLOW_PRIVATE_IPS` to `True`.

**Comment by cuu508** [comment]
Works with docker-compose too, after I added the following in `/docker/.env`

```
INTEGRATIONS_ALLOW_PRIVATE_IPS=True
HTTPS_PROXY=socks5://myhost:myport
```

**Comment by cuu508** [comment]
Now documented:

https://healthchecks.io/docs/self_hosted_configuration/#http_proxy
https://healthchecks.io/docs/self_hosted_configuration/#INTEGRATIONS_ALLOW_PRIVATE_IPS
