### ISSUE TITLE
Update email keywords via API

### ISSUE THREAD

**Issue by TFenby** [healthchecks/healthchecks#659]
Subject and subject_fail aren't exposed via the API:

https://github.com/healthchecks/healthchecks/blob/master/hc/api/models.py#L75

https://github.com/healthchecks/healthchecks/blob/master/hc/api/views.py#L97

Looks like a pretty simple change I could throw together a PR for. Are there any docs/tests/other things that would also need to be updated?

**Comment by cuu508** [comment]
Having API support for reading/writing `Check.subject` and `Check.subject_fail` would be great.

Yes, a complete a PR should include:

* updated or new test cases that exercise the new code
* updates in the "Management API" page: https://github.com/healthchecks/healthchecks/blob/master/templates/docs/api.md
