### ISSUE TITLE
Disable Alert

### ISSUE THREAD

**Issue by pzelnip** [healthchecks/healthchecks#67]
We use Chef as our configuration management tool, and provide the healthchecks.io url for a particular server instance as part of the config for that machine (it's an attribute in a node file).

The problem is we will bring machines up and down periodically, so if a machine is up, a cron job will run and then hit the healthcheck.io url, but if we then shut the machine down we continually get alerts for that machine until we boot it up again.

It'd be nice if you could disable (not delete) a healthcheck.io url, as deleting it means that you'll have to create a new url and change the config for that node in your config management tool.

**Comment by cuu508** [comment]
You will probably want to disable alerts from API as well, correct?

**Comment by pzelnip** [comment]
Correct.

**Comment by pzelnip** [comment]
Awesome stuff, thx!
