### ISSUE TITLE
Self-hosting via Docker, can't get rid of "Running in debug mode, do not use in production."

### ISSUE THREAD

**Issue by ovizii** [healthchecks/healthchecks#672]
I've read all issues here mentioning `DEBUG = "False"` but that did not help. I tried setting that as a docker ENV variable as well as putting it into local_settings.py   

Running healthecks via this image: https://hub.docker.com/r/linuxserver/healthchecks 
healtchecks:  v2.2.1

**Comment by cuu508** [comment]
Have you seen https://github.com/linuxserver/docker-healthchecks/issues/87 ?

**Comment by ovizii** [comment]
Thanks, I missed that, but they suggest exactly what I was doing namely adding DEBUG=False to docker-compose.yml 

Thanks for trying to help, I am giving up for now as I was facing multiple issues, like the PING_ENDPOINT not using SITE_ROOT to construct but simply localhost, totally ignoring my ENV variables. 

linuxserver makes some very nice images when they work, but when they don't, you're stuck. 

Will check back a few versions later to see if everything works again.
