### ISSUE TITLE
Notification emails: difference in plain text vs. HTML part

### ISSUE THREAD

**Issue by szepeviktor** [healthchecks/healthchecks#679]
Hello!

- in the plain text version items with "down" status are at the bottom of the list, in HTML they are at the top
- there are some header/footer differences

**Comment by cuu508** [comment]
Hi Viktor, do you mean the hourly/daily reminder emails ("Reminder: 1 check still down")?

In the reminder emails, in the HTML version checks are grouped by project, but in the plain text version they're in one long list, and the sort order is unclear  – is this what you are pointing out?

**Comment by szepeviktor** [comment]
> do you mean the hourly/daily reminder emails ("Reminder: 1 check still down")?

Yes.

> the sort order is unclear – is this what you are pointing out?

In my case the "down" check was first in HTML and last in plain text. That was so shocking I've opened this issue.

Looking into it deeper: the plain text is really unordered.
The HTML may grouped but I don't have multiple projects.
I think they are ordered by creation date.
Could you confirm it?

**Comment by cuu508** [comment]
Checks in the text version are indeed in arbitrary order – I'll look into fixing that.

The sort order in the HTML version is the same as in the check list view in the web UI. 

The default sort order is by creation date, but you can also change it to alphabetic by name, or by the last received ping date. The sort order you select in the web UI will also be used in the HTML version of the email.

**Comment by cuu508** [comment]
> The default sort order is by creation date, but you can also change it to alphabetic by name, or by the last received ping date. The sort order you select in the web UI will also be used in the HTML version of the email.

PS. there's one exception, – checks in the "down" state are always at the top.

**Comment by szepeviktor** [comment]
It would be so lovely to order checks in the plain text version and put "down" check at the top! ❤️

**Comment by szepeviktor** [comment]
Thank you.
