### ISSUE TITLE
Running with Docker

### ISSUE THREAD

**Issue by haswalt** [healthchecks/healthchecks#68]
Hi,

I've created this image: https://github.com/haswalt/docker-healthchecks not sure if it's of any interest but might be worth adding something similar to the docs.

**Comment by cuu508** [comment]
Cool, I will give this a go!

I see you are not running `manage.py sendalerts` from the container. Perhaps this is intentional? If not, it would be pretty easy to add with uwsgi's `--attach-daemon` feature.

**Comment by haswalt** [comment]
Initially I'd planned on pushing the sendalerts part into another container. The entrypoint also allows overriding the command but perhaps running in container with uwsgi is better, certainly simpler for users

**Comment by Braintelligence** [comment]
https://github.com/galexrt/docker-healthchecks
