### ISSUE TITLE
2FA Support: reset user 2fa 

### ISSUE THREAD

**Issue by louissegal** [healthchecks/healthchecks#682]
Is there scope to reset 2fa/disable 2fa from an already active user?
Somehow it's now telling me my 2fa codes are invalid

I've gone into the running container and with manage.py created a new superuser to login and get into admin console, but I don't see any way to remove 2fa from a user

Thanks

Edit: for some reason the 2fa is now not locked out, but being able to remove 2fa from the admin portal would still be a helpful feature.

**Comment by cuu508** [comment]
The 2FA credentials are stored in the `accounts_credential` database table. Deleting rows from this table disables 2FA for the corresponding user(s). When you're logged in as a superuser, you can go to `/admin/accounts/credential/` and delete the credentials from there, or you can run `DELETE` queries from the database shell.
