### ISSUE TITLE
SMTP server does not work with implicit TLS (port 465)

### ISSUE THREAD

**Issue by facorazza** [healthchecks/healthchecks#683]
When setting `EMAIL_PORT=587` I'm able to receive emails, but if I set it to `465` it doesn't work and I don't see any apparent error.
Possibly related to the fact that [EMAIL_USE_SSL](https://docs.djangoproject.com/en/4.0/ref/settings/#email-use-ssl) is not supported?

**Comment by cuu508** [comment]
Healthchecks currently does not read `EMAIL_USE_SSL` from the environment variables, so setting it there has no effect. If you put `EMAIL_USE_SSL = True` in `local_settings.py`, does it work then?

**Comment by facorazza** [comment]
Yes it does indeed work with `EMAIL_USE_SSL = True`. I've taken the liberty to open a PR #685.
