### ISSUE TITLE
Disable signup option

### ISSUE THREAD

**Issue by DarrenPIngram** [healthchecks/healthchecks#693]
Is there an environment (or can there be) to hide the sign-up option when you go to the default URL?

Similar to hide the "docs" link on the top of the pre-login page?

Thank you for the hard work on a great application.

**Comment by phaer** [comment]
There's `REGISTRATION_OPEN` listed in https://healthchecks.io/docs/self_hosted_configuration/

**Comment by phaer** [comment]
Does that solve your issue @DarrenPIngram ?
