### ISSUE TITLE
Additional schedule element

### ISSUE THREAD

**Issue by DarrenPIngram** [healthchecks/healthchecks#694]
For a script that runs (for example) between 1900-0500 UTC, could there be an additional monitoring element to say the script runs only between these times (so if it was running hourly between these times, Healthcheck would not say at 1200 UTC that "Houston, we have a problem"?

**Comment by cuu508** [comment]
Perhaps the cron schedule would work here?

![image](https://user-images.githubusercontent.com/661859/184885358-430df370-7ec9-404b-9f4c-b0dbb59088d1.png)

`0 19-23,0-4 * * *` says: expect a ping at the start of every hour, from 19:00 until 05:00 (exclusive).
