### ISSUE TITLE
Local Image: SITE_LOGO_URL

### ISSUE THREAD

**Issue by rwjack** [healthchecks/healthchecks#697]
Is it possible to have the SITE_LOGO image served locally on the docker host?

Perhaps serve the image statically and have: `SITE_LOGO_URL=http://healthchecks.local:port/static/logo.png`

Healthchecks being behind a reverse proxy shouldn't be a problem, because it should be able to fetch resources from itself, correct?

Also, I've noticed `docker/.env.example` doesn't contain `SITE_LOGO_URL`

**Comment by cuu508** [comment]
Healthchecks uses the `SITE_LOGO_URL` value in the HTML template as-is. For example, if you set

    SITE_LOGO_URL=foobar

You will end up with 

    <img id="logo" height="50" src="foobar" alt="Mychecks">

in the HTML. You should use an URL that **the end user's browser will be able to access.** 

You can, for example, drop a custom logo in `/static/img/custom-logo.png` and use:

    SITE_LOGO_URL=/static/img/custom-logo.png

Or you can use an absolute URL:

    SITE_LOGO_URL=https://example.org/static/img/custom-logo.png

**Comment by rwjack** [comment]
Awesome, thanks!
