### ISSUE TITLE
Add tags to integrations. Match checks and integrations using tags

### ISSUE THREAD

**Issue by job** [healthchecks/healthchecks#70]
Would be nice if the `hchk` tool can indicate which integrations should be used. By default all integrations are selected when a new check is created, and I have to manually go in and uncheck the integrations which are not needed.

I use the integrations to route information to different entities/organisations: example: http://instituut.net/~job/screenshots/42bb5441933ced72b96e4a73.png - the results of checks with tag`coloclue` should go to the coloclue integrations, not to peeringdb.

**Comment by cuu508** [comment]
I agree the UI gets confusing as soon as you need something other than "all alerts go to all integrations". The "Assign Checks to Channel" dialog is due to an overhaul.

By `hchk` tool do you mean the command line tool? Checks created by the command line tool should default to no integrations selected.

**Comment by job** [comment]
Whoops! Because of the webinterface I assumed the `hchk` CLI tool would behave the same. 

Some kind of `--integrations $ID1,$ID2`or `--integration-tags $TAG1` argument would be interesting, so I can group integrations with tags and have the check set up to use those.

**Comment by cuu508** [comment]
One idea I'm considering is: 

* let users tags integrations the same way as checks
* a check and an integration are "associated" if they have at least one common tag
* remove the current, explicit "Add Checks to Channel" facility

Then, as an example, you could have tags  `coloclue`, `peeringdb`, `coloclue-urgent` and `peeringdb-urgent`. 

Continuing the example, use tags `coloclue` and `peeringdb` for email integrations. Use `coloclue-urgent` and `peeringdb-urgent` for a high-importance, low-volume Slack channel #war-room.

Then assign tags to checks as needed, based on their project and importance. No manual check-integration assignments needed. What do you think?

**Comment by job** [comment]
Sounds perfect

**Comment by cuu508** [comment]
"Match checks and integrations using tags" would be tough to implement: 1) not trivial to explain the feature to the users 2) at this point in project's lifecycle, what to do with the existing mappings? Maintain two different ways of mapping checks to integrations? 

Meanwhile, Healthchecks now has Projects feature which in many cases simplifies the check-integration mapping, as all checks and all integrations don't need to be in a single big pile any more.

Also, the "My Checks" page shows toggle-able integration icons, which makes it easier to massage the check-integration mapping into the state you want.

With the above in mind, I'm closing this as a "wontfix".
