### ISSUE TITLE
Healthcheck sent on new creation?

### ISSUE THREAD

**Issue by DarrenPIngram** [healthchecks/healthchecks#701]
Self-hosted instance, latest version via Docker. 

I just set up a brand new HC alert/monitor. Went to document it and when I came back a few minutes later to close the tab, I saw there had been traffic immediately from IPs I do not recognise.

I accept people may randomly scan URLs, but the chances of this happening to a quiet HC instance on a sub-domain, guessing the "right" URL and within minutes of creation? 

Is there by chance some "auto health check" made by yourselves, even with self-hosted instances, that I am not aware of (or missed in any documentation)?

The stranger thing (looking at other entries) is that this does not happen all of the time.

1x
52.89.103.*** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18

2x
34.217.253.*** Mozilla/5.0 (compatible; DashLinkPreviews/5.1;)

1x
34.217.253*** Mozilla/5.0 (Macintosh; I

**Comment by phaer** [comment]
Browser often check links for either "safe-browsing" and/or local preview rendering, a user agent such as `DashLinkPreviews` does sound like the latter, no? 
I think it's best to assume that any HTTP endpoint not requiring authentication will be hit by random traffic sooner or later, in a mostly unpredictable matter.

**Comment by cuu508** [comment]
> Is there by chance some "auto health check" made by yourselves, even with self-hosted instances, that I am not aware of

No, there isn't, at least not in the code in this repository, or the official Docker images.

My guess: one or more tools you are using is automatically scanning all URLs it sees for malware and/or to generate link preview images.

**Comment by cuu508** [comment]
The `/log` endpoint was implemented in Healthchecks v2.3 – perhaps you are running an older version?
