### ISSUE TITLE
increasing PING_BODY_LIMIT=100000 breaks all ping 500 Server error

### ISSUE THREAD

**Issue by pinkworld123** [healthchecks/healthchecks#702]
Hello,

I tried to increase the PING_BODY_LIMIT from 10KB to 100KB
PING_BODY_LIMIT=100000 # 100KB

I am using default database sqlite

which broke all ping and causes 500 Server Error when Ping URL is called.

Please let me know how to fix this issue. Thank you for help.

**Comment by cuu508** [comment]
Thanks for the report. To understand what's going wrong I'll need to see the python traceback. 

If you have set `DEBUG=False`, you could temporarily set it back to `True`, then you should see the traceback in the server's standard output.

**Comment by pinkworld123** [comment]
Sorry for late reply. 

here is the debug. 

```
TypeError at /ping/61cacb0f-126f-48de-a071-7f0ac0abcb53

slice indices must be integers or None or have an __index__ method
```

**Comment by pinkworld123** [comment]
open the new ticket as this is closed. 
https://github.com/healthchecks/healthchecks/issues/727
