### ISSUE TITLE
Site documentation now indicates up to 100KB of logs will be persisted

### ISSUE THREAD

**Issue by dimo414** [healthchecks/healthchecks#703]
https://github.com/healthchecks/healthchecks/blob/58da098d6b2b66718f3d48bf517c8419d2c73f8a/templates/docs/attaching_logs.md?plain=1#L51-L61 and the rest of the code still seems to indicate the limit is 10KB, but the website (now) says it's 100KB:

![Screenshot of "Handling More Than 100KB of Logs" docs section](https://user-images.githubusercontent.com/1885701/188302148-6c1b1c2d-d168-4f9b-bc51-0c001cd608b3.png)

I'm guessing this change is in-progress and just got published early (if so, thanks for the increase!), but I wanted to flag it in case it's unintentional.

**Comment by cuu508** [comment]
The [PING_BODY_LIMIT](https://healthchecks.io/docs/self_hosted_configuration/#PING_BODY_LIMIT) configuration parameter sets the upper size limit for stored ping bodies (if the request body exceeds the limit, Healthchecks stores the first `<PING__BODY_LIMIT>` bytes and discards the rest).

The default value is 10000 (10KB). On the hosted service, Healthchecks.io, I've set the parameter to 100000 (100KB).

For the sake of simplicity, the documentation displays a static, hardcoded value. Therefore, if you change `PING_BODY_LIMIT` to a custom value, the change will not be reflected in the documentation. In this repository, the hardcoded value is "10KB" to match the default `PING_BODY_LIMIT`.

**Comment by dimo414** [comment]
Ok, so it's WAI that the site documentation and the repo documentation are out of sync regarding this value? If so feel free to close - I just assumed the inconsistency wasn't intentional.
