### ISSUE TITLE
"502 Bad Gateway" at /checks/<UUID>/log/ for new UUIDs

### ISSUE THREAD

**Issue by lukastribus** [healthchecks/healthchecks#705]
Hello,

I just created a new check/UUID, a few successful log entries are already in there.

Going to:

    https://healthchecks.io/checks/<UUID>/details/

shows everything is fine.

However clicking on "show more" (the new filter interface) leads to a long running transaction that after 30 seconds times out with a 502 Bad Gateway ("service down, please try in 10 minutes"):

    https://healthchecks.io/checks/<UUID>/log/

I'm assuming the new interface may be trying to access historic data that is not there yet. Not sure if the backend is busy looping.

This is on the hosted `healthchecks.io` instance.

Thank you!
Lukas

**Comment by cuu508** [comment]
Hi Lukas, thanks for reporting this. I can reproduce the issue, looking into it.

**Comment by cuu508** [comment]
@lukastribus I've now deployed a fix which *I think* should fix the issue. Could you please test again?

**Comment by lukastribus** [comment]
It works for me now, thank you!
