### ISSUE TITLE
Self hosted: email summary not working

### ISSUE THREAD

**Issue by Openhabber** [healthchecks/healthchecks#706]
Hello,
first thanks for the amazing software. Im really happy with health checks!
But:
the weekly/monthly summary is not being sent.
The email integration is working fine and sends emails if a service goes down.

When I activate monthly or weekly reports, the date is correctly shown when the next one should be sent. However, it never gets sent and the date stays. For example today:

![Screenshot_20220919-212000~2](https://user-images.githubusercontent.com/56535530/191098308-e622757b-76e6-450b-98e1-74e7d50899b1.png)

If I deactivate it, save, activate, and save again:
![Screenshot_20220919-212152~2](https://user-images.githubusercontent.com/56535530/191098571-b6a3a31e-df04-4649-8860-edc9b0c8583a.png)

Everything else is working fine.

I'm running it self hosted  on docker.
Thanks for your help.

**Comment by cuu508** [comment]
The `sendreports` management command is likely not running (it must be running continuously in the background, same as `sendalerts`). What Docker image are you using?

**Comment by Openhabber** [comment]
Thanks for your response. I'm running the linuxserver.io image. Should I post the issue there?

**Comment by cuu508** [comment]
Yes. 

Looking at linuxserver's uwsgi.ini, [there's a line that starts sendalerts](https://github.com/linuxserver/docker-healthchecks/blob/8dd09e86b4bdfa22d11ac6541dc118bb53d50ab8/root/defaults/uwsgi.ini#L11) but there isn't one for sendreports.
