### ISSUE TITLE
Advanced Custom Cron

### ISSUE THREAD

**Issue by MichalisDBA** [healthchecks/healthchecks#707]
Hello.

We have a cronjob that looks like this

```
00 09 1-7 * * [ "$(date '+\%a')" == "Sun" ]
```

It runs only At 09:00 on every day-of-month from 1 through 7 BUT if the day is Sunday. So to summarize it runs every first Sunday of a new month.

How is it possible to setup something like this in healthchecks system without giving false possitives alerts etc.?

**Comment by cuu508** [comment]
You can use `00 09 * * SUN#1`.

"#1" is a non-standard syntax feature. [Here are a couple others](https://github.com/cuu508/cronsim#cron-expression-feature-matrix) that healthchecks supports.
