### ISSUE TITLE
Create Projects API

### ISSUE THREAD

**Issue by lpadilia** [healthchecks/healthchecks#709]
I need to insert new hosts as projects, can I do it through the API or another automated way?

**Comment by cuu508** [comment]
No, there is currently no API for manipulating projects. 

If you run a self-hosted instance, look into writing a management command that takes the project's name and owner's email as arguments and creates a project. [createsuperuser](https://github.com/healthchecks/healthchecks/blob/master/hc/accounts/management/commands/createsuperuser.py) could be used as a starting point.

**Comment by rodrigodc** [comment]
@cuu508 would a PR implementing that API be welcome?

**Comment by cuu508** [comment]
I would consider a PR that implements a "createproject" management command. 

Doing the same via API calls would be a little complicated. The current API keys are project-scoped. For a "Create Project" API we would need account-level API keys too. We would need UI for generating and revoking them. In the documentation, we would need to explain the differences between the different kinds of the API keys.
