### ISSUE TITLE
Allow timeout and grace values for 30+ days

### ISSUE THREAD

**Issue by cuu508** [healthchecks/healthchecks#71]
For "every 3 months" checks and maybe even "every year" checks.

**Comment by job** [comment]
Maybe cron-like syntax with shortcuts like `@daily` `@yearly` `@montlhy` is cool

**Comment by cuu508** [comment]
I've now added support for cron syntax and rolled the change out on healthchecks.io. 
The `@daily`, `@yearly`, `@monthly` shortcuts are not in yet, but regular cron expressions should work, and would allow for periods longer than 30 days.

@job if you're still interested in this, you are welcome to test it out!

**Comment by job** [comment]
Sweet! Will check it out

**Comment by brianstorti** [comment]
Is there any reason to not support more than 1 week (604800) for the `timeout` parameter in the API to create new checks?

**Comment by cuu508** [comment]
@brianstorti that's a bug. Originally the max `timeout` was 1 week. In May 2016 we bumped it to 1 month. The web UI was updated, but the API was not. Fixed now!

**Comment by brianstorti** [comment]
@cuu508 Thank you!
