### ISSUE TITLE
Getting permission denied with building with docker-compose

### ISSUE THREAD

**Issue by 0x412e4e** [healthchecks/healthchecks#718]
Hello,

I'm getting a permission denied error during the build phase of the web container when trying to spin up the containers with docker compose. 

In the .env file I have configured `SECRET_KEY` variable as `asdasdasdasd` and I'm getting the following error running `docker compose up -d` in the `healthchecks/docker` folder:

```
Step 21/27 : RUN     rm -f /opt/healthchecks/hc/local_settings.py &&     DEBUG=False SECRET_KEY=build-key ./manage.py collectstatic --noinput &&     DEBUG=False SECRET_KEY=build-key ./manage.py compress
 ---> Running in 432d4115331e
/bin/sh: 1: ./manage.py: Permission denied
```

Currently running on Red Hat Enterprise Linux 9, trying to spin up the containers as root.

**Comment by cuu508** [comment]
I'm assuming you've cloned the repository locally on the RHEL9 system. What output do you get if you run `manage.py` locally, on the host system?

```
cd /path/to/healthchecks/repository/
./manage.py
```

**Comment by cuu508** [comment]
Also, can you provide the steps to reproduce the problem, starting from a freshly installed stock Red Hat Enterprise Linux 9 system?

**Comment by 0x412e4e** [comment]
Strange, I wanted to try running `manage.py` but it was not an executable (probably because I downloaded the repo zip on a windows and scp'd the files to the RHEL server). So I made it an executable and tried running `docker compose up -d` again just for the sake of testing it and it works 🧐

Apologies for missing half a brain 😄
