### ISSUE TITLE
Webhooks not working

### ISSUE THREAD

**Issue by lettore** [healthchecks/healthchecks#725]
From Version 2.4 webhooks are not working anymore, trying inside the container I'm able to ping and curl remote side.
Testing from web-ui I always receive Connection Failed, but nothing in the logs also with debug on.
I'm using the linuxserver image.

**Comment by cuu508** [comment]
1. Do you by any chance have `http_proxy` or `https_proxy` environment variables set?

2. Can you test webhook delivery using a throwaway [healthchecks/healthchecks](https://hub.docker.com/r/healthchecks/healthchecks) container? You can copy/paste the snippets from the "Quick Start using Docker CLI" section in README to get running quickly.

**Comment by lettore** [comment]
I don't have http_proxy env variable set.
As I said webhooks are working with version 2.3 and not in 2.4. Nothing is changed in compose file.
Testing using with a throwaway [healthchecks/healthchecks](https://hub.docker.com/r/healthchecks/healthchecks) container is not working either.
You can test yourself with a GET request to any webserver, in this case I tried also to contact itself (exposed to port 9150).
![image](https://user-images.githubusercontent.com/34779795/200135731-bedd3dce-22b9-426c-905a-a46437f9e19c.png)
![image](https://user-images.githubusercontent.com/34779795/200135740-c4883fe4-c943-4764-a5fc-8ad521a96808.png)
With the server with 2.3 version is working.
![image](https://user-images.githubusercontent.com/34779795/200135700-4572b01b-6f30-44df-bdd6-93e28046f716.png)
![image](https://user-images.githubusercontent.com/34779795/200135715-a15d0b22-8cb9-4dab-ad88-fb67be76c35b.png)

**Comment by cuu508** [comment]
From v2.4 onwards, to allow requests to private IP ranges, set `INTEGRATIONS_ALLOW_PRIVATE_IPS=True` env var.

https://healthchecks.io/docs/self_hosted_configuration/#INTEGRATIONS_ALLOW_PRIVATE_IPS

**Comment by lettore** [comment]
That's resolved, not totally sure why by default a private address inside a secure network should be a security issue. It's the first time I have faced this kind of problem, usually, only local addresses are allowed not otherwise.

**Comment by cuu508** [comment]
> not totally sure why by default a private address inside a secure network should be a security issue

It is a security issue if you let untrusted people create accounts on your Healthchecks instance. They can set up webhooks that probe your internal network. Of course, if you are the only user, or if you fully trust all your users, then that is not a concern, and you can set `INTEGRATIONS_ALLOW_PRIVATE_IPS=True`.

**Comment by lettore** [comment]
What if I don't fully trust only one user? Until 2.3 no one cared about this "issue" now you made by default a change that disrupt the webhook functionality, with just a setting that applies to the whole system and not per user or address. I had blocked by your rule https domain names that resolves also from the Internet with user authentication or token enabled. Just because the server is inside my Lan and it's resolved by local dns as a local address. Which kind of security risk is involved in a GET call to a local address with authentication enabled? In this way I have to disable your protection because is blocking every call to secure servers as well to unsecured one's. It wouldn't be better, if you take care of security, to make a more complex system where, for example, admins have full access to local lan, and other users should use address in a whitelist?

**Comment by cuu508** [comment]
> Until 2.3 no one cared about this "issue" now you made by default a change that disrupt the webhook functionality

Sorry about that :-/ In the hindsight, I should have called attention to this behavior change in the release notes.

> Which kind of security risk is involved in a GET call to a local address with authentication enabled?

https://portswigger.net/web-security/ssrf

> It wouldn't be better, if you take care of security, to make a more complex system where, for example, admins have full access to local lan, and other users should use address in a whitelist?

I don't self-host any notification delivery services (aside from signal-cli), and so don't have a need for this. But I can see how it could be useful in selfhosting scenarios.
