### ISSUE TITLE
Weekly report contains last months information

### ISSUE THREAD

**Issue by niklas2810** [healthchecks/healthchecks#736]
Hey there! First off, thank you so much for creating healthchecks! <3

Noticed something strange with the reports this morning: I used to receive a monthly report via mail, but switched to the "weekly on mondays" options to receive more regular updates. I _assumed_ that this would mean I'd get a comparison like CW x-2 / CW x-1 (if current calendar week is x). Instead, I received a comparison between September and October this morning, which isn't great data at the end of November anymore.

If the report displays last months data, I don't really see the point of a weekly email instead of the monthly one. What do you think about this? I hope you get my point and I didn't miss something obvious in the docs.

Cheers 🎉
Niklas

**Comment by cuu508** [comment]
Thanks for the report – I do get your point, and think we should fix this. 
Currently, when you switch to weekly reports, we change the report delivery schedule but the report generation is the same as for monthly reports. It would indeed make more sense to show the last week and the last - 1 week in the report instead.

**Comment by cuu508** [comment]
Done! Here's a fragment of a weekly report showing how it looks:

![image](https://user-images.githubusercontent.com/661859/204822581-ecbf1609-29da-4328-8cdb-ebeccae2280f.png)

**Comment by niklas2810** [comment]
> Done! Here's a fragment of a weekly report showing how it looks:
> 
> ![image](https://user-images.githubusercontent.com/661859/204822581-ecbf1609-29da-4328-8cdb-ebeccae2280f.png)

Looking awesome! Thank you very much :)
