### ISSUE TITLE
local_settings.py seems to ignore site_root and host

### ISSUE THREAD

**Issue by stevenmcastano** [healthchecks/healthchecks#75]
I was trying to move all my configs over to a proper local_settings.py file to make it easier to do "git pull" for updates, but when I leave the settings.py set for `HOST = "localhost"` and `SITE_ROOT = "hs.mydomain.com"` it doesn't work.

The main checks page in the web interface ends up showing `http://localhost:8000/ping/xyz....` and if I comment out the HOST and SITE_ROOT from settings.py to try to make use the values from local_settings.py, the app errors out and won't start.

**Comment by cuu508** [comment]
Maybe this is again an issue with stray .pyc files?

**Comment by stevenmcastano** [comment]
I doesn't appear to be... but I could have missed it. I'm going to shutdown the app in both places, delete all the .pyc file and try again. The only reason I think it wouldn't be related is that when I made the changes in the setting.py without deleting the pyc files, it worked fine.

**Comment by stevenmcastano** [comment]
Just tried again, git a `git reset`, left my only changes in local_settings.py, deleted all the .pyc files and it still does the same thing. shows "http://localhost:8000/ping/...." for all my URLs.

**Comment by cuu508** [comment]
Are all navigation links using localhost:8000, or just the ping URLs? If it's the latter, you need to redefine `PING_ENDPOINT` variable in local_settings.py too. It is defined in settings.py like so:

    PING_ENDPOINT = SITE_ROOT + "/ping/"

When you later redefine `SITE_ROOT` in local_settings.py, the `PING_ENDPOINT` variable still uses the original value.

**Comment by stevenmcastano** [comment]
I think you may be onto something there, that makes total sense. I'm going to try adding that to the local_settings.py and trying again in the morning!

**Comment by stevenmcastano** [comment]
I did just confirm this works. putting the `PING_ENDPOINT` line in `local_settings.py` works. Thanks again!
