### ISSUE TITLE
Reverse fail signal bit

### ISSUE THREAD

**Issue by c0nfus3d** [healthchecks/healthchecks#754]
I have a webserver that runs the webmin control panel. This server does a weekly backup.

In the backup settings, I can specify a "Command to run after backup"

It gives me variable options, such as the status of the backup.

> BACKUP_STATUS
> Set to 1 if the backup succeeded, 0 if not.

So I could set this command as `curl --retry 3 https://hc-ping.com/{GUID}/BACKUP_STATUS` to update my healthcheck.

However, this variable's value is the opposite of what Healthchecks.io is looking for-- "Healthchecks.io will interpret exit status 0 as success and all non-zero values as failures"

Is there a way that I can set this check to look for the reverse value, so it would interpret the **1** as a **success** instead of a fail and then interpret a **0** as a **fail** instead of success?

**Comment by cuu508** [comment]
The `/{status}` endpoint is for reporting the exit status of a process. On POSIX systems 0 is success and 1-255 is failure.

> Is there a way that I can set this check to look for the reverse value, so it would interpret the 1 as a success instead of a fail and then interpret a 0 as a fail instead of success?

You can write a wrapper script which reverses the BACKUP_STATUS and calls curl. And specify the wrapper script as the command to run after backup.

**Comment by c0nfus3d** [comment]
I like the idea @cuu508! Thanks! Closing this issue.
