### ISSUE TITLE
[v2.5] Matrix integration broken

### ISSUE THREAD

**Issue by rwjack** [healthchecks/healthchecks#759]
When upgrading v2.4->v2.5, the matrix integration doesn't seem to be working, unsure as to why. I tried creating a new access token for the bot, but HC spits the same error.

![image](https://user-images.githubusercontent.com/59068073/208677723-a5261fdf-f674-47ba-ae12-b007e61252b3.png)

**Comment by cuu508** [comment]
There were no Matrix-specific changes in v2.5. Are you sure Matrix notifications worked before the upgrade?

Can you test if sending messages works with curl from command line? You can try something like:

```
curl -XPOST -d '{"msgtype":"m.text", "body":"Hello"}' "https://matrix.org/_matrix/client/r0/rooms/\!QaRABAkxDBNukDoCOY:matrix.org/send/m.room.message?access_token=MDAxO...blahblah"
```

**Comment by rwjack** [comment]
> There were no Matrix-specific changes in v2.5. Are you sure Matrix notifications worked before the upgrade?

Yes that is what confuses me the most, I have tried upgrading to master a month ago, and I had the same results. When I saw 2.5 today I thought maybe it would work, but no dice.

Let me try the command line.

**Comment by rwjack** [comment]
Yep, it works from the cli, on both 2.4 and 2.5.

**Comment by cuu508** [comment]
Does the Matrix server run on a private IP? If yes, see https://healthchecks.io/docs/self_hosted_configuration/#INTEGRATIONS_ALLOW_PRIVATE_IPS

**Comment by rwjack** [comment]
Ah, there it is, all good now. Thanks!
