### ISSUE TITLE
Outage

### ISSUE THREAD

**Issue by szepeviktor** [healthchecks/healthchecks#76]
Was there an outage?
I've got only "red exclamation marks".

**Comment by CameronBanga** [comment]
Seeing similar, have two checks that are down, and don't seem to be working. Seeing following when I try manually:

```
wget https://hchk.io/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx -O /dev/null
--2016-08-19 16:29:29--  https://hchk.io/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
Resolving hchk.io... 2604:a880:800:10::170d:6001, 104.236.126.203
Connecting to hchk.io|2604:a880:800:10::170d:6001|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2016-08-19 16:29:29 ERROR 400: Bad Request.
```

**Comment by hakanw** [comment]
+1

**Comment by hakanw** [comment]
error 400 on the healthchecks

**Comment by pahud** [comment]
I also got 400 here

**Comment by Saxtus** [comment]
Confirming outage.
It began just after [19-Aug-2016 20:35 UTC](http://www.timeanddate.com/worldclock/fixedtime.html?iso=20160819T2035&p1=1440)

**Comment by barryrowlingson** [comment]
400 Bad Requests all over here too. On the plus side, I've now discovered the code is on github and I can host my own healthchecks site...

**Comment by pzelnip** [comment]
Ditto here.

**Comment by szepeviktor** [comment]
Email sent to `contact@`

**Comment by foozmeat** [comment]
contacted via twitter

**Comment by cuu508** [comment]
Hello,  hchk.io server was having database connectivity issue, and I was out of the country with roaming data off (bad idea!). Fixed for now. Will look into preventing this kind of issue in future, and will write a postmortem. Sorry about this.

**Comment by szepeviktor** [comment]
Thank you for your free service.

**Comment by cuu508** [comment]
post-mortem of this outage: https://medium.com/@healthchecks/outage-postmortem-20-august-2016-204297b9d3dd#.58n9g8tnj

**Comment by vmalloc** [comment]
@cuu508 thanks for the post mortem, and many thanks for this awesome service!

**Comment by hakanw** [comment]
Agree with everyone else. Thanks for a great service!!

2016-08-23 6:14 GMT+02:00 Rotem Yaari <notifications@github.com>:
