### ISSUE TITLE
Update PagerTree Integration Documentation

### ISSUE THREAD

**Issue by armiiller** [healthchecks/healthchecks#760]
PagerTree integration documentation (in Healthchecks app) is out of date. We need to add new screenshots to follow this integration guide: https://pagertree.com/docs/integration-guides/healthchecks

Specifically, in Healthchecks we need to update the following:
1. Create an Integration in PagerTree of type Healthchecks - https://pagertree.com/docs/integration-guides/introduction#create-an-integration
2. Copy the Endpoint URL - https://pagertree.com/docs/integration-guides/introduction#copy-the-endpoint-url

Happy to take this PR on just wanting to formally document. Feel free to assign it to me.

**Comment by cuu508** [comment]
Sounds good, will accept a PR!

For the new screenshots, if possible, please make them 150% scale so they look better on HiDPI screens. Most current screenshots are still 100% scale, but I use 150% scale for any new ones I add, example – https://github.com/healthchecks/healthchecks/blob/master/static/img/integrations/setup_mattermost_1.png
