### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Vic51993** [healthchecks/healthchecks#762]
Hi, good day!

I am new to this. Can you please tell me what seems to be wrong with this?

I managed to ./manage.py runserver as shown

![image](https://user-images.githubusercontent.com/120757843/208770309-41bcfe39-b2c4-4e1f-84f4-9478e6734c56.png)

but when I try to open it to my browser, it says connection refused

![image](https://user-images.githubusercontent.com/120757843/208770478-53da1bfe-2f53-4e88-9763-0d081c621951.png)

**Comment by gamerlv** [comment]
The `manage.py runserver` is only intended for development of the application, thus it only started on localhost. You tried to access it externally. For [production deployment](https://github.com/healthchecks/healthchecks#running-in-production) it is recommended to to setup a full Django stack using [uWSGI](https://uwsgi-docs.readthedocs.io/en/latest/) or [gunicorn](https://gunicorn.org/).

It may be easier to use [Docker compose](https://github.com/healthchecks/healthchecks/tree/master/docker) to setup a running instance.
