### ISSUE TITLE
API providing project information

### ISSUE THREAD

**Issue by m42e** [healthchecks/healthchecks#772]
Hi,

At the moment there is no way, using the api, to get information about the project, if only the `API key` is known.
It would be great to have access to basic project information, like:
- Project Name
- Team Access

Best
m42e

**Comment by cuu508** [comment]
Hello @m42e,

Thanks for the suggestion. What use case do you have in mind?

With "Team Access", do you mean a list of team member email addresses, and their access levels, in a JSON structure?

**Comment by cuu508** [comment]
No reply, closing.
