### ISSUE TITLE
Could not send a test notification. Connection failed.

### ISSUE THREAD

**Issue by ngosang** [healthchecks/healthchecks#775]
HealthChecks 2.5 / Docker

I have 2 integrations for notifications. I don't know exactly when they stop working but probably after update to version 2.5.
How I can debug the issue? I tried with the cURL command inside the Docker container and it's working fine.

![image](https://user-images.githubusercontent.com/10577978/212637403-1a95927b-1f78-4d6a-bf6b-e857f31d595e.png)

**Comment by cuu508** [comment]
Is Gotify running on the private network? If so, enable the [INTEGRATIONS_ALLOW_PRIVATE_IPS](https://healthchecks.io/docs/self_hosted_configuration/#INTEGRATIONS_ALLOW_PRIVATE_IPS) setting.

**Comment by ngosang** [comment]
Yeah, I will try this afternoon.
Maybe you could improve the message in the Web UI or print a log trace. Without your help I would not have been able to find the problem.

**Comment by ngosang** [comment]
It's working. Thank you!
