### ISSUE TITLE
PagerDuty Integration setup broken

### ISSUE THREAD

**Issue by revilo951** [healthchecks/healthchecks#776]
Trying to connect the PagerDuty Integration just ends up with you logged in on the PagerDuty site, it doesn't function as displayed in the HealthChecks docs.

**Comment by cuu508** [comment]
Hi @revilo951, thanks for reporting this. Just tested it and I see the same issue. I *think* it's an issue on PagerDuty side, so I'm contacting PagerDuty support.

**Comment by cuu508** [comment]
It was indeed something on the PagerDuty side, and has been fixed now – creating new PagerDuty integrations should work again now!

**Comment by revilo951** [comment]
Great, thank you!
