### ISSUE TITLE
Can't create superuser

### ISSUE THREAD

**Issue by SofianeHamlaoui** [healthchecks/healthchecks#779]
I've been trying everything to be able to create the superuser but don't know what's going wrong !! 

![](https://i.imgur.com/iST7EN3.png)

Never used Django so I had to check the documentation, but still not working !! 

Any solution or help ?

**Comment by cuu508** [comment]
Thanks for reporting, and sorry – that's a bug I recently introduced. Will get it fixed.

**Comment by SofianeHamlaoui** [comment]
> Thanks for reporting, and sorry – that's a bug I recently introduced. Will get it fixed.

Thanks, Even while using the docker image everything works perfectly if I don't add the superuser email + password. 

Hope it gets fixed ASAP.
