### ISSUE TITLE
[Bug] Overall Status Badge incorrect

### ISSUE THREAD

**Issue by boopzz** [healthchecks/healthchecks#781]
We've started using the self-hosted version due to having to maintain internal tools. I am using a kubernetes chart which pulls the linuxserver.io image so it could be the case it's a problem with the way they set their envars.

I've noticed the "Overall Status" badge matches the name of the SITE_NAME envar but shows the health of the Project as opposed to the Overall Health of the account. I'm guessing either the name of the badge should be changed to match the Project name or another badge added to show project health as well as overall health of the account.

Much love for the project, you've done great work 💪

**Comment by cuu508** [comment]
The overall status badge shows the overall status of the project. It uses the SITE_NAME value for the label. 

The thinking here is as follows: let's say you have a README doc with several badges relating to your project, but from different sources – website uptime monitoring service, cron monitoring service, CI, issue tracking service etc. If each badge used your project's name for the label, it would be hard to tell them apart. 

You can change the label of the overall status badge by setting the [MASTER_BADGE_URL](https://healthchecks.io/docs/self_hosted_configuration/#MASTER_BADGE_URL) env var, but the label will be same for all projects.

**Comment by boopzz** [comment]
Fair enough, if its intentional then thats fine. I thought it was something that was missed. I'll close the ticket. 👍
