### ISSUE TITLE
[Feature] Add ability to send RESPONSE_BODY in webhook integration

### ISSUE THREAD

**Issue by boopzz** [healthchecks/healthchecks#784]
We currently use Mattermost as our messaging system and use it for simple alerting also. Currently the Mattermost integration works but wont give the response body in a message. To give some more information with our scripts we send an error message in the body of our failed healthcheck which we'd like sent with the alert. I can see in the docs where we can use a webhook instead for the alert to Mattermost with some other placeholders.

It would be really cool to have another placeholder called $BODY or $RESPONSE_BODY that outputs the response body sent with the alert. Arguably not everyone would want this, especially if they are sending a log file to be viewed within the healthchecks webapp but thought it could be nice functionality should be fairly easy to implement.

**Comment by boopzz** [comment]
I'd like to try and help out and add this in myself as it feels like it should be a fairly quick thing but cant for the life of me find where the values are set. All the vars are fairly common words in the code base like CODE, STATUS, TAGS 😅 . Any pointers to where the current ones are?

**Comment by boopzz** [comment]
I think the functionality is there but not surfaced yet? https://github.com/healthchecks/healthchecks/blob/e5e369257c7e784ae4c0784c2f4390f0f3b57c6f/templates/integrations/webhook_form.html#L224

**Comment by boopzz** [comment]
ok cool, might it be worth surfacing a checkbox on the form to say if you want it passed or not? I guess some people would want to send a bunch of logs to the UI but not forced into sending them via the notification

**Comment by cuu508** [comment]
Potentially yes, but I'd say only if and when end users specifically request it. The Slack integration includes the last ping body with no opt-out option, and there have been no complaints.
