### ISSUE TITLE
[feature] add custom integration icon

### ISSUE THREAD

**Issue by setop** [healthchecks/healthchecks#787]
Sometime in a project you have many using integrations of the same type  like email or web-hook. Web-hook are especially useful to [integrate with tools](#689) that are not directly proposed by HC.

Unfortunately, all these integrations ends up with the same icon on the integration list :

![](https://user-images.githubusercontent.com/7794056/216041887-4608a9e8-622a-43a5-8d61-dcdabd0f0c58.png)

It would be nice to be able to customize the integration icon in order to override the default one.

For example if I use a webhook to send SMS notification, I'd like to be able to put a nice icon on it :

![](https://user-images.githubusercontent.com/7794056/216044965-5086baf8-1cce-48a7-8193-592d0e2b015e.png)

**Comment by cuu508** [comment]
The integration icons in the "My Checks" page use an icon font. This is done for performance reasons – if an account has many checks, there can be potentially hundreds of icons, and using an `<img>` element for each one can slow down the browser to the point the where it is noticeably sluggish.

The limitations of using an icon font are: each icon can have only one color, and it is not easy to add new icons. 

One thing that may help somewhat: you can give integrations names. If the integration has a name, the name will display in a tooltip when you hover over the icon.

**Comment by cuu508** [comment]
Yeah, I think it's a neat idea, but the effort to implement it, and the resulting extra complexity is not worth it.
