### ISSUE TITLE
MS Teams Integration / Test-Notification failed / no logs

### ISSUE THREAD

**Issue by zenhighzer** [healthchecks/healthchecks#788]
Hi, 

we are running healthchecks.io on-prem with docker-compose. 
We setup MS Teams Integration, but Test-Notification failed:  Could not send a test notification. Connection failed.

We cant figure out what could be the problem, because in the logs (docker-compose logs -f) we cant find anything related to teams... we also enabled the debug-mode. 

we also configured our cooporate-proxy in env-file like: 

HTTP_PROXY="http://proxy:8080"
HTTPS_PROXY="http://proxy:8080"
http_proxy="http://proxy:8080"
https_proxy="http://proxy:8080"

curl within the web-container works fine via. proxy 

Please help us :-) 

BR
Zen

**Comment by cuu508** [comment]
Look into the [INTEGRATIONS_ALLOW_PRIVATE_IPS](https://healthchecks.io/docs/self_hosted_configuration/#INTEGRATIONS_ALLOW_PRIVATE_IPS) setting – if your proxy has a private IP, you will need to set this setting to `True`.
