### ISSUE TITLE
A click is ignored in "check details view"

### ISSUE THREAD

**Issue by pmatuszy** [healthchecks/healthchecks#792]
Hello 

In the latest release clicking on that doesn't work anymore - the click is ignored. Expected action: show details of the run:

![image](https://user-images.githubusercontent.com/58336955/219385687-652e1406-f16c-4796-b754-fd0cd36b101b.png)

**Comment by cuu508** [comment]
Are there any errors in JS console?

**Comment by pmatuszy** [comment]
completely nothing in gunicorn logs (neither errorlog nor accesslog)... :-(

**Comment by cuu508** [comment]
Do you see any errors (or any other output) in your browser's JS console?

**Comment by pmatuszy** [comment]
hmmm - I can see this - will it help you to troubleshoot my issue?
![image](https://user-images.githubusercontent.com/58336955/219865044-94920a44-448f-41e1-951c-121444c35b0d.png)

**Comment by cuu508** [comment]
My guess is the JS files are out of date, try running

```
manage.py compress
manage.py collectstatic
```

**Comment by pmatuszy** [comment]
yes - thank you 
those helped:
```
manage.py compress
manage.py collectstatic
```

Question for better understanding:
1. Shall I run them at regular intervals - if so how often
2. can those commands be run while gunincorn is up and running or shall I shut down the web service?

**Comment by cuu508** [comment]
1. They should be run on every deployment (every time you upgrade to a newer version). `manage.py migrate` as well. See the [Running in Production](https://github.com/healthchecks/healthchecks#running-in-production) section in README.
2. They don't interfere with a running gunicorn process, and can be run while gunicorn is running.
