### ISSUE TITLE
"COPY URL" button doesn't work

### ISSUE THREAD

**Issue by pmatuszy** [healthchecks/healthchecks#793]
Hello
In the latest relese the "Copy URL" button doesn't work:

![image](https://user-images.githubusercontent.com/58336955/219386175-7c24028a-94bc-4e71-b1dc-a913301533b5.png)

**Comment by SofianeHamlaoui** [comment]
> Hello In the latest relese the "Copy URL" button doesn't work:
> 
> ![image](https://user-images.githubusercontent.com/58336955/219386175-7c24028a-94bc-4e71-b1dc-a913301533b5.png)

what version are you using ?

**Comment by pmatuszy** [comment]
it didn't work in my 2.6.1 installation until I run those commands:

```
manage.py compress
manage.py collectstatic
```
