### ISSUE TITLE
Please consider adding Telegram as a notification service

### ISSUE THREAD

**Issue by tessierp** [healthchecks/healthchecks#799]
This is a feature request and would like to ask you to consider adding Telegram support as a notification service.

**Comment by cuu508** [comment]
Telegram is already supported, see–

* https://healthchecks.io/integrations/telegram/
* https://github.com/healthchecks/healthchecks#telegram

**Comment by Polve** [comment]
Is it available to use it on personal custom install?

**Comment by tessierp** [comment]
> Telegram is already supported, see–
> 
> * https://healthchecks.io/integrations/telegram/
> * https://github.com/healthchecks/healthchecks#telegram

Thanks for sharing. However, what I meant was to add support directly in the UI. I'm using a docker container, linuxserver/healthchecks, which doesn't seem to have support to configure Telegram from the compose file. I could very well login to the container and activate telegram but it would be gone the next time the container restarts.

**Comment by Polve** [comment]
My bad, I didn't read carefully enough the configuration!
Thanks!

**Comment by cuu508** [comment]
> I'm using a docker container, linuxserver/healthchecks, which doesn't seem to have support to configure Telegram from the compose file. 

Did you mean to file this issue in [linuxserver/docker-healthchecks](https://github.com/linuxserver/docker-healthchecks) but filed here by error?

**Comment by tessierp** [comment]
> > I'm using a docker container, linuxserver/healthchecks, which doesn't seem to have support to configure Telegram from the compose file.
> 
> Did you mean to file this issue in [linuxserver/docker-healthchecks](https://github.com/linuxserver/docker-healthchecks) but filed here by error?

I meant this one https://hub.docker.com/r/linuxserver/healthchecks but we are talking about the same thing. linuxserver/healthchecks is the name of the image.

**Comment by cuu508** [comment]
@tessierp I do not maintain the linuxserver image, it is a separate project. To fix issues with it, or receive support regarding it, you will need to work with the LinuxServer team.
