### ISSUE TITLE
Error `argument --port: expected` when build docker version of Healthchecks

### ISSUE THREAD

**Issue by djacquensf9** [healthchecks/healthchecks#803]
Hi,

I tried to build the latest docker version of Healthchecks (using `docker compose up`) but I have every times an error: `manage.py smtpd: error: argument --port: expected one argument` (see picture)

![image](https://user-images.githubusercontent.com/61232255/225660969-eb9fe830-2d1c-4a84-a392-a966a183335d.png)

Do you have an idea what could be going wrong?

Thanks,

David

**Comment by cuu508** [comment]
In the .env file, please comment out or remove the `SMTPD_PORT=` line.

**Comment by djacquensf9** [comment]
Thank you so much !! 
You are my Piotr Ugrumov !! 😉
