### ISSUE TITLE
SMTP with fastmail not working

### ISSUE THREAD

**Issue by ramlev** [healthchecks/healthchecks#804]
I have installed healthchecks on my own server with docker, and i cannot get the smtp to work.

I have these settings in the environment section in docker-compose.yml

```
- EMAIL_HOST=smtp.fastmail.com
- EMAIL_PORT=465
- EMAIL_HOST_USER=me@host.com
- EMAIL_HOST_PASSWORD=my-secret-smtp-password
- EMAIL_USE_TLS=False
- EMAIL_USE_SSL=True
```

and i dont get any email when trying to enable OTP or any email reports, what am i doing wrong

**Comment by KiwiActinidia** [comment]
I have the same problem with a self-hosted email server

**Comment by cuu508** [comment]
@ramlev can you test if these credentials work for sending email from the same machine, but from any software other than Healthchecks?

**Comment by ramlev** [comment]
It does
