### ISSUE TITLE
Trello Integration returning error 400

### ISSUE THREAD

**Issue by daviewales** [healthchecks/healthchecks#806]
I'm trying to setup a Trello integration, but it's returning error 400.

## What works:

I can click the integration, authorise Healthchecks access to Trello, and even select a Trello board and list:

![image](https://user-images.githubusercontent.com/2499066/226219710-73b4dc13-756c-417f-b2e4-3f0c91b11eaf.png)

## What doesn't work

After I click the 'Save integration' button, I get error 400 from the POST to `https://healthchecks.io/projects/abc-123/add_trello/`
(Note: Fake project ID used in URL above)

**Comment by cuu508** [comment]
Thanks for the report.

I'd like to see the POST data in the request that returns 400. The POST data should contain an access token, the board name, the list name, and the list ID. I don't need the actual values, but only their lengths, and if any of them is empty or absent.

**Comment by daviewales** [comment]
Thanks @cuu508, here's the POST data:

```
csrfmiddlewaretoken: 64 chars
token: 76 chars
board_name: 21 chars
list_name: 26 chars
list_id: 24 chars
board_list_id: 49 chars
```

**Comment by cuu508** [comment]
Trello [increased the length of auth tokens](https://community.developer.atlassian.com/t/trello-tokens-are-getting-longer/62964). This caused our Trello onboarding form validation to fail, as it was expecting the token length to be a single, fixed value (64 characters). Fixed, and should work now!
