### ISSUE TITLE
Exit code whitelisting

### ISSUE THREAD

**Issue by quentinus95** [healthchecks/healthchecks#809]
Hello, would it be possible to have a feature that allows some non-0 exit codes to be whitelisted and considered as a success (or a warning for instance)?

I have some scripts that can end with a non-0 exit code that is not critical. It would be nice to be able to allow them and still consider execution as successful.

**Comment by cuu508** [comment]
Thanks for the suggestion. Technically possible of course, but I'm not sure how widely applicable this would be – is it common for to have scripts that return non-zero exit codes in success scenarios, and there is also no way to influence this either by passing parameters, by editing the scripts, or by using wrapper scripts with additional conditional logic?

**Comment by quentinus95** [comment]
Hello @cuu508, here is one example I have in mind: when `rsync` performs a copy of a folder (e.g., a backup) and some files are deleted before they are copied (`rsync` performs a scan of the files, then runs the backup), it may return a non 0. In some (most?) scenarios, it is fine to ignore that specific error code because it can be related to some logs that were rotated, or some lock files that were removed (which is fine when performing a snapshot).

In such situations, it would be nice to have a warning state, rather than a failure. It would allow in the previous example to say “maybe you're backing up some folders or files that should be ignored”. Those situations are fine and can be investigated later (very different from a backup that failed to execute and might require immediate action).

**Comment by davidtorosyan** [comment]
I have a similar use case, also backup related.

I expect my backup script to run successfully once a day. However, if it runs more frequently (say due to manual triggers), it'll bail out without actually doing anything.

I don't want to count this as success, but I don't want to alert on the failure either. So right now the only thing I can think to do is omit the "start" ping.

If I want to retain "start", then I'd need a way to signal that a run is canceled. Using an allow-listed non-zero status code could work for that.

**Comment by davidtorosyan** [comment]
After thinking about it more, I think I might be doing to much with healthchecks.

From what I can tell, healthchecks is best at making sure that a job is running with a given schedule (i.e. the backup job runs daily), not validating arbitrary conditions (i.e. the data that's backed up is the data I want).

That said I still do have a need for the latter, so maybe what I'll do is something like this:
```kt
/* append this to backup script described in previous comment */

backups = getBackups()
if backups.latest > ago(1d) {
  http.post("hc.com/backups_healthy/success")
} else {
  http.post("hc.com/backups_healthy/fail")
}
```

**Comment by quentinus95** [comment]
@cuu508 which alternative would you suggest?

**Comment by cuu508** [comment]
@quentinus95 if you want to treat some non-zero exit codes as success, use a wrapper script which inspects the exit code and decides whether to report success or failure to Healthchecks.

If you want additional warning state, use monitoring software that supports metric collection, and configurable alerting rules based on collected metric values. 

If you want to use something sort-of similar to Healthchecks, look into [sensorpad](https://sensorpad.io/).
