### ISSUE TITLE
HTTP request getting in queue - Self hosted healthcheck 

### ISSUE THREAD

**Issue by aftab70** [healthchecks/healthchecks#810]
Hi Team,

I am happy to use the self-hosted health checks using the Azure web app, but any time the health check runs slow and takes too much time to respond on HTTP So that's why other applications getting down like Prometheus, however, we were getting uwsgi socket limit message in docker logs, We did increase with from 100 to 1024 but still any time health check getting slow over the HTTP, Please suggest for the same.

The average HTTP request on Healthchecks is  100 to 150 per sec.

**Comment by cuu508** [comment]
Hi @aftab70, are you saying HTTP requests to your Healthchecks instance are sometimes slow, and cause issues on the clients?

**Comment by cuu508** [comment]
> The average HTTP request on Healthchecks is 100 to 150 per sec.

Do you mean you have run benchmarks, and your setup can manage 100 to 150 requests per second?

> We did not find any parameter to increase the HTTP thread count, Can you guide me on what i need to do?

Are you using the official docker image? uwsgi in the official image [is configured to run 4 processes](https://github.com/healthchecks/healthchecks/blob/master/docker/uwsgi.ini), this should be sufficient for at least a few hundred requests per second, assuming the database can keep up.

**Comment by aftab70** [comment]
Yes, We are using an official health check image with uwsgi thread count 4, Can you guide me on what kind of setting I need to do for the database connection, We are using Postgres.
