### ISSUE TITLE
Remove the '$' from the code section of the README

### ISSUE THREAD

**Issue by djacquensf9** [healthchecks/healthchecks#814]
Hi,

The actual README.md is very well but at the beginning of each code section, there are some '$' at each beginning of each line.
The issue with this is that if you wish to copy the code, you also copy the '$'.

I propose to remove these '$'.

If this is OK, I can do it quickly.

Thanks,

David

**Comment by cuu508** [comment]
Thanks, that's a good idea, fixed!

**Comment by djacquensf9** [comment]
Thank you again !!

**Comment by djacquensf9** [comment]
@cuu508, same same with the README.md in the docker directory

**Comment by cuu508** [comment]
Ah yes, fixed!
