### ISSUE TITLE
Add paho-mqtt to image to enable mqtt in Apprise

### ISSUE THREAD

**Issue by seizedengine** [healthchecks/healthchecks#818]
Trying to enable mqtts in Apprise in self hosted. It fails sending a test from the integrations page, so I found that I could test it in the container:

root@healthchecks:/# apprise -vvv -b test -t title mqtts://mqttserver/healthchecksio
2023-04-05 14:07:54,272 - ERROR - mqtts:// is disabled on this system.
2023-04-05 14:07:54,272 - ERROR - There are no service(s) to notify

Which lead to:

root@healthchecks:/config# apprise -l
- MQTT Notification              
   Python Packages Required:
     - paho-mqtt

Any chance paho-mqtt could be added to the image?

Thank you for the great product! Ive used the free tier for a long time and it has always been excellent.

**Comment by cuu508** [comment]
You can build a custom image that extends the standard image, and adds the `paho-mqtt` package. I think a Dockerfile like this should work:

```dockerfile
FROM healthchecks/healthchecks
RUN pip install paho-mqtt
```
