### ISSUE TITLE
Hosting under a subpath does not work well

### ISSUE THREAD

**Issue by spantaleev** [healthchecks/healthchecks#822]
I'm trying to host Healthchecks under a subpath like `/healthchecks` and I'm using the following configuration:

Environment variables:

```
SITE_ROOT=https://DOMAIN/healthchecks
SCRIPT_NAME=/healthchecks
```

`local_settings.py` mounted to `/opt/healthchecks/hc/local_settings.py` in the container image:

```python
FORCE_SCRIPT_NAME = "/healthchecks/"

STATIC_URL = "/healthchecks/static/"
```

----

I think that adding `/healthchecks` to `SITE_ROOT` may be unnecessary. Perhaps defining the `SCRIPT_NAME` environment variable does nothing as well.

Nevertheless, `FORCE_SCRIPT_NAME` and `STATIC_URL` are obeyed.

---------

With this configuration, I also needed to configure my reverse-proxy to:

- preserve the `/healthchecks/static` prefix intact
- strip the `/healthchecks` prefix from all other (non-static file) requests

What **works**:

- `/healthchecks/` redirects to `/healthchecks/accounts/login/`, as expected
- `/healthchecks/accounts/login/` is rewritten to `/accounts/login/` by the reverse-proxy and serves a page, as expected
- links on the page have the `/healthecks` prefix, as expected
- links to static files have the `/healthecks` prefix, as expected. If I hadn't redefined `STATIC_URL` with my custom `local_settings.py` file, this wouldn't have been the case.
- requests for static files (e.g. `/healthchecks/static/CACHE/css/output.c2fb96c40f0a.css`) are kept as-is (no stripping of the prefix), and are served, as expected. Note that if we strip the prefix (like we do for other URLs), we'll get 404s

What **doesn't** work:

- the CSS file hardcodes font paths as `/static/..`, not `/healthchecks/static/..`

Because of this, fonts can't load, which breaks various icons and makes the system unusable.

-----

Is there a way to make the generated CSS file actually use relative URLs, not absolute ones? Or to make it obey `STATIC_URL`?

**Comment by cuu508** [comment]
As an experiment, I added to my local_setting.py:

```
STATIC_URL = "/foo/static/"
```

I ran `manage.py collectstatic` and `manage.py compress`. 

In HTML pages, I now see CSS includes with the /foo/ prefix:

```
<link rel="stylesheet" href="[/foo/static/CACHE/css/output.880e75aea7f0.css](view-source:http://localhost:8000/foo/static/CACHE/css/output.880e75aea7f0.css)" type="text/css">
```

In the CSS file, I see fonts referenced with the `/foo/` prefix:

```
@font-face{font-family:'icomoon';src:url('/foo/static/fonts/icomoon.ttf?bncoc2&fc585b7120f2') (...)
```

One thing to try, if you haven't done it yet, is to run `manage.py collectstatic` and `manage.py compress`.

**Comment by spantaleev** [comment]
I haven't tried these. Thanks for the pointers!

This may work, but it's problematic, because:

- my container runs with a `--read-only` filesystem, so these files aren't writable
- my container runs with a non-root user (`--user=...`), so it can't write to these files even if they're not readonly

Looks like solving it this way will require both some hacks (`--entrypoint=/bin/sh` + `-c "python /opt/healthchecks/manage.py collectstatic --no-input && python /opt/healthchecks/manage.py compress && uwsgi /opt/healthchecks/docker/uwsgi.ini"`) and also decreasing security.

I was considering doing a `sed`-replace instead of running these `manage.py` commands, but.. these files are not writable due to the read-only filesystem anyway, so that's another no-go. Seems like the `/opt/healthchecks/static-collected` files are all `root:root`-owned too.

**Comment by cuu508** [comment]
Looking at [django-compressor docs](https://django-compressor.readthedocs.io/en/stable/settings.html) there might be a way to generate relative paths to the font files – use `CssRelativeFilter` instead of `CssAbsoluteFilter`. I'll look into that.

Assuming relative paths work, I think the prebuilt CSS would work regardless of the STATIC_URL value at runtime.

**Comment by cuu508** [comment]
I pushed a change which switches CSS bundles from using absolute file paths to using relative file paths.

I'm not planning to do a new release soon, but in the meantime you can build an image yourself: clone the repository and from its root directory run

```
docker build -t healthchecks:v2.9-dev -f docker/Dockerfile .
```
