### ISSUE TITLE
Tags and sorting can't work together

### ISSUE THREAD

**Issue by solracsf** [healthchecks/healthchecks#828]
To reproduce:

1. Create at least 2 tags (here backup and cron)
2. On the Jobs list, click on a tag (here backup)
3. Try to sort (by Name, or by Last ping)
4. It sorts all jobs, not only the selected tag

It works in the other way (sort first, select Tag afterwards)

![image](https://user-images.githubusercontent.com/12234510/236925573-73209c9d-2a10-456f-8425-e6127b4ace63.png)

**Comment by cuu508** [comment]
Thanks for the report – fixed!
