### ISSUE TITLE
Problem with grace period

### ISSUE THREAD

**Issue by hamx01** [healthchecks/healthchecks#830]
Hi! 
I'm using HC to monitor some cronjobs on prod server. Check is configured with cron expression.
And the issue is (as I understood) that check is waiting for `/success` code at the times indicated, but receives `/start` signal and because of this check is always late, all the time. And on this “fake” check late, there are false alarms. As you can see from cron expression, the last cronjob is starting at 22:51 and the next is at 5:21. I understand that I can set grace time like to 7 or 8 hours, but when I'm actually will have problem with cronjob it will not inform me about it.
![image](https://github.com/healthchecks/healthchecks/assets/101278038/9adc0652-d12a-45a5-8227-b8d1de5d75c5)
The strange thing is also that check receives OK signal at 22:51 but started counting grace time. Maybe it is related to the fact that I'm using `/0` signal instead of `/success`?
![image](https://github.com/healthchecks/healthchecks/assets/101278038/4b9bbfa6-f8ee-42d3-a409-ed6f89f4fe1d)
I will be graceful if you will help me with this problem.

**Comment by cuu508** [comment]
Hi @hamx01, the screenshot shows the OK signal arrived at 22:50, a minute early.

Healthchecks expects a ping at 22:51 (the one received at 22:50 does not count). There's no OK signal at or after 22:51, and so after the grace time passes (is it 6 hours?), it sends out a notification.

**Comment by hamx01** [comment]
@cuu508
Yes, it is actually 6 hours.
![image](https://github.com/healthchecks/healthchecks/assets/101278038/7b99d0e8-8e97-47ae-8c20-fc54a65fa6cc)
Ok, I was trying to set expression a one minute earlier, but then the problem is that cronjob is running for about 20–30 minutes. And for example at 22:50 it receives `/start` and at 23:14 `/success`. And all the time between 22:50 and 23:14 check is late, and it is weird for me because `/start` signal was received then process is running, and you just need to wait for `/success`, without alert that check is late but with "Running" status.

**Comment by cuu508** [comment]
The **cron expression** specifies when Healthchecks expects the pings to arrive. The **grace time** is the additional time Healthchecks waits for a job that is late (probably still running) before declaring it failed and sending out alerts.

> and you just need to wait for /success, without alert that check is late but with "Running" status.

Healthchecks does not send alerts when the grace period starts. A check can be both "running" and "late" at the same time, this is indicated by an amber icon with the animated progress spinner under it.

I'm assuming you interpreted the amber icon as "something is slightly wrong", while things were still perfectly fine and working as expected, right? I'm open to suggestions and ideas – how would you like this to ideally work?
