### ISSUE TITLE
Get by slug

### ISSUE THREAD

**Issue by scheibling** [healthchecks/healthchecks#844]
With it now being possible to create a check with a specific slug instead of auto-generating it, it would be really helpful to have a get endpoint in the v3 API that supports accessing a specific slug.

Just saw that the auto-provisioning is now enabled which is nice as well, we're currently creating checks via the API if it doesn't exist and are using the Tag-field as a unique "external" identifier (which means list -> get first result), the by-slug endpoint would be a much better solution

**Comment by cuu508** [comment]
Slugs are not guaranteed to be unique, so a "get by slug" call could have 0, 1 or N matches. 

The "List Existing Checks" API call currently supports filtering by tag:

```
https://healthchecks.io/api/v3/checks/?tag=foo&tag=bar
```

We could add an option to filter by slug as well:

```
https://healthchecks.io/api/v3/checks/?slug=my-custom-slug
```

Would that help?

> Just saw that the auto-provisioning is now enabled which is nice as well

Yep! But, note, this change has not yet been deployed to the hosted service.

**Comment by scheibling** [comment]
The slug is unique per project though, right?

I opened a pull request with an example, feel free to have a look at it and push it in if you want, I'm gonna try it out locally on our instance since it saves us a couple of requests for some of our checks.

**Comment by cuu508** [comment]
No, there is no uniqueness constraint for slugs even within a single project. Multiple checks can have slug, a check can have an empty slug. 

I just pushed a commit which adds filtering by slug to the "List Checks" call:

```
http://healthchecks.io/api/v3/checks/?slug=foo
```
