### ISSUE TITLE
SMTP Server Setup for receiving Pings

### ISSUE THREAD

**Issue by djarbz** [healthchecks/healthchecks#867]
I have been fighting with this all afternoon.
I have email notifications working, but I am unable to receive emails on my instance.

If I Telnet in, I can dump an email, but if I send an email from say my Gmail account, my instance will never receive it.
Actually, in Google Workspace, it will say rejected: `The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 [healthchecks.example.com. <REDACTED IP ADDRESS>: FAILED_PRECONDITION: connect error (111): Connection refused]`

I know that my service is listening on port 25 and reachable externally, tested via telnet on a remote VPS as my ISP blocks port 25.

**Comment by cuu508** [comment]
Can you test with a few other mail providers besides Gmail, to see if it's something Gmail-specific?

**Comment by djarbz** [comment]
Gmail is the only service that I have access to the server side logs to.
I did test with my work email and it bounced as well.

**Comment by cuu508** [comment]
Does sending test email from here work? https://sendtestemail.com/

**Comment by djarbz** [comment]
Unfortunately it did not work.

```
Date:
Jul 31 07:23:07

Email To:
8a6bf565-6ae0-4625-b54c-bca255df8654@<REDACTED>

Relay:
none

Connection Set-up Time:
0s

Send Time:
0s

Delivery Status Notification:
4.4.2

Status:
deferred

Email ID:
c07decfebaa4cee7e92b2437c192858d
```

This tool did work however: https://www.smtper.net/
I filled out the host/port/from/to fields.

**Comment by djarbz** [comment]
In my registrar I do have the following records.
A - example.com --> server IP (ideally I would like this one to go away)
A - healthchecks.example.com --> server IP
MX - healthchecks.example.com --> healthchecks.example.com priority 10

**Comment by cuu508** [comment]
In https://www.smtper.net/ the default port is 25 – did you leave it as-is, or did you specify a different port?

**Comment by djarbz** [comment]
I did use port 25.

**Comment by cuu508** [comment]
I'm not sure what to make of it – perhaps the server running your Healthchecks instance has port 25 blocked to/from some destinations but not all?

**Comment by djarbz** [comment]
This is really weird, I just got a bunch of emails to come through on my test check.

Thing is, I didn't change anything...

**Comment by cuu508** [comment]
Another guess – perhaps it's something to do with DNS caching? 

Say, if you were changing the A and MX records for healthchecks.example.org, perhaps the old values were still in some DNS resolver caches. Once the cached values expired, the deferred emails could come through?

**Comment by djarbz** [comment]
I haven't touched them since Friday.

**Comment by djarbz** [comment]
Yeah, I think I can close this out. I just wish I knew what the issue was.
