### ISSUE TITLE
Feature Request: Remove version from footer and update notification

### ISSUE THREAD

**Issue by jl-678** [healthchecks/healthchecks#868]
Hi,

I have a couple of enhancement suggestions:

1. I notice that HC prominently shows the running version in the footer on the public page. I remove this by editing the master template file because it feels to me like a security risk. (e.g. if someone knows the version that could potentially help with some form of attack.) Admittedly, I might be overthinking this, but I want to do whatever I can to make would-be attackers life more difficult. Can we add an option to hide it?

2. There are frequent updates to the product which is great. Thank you! Can you put a banner in the product dashboard somewhere to alert on the new version? It would be easier than having to check github periodically.

TIA!

**Comment by cuu508** [comment]
1. I suppose we could, but note that the attacker can still determine the version of a running Healthchecks instance fairly easily by checking the filenames and file contents of CSS and JS bundles. OTOH the version number in footer is handy when troubleshooting ("am I running the image I think I'm running?", "am I looking at the right IP?", "is there still a dangling old container running, which I might be looking at right now?", and so on).

2. In GitHub repository page, if you select "Watch" - "Custom" - "Releases",  you will receive notifications from GitHub on every new release: 

![image](https://github.com/healthchecks/healthchecks/assets/661859/55b3fd39-496f-4d66-846b-64b8fa00fb72)
