### ISSUE TITLE
Feature request: SLA availability computation

### ISSUE THREAD

**Issue by rudolf-bauer** [healthchecks/healthchecks#874]
According to my SLA with a customer, I need to compute the monthly availability (uptime) of my services. Some of them are monitored by healthchecks on a per-minute basis. Threfore, I used the management API to get all flips of the corresponding checks and compute the downtime in a specified time range. Does it make sense to add such a page (html/pdf) to healthchecks? E.g. in the check's details?

Off-topic: I love healthchecks, great product!

**Comment by cuu508** [comment]
In the check details pages we already display the number of downtimes and the total duration of downtimes for past 3 months:

![image](https://github.com/healthchecks/healthchecks/assets/661859/7e1d25e8-de94-4a44-a28b-1f48f2c0d450)

Using the data already there, it would be easy to also calculate uptime as percentage. In the above example, where it says "21 hours total", we could calculate the uptime percentage as 21 / (31 * 24) = 2.8%, and show it as: "2 downtimes, 21 hours total (97.2% uptime)".

Would something like this work? 

When calculating SLA, do you calculate it for every month separately, or do you calculate it for a sliding window of last 30 days?

**Comment by cuu508** [comment]
No reply, closing.
