### ISSUE TITLE
Tags with Values

### ISSUE THREAD

**Issue by djarbz** [healthchecks/healthchecks#875]
I would like to be able to assign a tag with a value.

Currently, for my Proxmox backups I tag "VMID=1234".
This gets unruly quite quickly and it would be nice to have a tag "VMID" that then has filterable values of the actual VMID.
Same with the PVE Node.

Perhaps show the tag with a small down arrow to the right to open a drop down listing the possible values we can filter by.

**Comment by cuu508** [comment]
Thanks for the suggestion. That is an interesting idea, but tags with values would not be classic tags (short alphanumeric labels) any more, but more like custom filters.

Ideas for organization:

* omit the "VMID=" part in the tag
* put stuff like IDs in check's name, use the search box for filtering
* use multiple projects to separate unrelated checks
* if you intrinsically need to slice and dice the data in many different ways, look into building a custom dashboard, or exporting data to a spreadsheet or a SQL database
