### ISSUE TITLE
Mobile Friendly Email

### ISSUE THREAD

**Issue by djarbz** [healthchecks/healthchecks#876]
When I look at the weekly report email, it is formatted for desktop mode and very hard to read on mobile.

**Comment by cuu508** [comment]
@djarbz can you please forward an example of a problematic report email to contact at healthchecks.io? Thanks!

**Comment by djarbz** [comment]
I sent it in yesterday morning with the subject of this GH Issue, let me know if you don't get it.
Also, I'll note that it wasn't the weekly report but rather the reminder email.

**Comment by cuu508** [comment]
Thanks–I did receive your forwarded report.

The problem I see is that your checks use many and long tags. The report template tries to show the all on a single line, which causes issues. This is not a mobile-specific issue, the tags list does not fit on my desktop display either.

**Comment by djarbz** [comment]
I never would have thought of that.
Thanks, I'll revisit my tagging.
