### ISSUE TITLE
Feature request: Ntfy token authorization and cert no verification option 

### ISSUE THREAD

**Issue by sebeksd** [healthchecks/healthchecks#879]
Right now Ntfy integration do not have any authorization. It would be nice if there was a field to provide authorization token.
I'm using Ntfy with tokens in few other places (self hosted Ntfy).

Ntfy supports Tokens or User+Password authorization.
https://docs.ntfy.sh/publish/#access-tokens

Also it would be great if Ntfy (and probably all other http/s integration) supported "no cert verification" option. Unfortunately LetsEncrypt (self hosting) certs are not liked by curl and python (maybe Linux in general?), while web browsers have no problem with them.

Edit:
Problem with LetsEncrypt cert was because I was using cert without fullchain (parent certs).

**Comment by cuu508** [comment]
> It would be nice if there was a field to provide authorization token.

Thanks for the suggestion, I will look into that.

> Unfortunately LetsEncrypt (self hosting) certs are not liked by curl and python (maybe Linux in general?)

Can you point me to a HTTP endpoint with a LetsEncrypt certificate that Healthchecks.io (the hosted service, or the official Docker image) has problems with?

**Comment by sebeksd** [comment]
> Can you point me to a HTTP endpoint with a LetsEncrypt certificate that Healthchecks.io (the hosted service, or the official Docker image) has problems with?

Right now no. I could not test Ntfy because lack of Authorization token but I assumed that after adding it it will start to have a problem with cert (other services have this problem).

I will try to make Ntfy with no token required and test it. So sorry for thinking into the future without checking it :(

**Comment by sebeksd** [comment]
Clean install of Ntfy without any authorization enabled (default setting from ntfy docker image):

![image](https://github.com/healthchecks/healthchecks/assets/18705953/6995f933-26fb-4e50-9e07-f49703cf2b70)

Certs are provided by LetsEncrypt, https is done by Traefik (both in docker).

**Comment by cuu508** [comment]
Can you provide me with an HTTP address that I can play around with? You can share it privately via email to contact at healthchecks io.

**Comment by sebeksd** [comment]
Done, you should have an email with url.

**Comment by Tarow** [comment]
I also just stumbled across this with a similar setup.

While Authentication is not yet implemented for ntfy, as a workaround/different approach [enabling Apprise](https://healthchecks.io/docs/self_hosted_configuration/#APPRISE_ENABLED) could be a solution in the meantime. With an URI like `ntfy://{token}@{hostname}/{topic}` it works perfectly fine. For the hostname, i am just using the internal service name, since `ntfy` and `healthchecks` are in the same Docker network.

Additional docs [here](https://github.com/caronc/apprise/wiki/Notify_ntfy).

**Comment by sebeksd** [comment]
Thanks to @cuu508 I was able to pinpoint problem with my LetsEncrypt cert and why curl/python (and others) didn't like it.
Problem was I was using certificate without full chain (parent certificates). For some reason browser did not care about that but other tools did. So my statement about about LetsEncrypt certs in my first message was false.
