### ISSUE TITLE
Login Issue Arising After Creating Two Profiles with the Same Email

### ISSUE THREAD

**Issue by yahyamlaouhi** [healthchecks/healthchecks#880]
I encountered a problem related to the login functionality on the platform. It seems that there's an issue when attempting to log in after creating two user profiles with the same email address.

![Screenshot from 2023-08-20 14-59-09](https://github.com/healthchecks/healthchecks/assets/57452767/ca413266-9808-4f89-8f4d-3f4d7b62660b)

**Comment by yahyamlaouhi** [comment]
i have fixed the issue for multiple account with the same users if you want to do a pull request and you can review my code

**Comment by cuu508** [comment]
> It seems that there's an issue when attempting to log in after creating two user profiles with the same email address.

How did you create two user profiles with the same email address? (did you use the signup form, the `createsuperuser` management command, something else?)

**Comment by cuu508** [comment]
Ah, thanks, I see – I've now updated `createsuperuser` to reject already registered email addresses.

**Comment by cuu508** [comment]
PS – another preventive measure you can do is to add an uniqueness constraint on the email column in the database: https://github.com/healthchecks/healthchecks/issues/290#issuecomment-541303752
