### ISSUE TITLE
Is this repo is presently also open for contribution?

### ISSUE THREAD

**Issue by Kunal7069** [healthchecks/healthchecks#887]
I want to confirm if this repository is open for open source contribution or not?

**Comment by cuu508** [comment]
Yes – see https://github.com/healthchecks/healthchecks/blob/master/CONTRIBUTING.md

**Comment by Kunal7069** [comment]
See I am new to open source but want to really contribute in your repo 
So can you please give me some brief about your repo means what it is all about?
I will be highly obliged to you

**Comment by cuu508** [comment]
Please start by reading the README: https://github.com/healthchecks/healthchecks/blob/master/README.md
I'm happy to answer specific questions.

**Comment by Kunal7069** [comment]
Ok thanks sir
