### ISSUE TITLE
Unable to configure ntfy access token

### ISSUE THREAD

**Issue by miversen33** [healthchecks/healthchecks#891]
With commit [bbb06ff](https://github.com/healthchecks/healthchecks/commit/bbb06ff358226ba2c3a5f2b4e526eb2ab8ca3ce2), the ability to use an access token with healthchecks appears to have been added. However, when using the "latest" docker image [sha256-9b7323e548076857ac465f3d4dd2e9acc45da5ce387dc83a64e14285204df759](https://hub.docker.com/layers/healthchecks/healthchecks/latest/images/sha256-9b7323e548076857ac465f3d4dd2e9acc45da5ce387dc83a64e14285204df759?context=explore),l this option is not available

![image](https://github.com/healthchecks/healthchecks/assets/2640668/5ea3e8e1-8598-4383-89fa-570f30292f30)

This makes some sense as it appears the latest docker image (linked above, at the time of this issue submission) was built 2 months ago
![image](https://github.com/healthchecks/healthchecks/assets/2640668/0dd48091-8a18-45c1-817b-f66638d9eabd)

Whereas the commit in question was added a handful of weeks ago. Is there a release schedule for when the released docker image is built?

As a workaround, I am sure I can just pull down the repo and build my own image. I would just rather _not_ do that if an image is readily available

**Comment by cuu508** [comment]
The latest release is v2.10, it was released in July 2. The ntfy token authorization was added after that, and will be available in the next release.

There isn't a specific release schedule. I usually make releases when there is a good amount of new or improved features. Usually this is every 1-2 months.

You could build your own image now, and switch to a pre-built image after the next release.
