### ISSUE TITLE
smtp Failed; 5.4.0 (other or undefined network or routing status)

### ISSUE THREAD

**Issue by odtgit** [healthchecks/healthchecks#892]
My smtp healtcheck has been failing for some 22 hours without any known configuration changes on my end. I use an ISP relay (mailout.telia.com) and it's returning now a mailer-daemon error. Just before I start looking at their support options, posting this issue to check if it might actually be some configuration change on hc-ping.com MX?

From: Mail Delivery Service <MAILER-DAEMON@telia.com>
Subject: Delivery Status Notification
To: ###
Date: Wed, 13 Sep 2023 14:25:43 +0200
Message-ID: <64171A4007A9F9E7@ts201-smtpout73.ddc.teliasonera.net>
X-CP-Transaction-ID: 64171A4007A9F9E5
X-CP-For: ###@hc-ping.com
MIME-Version: 1.0
Content-Type: Multipart/Report; report-type=delivery-status; boundary="========/64171A4007A9F9E5/ts201-smtpout73.ddc.teliasonera.net"

--========/64171A4007A9F9E5/ts201-smtpout73.ddc.teliasonera.net
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

 - These recipients of your message have been processed by the mail server:
###@hc-ping.com; Failed; 5.4.0 (other or undefined network or routing status)

--========/64171A4007A9F9E5/ts201-smtpout73.ddc.teliasonera.net
Content-Type: Message/Delivery-Status

**Comment by cuu508** [comment]
Yes, I've made several changes to the SMTP service recently:

* The SMTP service now suports STARTTLS (but still allows unencrypted communication as before)
* I removed DNS MX records for the hc-ping.com domain. 

From the bounce message it is not clear which change is the culprit and why. 

FWIW I've tested email delivery from Gmail and Fastmail.

**Comment by odtgit** [comment]
Thanks for the info, changed to use gmail relay for now.

**Comment by MichealDavid1** [comment]
I was having issues like this with gmail until I setup my gmail (Delivery mail) to use token instead of password

**Comment by cuu508** [comment]
@MichealDavid1 this issue is about a previously known good and working setup breaking on September 12, due to changes on hc-ping.com side (added STARTTLS support, removed MX records). Did you also have a working setup that broke around September 12? If not, you are probably describing a separate issue.
