### ISSUE TITLE
[feature] integration groups / tagged integrations

### ISSUE THREAD

**Issue by apollo13** [healthchecks/healthchecks#894]
It would be great to be able to tag integrations and then instead of enabling integrations manually for checks one could enable all integrations by simply enabling a tag. This would also be nice to have for auto provisioning of checks while being able to enable a set of integrations?

What do you think? I should be able to provide the code if that is something you'd like to have.

**Comment by cuu508** [comment]
This is an interesting idea but I think figuring a reasonable UI / UX would be challenging:

* If implemented naively (user can specify tags for checks, user can specify tags for integrations, and that's it UI-wise), users can assign integrations by accident. If I'm working in somebody else's project, whenever I add a tag, I would have to cross-check if it has a side-effect of enabling some integrations.

* If there are more than a couple integrations, and more than a few tags, it could be cumbersome for the user to figure out which integrations will get enabled by a given tag combination.

* We currently assign integrations to checks using a many-to-many relation. This mechanism would still need to work, and it would need to be made clear to the user how the two mechanisms interact. 

I think the idea of matching checks with integrations using tags sounds good when starting a new project, and planning out the project structure from scratch. But as the project grows and evolves it could become a pain. Changing any tags would be risky as it could enable or disable integrations in unintended ways. You could decide on a tag naming convention, but then your team mate comes in, they do not know about the convention, and makes mess of things...

**Comment by apollo13** [comment]
> If implemented naively (user can specify tags for checks, user can specify tags for integrations, and that's it UI-wise), users can assign integrations by accident.

Oh I didn't expect them to "auto-assign" like that. Ie the tags of the checks and the tags of the integrations would not have any relation to each other. One would have to explicitly enable a notification tag in the check settings instead of manually enabling an integration (or if wanted in addition to).

> If there are more than a couple integrations, and more than a few tags, it could be cumbersome for the user to figure out which integrations will get enabled by a given tag combination.

Yes, probably. So let me try to rephrase what I am trying to achieve. Assume we have two classes of checks; one are non-critical checks where the notifications should go to a $chat channel and critical checks where the notifications should go to a webhook and pagerduty. As it is currently I have to remember which integrations to assign to which check. If it were possible to select an "integration group" or "integration tag" as notification target of a check (independent of the tags of the checks itself) I would get the following features:

 * Chances of miss-assigning integrations to checks are reduced, especially when there are many integrations available since I could just assign "critical notifications" to a check without having to know the details of the integrations.
 * As an admin I could adjust the "critical notifications" group one time when we switch from pagerduty to victorops (just as an example) without having to go into every check.
 * For auto-provisioning it would provide a nice way to select a set of integrations for the check as opposed to simply enabling them all.

Does that make more sense and eliminate some of your concerns about unintended changes to notifications?

**Comment by cuu508** [comment]
Thanks, I now understand your suggestion better: allow users to create groups of integrations (with tagging being one way to define groups), then let users use groups the same way as they would use regular integrations.

Off the top of my head, one way this could work would be a new integration type in the list of available integrations: "Group". When adding the "Group" integration, users would select the existing integrations to be included in the group. Afterwards the group integration could be used as any other integration.

**Comment by apollo13** [comment]
Yes a group integration would work. The only downside I see there is that UI wise it would be "just" another integration (unless we special case it). I'd love for the group selection to be visible prominently so the users will opt for the groups instead of individual integrations (which would probably the main usecase once groups are defined in a team).

I suggested the use of tags for grouping since there is already precedence for it on the checks page and the same filtering code etc could probably be reused and it would not require a new concept to be introduced.

That said I'll be happy with whatever you would prefer and will get coding once we have decided on a model.

Regarding the Integration-Type "Group": Would that have a m2m table to the integrations, or would you want to de-normalize that? Should it be possible to add groups to groups?

**Comment by cuu508** [comment]
> I suggested the use of tags for grouping since there is already precedence for it on the checks page and the same filtering code etc could probably be reused and it would not require a new concept to be introduced.

My worry is that if integrations can be tagged, and especially if the tagging and filtering interface is similar to the checks, there could be confusion on whether check and channel tags are in any way related (like I had initially :-). 

On the other hand, I think many users would intuitively "get" the Group concept – it would be similar to UNIX groups where a system user can belong to multiple groups, or to chat groups in chat apps where you can create the group and then pick the users to be invited into the group. 

Some ideas on how to make groups more prominent:

* Allow users to change the order of integrations (currently they are displayed in the creation order, the order cannot be changed)
* Alternatively, show groups before normal integrations. Similar to how file browsers sometimes sort folders before regular files.
* When creating or editing a group, let the user specify its icon from a list. Or, perhaps, use a fixed icon but let the user pick its color from a fixed set of choices.

But I think these could come later, not in the initial implementation.

> Regarding the Integration-Type "Group": Would that have a m2m table to the integrations, or would you want to de-normalize that? Should it be possible to add groups to groups?

Pros for de-normalization (let's say, a channel's value field is a comma-separated list of other channel UUIDs):

* no schema changes needed
* unlike m2m, the data model cannot express weird states where a non-group integration (say, email) has group members

Cons:

* When deleting an integration via UI or API we would also want to update any group integrations that have it as a member
* No help from Django ORM for loading group members 

Having not written any code, just thinking over it, I'm leaning towards the de-normalization approach. It would require a bit more code for loading group members, and for cleaning up groups when integrations are are removed. But I think the extra code would be relatively simple and more explicit.

**Comment by apollo13** [comment]
> My worry is that if integrations can be tagged, and especially if the tagging and filtering interface is similar to the checks, there could be confusion on whether check and channel tags are in any way related (like I had initially :-).

Yes, that is a valid concern. Though I would argue that since english is my second language my initial post was also badly worded to convey the concept.

> Having not written any code, just thinking over it, I'm leaning towards the de-normalization approach. It would require a bit more code for loading group members, and for cleaning up groups when integrations are are removed. But I think the extra code would be relatively simple and more explicit.

Ok, I will see if I can come up with a prototype.

**Comment by cuu508** [comment]
> Should it be possible to add groups to groups?

I'd say, to keep group member lookups simple, at least initially – no.

**Comment by apollo13** [comment]
I have pushed a really really MVP for groups: https://github.com/healthchecks/healthchecks/commit/7024c9412c52d35bf6fa318bd2be2eab33ab712a

It seems to work okayish. A few things that I noticed:

 * It is not exactly clear what `Channel.last_error` should get set to if multiple integrations fail
 * An integration might get called multiple times if it is activated manually and via the group (though that might be okay)
 * I have no idea how I can add/get a group icon for icomoon

If you find some time to look over the code please let me know if that is what you envisioned and I'll try to push it further (ie full functionality, cleanups & tests)

**Comment by cuu508** [comment]
> Yes, that said I think the validation is already done by the form since you can only use the choices from the field which is already limited to the project.

Ah, right, I didn't think of that.

> Can we just leave the old uuids (they would automatically get removed once the user resaves the group)?

I think yes. It would be hard to guarantee that we always clean them up (when deleting a channel from UI, when deleting a channel via API, when deleting it via Django admin, when deleting it with a manual SQL query). So we would want the code be able to cope with UUIDs of non-existent channels anyway. One downside is we cannot accurately tell the group's member count just by counting the UUIDs, have to keep that in mind.

**Comment by apollo13** [comment]
I think I have addressed all comments in #901. I have also put the groups to the front (visually) if they are defined:
![image](https://github.com/healthchecks/healthchecks/assets/81547/ca46b122-9779-478f-87c1-7557a24358e7)

I think functionality wise we are done here. Can you checkout my branch, click it through and if you like it I will add the missing tests. It would be great if you could do the icon updates and select a proper icon for the group as well as an IcoMoon icon.

**Comment by cuu508** [comment]
I like it and it indeed looks complete functionality-wise.

I have a few minor code suggestions, and a couple UI ideas.

Code:

There's a bit of code repetition when selecting channels in `Channel.group_channels` and in `group_form` view. If `Channel.group_channels` returned a queryset, GroupForm could use that:

```python
# in hc.api.models, Channel class:
@property
def group_channels(self) -> QuerySet[Channel]:
    assert self.kind == "group"
    return self.project.channel_set.filter(code__in=self.value.split(","))
```

```python
# in hc.front.views, group_form view:
channels = list(channel.group_channels.values_list("code", flat=True))
form = forms.GroupForm({"channels": channels}, project=channel.project)
```

UI:

I like your idea of showing the group notification separately from the other integrations in the Check's Details page. I think it would be good to use the same sort order (groups first) also for the icons in the checks list, and in the integrations list:

![image](https://github.com/healthchecks/healthchecks/assets/661859/1550344b-7e1d-44cc-ac1f-9f9aac3d4fb3)

When adding a new group, I think the user will likely also want to name it. We could let the user do it in a single step, while adding the group, by adding a "Label" field in the form. The SMS integration, for example, already does it:

![image](https://github.com/healthchecks/healthchecks/assets/661859/87d996cb-97a9-41a6-add0-fe598779a1a0)
 
And, finally, a tricky one – in the group form, I would like every group member candidate to display its icon, its name, and perhaps some additional details about it, to help the user pick the right members. The select-multiple control has very limited styling options, so I think we would need to use checkboxes. I did a couple quick experiments. 

Checkboxes with icon and name:

![image](https://github.com/healthchecks/healthchecks/assets/661859/a6cf8da1-51e2-4b33-afcb-8f8d5a507fde)

This should be relatively easy to implement, but the checkboxes next to the icons look a bit off, and we are still limited in how much information we can display per item.

Hidden checkboxes, labels styled to look like selectable tiles:

![image](https://github.com/healthchecks/healthchecks/assets/661859/7e1681ce-4be7-435f-8188-61b2f201d936)

This could take considerable effort to get every small detail right, but I think would let the user easily recognize which integrations to select. I'd like to further explore this option, but I will understand if you don't want to be dragged into CSS tweaking. I'll be happy to accept a PR that uses regular checkboxes.

**Comment by cuu508** [comment]
Let's try these icons:

![image](https://github.com/healthchecks/healthchecks/assets/661859/df3d0e0e-17a9-46ae-8683-9ae05cd13ea2)

![image](https://github.com/healthchecks/healthchecks/assets/661859/4e249a4f-3b0c-4610-9272-aa63584ce4a7)

[group-assets.zip](https://github.com/healthchecks/healthchecks/files/12790912/group-assets.zip)

Folder is not the ideal metaphor for this, as in the real world items cannot be in multiple folders at the same time. Better suggestions welcome :-)

**Comment by apollo13** [comment]
Great suggestions, will do (harsh week though, might not manage it this week). And yeah CSS is not my string suit, so might end up with just the checkboxes.

**Comment by apollo13** [comment]
I added most of it in #901 including a small test. The checkbox stuff is the best I could come up with (I really hate CSS). Let me know what else you want me to do there.

**Comment by cuu508** [comment]
Thanks, looks good!

**Comment by cuu508** [comment]
I [tweaked the group form](https://github.com/healthchecks/healthchecks/commit/37caa94ff5ae0db1abacc206ebfc808f73262816) some more to get it to look like so:

![image](https://github.com/healthchecks/healthchecks/assets/661859/fadccb6e-363b-4985-a224-4e9896c87846)

* It uses the custom-styled checkboxes that we use throughout the project (for example, in the "Add SMS" form)
* It uses PNG images instead of the icon font for channel kind logos
* It shows channel's description for each channel, same as in the channels list (both places use the same shared template for this)

**Comment by apollo13** [comment]
Oh that is lovely, thank you!
