### ISSUE TITLE
Question: Dependencies between checks

### ISSUE THREAD

**Issue by Synt3x** [healthchecks/healthchecks#913]
Hello

I was wondering if it is possible to setup an check to not trigger an alert if another check is already down.

**Example:**
- check1 - Checks if the server is online
- check2 - Doing some task
- check3 - Doing another task

If check1 goes down, check2 and check3 should not trigger any notification, but the status should still change to down.

Thanks in advance.

/Robin

**Comment by cuu508** [comment]
Thanks for the suggestion. This is not currently supported, some previous discussion here: https://github.com/healthchecks/healthchecks/issues/316
