### ISSUE TITLE
Feature request: dependency between checks for decision on changing health status or sending notifications

### ISSUE THREAD

**Issue by netstx** [healthchecks/healthchecks#917]
Hi @cuu508,

I checked closed issues, does not seem like this has been suggested before.

My suggestion / feature request is for dependency between checks, to avoid raising an alert for check Y if check X is already in alert.

For example: let's say I have a check on my internet router and a check for a cron job on a server that depends on this router to connect to the internet. If my router (parent check) goes down, the cron job check (child) would also would fail. Because of this dependency, I'd only need the router check alert notification(s), and could ignore the cron job check's alert notifications(s).

This is a simple example, but there are many other types of "dependencies" that I think users could come up with (between applications or cron jobs, scripts, etc).

The dependency check could simply not issue the notifications, but still keep track of missed checks, or ignore missed checks until the dependency clears (or having option for both). This would be somewhat similar to the "maintenance window" feature in some uptime monitoring tools out there, like UptimeRobot.

One thing to keep in mind, if grace period is the same for parent and child checks, it could cause issues, so perhaps part of the dependency feature, a child check would automatically have its grace period set higher by X% of the parent check's grace period - or some other method to avoid missing the dependency due to parent grace period.

Another way to go about this would be to implement a "maintenance window" feature where a one-time date/time or recurring date/time maintenance window would ignore missed pings or not send notifications. Then, a child check could automatically have a maintenance window created if a parent check is down. This may not be as elegant.

Thanks for listening, and for all your work on this awesome project.

Best,
Rafael

**Comment by cuu508** [comment]
Thanks for the suggestion @netstx. There's a similar feature suggestion here: #316

**Comment by netstx** [comment]
> Thanks for the suggestion @netstx. There's a similar feature suggestion here: #316 

Didn't catch that, thank you.
