### ISSUE TITLE
expose publicly accessible OK/NOT_OK curlable URL per check

### ISSUE THREAD

**Issue by job** [healthchecks/healthchecks#92]
This idea is somewhat similar to the publicly accessible badges per tag, but the feature request here is a text string per check (rather then svg image per tag).

It would be cool if a keyword is exposed at a per check unique URL so that I can poll whether a healthcheck is still in good shape or not.

health check in good shape:

```
$ curl https://hchk.io/txt/0b5eb61f-58af-4c8a-b6ce-2732892abe
OK
$
```

healthcheck in bad shape

```
$ curl https://hchk.io/txt/0b5eb61f-58af-4c8a-b6ce-2732892abe
NOT_OK
$
```

**Comment by cuu508** [comment]
Hi @job, I'm guessing this is for an internal dashboard? Would the calls be made from a browser, or from a server side process? If it's the latter, we could add an API call to get status, e.g.

Get full details about all your checks (this one is already there):

    GET https://healthchecks.io/api/v1/checks/

Get full details about a specific check:

    GET https://healthchecks.io/api/v1/checks/<uuid>/

Get just the status value of a specific check: 

    GET https://healthchecks.io/api/v1/checks/<uuid>/status

**Comment by job** [comment]
The API calls are useful, and I encourage you to implement that. This specific usecase is to make uptimerobot.com and healtchecks.io talk with each other.

uptimerobot.com has a 'keyword' check (in addition to http get, ping, tcp port), where it fetches a website and searches for the presence of absence of a keyword. more info here: http://theheat.dk/blog/?p=1934

I suspect that the `GET https://healthchecks.io/api/v1/checks/<uuid>/status` would integrate nicely with uptimerobot!

Which values can come out of the that API status call?

**Comment by cuu508** [comment]
The API calls would require a custom authentication header, so Uptime Robot would not be able to use them...

There is a hacky way to hook up UptimeRobot using the existing badge URLs. The badges are SVG files, so they are text based. You can create a keyword monitor which points at a bade URL and alerts when a keyword ">down<" is found in the response. 

Badges have three possible status values: up, grace, down. 

I know Uptime Robot recently added  public status pages, and it would be nice to show healthchecks.io checks there as well, but polling for status once a minute is not an efficient approach for either service. I'll have a think about the options there.

**Comment by job** [comment]
An auth header wont work indeed.

The SVG hack is 'meh', for some reason I could not get that to work.

the polling once a minute shouldn't be an issue, it is mostly static content, you could even do this on a `tmpfs` and not have file content but just hardlink to the file with the proper content.

**Comment by job** [comment]
@cuu508 i got the SVG hack to work, pebkac, so you can make this issue lower priority!

**Comment by cuu508** [comment]
I just added a JSON response format for the badge URLs. Should make custom dashboards easier to implement, and UptimeRobot-type checks less hacky.

![screenshot from 2017-06-29 16-09-00](https://user-images.githubusercontent.com/661859/27689014-50dd99f8-5ce5-11e7-903c-eace2d918c75.png)

**Comment by cuu508** [comment]
PS. the possible status values in the JSON responses are `up`, `late` and `down`.

**Comment by job** [comment]
thanks!
