### ISSUE TITLE
Configure disabling magic link sign-in

### ISSUE THREAD

**Issue by strboul** [healthchecks/healthchecks#922]
In the home page, there's an option to sign-in with magic links. It'd be nice to have it gone for some self-installations that have no SMTP host configured.

For example, `SIGNIN_DISABLE_MAGIC_LINK` (default `True`)

**Comment by cuu508** [comment]
Thanks for the suggestion.

I'm not planning to work on this in near term myself, but I will accept a PR if changes are minimal and not disruptive.

I don't think a new setting is necessary, you could check if the EMAIL_HOST setting is empty ([which is the default](https://github.com/healthchecks/healthchecks/blob/f33c296349b9e7f26338555267e1111fb851cf84/hc/settings.py#L225)).

**Comment by cuu508** [comment]
cc: #989

**Comment by cuu508** [comment]
@ilium007 sign-in links are only sent for accounts that exist. If bots submit the form, they will likely use email addresses that have no corresponding account and so no email will be sent.
