### ISSUE TITLE
README at Docker Hub is outdated

### ISSUE THREAD

**Issue by huyz** [healthchecks/healthchecks#928]
https://hub.docker.com/r/healthchecks/healthchecks is outdated as it references sqlite rather than PostgreSQL.

**Comment by cuu508** [comment]
The examples are not outdated, Healthchecks does work with SQLite too.

**Comment by huyz** [comment]
Ok, well it's confusing as it doesn't match the repo README, the blog entries.
Plus, it throws an exception as soon as you start the container

**Comment by cuu508** [comment]
I just tested this command from the README:

```
docker run \
  --name=healthchecks \
  -p 8000:8000 \
  --restart unless-stopped \
  -e ALLOWED_HOSTS=localhost \
  -e DB=sqlite \
  -e DB_NAME=/data/hc.sqlite \
  -e DEBUG=False \
  -e DEFAULT_FROM_EMAIL=fixme-email-address-here \
  -e EMAIL_HOST=fixme-smtp-host-here \
  -e EMAIL_HOST_PASSWORD=fixme-smtp-password-here \
  -e EMAIL_HOST_USER=fixme-smtp-username-here \
  -e EMAIL_PORT=587 \
  -e EMAIL_USE_TLS=True \
  -e SECRET_KEY=--- \
  -e SITE_ROOT=http://localhost:8000 \
  -v healthchecks-data:/data \
healthchecks/healthchecks:latest
```

It started up with no exceptions. What command did you use to start the container, and what did the exception say?

**Comment by cuu508** [comment]
I've updated README on Docker Hub to say:

> For simplicity, this example stores data using SQLite, in hc.sqlite file inside a volume named "healthchecks-data". Healthchecks can also store data in PostgreSQL and MySQL databases. You can configure the database backend using [the DB_* environment variables](https://healthchecks.io/docs/self_hosted_configuration/#DB).
