### ISSUE TITLE
Integration with OpsGenie

### ISSUE THREAD

**Issue by chris021** [healthchecks/healthchecks#93]
It would be great to see integration with OpsGenie

Happy to help with any testing if needed.

**Comment by cuu508** [comment]
Hi @chris021, just deployed OpsGenie integration to healthchecks.io. Would you mind testing it out? If you have suggestions on the wording of messages, the instructions screen or anything really–I'm all ears!

**Comment by chris021** [comment]
Working great! Thanks!
