### ISSUE TITLE
Better Stack Incident creation / alerting integration?

### ISSUE THREAD

**Issue by gh0stdotexe** [healthchecks/healthchecks#936]
We use [Better Stack](https://betterstack.com) in our organization for all incident response and general monitoring/alerting. 

We've recently switched back to HealthChecks for certain aspects (due to native integration with a few tools we use, alongside the context provided when an alert is sent), but it would be great to still have a Better Stack incident created when a HealthCheck goes down (and autoresolving the incident when it comes back up). 

Would this be possible? Have tried to use the webhook integration to trigger an incident, but it doesn't quite work as expected (Better Stack webhooks work with heartbeat monitors, not normal monitors).

**Comment by cuu508** [comment]
You may be able to use the Webhook integration with [BetterStack's Incident API endpoints](https://betterstack.com/docs/uptime/api/create-a-new-incident/).

As a quick experiment, I set up a Webhook integration like so: 

![image](https://github.com/healthchecks/healthchecks/assets/661859/d67132b8-832f-4912-944e-817c6523a347)

I saved the integration, and clicked the "Test" button to test it. An incident appeared on the other side:

![image](https://github.com/healthchecks/healthchecks/assets/661859/cdb94d4b-4a56-438f-8d6e-ebdb59b9585d)

**Comment by gh0stdotexe** [comment]
Awesome, appreciate the walkthrough! Set this up on our end and indeed it is working - probably should've done a bit more digging before bugging you, my b! 

Closing this out 🙏🏻
