### ISSUE TITLE
Prune outdated history

### ISSUE THREAD

**Issue by RoboMagus** [healthchecks/healthchecks#938]
I've been looking around for an option where outdated status history (e.g. older than X days) could be auto deleted to avoid infinitely growing DBs on large systems.

I could be overlooking something, but if such a feature is not yet implemented it'd be a nice addition :)

**Comment by cuu508** [comment]
Entries from the `api_ping` and the `api_notification` tables are being deleted automatically, see: https://github.com/healthchecks/healthchecks/blob/ae94648efd19bc6f2fbe3f740065adf43a5b6b57/hc/api/models.py#L507

Entries from the `api_flip` table are not being deleted automatically, but there is a `pruneflips` management command for that: https://github.com/healthchecks/healthchecks#database-cleanup

**Comment by RoboMagus** [comment]
Thanks! I figured something like that would've been implemented already, but I was not able to find it in the healthchecks.io documents.
