### ISSUE TITLE
Grace Time not completely editable once a job is created

### ISSUE THREAD

**Issue by saschabrockel** [healthchecks/healthchecks#945]
![image](https://github.com/healthchecks/healthchecks/assets/33376463/2e3418a7-c4a8-48a7-8ef8-5270e56c3b46)
Images can say more than words.

You can see that I want to change the grace time here but it's just possible to change it completely on creation. I cannot change the field from minutes to hours or anything else. It is not a button. It would be lovely to be able to edit this because recreation means another ID and changes in the script/app or whatever.

**Comment by cuu508** [comment]
You can set it to 120 to get two hours, to 180 to get three hours, etc.

I will accept a PR which turns the minutes part into a dropdown, if:

* the end result looks good visually (both in light and dark mode)
* the code changes are not big, and it does not introduce new dependencies
* the dropdown works well with keyboard navigation
