### ISSUE TITLE
Support 12 hour time

### ISSUE THREAD

**Issue by LunarTwilight** [healthchecks/healthchecks#948]
Would it be possible to support 12 hour time (AM/PM) too instead of just 24 hour time?

**Comment by LunarTwilight** [comment]
Poking around the codebase, it seems like it might just be an easy change from `HH:mm` to `LT`

https://github.com/healthchecks/healthchecks/blob/7ba23746167dca7767df6a36ac4aecf71a4071d9/static/js/log.js#L61
https://github.com/healthchecks/healthchecks/blob/7ba23746167dca7767df6a36ac4aecf71a4071d9/static/js/log.js#L82
https://github.com/healthchecks/healthchecks/blob/7ba23746167dca7767df6a36ac4aecf71a4071d9/static/js/log.js#L83
https://github.com/healthchecks/healthchecks/blob/7ba23746167dca7767df6a36ac4aecf71a4071d9/static/js/log.js#L110

tho I'm not sure how that'd work for the server's timezone and UTC, as `LT` (and similar) will also show those in the user's locale (eg UTC will show "5:00 AM" instead of "05:00")

**Comment by cuu508** [comment]
Thanks for the suggestion!

Healthchecks currently uses 24 hour time, as it's a sensible default that most people understand. The audience of Healthchecks is technical, so I wouldn't expect there to be a problem with it. 

Quoting from https://ux.stackexchange.com/a/108364/5648:

> People who are used to the am/pm format will be able to correctly understand the 24:00 format. People who are used to the 24:00 format will occasionally misunderstand 12:00 pm. Even people who are used to am/pm will occasionally [misunderstand](https://en.wikipedia.org/wiki/12-hour_clock#Confusion_at_noon_and_midnight) 12:00 pm.

On one hand it would be nice to be user-friendly and offer an option to format times in 12-hour format. On the other hand, that's extra code that would need to be written and maintained, and it's unclear how many users would find the option useful or important.

I'd like to keep the project as minimalistic as possible, and will not work on this, or accept a PR. If I see interest in this feature for more users (and especially customers), I will reconsider.
