### ISSUE TITLE
Feature: Readiness healthcheck for healthcheck itself

### ISSUE THREAD

**Issue by gjrtimmer** [healthchecks/healthchecks#949]
Great work on health checks; however, I still need a vital feature.
I'm running Healthchecks on Nomad with Consul and Vault for the secrets.

I still need an API management call that returns the readiness status of health checks like Gitlab.
Could you please consider a management API call like `/API/v3/health` or `/API/v3/ready`, which returns an HTTP 200 if the web server is running and the database can be reached so I can use this in either a container health check or in Consul.

I found it surprising that a health check application does not have its own health check.
Please consider this.

**Comment by cuu508** [comment]
There's a (currently undocumented) endpoint at `/api/v3/status`

https://github.com/healthchecks/healthchecks/blob/08eb27957417b15a38d52eb0e6eadba09f94a2a1/hc/api/views.py#L809

**Comment by gjrtimmer** [comment]
@cuu508 Thank you, I was looking in the documentation, maybe this issue can be used as a reminder to update the docs?

**Comment by gjrtimmer** [comment]
@cuu508 Question, I'm getting a HTTP 400 Bad Request on Curl and within Consul.
Any clue where to look?
```
curl http://healthchecks.service.consul:27882/api/v3/status

<!doctype html>
<html lang="en">
<head>
  <title>Bad Request (400)</title>
</head>
<body>
  <h1>Bad Request (400)</h1><p></p>
</body>
</html>
```

**Comment by cuu508** [comment]
Try with a trailing slash.

On Sun, Jan 28, 2024, at 3:23 PM, Gert-Jan (Garrett) Timmer wrote:
> 
> 
> 
> @cuu508 <https://github.com/cuu508> Question, I'm getting a HTTP 400 Bad Request on Curl and within Consul.
> Any clue where to look?
> 
> `curl http://healthchecks.service.consul:27882/api/v3/status
> 
> <!doctype html>
> <html lang="en">
> <head>
>   <title>Bad Request (400)</title>
> </head>
> <body>
>   <h1>Bad Request (400)</h1><p></p>
> </body>
> </html>
`

**Comment by ovizii** [comment]
How would such a healthcheck inside a docker-compose.yml file look like?  Any tips?

I tried this:

```
    healthcheck:
      test: curl -ILfSs http://localhost:8000/api/v3/status/ > /dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m00s
```

even manually from inside the container and I always receive:

```
curl -I http://localhost:8000/api/v3/status/
HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=utf-8
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin
```

**Comment by cuu508** [comment]
@ovizii I think you are likely receiving "400 Bad Request" because the Host header in the request does not match any host in [ALLOWED_HOSTS](https://healthchecks.io/docs/self_hosted_configuration/#ALLOWED_HOSTS).

From the container, try:

```
curl -I -H "Host: your-hc-domain.com" http://localhost:8000/api/v3/status/
```

**Comment by ovizii** [comment]
> @ovizii I think you are likely receiving "400 Bad Request" because the Host header in the request does not match any host in [ALLOWED_HOSTS](https://healthchecks.io/docs/self_hosted_configuration/#ALLOWED_HOSTS).
> 
> From the container, try:
> 
> ```
> curl -I -H "Host: your-hc-domain.com" http://localhost:8000/api/v3/status/
> ```

Hm, I'll give that a try. I had already tried adding localhost to the env. Variable like this in my compose file but maybe there's a formatting error or something like that .

`      - ALLOWED_HOSTS=['healthchecks.domain.tld', 'localhost']`

**### Your solution works perfectly. Thanks.**
