### ISSUE TITLE
Check goes down after one hour

### ISSUE THREAD

**Issue by The-Inamati** [healthchecks/healthchecks#952]
Hello,

I am having a very strange issue with healthchecks. 

I have three backup scripts that run daily and do a curl in the beggining and the end so I can also measure execution time. 

Two of them I have no issues with but one of them is misbehaving in a very strange way.  The issue goes as follows:
- Script starts and the first curl is done
- Healthchecks gets the curls and starts counting time
- Script ends the second curl is sent
- Healthchecks gets the second curl, posts execution time
- One hour later the check goes down with no other curls received or sent

You can see a print of the last two days below.
![image](https://github.com/healthchecks/healthchecks/assets/45592340/ebb9887e-55b7-40b1-a320-179d276d57eb)

What am I missing?

**Comment by cuu508** [comment]
What are the schedule settings for this check? Is it using a cron expression?

**Comment by The-Inamati** [comment]
![image](https://github.com/healthchecks/healthchecks/assets/45592340/88183ceb-4c3f-4090-a6b8-7d9f432afd9c)

The ones that work are the same but with a different hour.

**Comment by The-Inamati** [comment]
I just noticed that the script is starting at the wrong time. That's probably the issue.  I have adjusted the service file and will check tonight if it works.

**Comment by The-Inamati** [comment]
Yep. It was the script start up time. Idiot mistake. Thanks for the help.
