### ISSUE TITLE
Pinged but down

### ISSUE THREAD

**Issue by szepeviktor** [healthchecks/healthchecks#96]
Hello!

Today I am experiencing two of the servers were down for a cycle (1 hour). I use monit to execute this shell script

```
wget -q -t 3 -O- "$HEALTHCHECKS_URL" | grep -Fx "OK"
```

There was no trace of a non-OK response in the log but healthchecks alerted me that this check is down.
How to debug this?
Please advise.

**Comment by cuu508** [comment]
Hi, 

a couple questions:

- which checks had the issue? (can you post a fragment of the uuid?)
- at what time did you receive the unexpected "down" notification?

**Comment by szepeviktor** [comment]
- 26e52c2c-f8d3-43b0-8761-18727ca4****
- it is an hourly check with 3 minutes tolerance, I've received the down email at the end of this 3 minutes `10:06:56 CET`

**Comment by cuu508** [comment]
Not sure why the ping was not registered, but here's some information that might help. The server process on hchk.io writes a log file listing all received requests. Here's grep results from around that time:

```
$ grep 26e52c2c hchk.log.1
2016/11/25 06:04:41 Ping 26e52c2c-f8d3-43b0-8761-18727ca4**** 2a04:3542:1000:910:f8ae:70ff:fe7b:28af
2016/11/25 07:04:49 Ping 26e52c2c-f8d3-43b0-8761-18727ca4**** 2a04:3542:1000:910:f8ae:70ff:fe7b:28af
2016/11/25 08:04:54 Ping 26e52c2c-f8d3-43b0-8761-18727ca4**** 2a04:3542:1000:910:f8ae:70ff:fe7b:28af
2016/11/25 10:03:09 Ping 26e52c2c-f8d3-43b0-8761-18727ca4**** 2a04:3542:1000:910:f8ae:70ff:fe7b:28af
2016/11/25 11:03:16 Ping 26e52c2c-f8d3-43b0-8761-18727ca4**** 2a04:3542:1000:910:f8ae:70ff:fe7b:28af
2016/11/25 12:03:18 Ping 26e52c2c-f8d3-43b0-8761-18727ca4**** 2a04:3542:1000:910:f8ae:70ff:fe7b:28af
```

The times are in UTC. There's an entry missing for 9AM. The way the server process works is:

 - it first writes a line to the log file
 - it then submits the ping for processing
 - it then returns HTTP 200 message with body "OK"

These are sequential steps, so if an entry is missing from the log file, it's very likely the server *also did not respond with an "OK" message*. So I'm guessing either the cron job on your side did not run or its failure was not recorded correctly. I might be missing something though...

One thing worth checking is: if you temporarily change $HEALTHCHECKS_URL to an invalid address (for example, change a single character in the uuid), and let the cron job run -- does the failure end up in the logs on your side?

**Comment by szepeviktor** [comment]
> I use monit to execute this shell script

As I was mentioning I use monit to schedule the ping.
https://mmonit.com/monit/documentation/monit.html

> wget -q -t 3 -O- "$HEALTHCHECKS_URL" | grep -Fx "OK"

And grep -Fx makes sure the exit status in non-zero if one whole line is not `OK`
so if `OK` is not coming out of wget then grep exits with non-zero and monit will alert me and log a failure.

**Comment by szepeviktor** [comment]
Actually monit runs every 2 minutes and it is not able to guarantee that in minute 03 or in 04 it will run.

> 08:04:54

From your log it seems that some monitoring checks take longer that 2 minutes so pinging your service is missed.
Thank you for sharing your log.

I am sorry for the noise.

**Comment by szepeviktor** [comment]
From the monit manual:

> The current scheduler is poll cycle based. If a service check is scheduled with the every cron statement, Monit will check if the current time match the cron-string pattern. If it does, then the check is performed otherwise it is skipped.
