### ISSUE TITLE
new price plan - Hobbyist+

### ISSUE THREAD

**Issue by asdffdsazqqq** [healthchecks/healthchecks#962]
Hello, Thanks, how about additional pricing plains, 
for example:
* more jobs
* less notifications
* zero team members

**Hobbyist +**
$5 / month

Monitor 100 jobs
    100 log entries per job
    0  SMS & WhatsApp credits 
    0 team members

**Comment by cuu508** [comment]
Thanks for the suggestion. 
Hitting the number of monitors is the primary reason users upgrade. Adding a cheaper 100-job plan would cannibalize the existing 100-job plan, and risk the sustainability of the project.

**Comment by asdffdsazqqq** [comment]
OK. I will signup for the Hobbyist plan.
