### ISSUE TITLE
Requested Integration Text-Em-All

### ISSUE THREAD

**Issue by sew3521** [healthchecks/healthchecks#969]
I know that Text-Em-All has an API available for "approved applications". I would love to be able to use them as an integration. The URL to their API info is
https://support.text-em-all.com/article/278-how-do-i-get-api-authorization#

**Comment by cuu508** [comment]
FWIW, Healthchecks already has a SMS integration. 
What would be the use case for integrating Healthchecks with Text-Em-All?

**Comment by sew3521** [comment]
If you organization already has Text-Em-All and uses it for other notifications it would be nice to not re-enroll all the devices and configure all the groups inside of Text-Em-All. Plus for management reasons groups are easier to mess around with in one portal instead of two (or more)

**Comment by cuu508** [comment]
Is your company using Text-Em-All? Do you use it to deliver monitoring notifications to employees, or for something else?
