### ISSUE TITLE
Can not login admin page after create superuser in django app 

### ISSUE THREAD

**Issue by huyhoang17** [healthchecks/healthchecks#97]
- I clone your project in my PC, migrate data and create a superuser account. Everything is OK. But when I create superuser account :

```
python manage.py createsuperuser 
```

and I can't log in my admin page with username and password I created, any idea? Thanks !

**Comment by cuu508** [comment]
What error message did you get?
Which log in form did you use: `/login/` or `/admin/login/`?

The `/admin/login/` one was confusing, it was asking for username and password, but for it to work you had to actually enter email address and password. I have just updated the project to use the same form in both places.
