### ISSUE TITLE
Add a visual indication to Favicon/Tab

### ISSUE THREAD

**Issue by solracsf** [healthchecks/healthchecks#971]
![image](https://github.com/healthchecks/healthchecks/assets/12234510/6776c6bb-fae0-4f5c-9b7e-bfbab4ea3037)

This is what we get when a monitor is down in a full tab. Howhever, if the tab is pinned on browser, we have no visual indication.

[Uptime-Kuma](https://github.com/louislam/uptime-kuma) project has implemented this, for reference _(here both tabs pinned, side by side, where both have 2 monitors down)_:

![image](https://github.com/healthchecks/healthchecks/assets/12234510/26c6c97e-3091-4428-be45-cedc2278ff85)

**Comment by princekhunt** [comment]
Hi

I have tried to implement this in a PR #977

**Comment by solracsf** [comment]
Please allow me to specify that favicon is only updated if inside the project where a monitor is down.
If on "1ll projects" tab, favicon is not updated, and it should be IMO.
