### ISSUE TITLE
Make the timezone selection key sensitive

### ISSUE THREAD

**Issue by simeonreusch** [healthchecks/healthchecks#973]
First of all: I love this tool.

Secondly: For each new job I have to change the timezone from UTC to a specified value. As I'm in Europe, it's pretty far down the list. I would love to be able to just start entering "Berlin" and it autocompletes from the list to speed up the selection process.

Further on: Enabling a new timezone default in the settings would be **awesome** (#365 and #291)

**Comment by cuu508** [comment]
> I would love to be able to just start entering "Berlin" and it autocompletes from the list to speed up the selection process.

Unless I'm misunderstanding you, that's how it should work already: you can type in the timezone selection field and it will filter the list. You should be able to type "Berlin" or "berlin" and see a single match: "Europe/Berlin".

![image](https://github.com/healthchecks/healthchecks/assets/661859/23212cca-fb6f-477c-aa92-c9297a93b925)

**Comment by simeonreusch** [comment]
It does indeed work upon event creation, sorry for missing that. 
I does not work though when adding cron information later on to a job that already exists (which I usually do).

**Comment by cuu508** [comment]
It should work the same when editing schedules of existing checks too. 

* Can you reproduce the issue on the hosted service? 
*  Are you editing the schedule from the list of checks, or from individual check's details page?
* In case there's a browser-specific issue, what browser, and what browser version are you using?

**Comment by cuu508** [comment]
No response, closing.
