### ISSUE TITLE
non-developmnet mode?

### ISSUE THREAD

**Issue by claytondukes** [healthchecks/healthchecks#98]
Hi, is there a guide for setting this up on an intranet in production mode?
I have it installed, but after setting Debug = False, it still loads using http://127.0.0.1:8080

**Comment by alanthing** [comment]
:+1:

When searching for Django errors with Debug=False, it's nearly all solutions with setting `ALLOWED_HOSTS = [ "$HOSTNAME" ]` or similar. That alone did not resolve it for me, even with an asterisk as the provided value. For my own paranoia, I have my app running with basic authentication (over TLS) on all URLs except /badge/ and /ping/, but I'd ultimately like to be able to turn debug off.

**Comment by iphoting** [comment]
Consider turning logging as well to obtain stacktraces of the error. One of them I noted was solved by building static assets and compressing them.

**Comment by rawlk** [comment]
Don't suppose y'all have stumbled across turning off "Debug" mode?

**Comment by ttr** [comment]
in local_settings.py
`DEBUG = False

**Comment by cuu508** [comment]
I've updated README with a "Running in Production" section. It's pretty minimal and some parts likely need to be expanded on. But I also think it will be out of scope to go into full detail about configuring the web server, the task runner, the database, external monitoring etc. etc.
