### ISSUE TITLE
Unable to use different domains for web GUI and pings?

### ISSUE THREAD

**Issue by pro-sumer** [healthchecks/healthchecks#981]
Until recently I was using the single domain _old.domain.tld_ for both the web GUI and for pings, but now I want to split this up:
* _new.domain.tld_ for the web GUI
* _old.domain.tld_ for the pings (so I don't have to update any of my scripts)

This is what I'm trying:

**Caddyfile**:
```
old.domain.tld {
  import cloudflare

  reverse_proxy /ping/* healthchecks_web:8000
  redir https://new.domain.tld{uri}
}

new.domain.tld {
  import cloudflare

  reverse_proxy healthchecks_web:8000
}
```

**.env.production**:
```
ALLOWED_HOSTS=new.domain.tld,old.domain.tld
SITE_ROOT=https://new.domain.tld
PING_ENDPOINT=https://old.domain.tld/ping/
```

This works:
* webGUI is available on _new.domain.tld_
* when I accidentally surf to _old.domain.tld_ this get redirected to _new.domain.tld_

This fails:
* all of my pings no longer work with this setup

What am I doing wrong?

**Comment by cuu508** [comment]
Where are the ping requests landing? Do you see them in healthchecks_web container's logs?

**Comment by pro-sumer** [comment]
Figured it out thanks to [this post](https://caddy.community/t/reverse-proxy-and-redirect-on-same-directive/13087/2):

> The issue you’re running into is that Caddy sorts directives according to this predetermined directive order (redir gets sorted before reverse_proxy)

So this fixes it:
```
old.domain.tld {
  import cloudflare

  @notPings not path /ping/*
  redir @notPings https://new.domain.tld{uri}
  reverse_proxy healthchecks_web:8000
}
```
