### ISSUE TITLE
[Docker] replace pip with apt

### ISSUE THREAD

**Issue by Firesphere** [healthchecks/healthchecks#982]
I believe build of the Docker container could be sped up by using apt python packages instead of running the installation using pip?
From what I can see, the following packages are readily available in apt, if prefixed with `pithon3-`
 ```
aiosmtpd
fido2
psycopg2
pycurl
pydantic
pyotp
segno
statsd
whitenoise
```
By using apt instead of pip, build times could be greatly reduced, as apt installations are a lot faster than pip

**Comment by cuu508** [comment]
We install specific versions of python packages. Debian repositories usually lag behind PyPI, and only have older versions available.

fido2 requires cryptography which is the slowest one to build. The rest are not that different from deb packages, install speed wise.
