### ISSUE TITLE
Feature request: High-Availability

### ISSUE THREAD

**Issue by nh2** [healthchecks/healthchecks#983]
Hi,

I'm looking for an alternative to the abandoned https://github.com/AcalephStorage/consul-alerts

Does `healthchecks` have any form of high-availability (HA) feature currently?

With HA I mean that you can run a cluster of machines, all running `healthchecks`, and if one goes down, the others will still alert you of failed health checks.

From a first look, it seems `healthchecks` is a plain single-server Django app without any dependency on a highly available database package like `consul` or `etcd`.

Of course one can HA the underlying DB, such as postgres, but it would still require that `healthchecks` actually supports running multiple `healthchecks` instances on different servers against the underlying HA database.

Is that supported?

if not, consider this a feature request -- i think it makes sense that the software that watches my HA software for uptime is also HA itself :)

Thanks!

**Comment by cuu508** [comment]
> Of course one can HA the underlying DB, such as postgres, but it would still require that healthchecks actually supports running multiple healthchecks instances on different servers against the underlying HA database.

Yes, that is supported. You can run multiple (probably load-balanced) Healthchecks web servers against a single database. The `manage.py sendalerts` command, which is in charge of sending out notifications, can also be run concurrently on multiple servers.

**Comment by nh2** [comment]
Thank you!
