### ISSUE TITLE
Alert gets sent even though check is OK

### ISSUE THREAD

**Issue by ovizii** [healthchecks/healthchecks#984]
I have a weekly cron job which works and sends the OK to healthchecks but 15 minutes later healthchecks still sends out an alert. If I remember correctly, the grace time was 20 minutes and I think I raised it to 30 minutes, so the alerts used to go out 20 minutes after the OK and now 30 minutes after the OK.

Any idea if I am doing something wrong?

![image](https://github.com/healthchecks/healthchecks/assets/837902/2b9b6172-927b-430e-a9a4-e1d712dce1e5)

**Comment by cuu508** [comment]
The schedule `5 5 * * *` is for a daily, not a weekly cron job.

**Comment by ovizii** [comment]
> The schedule `5 5 * * *` is for a daily, not a weekly cron job.

Damn! Thanks for spotting that. My crontab was `5 5 * * 0` and when setting up the healthcheck I must have made a typo and set it tu `5 5 * * *`. This was driving me insane. Thanks for spotting it!
