### ISSUE TITLE
SITE_ROOT in local_settings.py

### ISSUE THREAD

**Issue by PublicNME** [healthchecks/healthchecks#985]
Install HC on clear ubuntu 22.04 baremetal install, hc-venv, apt install, etc. Running with nginx and unicorn.
settings.py and local_settings.py stored in /var/www/healthchecks/hc/
settings.py from the repository without changes
local_settings.py have line
`SITE_ROOT = "https://hc.mysite.com"`
and other like SECRET_KEY, DEBUG = False etc

The bug is that inside each check there is a hint "How To Ping" with url http://localhost:8000/ping/*** from settings.py remains, and the local_settings.py entry is ignored. Also because of this, dependent buttons in the interface (such as “ping now”) stop working. 
If i write SITE_ROOT in settings.py this fix hint to correct url and everything work.

This ignoring SITE_ROOT in local_settings.py a bug?

**Comment by cuu508** [comment]
The URL displayed in the "How To Ping" panel is controlled by the [PING_ENDPOINT](https://healthchecks.io/docs/self_hosted_configuration/#PING_ENDPOINT) configuration setting. 

In settings.py, PING_ENDPOINT by default gets derived from SITE_ROOT:

```python
PING_ENDPOINT = os.getenv("PING_ENDPOINT", SITE_ROOT + "/ping/")
```

If you redefine SITE_ROOT in local_settings.py, you should also redefine PING_ENDPOINT. Example:

```python
SITE_ROOT = "https://hc.mysite.com"
PING_ENDPOINT = SITE_ROOT + "/ping"
```

I do see how this can be tricky to figure out, and perhaps documentation for SITE_ROOT and PING_ENDPOINT settings could be improved.

**Comment by PublicNME** [comment]
Oh yeah, thanks for the explanation! Redefining PING_ENDPOINT seems to have fixed everything. 
Perhaps I was confused by local_settings.py.example, which does not mention PING_ENDPOINT but suggests fixing SITE_ROOT. It's probably possible to make changes to the original local_settings.py.example so that new users don't have this problem
