### ISSUE TITLE
auto refresh/real time updates

### ISSUE THREAD

**Issue by jayzeng** [healthchecks/healthchecks#99]
Just started to use the product and it works great in most cases. One small feature I really wish to see is the auto refresh or real time updates at least on the 'checks' (https://healthchecks.io/checks/) page. 

I was testing my setup, stopped the server and starring at the page, nothing really works until I realized it requires a fresh.

**Comment by cuu508** [comment]
What use case do you have in mind? Do you have a tab open, and will sometimes check up on it? Or do you have the list of checks always visible on a separate screen? 

Maybe it makes sense to implement a kiosk mode: header and footer is hidden, probably ping URLs are hidden too, and the page refreshes once every minute or so. In kiosk mode we could assume it's "eyes only", and it's OK to reload the whole page and not risk interfering with any open popups and such.

What do you think?

**Comment by mkelley82** [comment]
I think the real value comes from the integrations... one of the checks shows status down - get a notification through the integration of your choice. I have it set-up for a pushbullet and an email. But using the API you should have no problem setting up a simple auto-updating dashboard that lists all your checks,

**Comment by wahmedswl** [comment]
Hi,
    This is a good for UX as just deployed HealthChecks and also wondering when it will get updated but Page get updated on refresh. It would be great if it keeps statuses updated without refreshing the page otherwise, any Tab refresher extension will suffice but that will also interfere with any open Popups as you mentioned.

Thanks for this minimal and awesome app, really appreciate it.

**Comment by cuu508** [comment]
I have now added an auto-refresh feature to the "My Checks" page. You can check it out on https://healthchecks.io

The things that are updated are the status icons for each check, and the "Last Ping" field.
Other fields are not touched. So, for example, if you rename a check in another browser window, the name will not update on your first browser window.

The update frequency is "every 3 seconds". It changes to "every 60 seconds" if user is inactive for a minute, or changes tab or minimizes the browser. When user becomes active (moves mouse) or the tab becomes visible again, the "every 3 seconds" loop resumes.

If you get a chance, please try it out and let me know what you think.
