### ISSUE TITLE
Slack legacy webhook integration 

### ISSUE THREAD

**Issue by jbuitt** [healthchecks/healthchecks#991]
Hello!

Slack will eventually be deprecating the webhook integration. The new suggested way to send messages to Slack channels is by creating a custom Slack App in the user's Workspace, which uses a OAuth token (with appropriate scopes) instead of a webhook URL. Could this new method of sending Slack notifications please be incorporated into Healthchecks?

Thanks!
Jim

**Comment by cuu508** [comment]
> Slack will eventually be deprecating the webhook integration. 

Everything will eventually cease to exist. Is there a known sunset date?

> Could this new method of sending Slack notifications please be incorporated into Healthchecks?

It's supported, see [SLACK_CLIENT_ID](https://healthchecks.io/docs/self_hosted_configuration/#SLACK_CLIENT_ID).

**Comment by jbuitt** [comment]
> 
> Everything will eventually cease to exist. Is there a known sunset date?
> 

Sorry, I didn't clarify. Slack is deprecating plain (non-App) webhooks. No sunset date at this point.

> 
> It's supported, see [SLACK_CLIENT_ID](https://healthchecks.io/docs/self_hosted_configuration/#SLACK_CLIENT_ID).

Excellent! Apologies, I didn't see this in your docs. I will give this a shot.

Thank you!
