### ISSUE TITLE
Mute all checks while updating

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [healthchecks/healthchecks#993]
It would be great, if the admins had a button or something, to disable all notifications globally during upgrades, especially for "short running checks" which are pinged and expected every minute.

This would enable admins to disable all notifications for e.g. 10 minutes, while restarting the instance.

Same would be great for each project (and tags), e.g. if a VM or host needs to be restarted (I use it to monitor if my systems crash, and if for one minute no ping is received, I get notified).

**Comment by lnlyssg** [comment]
FYI #316 and #451 have both requested similar

**Comment by cuu508** [comment]
Indeed, #451 is pretty much the same feature request. I'll close this one as a duplicate.

**Comment by TheCataliasTNT2k** [comment]
Yes, it is similar to #451 but more than this. But I will use the other issue instead.
